DROP TABLE IF EXISTS `cluster_skill`;
CREATE TABLE `cluster_skill` (skill VARCHAR(50) NOT NULL, shiny VARCHAR(50) NOT NULL, bright VARCHAR(50) NOT NULL, faded VARCHAR(50) NOT NULL);
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('1h Blunt', 'rarm', 'rwrist', 'rhand');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('1h Edged', 'rarm', 'rwrist', 'rhand');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('2h Blunt', 'rarm', 'larm', 'chest');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('2h Edged', 'rarm', 'larm', 'waist');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('% Add All Def. Jobe', 'larm', 'rarm', 'feet');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('% Add All Off Jobe', 'larm', 'rarm', 'feet');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('% Add. Chem. Dam. Jobe', 'rhand', 'lwrist', 'rwrist');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('% Add. Energy Dam. Jobe', 'rhand', 'lwrist', 'rwrist');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('% Add. Fire Dam. Jobe', 'rhand', 'lwrist', 'rwrist');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('% Add. Melee Dam. Jobe', 'rhand', 'lwrist', 'rwrist');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('% Add. Poison Dam. Jobe', 'rhand', 'lwrist', 'rwrist');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('% Add. Proj. Dam. Jobe', 'rhand', 'lwrist', 'rwrist');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('% Add.Rad. Dam. Jobe', 'rhand', 'lwrist', 'rwrist');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('% Add. Xp Jobe', 'ear', 'feet', 'legs');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Adventuring', 'legs', 'waist', 'chest');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Agility', 'legs', 'feet', 'waist');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Aimed Shot', 'eye', 'rwrist', 'rhand');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Assault Rif', 'rarm', 'rhand', 'eye');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Bio.Metamor', 'head', 'chest', 'waist');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Body Dev', 'chest', 'waist', 'legs');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Bow', 'rarm', 'larm', 'eye');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Bow Spc Att', 'head', 'rhand', 'rwrist');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Brawling', 'larm', 'rarm', 'waist');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Break & Entry', 'rarm', 'larm', 'chest');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Burst', 'rarm', 'rwrist', 'rhand');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Chemical AC', 'waist', 'rarm', 'larm');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Chemistry', 'head', 'eye', 'rhand');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Cold AC', 'waist', 'rhand', 'lhand');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Comp. Liter', 'head', 'eye', 'rhand');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Concealment', 'feet', 'ear', 'eye');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Dimach', 'chest', 'head', 'waist');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Disease AC', 'head', 'legs', 'chest');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Dodge-Rng', 'legs', 'feet', 'waist');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Duck-Exp', 'legs', 'waist', 'feet');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Elec. Engi', 'eye', 'head', 'rhand');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Energy AC', 'chest', 'legs', 'waist');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Evade-ClsC', 'feet', 'legs', 'waist');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Fast Attack', 'lhand', 'rhand', 'rarm');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Fire AC', 'waist', 'lhand', 'rhand');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('First Aid', 'head', 'rhand', 'lhand');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Fling Shot', 'rarm', 'rhand', 'rwrist');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Full Auto', 'rarm', 'rwrist', 'waist');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Grenade', 'rarm', 'eye', 'rhand');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Heal Delta Jobe', 'larm', 'feet', 'legs');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Heavy Weapons', 'rarm', 'eye', 'rhand');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Imp/Proj AC', 'legs', 'chest', 'waist');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Intelligence', 'head', 'eye', 'ear');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Map Navig', 'eye', 'head', 'ear');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Martial Arts', 'rhand', 'feet', 'lhand');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Matter Crea', 'head', 'rhand', 'eye');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Matt.Metam', 'head', 'chest', 'larm');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Max Health', 'chest', 'waist', 'legs');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Max Nano', 'head', 'waist', 'chest');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Max NCU Jobe', 'ear', 'rwrist', 'legs');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Mech. Engi', 'head', 'eye', 'rarm');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Melee Ener', 'head', 'lwrist', 'rwrist');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Melee. Init', 'feet', 'legs', 'waist');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Melee/MA AC', 'chest', 'waist', 'legs');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('MG / SMG', 'rarm', 'rhand', 'chest');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Multi Ranged', 'lwrist', 'rwrist', 'eye');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Mult. Melee', 'lwrist', 'eye', 'rwrist');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('NanoC. Init', 'head', 'eye', 'chest');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Nano Formula Interrupt Modifier Jobe', 'legs', 'lhand', 'chest');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Nano Point Cost Modifier Jobe', 'waist', 'ear', 'larm');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Nano Pool', 'chest', 'head', 'waist');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Nano Progra', 'head', 'eye', 'rhand');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Nano Resist', 'head', 'rwrist', 'lwrist');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Parry', 'rwrist', 'lwrist', 'rarm');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Perception', 'ear', 'eye', 'head');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Pharma Tech', 'head', 'eye', 'rhand');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Physic. Init', 'feet', 'rarm', 'larm');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Piercing', 'rarm', 'larm', 'waist');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Pistol', 'rwrist', 'rhand', 'eye');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Psychic', 'head', 'chest', 'ear');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Psychology', 'head', 'ear', 'eye');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Psycho Modi', 'head', 'eye', 'ear');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Quantum FT', 'head', 'eye', 'rhand');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Radiation AC', 'waist', 'larm', 'rarm');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Ranged Ener', 'head', 'eye', 'lhand');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Ranged. Init', 'rwrist', 'head', 'rhand');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('RangeInc. NF Jobe', 'larm', 'lhand', 'rarm');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('RangeInc. Weapon Jobe', 'eye', 'feet', 'rarm');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Rifle', 'eye', 'rwrist', 'lwrist');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Riposte', 'rwrist', 'lwrist', 'rarm');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Run Speed', 'rwrist', 'lwrist', 'legs');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Sense', 'chest', 'waist', 'head');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Sensory Impr', 'head', 'eye', 'chest');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Sharp Obj', 'rwrist', 'rhand', 'eye');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Shield Chemical AC Jobe', 'lhand', 'feet', 'lwrist');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Shield Cold AC Jobe', 'lhand', 'feet', 'lwrist');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Shield Energy AC Jobe', 'lwrist', 'lhand', 'legs');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Shield Fire AC Jobe', 'lwrist', 'lhand', 'legs');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Shield Melee AC Jobe', 'lhand', 'feet', 'lwrist');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Shield Poison AC Jobe', 'lhand', 'feet', 'lwrist');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Shield Projectile AC Jobe', 'lwrist', 'lhand', 'legs');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Shield Radiation AC Jobe', 'lwrist', 'lhand', 'legs');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Shotgun', 'rarm', 'rhand', 'waist');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Skill Time Lock Modifier Jobe', 'legs', 'lhand', 'chest');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Sneak Atck', 'feet', 'rwrist', 'eye');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Stamina', 'chest', 'legs', 'waist');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Strength', 'rarm', 'larm', 'chest');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Swimming', 'legs', 'rarm', 'larm');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Time & Space', 'head', 'rhand', 'eye');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Trap Disarm', 'rhand', 'lhand', 'head');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Treatment', 'head', 'eye', 'rhand');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Tutoring', 'eye', 'ear', 'head');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Vehicle Air', 'eye', 'ear', 'head');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Vehicle Grnd', 'head', 'eye', 'ear');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Vehicle Hydr', 'head', 'eye', 'ear');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('Weapon Smt', 'rhand', 'head', 'eye');
INSERT INTO `cluster_skill` (skill, shiny, bright, faded) VALUES ('NanoCluster of Nano Regeneration', 'rwrist', 'rarm', 'feet');