DROP TABLE IF EXISTS `cluster`;
CREATE TABLE `cluster` (skill VARCHAR(50) NOT NULL, shiny VARCHAR(50) NOT NULL, bright VARCHAR(50) NOT NULL, faded VARCHAR(50) NOT NULL);
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('1h Blunt', 'R.Arm', 'R.Wrist', 'R.Hand');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('1h Edged Weapon', 'R.Arm', 'R.Wrist', 'R.Hand');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('2h Blunt', 'R.Arm', 'L.Arm', 'Chest');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('2h Edged', 'R.Arm', 'L.Arm', 'Waist');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('% Add All Def. Jobe', 'L.Arm', 'R.Arm', 'Feet');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('% Add All Off Jobe', 'L.Arm', 'R.Arm', 'Feet');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('% Add. Chem. Dam. Jobe', 'R.Hand', 'L.Wrist', 'R.Wrist');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('% Add. Energy Dam. Jobe', 'R.Hand', 'L.Wrist', 'R.Wrist');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('% Add. Fire Dam. Jobe', 'R.Hand', 'L.Wrist', 'R.Wrist');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('% Add. Melee Dam. Jobe', 'R.Hand', 'L.Wrist', 'R.Wrist');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('% Add. Poison Dam. Jobe', 'R.Hand', 'L.Wrist', 'R.Wrist');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('% Add. Proj. Dam. Jobe', 'R.Hand', 'L.Wrist', 'R.Wrist');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('% Add.Rad. Dam. Jobe', 'R.Hand', 'L.Wrist', 'R.Wrist');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('% Add. Xp Jobe', 'Ear', 'Feet', 'Leg');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Adventuring', 'Leg', 'Waist', 'Chest');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Agility', 'Leg', 'Feet', 'Waist');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Aimed Shot', 'Eye', 'R.Wrist', 'R.Hand');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Assault Rif', 'R.Arm', 'R.Hand', 'Eye');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Bio.Metamor', 'Head', 'Chest', 'Waist');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Body Dev', 'Chest', 'Waist', 'Leg');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Bow', 'R.Arm', 'L.Arm', 'Eye');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Bow Spc Att', 'Head', 'R.Hand', 'R.Wrist');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Brawling', 'L.Arm', 'R.Arm', 'Waist');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Break & Entry', 'R.Arm', 'L.Arm', 'Chest');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Burst', 'R.Arm', 'R.Wrist', 'R.Hand');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Chemical AC', 'Waist', 'R.Arm', 'L.Arm');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Chemistry', 'Head', 'Eye', 'R.Hand');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Cold AC', 'Waist', 'R.Hand', 'L.Hand');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Comp. Liter', 'Head', 'Eye', 'R.Hand');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Concealment', 'Feet', 'Ear', 'Eye');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Dimach', 'Chest', 'Head', 'Waist');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Disease AC', 'Head', 'Leg', 'Chest');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Dodge-Rng', 'Leg', 'Feet', 'Waist');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Duck-Exp', 'Leg', 'Waist', 'Feet');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Elec. Engi', 'Eye', 'Head', 'R.Hand');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Energy AC', 'Chest', 'Leg', 'Waist');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Evade-ClsC', 'Feet', 'Leg', 'Waist');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Fast Attack', 'L.Hand', 'R.Hand', 'R.Arm');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Fire AC', 'Waist', 'L.Hand', 'R.Hand');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('First Aid', 'Head', 'R.Hand', 'L.Hand');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Fling Shot', 'R.Arm', 'R.Hand', 'R.Wrist');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Full Auto', 'R.Arm', 'R.Wrist', 'Waist');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Grenade', 'R.Arm', 'Eye', 'R.Hand');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Heal Delta Jobe', 'L.Arm', 'Feet', 'Leg');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Heavy Weapons', 'R.Arm', 'Eye', 'R.Hand');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Imp/Proj AC', 'Leg', 'Chest', 'Waist');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Intelligence', 'Head', 'Eye', 'Ear');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Map Navig', 'Eye', 'Head', 'Ear');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Martial Arts', 'R.Hand', 'Feet', 'L.Hand');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Matter Crea', 'Head', 'R.Hand', 'Eye');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Matt.Metam', 'Head', 'Chest', 'L.Arm');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Max Health', 'Chest', 'Waist', 'Leg');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Max Nano', 'Head', 'Waist', 'Chest');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Max NCU Jobe', 'Ear', 'R.Wrist', 'Leg');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Mech. Engi', 'Head', 'Eye', 'R.Arm');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Melee Ener', 'Head', 'L.Wrist', 'R.Wrist');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Melee. Init', 'Feet', 'Leg', 'Waist');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Melee/Ma AC', 'Chest', 'Waist', 'Leg');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('MG / SMG', 'R.Arm', 'R.Hand', 'Chest');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Multi Ranged', 'L.Wrist', 'R.Wrist', 'Eye');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Mult. Melee', 'L.Wrist', 'Eye', 'R.Wrist');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('NanoC. Init', 'Head', 'Eye', 'Chest');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Nano Formula Interrupt Modifier Jobe', 'Leg', 'L.Hand', 'Chest');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Nano Point Cost Modifier Jobe', 'Waist', 'Ear', 'L.Arm');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Nano Pool', 'Chest', 'Head', 'Waist');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Nano Progra', 'Head', 'Eye', 'R.Hand');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Nano Resist', 'Head', 'R.Wrist', 'L.Wrist');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Parry', 'R.Wrist', 'L.Wrist', 'R.Arm');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Perception', 'Ear', 'Eye', 'Head');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Pharma Tech', 'Head', 'Eye', 'R.Hand');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Physic. Init', 'Feet', 'R.Arm', 'L.Arm');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Piercing', 'R.Arm', 'L.Arm', 'Waist');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Pistol', 'R.Wrist', 'R.Hand', 'Eye');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Psychic', 'Head', 'Chest', 'Ear');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Psychology', 'Head', 'Ear', 'Eye');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Psycho Modi', 'Head', 'Eye', 'Ear');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Quantum FT', 'Head', 'Eye', 'R.Hand');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Radiation AC', 'Waist', 'L.Arm', 'R.Arm');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Ranged Ener', 'Head', 'Eye', 'L.Hand');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Ranged. Init', 'R.Wrist', 'Head', 'R.Hand');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('RangeInc. NF Jobe', 'L.Arm', 'L.Hand', 'R.Arm');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('RangeInc. Weapon Jobe', 'Eye', 'Feet', 'R.Arm');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Rifle', 'Eye', 'R.Wrist', 'L.Wrist');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Riposte', 'R.Wrist', 'L.Wrist', 'R.Arm');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Run Speed', 'R.Wrist', 'L.Wrist', 'Leg');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Sense', 'Chest', 'Waist', 'Head');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Sensory Impr', 'Head', 'Eye', 'Chest');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Sharp Obj', 'R.Wrist', 'R.Hand', 'Eye');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Shield Chemical AC Jobe', 'L.Hand', 'Feet', 'L.Wrist');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Shield Cold AC Jobe', 'L.Hand', 'Feet', 'L.Wrist');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Shield Energy AC Jobe', 'L.Wrist', 'L.Hand', 'Leg');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Shield Fire AC Jobe', 'L.Wrist', 'L.Hand', 'Leg');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Shield Melee AC Jobe', 'L.Hand', 'Feet', 'L.Wrist');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Shield Poison AC Jobe', 'L.Hand', 'Feet', 'L.Wrist');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Shield Projectile AC Jobe', 'L.Wrist', 'L.Hand', 'Leg');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Shield Radiation AC Jobe', 'L.Wrist', 'L.Hand', 'Leg');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Shotgun', 'R.Arm', 'R.Hand', 'Waist');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Skill Time Lock Modifier Jobe', 'Leg', 'L.Hand', 'Chest');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Sneak Atck', 'Feet', 'R.Wrist', 'Eye');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Stamina', 'Chest', 'Leg', 'Waist');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Strength', 'R.Arm', 'L.Arm', 'Chest');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Swimming', 'Leg', 'R.Arm', 'L.Arm');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Time & Space', 'Head', 'R.Hand', 'Eye');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Trap Disarm', 'R.Hand', 'L.Hand', 'Head');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Treatment', 'Head', 'Eye', 'R.Hand');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Tutoring', 'Eye', 'Ear', 'Head');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Vehicle Air', 'Eye', 'Ear', 'Head');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Vehicle Grnd', 'Head', 'Eye', 'Ear');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Vehicle Hydr', 'Head', 'Eye', 'Ear');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('Weapon Smt', 'R.Hand', 'Head', 'Eye');
INSERT INTO `cluster` (skill, shiny, bright, faded) VALUES ('NanoCluster of Nano Regeneration', 'R.Wrist', 'R.Arm', 'Feet');