DROP TABLE IF EXISTS premade_implant;
CREATE TABLE premade_implant ( ImplantTypeID INT NOT NULL, ProfessionID INT NOT NULL, AbilityID INT NOT NULL, shiny char(30) NOT NULL, bright char(30) NOT NULL, faded CHAR(30) NOT NULL );
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (4,1,5,'Max Health','Matter Metamorphosis','Sensory Improvement');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (4,2,3,'Nano Pool','Biological Metamorphosis','Sensory Improvement');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (4,3,3,'Nano Pool','Biological Metamorphosis','Sensory Improvement');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (4,4,5,'Max Health','Matter Metamorphosis','Max Nano');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (4,5,5,'Max Health','Matter Metamorphosis','2h Blunt');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (4,6,3,'Nano Pool','Biological Metamorphosis','NanoC Init');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (4,7,5,'Max Health','Matter Metamorphosis','Sensory Improvement');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (4,8,5,'Max Health','Biological Metamorphosis','Strength');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (4,9,3,'Dimach','Biological Metamorphosis','Sensory Improvement');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (4,10,3,'Nano Pool','Matter Metamorphosis','Sensory Improvement');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (4,11,3,'Nano Pool','Matter Metamorphosis','Sensory Improvement');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (4,13,5,'Max Health','Projectile AC','Max Nano');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (4,14,5,5,'Matter Metamorphosis','Strength');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (3,1,4,'Perception','Tutoring','Intelligence');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (3,2,4,'Perception','Concealment','Psychological Modifications');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (3,3,2,'N/A','Psychology','Psychological Modifications');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (3,4,2,'N/A','Tutoring','Intelligence');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (3,5,1,'N/A','Concealment','Psychological Modifications');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (3,6,2,'N/A','Tutoring','Intelligence');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (3,7,2,'N/A','Tutoring','Psychic');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (3,8,2,'N/A','Psychology','Psychological Modifications');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (3,9,2,'N/A','Tutoring','Psychological Modifications');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (3,10,2,'N/A','Tutoring','Intelligence');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (3,11,4,'Perception','Tutoring','Intelligence');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (3,13,1,'N/A','Concealment','Psychological Modifications');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (3,14,4,'Perception','Tutoring','Intelligence');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (1,1,1,'N/A','Heavy Weapons','Matter Creation');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (1,2,1,'Rifle','Psychological Modifications','Time and Space');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (1,3,2,'Electrical Engineering','Psychological Modifications','Time and Space');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (1,4,2,'N/A','Treatment','Matter Creation');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (1,5,3,'N/A','Sensory Improvement','Matter Creation');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (1,6,2,'Tutoring','Intelligence','Time and Space');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (1,7,2,'Tutoring','Sensory Improvement','Time and Space');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (1,8,2,'N/A','Psychological Modificationsi','Time and Space');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (1,9,2,'Tutoring','Psychological Modifications','Time and Space');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (1,10,2,'Tutoring','Psychological Modifications','Time and Space');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (1,11,2,'Tutoring','Computer Literacy','Matter Creation');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (1,13,1,'Aimed Shot','Ranged Energy','Assault Rifle');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (1,14,4,'Map Navigation','Psychological Modifications','Time and Space');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (7,1,1,'Melee Init','Agility','Duck Explosions');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (7,2,1,'Concealment','Agility','Duck Explosions');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (7,3,1,'Evade Close','Dodge Ranged','Duck Explosions');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (7,4,1,'Evade Close','Dodge Ranged','Duck Explosions');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (7,5,1,'Evade Close','Agility','Duck Explosions');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (7,6,1,'Evade Close','Agility','Duck Explosions');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (7,7,1,'Evade Close','Agility','Duck Explosions');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (7,8,1,'Melee Init','Dodge Ranged','N/A');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (7,9,1,'Physical Init','Martial Arts','Duck Explosions');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (7,10,1,'Evade Close','Agility','Duck Explosions');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (7,11,1,'Evade Close','Dodge Ranged','Duck Explosions');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (7,13,1,'Evade Close','Agility','Duck Explosions');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (7,14,1,'Evade Close','Agility','Duck Explosions');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (2,1,2,'Biological Metamorphosis','Map Navigation','Sense');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (2,2,3,'Sensory Improvement','Ranged Init','Sense');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (2,3,2,'Matter Creation','Nano Pool','Tutoring');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (2,4,2,'Biological Metamorphosis','Nano Pool','Sense');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (2,5,1,'Biological Metamorphosis','N/A','Sense');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (2,6,2,'Matter Creation','Nano Pool','Tutoring');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (2,7,2,3,'Nano Pool','Tutoring');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (2,8,3,'Sensory Improvement','Dimach','Sense');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (2,9,4,'First Aid','Dimach','Sense');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (2,10,2,'Matter Creation','Nano Pool','Sense');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (2,11,3,'Matter Creation','Nano Pool','N/A');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (2,13,1,'Ranged Energy','Ranged Init','N/A');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (2,14,2,'Psychological Modifications','Ranged Init','Sense');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (8,1,6,'Brawling','Strength','Matter Metamorphosis');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (8,2,1,'N/A','Break and Entry','Matter Metamorphosis');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (8,3,1,'N/A','Break and Entry','Matter Metamorphosis');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (8,4,5,'N/A','Strength','Matter Metamorphosis');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (8,5,6,'Brawling','2h Blunt','Matter Metamorphosis');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (8,6,2,'N/A','N/A','Matter Metamorphosis');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (8,7,1,'N/A','Break and Entry','Matter Metamorphosis');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (8,8,1,'Brawling','2h Edged','N/A');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (8,9,6,'Brawling','Strength','Physical Init');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (8,10,1,'N/A','Break and Entry','Matter Metamorphosis');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (8,11,2,'N/A','N/A','Matter Metamorphosis');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (8,13,5,'N/A','Strength','Matter Metamorphosis');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (8,14,5,'N/A','Strength','Matter Metamorphosis');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (6,1,5,'Agility','Melee Init','Max Health');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (6,2,1,1,'Evade Close','N/A');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (6,3,5,'Agility','Evade Close','Body Development');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (6,4,1,'Dodge Ranged','Evade Close','Max Health');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (6,5,1,'Dodge Ranged','Evade Close','Max Health');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (6,6,1,1,'Evade Close','N/A');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (6,8,1,'Dodge Ranged','Evade Close','Max Health');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (6,9,5,'Agility','Evade Close','Max Health');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (6,10,5,'Agility','Stamina','Run Speed');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (6,11,1,'Dodge Ranged','Evade Close','Body Development');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (6,13,5,'Agility','Stamina','Max Health');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (6,14,5,'Agility','Evade Close','Max Health');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (10,1,1,'Fast Attack','Trap Disarm','First Aid');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (10,2,1,'N/A','Trap Disarm','First Aid');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (10,3,5,'N/A','Fire AC','First Aid');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (10,4,5,'N/A','Fire AC','First Aid');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (10,5,1,'Fast Attack','Fire AC','Cold AC');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (10,6,4,'N/A','N/A','First Aid');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (10,7,1,'N/A','Trap Disarm','First Aid');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (10,8,5,'Fast Attack','N/A','First Aid');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (10,9,5,'N/A','Fire AC','Martial Arts');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (10,10,5,'N/A','Fire AC','First Aid');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (10,11,1,'N/A','Trap Disarm','First Aid');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (10,13,5,'N/A','Fire AC','Ranged Energy');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (10,14,5,'N/A','Fire AC','First Aid');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (9,1,1,'Multi Melee','Run Speed','Nano Resist');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (9,2,1,'N/A','Run Speed','Rifle');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (9,3,1,'Multi Ranged','Run Speed','Nano Resist');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (9,4,1,'N/A','Run Speed','Nano Resist');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (9,5,1,'Multi Melee','Run Speed','Nano Resist');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (9,6,3,'N/A','N/A','Nano Resist');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (9,7,1,'N/A','Run Speed','Nano Resist');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (9,8,3,'N/A','Run Speed','N/A');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (9,9,1,'N/A','Run Speed','Nano Resist');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (9,10,1,'Multi Melee','Run Speed','Nano Resist');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (9,11,1,'N/A','Run Speed','Nano Resist');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (9,13,1,'N/A','Run Speed','Nano Resist');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (9,14,1,'Multi Ranged','Run Speed','Nano Resist');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (11,1,1,'1h Edged','Brawling','Fast Attack');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (11,2,1,'Fling Shot','Swimming','Mechanical Engineering');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (11,3,1,'Shotgun','Chemical AC','Mechanical Engineering');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (11,4,1,'Break and Entry','Chemical AC','Radiation AC');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (11,5,6,'1h Blunt','Brawling','Fast Attack');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (11,5,6,'2h Blunt','Brawling','Fast Attack');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (11,7,1,'MG/SMG','Chemical AC','Radiation AC');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (11,8,1,'2h Edged','Brawling','Fast Attack');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (11,9,5,6,'Physical Init','Radiation AC');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (11,10,6,'1h Blunt','Chemical AC','Radiation AC');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (11,13,1,'Assault Rifle','Swimming','Radiation AC');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (11,14,1,'Shotgun','Chemical AC','Radiation AC');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (13,1,1,'N/A','Fast Attack','1h Edged');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (13,1,1,'Trap Disarm','Pistol','Burst');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (13,2,2,'N/A','Time and Space','Computer Literacy');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (13,3,2,'N/A','Time and Space','Treatment');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (13,4,2,'N/A','Matter Creation','Treatment');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (13,5,2,'N/A','Matter Creation','1h Blunt');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (13,5,2,'N/A','Matter Creation','Treatment');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (13,6,2,'N/A','Time and Space','Treatment');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (13,7,2,'N/A','Time and Space','Burst');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (13,8,2,'N/A','Time and Space','Treatment');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (13,9,1,'Martial Arts','First Aid','Treatment');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (13,10,2,'N/A','Time and Space','1h Blunt');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (13,11,2,'N/A','Matter Creation','Computer Literacy');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (13,13,1,'N/A','Assault Rifle','Burst');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (13,14,1,'Trap Disarm','Time and Space','Computer Literacy');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (12,1,1,'Parry','1h Edged','Multi Melee');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (12,1,1,'Pistol','Multi Ranged','Fling Shot');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (12,2,1,'Ranged Init','Rifle','Fling Shot');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (12,3,1,'Ranged Init','Nano Resist','Fling Shot');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (12,4,1,'Pistol','Nano Resist','Fling');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (12,5,1,'Run Speed','1h Blunt','Multi Melee');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (12,5,1,'Run Speed','Nano Resist','Multi Melee');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (12,6,1,'Pistol','Nano Resist','Fling');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (12,7,5,'Run Speed','Burst','N/A');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (12,8,1,'Parry','N/A','N/A');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (12,9,3,'Riposite','Nano Resist','N/A');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (12,10,1,'Run Speed','1h Blunt','Multi Melee');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (12,11,1,'Pistol','Nano Resist','Fling');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (12,13,1,'Run Speed','Burst','Fling Shot');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (12,14,1,'Ranged Init','Burst','Fling Shot');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (5,1,4,'Chemical AC','Sense','Agility');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (5,1,6,'N/A','N/A','Brawling');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (5,2,1,'N/A','Duck Explosions','Biological Metamorphosis');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (5,3,4,'Radiation AC','Max Nano','Shotgun');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (5,4,4,'Chemical AC','Max Nano','Stamina');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (5,5,5,'Cold AC','Max Health','Brawling');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (5,6,3,'N/A','Max Nano','Biological Metamorphosis');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (5,7,5,'Fire AC','Max Health','Stamina');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (5,8,5,'N/A','Max Health','Biological Metamorphosis');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (5,9,4,'Radiation AC','Max Health','Evade Close');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (5,10,4,'Chemical AC','Max Nano','Biological Metamorphosis');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (5,11,3,'N/A','Max Nano','Biological Metamorphosis');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (5,13,5,'Cold AC','Max Health','Stamina');
INSERT INTO premade_implant (`ImplantTypeID`, `ProfessionID`, `AbilityID`, `shiny`, `bright`, `faded`) VALUES (5,14,4,'Chemical AC','Max Nano','Shotgun');