DROP TABLE IF EXISTS premade_implant;
CREATE TABLE premade_implant ( slot CHAR(20) NOT NULL, profession CHAR(20) NOT NULL, ability CHAR(20) NOT NULL, shiny char(30) NOT NULL, bright char(30) NOT NULL, faded CHAR(30) NOT NULL );
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('chest','adv','Stamina','Max Health','Mat Met','Sensory Imp');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('chest','agent','Psychic','Nano Pool','Bio Met','Sensory Imp');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('chest','crat','Psychic','Nano Pool','Bio Met','Sensory Imp');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('chest','doc','Stamina','Max Health','Mat Met','Max Nano');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('chest','enf','Stamina','Max Health','Mat Met','2h Blunt');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('chest','eng','Psychic','Nano Pool','Bio Met','NanoC Init');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('chest','fixer','Stamina','Max Health','Mat Met','Sensory Imp');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('chest','keeper','Stamina','Max Health','Bio Meta','Strength');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('chest','ma','Psychic','Dimach','Bio Met','Sensory Imp');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('chest','mp','Psychic','Nano Pool','Mat Met','Sensory Imp');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('chest','nt','Psychic','Nano Pool','Mat Met','Sensory Imp');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('chest','sol','Stamina','Max Health','Proj AC','Max Nano');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('chest','trader','Stamina','Stamina','Mat Met','Strength');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('ear','adv','Sense','Perception','Tutoring','Intelligence');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('ear','agent','Sense','Perception','Concealment','Psycho Mod');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('ear','crat','Intelligence','N/A','Psychology','Psycho Mod');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('ear','doc','Intelligence','N/A','Tutoring','Intelligence');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('ear','enf','Agility','N/A','Concealment','Psycho Mod');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('ear','eng','Intelligence','N/A','Tutoring','Intelligence');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('ear','fixer','Intelligence','N/A','Turoring','Psychic');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('ear','keeper','Intelligence','N/A','Psychology','Psycho Mod');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('ear','ma','Intelligence','N/A','Tutoring','Psycho Mod');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('ear','mp','Intelligence','N/A','Tutoring','Intelligence');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('ear','nt','Sense','Perception','Tutoring','Intelligence');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('ear','sol','Agility','N/A','Concealment','Psycho Mod');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('ear','trader','Sense','Perception','Tutoring','Intelligence');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('eye','adv','Agility','N/A','Heavy Weapons','Matter Crea');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('eye','agent','Agility','Rifle','Psycho Mod','Time&Space');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('eye','crat','Intelligence','Elec Eng','Psycho Mod','Time & Space');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('eye','doc','Intelligence','N/A','Treatment','Matter Crea');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('eye','enf','Psychic','N/A','Sensory Imp','Matter Crea');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('eye','eng','Intelligence','Tutoring','Intelligence','Time & Space');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('eye','fixer','Intelligence','Tutoring','Sensory Imp','Time & Space');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('eye','keeper','Intelligence','N/A','Psycho Modi','Time & Space');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('eye','ma','Intelligence','Tutoring','Psycho Mod','Time & Space');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('eye','mp','Intelligence','Tutoring','Psycho Mod','Time & Space');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('eye','nt','Intelligence','Tutoring','Comp Lit','Matter Crea');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('eye','sol','Agility','Aimed Shot','Ranged Energy','Assault Rifle');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('eye','trader','Sense','Map Nav','Psycho Mod','Time&Space');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('feet','adv','Agility','Melee Init','Agility','Duck Explosions');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('feet','agent','Agility','Concealment','Agility','Duck Explosions');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('feet','crat','Agility','Evade Close','Dodge Ranged','Duck Explosions');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('feet','doc','Agility','Evade Close','Dodge Ranged','Duck Explosions');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('feet','enf','Agility','Evade Close','Agility','Duck Explosions');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('feet','eng','Agility','Evade Close','Agility','Duck Explosions');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('feet','fixer','Agility','Evade Close','Agility','Duck Explosions');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('feet','keeper','Agility','Melee Init','Dodge Ranged','N/A');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('feet','ma','Agility','Phys Init','Martial Arts','Duck Explosions');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('feet','mp','Agility','Evade Close','Agility','Duck Explosions');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('feet','nt','Agility','Evade Close','Dodge Ranged','Duck Explosions');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('feet','sol','Agility','Evade Close','Agility','Duck Explosions');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('feet','trader','Agility','Evade Close','Agility','Duck Explosions');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('head','adv','Intelligence','Bio Met','Map Nav','Sense');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('head','agent','Psychic','Sensory Imp','Ranged Init','Sense');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('head','crat','Intelligence','Matter Crea','Nano Pool','Tutoring');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('head','doc','Intelligence','Bio Met','Nano Pool','Sense');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('head','enf','Agility','Bio Met','N/A','Sense');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('head','eng','Intelligence','Matter Crea','Nano Pool','Tutoring');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('head','fixer','Intelligence','Psychic','Nano Pool','Tutoring');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('head','keeper','Psychic','Sensory Imp','Dimach','Sense');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('head','ma','Sense','First Aid','Dimach','Sense');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('head','mp','Intelligence','Matter Crea','Nano Pool','Sense');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('head','nt','Psychic','Matter Crea','Nano Pool','N/A');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('head','sol','Agility','Ranged Energy','Ranged Init','N/A');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('head','trader','Intelligence','Psycho Mod','Ranged Init','Sense');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('larm','adv','Strength','Brawling','Strength','Mat Met');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('larm','agent','Agility','N/A','B&E','Mat Met');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('larm','crat','Agility','N/A','B&E','Mat Met');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('larm','doc','Stamina','N/A','Strength','Mat Met');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('larm','enf','Strength','Brawling','2h Blunt','Mat Met');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('larm','eng','Intelligence','N/A','N/A','Mat Met');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('larm','fixer','Agility','N/A','B&E','Mat Met');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('larm','keeper','Agility','Brawling','2h Edged','N/A');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('larm','ma','Strength','Brawling','Strength','Phys Init');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('larm','mp','Agility','N/A','B&E','Mat Met');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('larm','nt','Intelligence','N/A','N/A','Mat Met');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('larm','sol','Stamina','N/A','Strength','Mat Met');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('larm','trader','Stamina','N/A','Strength','Mat Met');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('legs','adv','Stamina','Agility','Melee Init','Max Health');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('legs','agent','Agility','Agility','Evade Close','N/A');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('legs','crat','Stamina','Agility','Evade Close','Body Dev');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('legs','doc','Agility','Dodge Ranged','Evade Close','Max Health');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('legs','enf','Agility','Dodge Ranged','Evade Close','Max Health');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('legs','eng','Agility','Agility','Evade Close','N/A');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('legs','keeper','Agility','Dodge Ranged','Evade Close','Max Health');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('legs','ma','Stamina','Agility','Evade Close','Max Health');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('legs','mp','Stamina','Agility','Stamina','Run Speed');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('legs','nt','Agility','Dodge Ranged','Evade Close','Body Dev');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('legs','sol','Stamina','Agility','Stamina','Max Health');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('legs','trader','Stamina','Agility','Evade Close','Max Health');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lhand','adv','Agility','Fast Attack','Trap Disarm','First Aid');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lhand','agent','Agility','N/A','Trap Disarm','First Aid');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lhand','crat','Stamina','N/A','Fire AC','First Aid');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lhand','doc','Stamina','N/A','Fire AC','First Aid');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lhand','enf','Agility','Fast Attack','Fire AC','Cold AC');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lhand','eng','Sense','N/A','N/A','First Aid');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lhand','fixer','Agility','N/A','Trap Disarm','First Aid');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lhand','keeper','Stamina','Fast Attack','N/A','First Aid');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lhand','ma','Stamina','N/A','Fire AC','Martial Arts');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lhand','mp','Stamina','N/A','Fire AC','First Aid');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lhand','nt','Agility','N/A','Trap Disarm','First Aid');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lhand','sol','Stamina','N/A','Fire AC','Ranged Energy');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lhand','trader','Stamina','N/A','Fire AC','First Aid');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lwrist','adv','Agility','Multi Melee','Run Speed','Nano Resist');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lwrist','agent','Agility','N/A','Run Speed','Rifle');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lwrist','crat','Agility','Multi Ranged','Run Speed','Nano Resist');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lwrist','doc','Agility','N/A','Run Speed','Nano Resist');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lwrist','enf','Agility','Multi Melee','Run Speed','Nano Resist');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lwrist','eng','Psychic','N/A','N/A','Nano Resist');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lwrist','fixer','Agility','N/A','Run Speed','Nano Resist');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lwrist','keeper','Psychic','N/A','Run Speed','N/A');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lwrist','ma','Agility','N/A','Run Speed','Nano Resist');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lwrist','mp','Agility','Multi Melee','Run Speed','Nano Resist');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lwrist','nt','Agility','N/A','Run Speed','Nano Resist');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lwrist','sol','Agility','N/A','Run Speed','Nano Resist');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lwrist','trader','Agility','Multi Ranged','Run Speed','Nano Resist');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rarm','adv','Agility','1h Edged','Brawling','Fast Attack');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rarm','agent','Agility','Fling Shot','Swimming','Mech Eng');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rarm','crat','Agility','Shotgun','Chem AC','Mech Eng');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rarm','doc','Agility','B&E','Chem AC','Rad AC');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rarm','enf','Strength','1h Blunt','Brawling','Fast Attack');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rarm','enf','Strength','2h Blunt','Brawling','Fast Attack');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rarm','fixer','Agility','MG/SMG','Chem AC','Rad AC');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rarm','keeper','Agility','2h Edged','Brawling','Fast Attack');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rarm','ma','Stamina','Strength','Phys Init','Rad AC');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rarm','mp','Strength','1h Blunt','Chem AC','Rad AC');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rarm','sol','Agility','Assault Rifle','Swimming','Rad AC');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rarm','trader','Agility','Shotgun','Chem AC','Rad AC');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rhand','adv','Agility','N/A','Fast Attack','1h Edged');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rhand','adv','Agility','Trap Disarm','Pistol','Burst');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rhand','agent','Intelligence','N/A','Time & Space','Comp Lit');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rhand','crat','Intelligence','N/A','Time & Space','Treatment');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rhand','doc','Intelligence','N/A','Matter Crea','Treatment');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rhand','enf','Intelligence','N/A','Matter Crea','1h Blunt');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rhand','enf','Intelligence','N/A','Matter Crea','Treatment');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rhand','eng','Intelligence','N/A','Time & Space','Treatment');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rhand','fixer','Intelligence','N/A','Time & Space','Burst');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rhand','keeper','Intelligence','N/A','Time & Space','Treatment');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rhand','ma','Agility','Martial Arts','First Aid','Treatment');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rhand','mp','Intelligence','N/A','Time & Space','1h Blunt');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rhand','nt','Intelligence','N/A','Matter Crea','Comp Lit');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rhand','sol','Agility','N/A','Assault Rifle','Burst');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rhand','trader','Agility','Trap Disarm','Time & Space','Comp Lit');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rwrist','adv','Agility','Parry','1h Edged','Multi Melee');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rwrist','adv','Agility','Pistol','Multi Ranged','Fling Shot');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rwrist','agent','Agility','Ranged Init','Rifle','Fling Shot');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rwrist','crat','Agility','Ranged Init','Nano Resist','Fling Shot');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rwrist','doc','Agility','Pistol','Nano Resist','Fling');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rwrist','enf','Agility','Run Speed','1h Blunt','Multi Melee');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rwrist','enf','Agility','Run Speed','Nano Resist','Multi Melee');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rwrist','eng','Agility','Pistol','Nano Resist','Fling');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rwrist','fixer','Stamina','Run Speed','Burst','N/A');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rwrist','keeper','Agility','Parry','N/A','N/A');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rwrist','ma','Psychic','Riposite','Nano Resist','N/A');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rwrist','mp','Agility','Run Speed','1h Blunt','Multi Melee');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rwrist','nt','Agility','Pistol','Nano Resist','Fling');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rwrist','sol','Agility','Run Speed','Burst','Fling Shot');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rwrist','trader','Agility','Ranged Init','Burst','Fling Shot');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('waist','adv','Sense','Chem AC','Sense','Agility');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('waist','adv','Strength','N/A','N/A','Brawling');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('waist','agent','Agility','N/A','Duck Explosions','Bio Met');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('waist','crat','Sense','Rad AC','Max Nano','Shotgun');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('waist','doc','Sense','Chem AC','Max Nano','Stamina');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('waist','enf','Stamina','Cold AC','Max Health','Brawling');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('waist','eng','Psychic','N/A','Max Nano','Bio Met');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('waist','fixer','Stamina','Fire AC','Max Health','Stamina');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('waist','keeper','Stamina','N/A','Max Health','Bio Meta');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('waist','ma','Sense','Rad AC','Max Health','Evade Close');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('waist','mp','Sense','Chem AC','Max Nano','Bio Met');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('waist','nt','Psychic','N/A','Max Nano','Bio Met');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('waist','sol','Stamina','Cold AC','Max Health','Stamina');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('waist','trader','Sense','Chem AC','Max Nano','Shotgun');