DROP TABLE IF EXISTS premade_implant;
CREATE TABLE premade_implant ( slot CHAR(20) NOT NULL, profession CHAR(20) NOT NULL, ability CHAR(20) NOT NULL, shiny char(30) NOT NULL, bright char(30) NOT NULL, faded CHAR(30) NOT NULL );
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('chest','Adventurer','Stamina','Max Health','Mat Met','Sensory Imp');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('chest','Agent','Psychic','Nano Pool','Bio Met','Sensory Imp');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('chest','Bureaucrat','Psychic','Nano Pool','Bio Met','Sensory Imp');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('chest','Doctor','Stamina','Max Health','Mat Met','Max Nano');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('chest','Enforcer','Stamina','Max Health','Mat Met','2h Blunt');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('chest','Engineer','Psychic','Nano Pool','Bio Met','NanoC Init');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('chest','Fixer','Stamina','Max Health','Mat Met','Sensory Imp');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('chest','Keeper','Stamina','Max Health','Bio Meta','Strength');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('chest','Martial Artist','Psychic','Dimach','Bio Met','Sensory Imp');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('chest','Meta-Physicist','Psychic','Nano Pool','Mat Met','Sensory Imp');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('chest','Nano-Technician','Psychic','Nano Pool','Mat Met','Sensory Imp');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('chest','Soldier','Stamina','Max Health','Proj AC','Max Nano');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('chest','Trader','Stamina','Stamina','Mat Met','Strength');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('ear','Adventurer','Sense','Perception','Tutoring','Intelligence');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('ear','Agent','Sense','Perception','Concealment','Psycho Mod');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('ear','Bureaucrat','Intelligence','N/A','Psychology','Psycho Mod');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('ear','Doctor','Intelligence','N/A','Tutoring','Intelligence');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('ear','Enforcer','Agility','N/A','Concealment','Psycho Mod');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('ear','Engineer','Intelligence','N/A','Tutoring','Intelligence');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('ear','Fixer','Intelligence','N/A','Turoring','Psychic');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('ear','Keeper','Intelligence','N/A','Psychology','Psycho Mod');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('ear','Martial Artist','Intelligence','N/A','Tutoring','Psycho Mod');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('ear','Meta-Physicist','Intelligence','N/A','Tutoring','Intelligence');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('ear','Nano-Technician','Sense','Perception','Tutoring','Intelligence');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('ear','Soldier','Agility','N/A','Concealment','Psycho Mod');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('ear','Trader','Sense','Perception','Tutoring','Intelligence');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('eye','Adventurer','Agility','N/A','Heavy Weapons','Matter Crea');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('eye','Agent','Agility','Rifle','Psycho Mod','Time&Space');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('eye','Bureaucrat','Intelligence','Elec Eng','Psycho Mod','Time & Space');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('eye','Doctor','Intelligence','N/A','Treatment','Matter Crea');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('eye','Enforcer','Psychic','N/A','Sensory Imp','Matter Crea');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('eye','Engineer','Intelligence','Tutoring','Intelligence','Time & Space');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('eye','Fixer','Intelligence','Tutoring','Sensory Imp','Time & Space');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('eye','Keeper','Intelligence','N/A','Psycho Modi','Time & Space');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('eye','Martial Artist','Intelligence','Tutoring','Psycho Mod','Time & Space');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('eye','Meta-Physicist','Intelligence','Tutoring','Psycho Mod','Time & Space');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('eye','Nano-Technician','Intelligence','Tutoring','Comp Lit','Matter Crea');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('eye','Soldier','Agility','Aimed Shot','Ranged Energy','Assault Rifle');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('eye','Trader','Sense','Map Nav','Psycho Mod','Time&Space');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('feet','Adventurer','Agility','Melee Init','Agility','Duck Explosions');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('feet','Agent','Agility','Concealment','Agility','Duck Explosions');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('feet','Bureaucrat','Agility','Evade Close','Dodge Ranged','Duck Explosions');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('feet','Doctor','Agility','Evade Close','Dodge Ranged','Duck Explosions');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('feet','Enforcer','Agility','Evade Close','Agility','Duck Explosions');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('feet','Engineer','Agility','Evade Close','Agility','Duck Explosions');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('feet','Fixer','Agility','Evade Close','Agility','Duck Explosions');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('feet','Keeper','Agility','Melee Init','Dodge Ranged','N/A');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('feet','Martial Artist','Agility','Phys Init','Martial Arts','Duck Explosions');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('feet','Meta-Physicist','Agility','Evade Close','Agility','Duck Explosions');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('feet','Nano-Technician','Agility','Evade Close','Dodge Ranged','Duck Explosions');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('feet','Soldier','Agility','Evade Close','Agility','Duck Explosions');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('feet','Trader','Agility','Evade Close','Agility','Duck Explosions');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('head','Adventurer','Intelligence','Bio Met','Map Nav','Sense');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('head','Agent','Psychic','Sensory Imp','Ranged Init','Sense');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('head','Bureaucrat','Intelligence','Matter Crea','Nano Pool','Tutoring');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('head','Doctor','Intelligence','Bio Met','Nano Pool','Sense');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('head','Enforcer','Agility','Bio Met','N/A','Sense');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('head','Engineer','Intelligence','Matter Crea','Nano Pool','Tutoring');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('head','Fixer','Intelligence','Psychic','Nano Pool','Tutoring');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('head','Keeper','Psychic','Sensory Imp','Dimach','Sense');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('head','Martial Artist','Sense','First Aid','Dimach','Sense');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('head','Meta-Physicist','Intelligence','Matter Crea','Nano Pool','Sense');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('head','Nano-Technician','Psychic','Matter Crea','Nano Pool','N/A');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('head','Soldier','Agility','Ranged Energy','Ranged Init','N/A');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('head','Trader','Intelligence','Psycho Mod','Ranged Init','Sense');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('larm','Adventurer','Strength','Brawling','Strength','Mat Met');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('larm','Agent','Agility','N/A','B&E','Mat Met');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('larm','Bureaucrat','Agility','N/A','B&E','Mat Met');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('larm','Doctor','Stamina','N/A','Strength','Mat Met');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('larm','Enforcer','Strength','Brawling','2h Blunt','Mat Met');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('larm','Engineer','Intelligence','N/A','N/A','Mat Met');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('larm','Fixer','Agility','N/A','B&E','Mat Met');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('larm','Keeper','Agility','Brawling','2h Edged','N/A');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('larm','Martial Artist','Strength','Brawling','Strength','Phys Init');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('larm','Meta-Physicist','Agility','N/A','B&E','Mat Met');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('larm','Nano-Technician','Intelligence','N/A','N/A','Mat Met');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('larm','Soldier','Stamina','N/A','Strength','Mat Met');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('larm','Trader','Stamina','N/A','Strength','Mat Met');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('legs','Adventurer','Stamina','Agility','Melee Init','Max Health');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('legs','Agent','Agility','Agility','Evade Close','N/A');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('legs','Bureaucrat','Stamina','Agility','Evade Close','Body Dev');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('legs','Doctor','Agility','Dodge Ranged','Evade Close','Max Health');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('legs','Enforcer','Agility','Dodge Ranged','Evade Close','Max Health');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('legs','Engineer','Agility','Agility','Evade Close','N/A');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('legs','Keeper','Agility','Dodge Ranged','Evade Close','Max Health');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('legs','Martial Artist','Stamina','Agility','Evade Close','Max Health');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('legs','Meta-Physicist','Stamina','Agility','Stamina','Run Speed');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('legs','Nano-Technician','Agility','Dodge Ranged','Evade Close','Body Dev');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('legs','Soldier','Stamina','Agility','Stamina','Max Health');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('legs','Trader','Stamina','Agility','Evade Close','Max Health');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lhand','Adventurer','Agility','Fast Attack','Trap Disarm','First Aid');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lhand','Agent','Agility','N/A','Trap Disarm','First Aid');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lhand','Bureaucrat','Stamina','N/A','Fire AC','First Aid');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lhand','Doctor','Stamina','N/A','Fire AC','First Aid');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lhand','Enforcer','Agility','Fast Attack','Fire AC','Cold AC');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lhand','Engineer','Sense','N/A','N/A','First Aid');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lhand','Fixer','Agility','N/A','Trap Disarm','First Aid');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lhand','Keeper','Stamina','Fast Attack','N/A','First Aid');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lhand','Martial Artist','Stamina','N/A','Fire AC','Martial Arts');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lhand','Meta-Physicist','Stamina','N/A','Fire AC','First Aid');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lhand','Nano-Technician','Agility','N/A','Trap Disarm','First Aid');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lhand','Soldier','Stamina','N/A','Fire AC','Ranged Energy');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lhand','Trader','Stamina','N/A','Fire AC','First Aid');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lwrist','Adventurer','Agility','Multi Melee','Run Speed','Nano Resist');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lwrist','Agent','Agility','N/A','Run Speed','Rifle');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lwrist','Bureaucrat','Agility','Multi Ranged','Run Speed','Nano Resist');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lwrist','Doctor','Agility','N/A','Run Speed','Nano Resist');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lwrist','Enforcer','Agility','Multi Melee','Run Speed','Nano Resist');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lwrist','Engineer','Psychic','N/A','N/A','Nano Resist');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lwrist','Fixer','Agility','N/A','Run Speed','Nano Resist');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lwrist','Keeper','Psychic','N/A','Run Speed','N/A');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lwrist','Martial Artist','Agility','N/A','Run Speed','Nano Resist');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lwrist','Meta-Physicist','Agility','Multi Melee','Run Speed','Nano Resist');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lwrist','Nano-Technician','Agility','N/A','Run Speed','Nano Resist');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lwrist','Soldier','Agility','N/A','Run Speed','Nano Resist');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('lwrist','Trader','Agility','Multi Ranged','Run Speed','Nano Resist');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rarm','Adventurer','Agility','1h Edged','Brawling','Fast Attack');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rarm','Agent','Agility','Fling Shot','Swimming','Mech Eng');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rarm','Bureaucrat','Agility','Shotgun','Chem AC','Mech Eng');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rarm','Doctor','Agility','B&E','Chem AC','Rad AC');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rarm','Enforcer','Strength','1h Blunt','Brawling','Fast Attack');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rarm','Enforcer','Strength','2h Blunt','Brawling','Fast Attack');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rarm','Fixer','Agility','MG/SMG','Chem AC','Rad AC');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rarm','Keeper','Agility','2h Edged','Brawling','Fast Attack');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rarm','Martial Artist','Stamina','Strength','Phys Init','Rad AC');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rarm','Meta-Physicist','Strength','1h Blunt','Chem AC','Rad AC');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rarm','Soldier','Agility','Assault Rifle','Swimming','Rad AC');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rarm','Trader','Agility','Shotgun','Chem AC','Rad AC');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rhand','Adventurer','Agility','N/A','Fast Attack','1h Edged');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rhand','Adventurer','Agility','Trap Disarm','Pistol','Burst');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rhand','Agent','Intelligence','N/A','Time & Space','Comp Lit');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rhand','Bureaucrat','Intelligence','N/A','Time & Space','Treatment');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rhand','Doctor','Intelligence','N/A','Matter Crea','Treatment');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rhand','Enforcer','Intelligence','N/A','Matter Crea','1h Blunt');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rhand','Enforcer','Intelligence','N/A','Matter Crea','Treatment');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rhand','Engineer','Intelligence','N/A','Time & Space','Treatment');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rhand','Fixer','Intelligence','N/A','Time & Space','Burst');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rhand','Keeper','Intelligence','N/A','Time & Space','Treatment');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rhand','Martial Artist','Agility','Martial Arts','First Aid','Treatment');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rhand','Meta-Physicist','Intelligence','N/A','Time & Space','1h Blunt');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rhand','Nano-Technician','Intelligence','N/A','Matter Crea','Comp Lit');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rhand','Soldier','Agility','N/A','Assault Rifle','Burst');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rhand','Trader','Agility','Trap Disarm','Time & Space','Comp Lit');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rwrist','Adventurer','Agility','Parry','1h Edged','Multi Melee');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rwrist','Adventurer','Agility','Pistol','Multi Ranged','Fling Shot');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rwrist','Agent','Agility','Ranged Init','Rifle','Fling Shot');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rwrist','Bureaucrat','Agility','Ranged Init','Nano Resist','Fling Shot');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rwrist','Doctor','Agility','Pistol','Nano Resist','Fling');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rwrist','Enforcer','Agility','Run Speed','1h Blunt','Multi Melee');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rwrist','Enforcer','Agility','Run Speed','Nano Resist','Multi Melee');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rwrist','Engineer','Agility','Pistol','Nano Resist','Fling');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rwrist','Fixer','Stamina','Run Speed','Burst','N/A');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rwrist','Keeper','Agility','Parry','N/A','N/A');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rwrist','Martial Artist','Psychic','Riposite','Nano Resist','N/A');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rwrist','Meta-Physicist','Agility','Run Speed','1h Blunt','Multi Melee');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rwrist','Nano-Technician','Agility','Pistol','Nano Resist','Fling');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rwrist','Soldier','Agility','Run Speed','Burst','Fling Shot');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('rwrist','Trader','Agility','Ranged Init','Burst','Fling Shot');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('waist','Adventurer','Sense','Chem AC','Sense','Agility');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('waist','Adventurer','Strength','N/A','N/A','Brawling');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('waist','Agent','Agility','N/A','Duck Explosions','Bio Met');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('waist','Bureaucrat','Sense','Rad AC','Max Nano','Shotgun');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('waist','Doctor','Sense','Chem AC','Max Nano','Stamina');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('waist','Enforcer','Stamina','Cold AC','Max Health','Brawling');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('waist','Engineer','Psychic','N/A','Max Nano','Bio Met');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('waist','Fixer','Stamina','Fire AC','Max Health','Stamina');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('waist','Keeper','Stamina','N/A','Max Health','Bio Meta');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('waist','Martial Artist','Sense','Rad AC','Max Health','Evade Close');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('waist','Meta-Physicist','Sense','Chem AC','Max Nano','Bio Met');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('waist','Nano-Technician','Psychic','N/A','Max Nano','Bio Met');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('waist','Soldier','Stamina','Cold AC','Max Health','Stamina');
INSERT INTO premade_implant (`slot`, `profession`, `ability`, `shiny`, `bright`, `faded`) VALUES ('waist','Trader','Sense','Chem AC','Max Nano','Shotgun');