DROP TABLE IF EXISTS skills;
CREATE TABLE skills (id INT NOT NULL PRIMARY KEY, name VARCHAR(50) NOT NULL);
INSERT INTO skills (id, name) VALUES (525, "% Health");
INSERT INTO skills (id, name) VALUES (102, "1h Blunt");
INSERT INTO skills (id, name) VALUES (103, "1h Edged");
INSERT INTO skills (id, name) VALUES (107, "2h Blunt");
INSERT INTO skills (id, name) VALUES (105, "2h Edged");
INSERT INTO skills (id, name) VALUES (660, "AccountFlags");
INSERT INTO skills (id, name) VALUES (137, "Adventuring");
INSERT INTO skills (id, name) VALUES (17, "Agility");
INSERT INTO skills (id, name) VALUES (151, "Aimed Shot");
INSERT INTO skills (id, name) VALUES (169, "Alien Defender Title");
INSERT INTO skills (id, name) VALUES (116, "Assault Rif");
INSERT INTO skills (id, name) VALUES (349, "AutoAttackFlags");
INSERT INTO skills (id, name) VALUES (62, "Awarded Clan Tokens");
INSERT INTO skills (id, name) VALUES (75, "Awarded Omni-Tek Tokens");
INSERT INTO skills (id, name) VALUES (668, "Battlestation Side");
INSERT INTO skills (id, name) VALUES (128, "Bio Metamor");
INSERT INTO skills (id, name) VALUES (152, "Body Dev.");
INSERT INTO skills (id, name) VALUES (111, "Bow");
INSERT INTO skills (id, name) VALUES (121, "Bow Spc Att");
INSERT INTO skills (id, name) VALUES (142, "Brawling");
INSERT INTO skills (id, name) VALUES (165, "Break&amp;Entry");
INSERT INTO skills (id, name) VALUES (4, "Breed");
INSERT INTO skills (id, name) VALUES (148, "Burst");
INSERT INTO skills (id, name) VALUES (434, "CharState");
INSERT INTO skills (id, name) VALUES (163, "Chemistry");
INSERT INTO skills (id, name) VALUES (95, "Cold AC");
INSERT INTO skills (id, name) VALUES (161, "Comp. Liter");
INSERT INTO skills (id, name) VALUES (164, "Concealment");
INSERT INTO skills (id, name) VALUES (61, "Credit");
INSERT INTO skills (id, name) VALUES (173, "CurrentMovementMode");
INSERT INTO skills (id, name) VALUES (145, "Deflect");
INSERT INTO skills (id, name) VALUES (144, "Dimach");
INSERT INTO skills (id, name) VALUES (154, "Dodge-Rng");
INSERT INTO skills (id, name) VALUES (126, "Elec. Engi");
INSERT INTO skills (id, name) VALUES (92, "Energy AC");
INSERT INTO skills (id, name) VALUES (274, "Equipped Weapon Type");
INSERT INTO skills (id, name) VALUES (155, "Evade-ClsC");
INSERT INTO skills (id, name) VALUES (531, "ExpansionPlayfield");
INSERT INTO skills (id, name) VALUES (389, "Expansions");
INSERT INTO skills (id, name) VALUES (567, "Faction with Followers");
INSERT INTO skills (id, name) VALUES (566, "Faction with Guardian of Shadow");
INSERT INTO skills (id, name) VALUES (568, "Faction with The Assertive Operators");
INSERT INTO skills (id, name) VALUES (571, "Faction with The Benign Conservers");
INSERT INTO skills (id, name) VALUES (570, "Faction with The Devoted");
INSERT INTO skills (id, name) VALUES (572, "Faction with The Redeemed");
INSERT INTO skills (id, name) VALUES (569, "Faction with The Unredeemed");
INSERT INTO skills (id, name) VALUES (147, "Fast Attack");
INSERT INTO skills (id, name) VALUES (97, "Fire AC");
INSERT INTO skills (id, name) VALUES (123, "First Aid");
INSERT INTO skills (id, name) VALUES (0, "Flags");
INSERT INTO skills (id, name) VALUES (150, "Fling Shot");
INSERT INTO skills (id, name) VALUES (167, "Full Auto");
INSERT INTO skills (id, name) VALUES (59, "Gender");
INSERT INTO skills (id, name) VALUES (47, "Girth");
INSERT INTO skills (id, name) VALUES (215, "GM Level");
INSERT INTO skills (id, name) VALUES (109, "Grenade");
INSERT INTO skills (id, name) VALUES (65, "HairTexture");
INSERT INTO skills (id, name) VALUES (64, "HeadMesh");
INSERT INTO skills (id, name) VALUES (27, "Health");
INSERT INTO skills (id, name) VALUES (110, "Heavy Weapons");
INSERT INTO skills (id, name) VALUES (410, "InFight");
INSERT INTO skills (id, name) VALUES (19, "Intelligence");
INSERT INTO skills (id, name) VALUES (54, "Level");
INSERT INTO skills (id, name) VALUES (140, "Map Navig.");
INSERT INTO skills (id, name) VALUES (586, "MapArea");
INSERT INTO skills (id, name) VALUES (471, "MapFlags1");
INSERT INTO skills (id, name) VALUES (472, "MapFlags2");
INSERT INTO skills (id, name) VALUES (470, "MapOptions");
INSERT INTO skills (id, name) VALUES (100, "Martial Arts");
INSERT INTO skills (id, name) VALUES (127, "Matt.Metam");
INSERT INTO skills (id, name) VALUES (130, "Matter Crea");
INSERT INTO skills (id, name) VALUES (1, "Max Health");
INSERT INTO skills (id, name) VALUES (221, "Max Nano");
INSERT INTO skills (id, name) VALUES (125, "Mech. Engi");
INSERT INTO skills (id, name) VALUES (104, "Melee Ener.");
INSERT INTO skills (id, name) VALUES (118, "Melee. Init.");
INSERT INTO skills (id, name) VALUES (114, "MG / SMG");
INSERT INTO skills (id, name) VALUES (686, "Mission Bits 15");
INSERT INTO skills (id, name) VALUES (257, "Mission Bits 2");
INSERT INTO skills (id, name) VALUES (455, "Monster Type");
INSERT INTO skills (id, name) VALUES (101, "Mult. Melee");
INSERT INTO skills (id, name) VALUES (134, "Multi Ranged");
INSERT INTO skills (id, name) VALUES (214, "Nano Points");
INSERT INTO skills (id, name) VALUES (132, "Nano Pool");
INSERT INTO skills (id, name) VALUES (160, "Nano Progra");
INSERT INTO skills (id, name) VALUES (168, "Nano Resist");
INSERT INTO skills (id, name) VALUES (251, "Number of pets");
INSERT INTO skills (id, name) VALUES (587, "Number of team members");
INSERT INTO skills (id, name) VALUES (5, "Organization");
INSERT INTO skills (id, name) VALUES (136, "Perception");
INSERT INTO skills (id, name) VALUES (159, "Pharma Tech");
INSERT INTO skills (id, name) VALUES (106, "Piercing");
INSERT INTO skills (id, name) VALUES (112, "Pistol");
INSERT INTO skills (id, name) VALUES (589, "Playfield");
INSERT INTO skills (id, name) VALUES (438, "Playfield type");
INSERT INTO skills (id, name) VALUES (10, "Prof.Title Lvl");
INSERT INTO skills (id, name) VALUES (60, "Profession");
INSERT INTO skills (id, name) VALUES (21, "Psychic");
INSERT INTO skills (id, name) VALUES (129, "Psycho Modi");
INSERT INTO skills (id, name) VALUES (162, "Psychology");
INSERT INTO skills (id, name) VALUES (157, "Quantum FT");
INSERT INTO skills (id, name) VALUES (520, "RandomNumberRoll");
INSERT INTO skills (id, name) VALUES (133, "Ranged Ener");
INSERT INTO skills (id, name) VALUES (119, "Ranged. Init.");
INSERT INTO skills (id, name) VALUES (206, "ReflectMeleeAC");
INSERT INTO skills (id, name) VALUES (526, "RemainingNano");
INSERT INTO skills (id, name) VALUES (690, "RHandWeaponType");
INSERT INTO skills (id, name) VALUES (113, "Rifle");
INSERT INTO skills (id, name) VALUES (143, "Riposte");
INSERT INTO skills (id, name) VALUES (156, "Run Speed");
INSERT INTO skills (id, name) VALUES (273, "Secondary Item Template ID");
INSERT INTO skills (id, name) VALUES (431, "Selected target");
INSERT INTO skills (id, name) VALUES (397, "SelectedTargetType");
INSERT INTO skills (id, name) VALUES (20, "Sense");
INSERT INTO skills (id, name) VALUES (122, "Sensory Impr");
INSERT INTO skills (id, name) VALUES (359, "ShapeShift");
INSERT INTO skills (id, name) VALUES (108, "Sharp Obj");
INSERT INTO skills (id, name) VALUES (229, "ShieldChemicalAC");
INSERT INTO skills (id, name) VALUES (231, "ShieldColdAC");
INSERT INTO skills (id, name) VALUES (228, "ShieldEnergyAC");
INSERT INTO skills (id, name) VALUES (233, "ShieldFireAC");
INSERT INTO skills (id, name) VALUES (227, "ShieldMeleeAC");
INSERT INTO skills (id, name) VALUES (234, "ShieldPoisonAC");
INSERT INTO skills (id, name) VALUES (226, "ShieldProjectileAC");
INSERT INTO skills (id, name) VALUES (230, "ShieldRadiationAC");
INSERT INTO skills (id, name) VALUES (115, "Shotgun");
INSERT INTO skills (id, name) VALUES (33, "Side");
INSERT INTO skills (id, name) VALUES (146, "Sneak Atck");
INSERT INTO skills (id, name) VALUES (182, "Specialization");
INSERT INTO skills (id, name) VALUES (18, "Stamina");
INSERT INTO skills (id, name) VALUES (16, "Strength");
INSERT INTO skills (id, name) VALUES (889, "TargetDistanceChange");
INSERT INTO skills (id, name) VALUES (488, "TargetFacing");
INSERT INTO skills (id, name) VALUES (6, "Team");
INSERT INTO skills (id, name) VALUES (247, "TemporarySkillReduction");
INSERT INTO skills (id, name) VALUES (131, "Time&amp;Space");
INSERT INTO skills (id, name) VALUES (37, "TitleLevel");
INSERT INTO skills (id, name) VALUES (124, "Treatment");
INSERT INTO skills (id, name) VALUES (141, "Tutoring");
INSERT INTO skills (id, name) VALUES (662, "Use Mech");
INSERT INTO skills (id, name) VALUES (139, "Vehicle Air");
INSERT INTO skills (id, name) VALUES (166, "Vehicle Ground");
INSERT INTO skills (id, name) VALUES (117, "Vehicle Water");
INSERT INTO skills (id, name) VALUES (368, "VisualProfession");
INSERT INTO skills (id, name) VALUES (430, "WaitState");
INSERT INTO skills (id, name) VALUES (158, "Weapon Smt");
INSERT INTO skills (id, name) VALUES (355, "WornItem");