DROP TABLE IF EXISTS skills;
CREATE TABLE skills (name VARCHAR(50) NOT NULL, common INT NOT NULL);
INSERT INTO skills (name, common) VALUES ('1h Blunt', 1);
INSERT INTO skills (name, common) VALUES ('1h Edged', 1);
INSERT INTO skills (name, common) VALUES ('2h Blunt', 1);
INSERT INTO skills (name, common) VALUES ('2h Edged', 1);
INSERT INTO skills (name, common) VALUES ('Absorb chemical damage', 0);
INSERT INTO skills (name, common) VALUES ('Absorb cold damage', 0);
INSERT INTO skills (name, common) VALUES ('Absorb energy damage', 0);
INSERT INTO skills (name, common) VALUES ('Absorb fire damage', 0);
INSERT INTO skills (name, common) VALUES ('Absorb hits', 0);
INSERT INTO skills (name, common) VALUES ('Absorb melee damage', 0);
INSERT INTO skills (name, common) VALUES ('Absorb poison damage', 0);
INSERT INTO skills (name, common) VALUES ('Absorb projectile damage', 0);
INSERT INTO skills (name, common) VALUES ('Absorb radiation damage', 0);
INSERT INTO skills (name, common) VALUES ('Absorb special attacks', 0);
INSERT INTO skills (name, common) VALUES ('Adventuring', 1);
INSERT INTO skills (name, common) VALUES ('Agg/Def', 1);
INSERT INTO skills (name, common) VALUES ('Aggressiveness', 0);
INSERT INTO skills (name, common) VALUES ('Agility', 1);
INSERT INTO skills (name, common) VALUES ('Aimed shot', 1);
INSERT INTO skills (name, common) VALUES ('Alien level', 0);
INSERT INTO skills (name, common) VALUES ('Assault rifle', 1);
INSERT INTO skills (name, common) VALUES ('Attack modifier', 1);
INSERT INTO skills (name, common) VALUES ('Attack rating cap', 0);
INSERT INTO skills (name, common) VALUES ('Attack time cap', 0);
INSERT INTO skills (name, common) VALUES ('Attribute 0xad', 0);
INSERT INTO skills (name, common) VALUES ('Behind target', 0);
INSERT INTO skills (name, common) VALUES ('Belt decks', 1);
INSERT INTO skills (name, common) VALUES ('Biological metamorphosis', 1);
INSERT INTO skills (name, common) VALUES ('Body development', 1);
INSERT INTO skills (name, common) VALUES ('Bow', 1);
INSERT INTO skills (name, common) VALUES ('Bow special attack', 1);
INSERT INTO skills (name, common) VALUES ('Brawl', 1);
INSERT INTO skills (name, common) VALUES ('Breaking and entry', 1);
INSERT INTO skills (name, common) VALUES ('Breed', 1);
INSERT INTO skills (name, common) VALUES ('Burst', 1);
INSERT INTO skills (name, common) VALUES ('Burst cycle', 0);
INSERT INTO skills (name, common) VALUES ('Chance of break on attack', 0);
INSERT INTO skills (name, common) VALUES ('Chance of break on debuff', 0);
INSERT INTO skills (name, common) VALUES ('Chance of break on nano', 0);
INSERT INTO skills (name, common) VALUES ('Character state', 0);
INSERT INTO skills (name, common) VALUES ('Chemical AC', 0);
INSERT INTO skills (name, common) VALUES ('Chemical damage modifier', 1);
INSERT INTO skills (name, common) VALUES ('Chemistry', 1);
INSERT INTO skills (name, common) VALUES ('Clan tokens', 0);
INSERT INTO skills (name, common) VALUES ('Cold AC', 0);
INSERT INTO skills (name, common) VALUES ('Cold damage modifier', 1);
INSERT INTO skills (name, common) VALUES ('Computer literacy', 1);
INSERT INTO skills (name, common) VALUES ('Concealment', 1);
INSERT INTO skills (name, common) VALUES ('Credits', 0);
INSERT INTO skills (name, common) VALUES ('Critical chance', 1);
INSERT INTO skills (name, common) VALUES ('Critical decrease', 1);
INSERT INTO skills (name, common) VALUES ('Current nano', 0);
INSERT INTO skills (name, common) VALUES ('Cyberdeck', 1);
INSERT INTO skills (name, common) VALUES ('Damage type', 1);
INSERT INTO skills (name, common) VALUES ('Defense modifier', 1);
INSERT INTO skills (name, common) VALUES ('Dimach', 1);
INSERT INTO skills (name, common) VALUES ('Distinance to target delta', 0);
INSERT INTO skills (name, common) VALUES ('Dodge ranged', 1);
INSERT INTO skills (name, common) VALUES ('Duck explosives', 1);
INSERT INTO skills (name, common) VALUES ('Effect icon', 0);
INSERT INTO skills (name, common) VALUES ('Electrical engineering', 1);
INSERT INTO skills (name, common) VALUES ('Energy', 1);
INSERT INTO skills (name, common) VALUES ('Energy AC', 0);
INSERT INTO skills (name, common) VALUES ('Energy damage modifier', 1);
INSERT INTO skills (name, common) VALUES ('Evade close', 1);
INSERT INTO skills (name, common) VALUES ('Expansion sets', 1);
INSERT INTO skills (name, common) VALUES ('Experience', 0);
INSERT INTO skills (name, common) VALUES ('Experience modifier', 0);
INSERT INTO skills (name, common) VALUES ('Experience recovery', 0);
INSERT INTO skills (name, common) VALUES ('Experience regain percentage', 0);
INSERT INTO skills (name, common) VALUES ('Faction', 0);
INSERT INTO skills (name, common) VALUES ('Faction Conserver', 0);
INSERT INTO skills (name, common) VALUES ('Faction Devoted', 0);
INSERT INTO skills (name, common) VALUES ('Faction Followers', 0);
INSERT INTO skills (name, common) VALUES ('Faction Operators', 0);
INSERT INTO skills (name, common) VALUES ('Faction Redeemed', 0);
INSERT INTO skills (name, common) VALUES ('Faction Unredeemed', 0);
INSERT INTO skills (name, common) VALUES ('Fast attack', 1);
INSERT INTO skills (name, common) VALUES ('Fatness', 0);
INSERT INTO skills (name, common) VALUES ('Features', 0);
INSERT INTO skills (name, common) VALUES ('Fire AC', 0);
INSERT INTO skills (name, common) VALUES ('Fire damage modifier', 1);
INSERT INTO skills (name, common) VALUES ('First aid', 1);
INSERT INTO skills (name, common) VALUES ('Fling shot', 1);
INSERT INTO skills (name, common) VALUES ('Form', 0);
INSERT INTO skills (name, common) VALUES ('Full auto', 1);
INSERT INTO skills (name, common) VALUES ('Fullauto cycle', 0);
INSERT INTO skills (name, common) VALUES ('GM level', 0);
INSERT INTO skills (name, common) VALUES ('GOS', 0);
INSERT INTO skills (name, common) VALUES ('Gender', 0);
INSERT INTO skills (name, common) VALUES ('Grenade', 1);
INSERT INTO skills (name, common) VALUES ('Have apartment', 0);
INSERT INTO skills (name, common) VALUES ('Heal delta', 1);
INSERT INTO skills (name, common) VALUES ('Heal interval', 0);
INSERT INTO skills (name, common) VALUES ('Heal modifier', 0);
INSERT INTO skills (name, common) VALUES ('Health', 0);
INSERT INTO skills (name, common) VALUES ('Heavy weapons', 1);
INSERT INTO skills (name, common) VALUES ('IP', 0);
INSERT INTO skills (name, common) VALUES ('In battle', 0);
INSERT INTO skills (name, common) VALUES ('Initiative skill', 0);
INSERT INTO skills (name, common) VALUES ('Inside Shadowlands', 0);
INSERT INTO skills (name, common) VALUES ('Intelligence', 1);
INSERT INTO skills (name, common) VALUES ('Last random roll', 0);
INSERT INTO skills (name, common) VALUES ('Level', 0);
INSERT INTO skills (name, common) VALUES ('Lock difficulty', 0);
INSERT INTO skills (name, common) VALUES ('Map navigation', 1);
INSERT INTO skills (name, common) VALUES ('Map upgrades', 0);
INSERT INTO skills (name, common) VALUES ('Maps A', 0);
INSERT INTO skills (name, common) VALUES ('Maps B', 0);
INSERT INTO skills (name, common) VALUES ('Maps C', 0);
INSERT INTO skills (name, common) VALUES ('Maps D', 0);
INSERT INTO skills (name, common) VALUES ('Martial arts', 1);
INSERT INTO skills (name, common) VALUES ('Mass', 0);
INSERT INTO skills (name, common) VALUES ('Matter creation', 1);
INSERT INTO skills (name, common) VALUES ('Matter metamorphosis', 1);
INSERT INTO skills (name, common) VALUES ('Max health', 1);
INSERT INTO skills (name, common) VALUES ('Max nano', 1);
INSERT INTO skills (name, common) VALUES ('Maximum chemical reflect', 0);
INSERT INTO skills (name, common) VALUES ('Maximum cold reflect', 0);
INSERT INTO skills (name, common) VALUES ('Maximum damage', 0);
INSERT INTO skills (name, common) VALUES ('Maximum energy reflect', 0);
INSERT INTO skills (name, common) VALUES ('Maximum fire reflect', 0);
INSERT INTO skills (name, common) VALUES ('Maximum melee reflect', 0);
INSERT INTO skills (name, common) VALUES ('Maximum nano reflect', 0);
INSERT INTO skills (name, common) VALUES ('Maximum poison reflect', 0);
INSERT INTO skills (name, common) VALUES ('Maximum projectile reflect', 0);
INSERT INTO skills (name, common) VALUES ('Maximum radiation reflect', 0);
INSERT INTO skills (name, common) VALUES ('Mechanical engineering', 0);
INSERT INTO skills (name, common) VALUES ('Melee AC', 0);
INSERT INTO skills (name, common) VALUES ('Melee damage modifier', 1);
INSERT INTO skills (name, common) VALUES ('Melee energy', 1);
INSERT INTO skills (name, common) VALUES ('Melee init', 1);
INSERT INTO skills (name, common) VALUES ('Minimum damage', 0);
INSERT INTO skills (name, common) VALUES ('Multi melee', 1);
INSERT INTO skills (name, common) VALUES ('Multi ranged', 1);
INSERT INTO skills (name, common) VALUES ('NCU memory', 1);
INSERT INTO skills (name, common) VALUES ('NPC hatelist size', 0);
INSERT INTO skills (name, common) VALUES ('NPC type', 0);
INSERT INTO skills (name, common) VALUES ('Nano attack damage modifier', 1);
INSERT INTO skills (name, common) VALUES ('Nano cost modifier', 1);
INSERT INTO skills (name, common) VALUES ('Nano damage modifier', 1);
INSERT INTO skills (name, common) VALUES ('Nano delta', 1);
INSERT INTO skills (name, common) VALUES ('Nano init', 1);
INSERT INTO skills (name, common) VALUES ('Nano interrupt chance', 1);
INSERT INTO skills (name, common) VALUES ('Nano pool', 1);
INSERT INTO skills (name, common) VALUES ('Nano programming', 1);
INSERT INTO skills (name, common) VALUES ('Nano range', 1);
INSERT INTO skills (name, common) VALUES ('Nano resist', 1);
INSERT INTO skills (name, common) VALUES ('Nano vulnerability', 0);
INSERT INTO skills (name, common) VALUES ('Number of team members', 0);
INSERT INTO skills (name, common) VALUES ('Object', 0);
INSERT INTO skills (name, common) VALUES ('Offense modifier', 1);
INSERT INTO skills (name, common) VALUES ('Omni tokens', 0);
INSERT INTO skills (name, common) VALUES ('Organization', 0);
INSERT INTO skills (name, common) VALUES ('Organization rank', 0);
INSERT INTO skills (name, common) VALUES ('Organization upkeep', 0);
INSERT INTO skills (name, common) VALUES ('Parry', 1);
INSERT INTO skills (name, common) VALUES ('Percentage of health', 0);
INSERT INTO skills (name, common) VALUES ('Perception', 1);
INSERT INTO skills (name, common) VALUES ('Pets', 0);
INSERT INTO skills (name, common) VALUES ('Pharmaceuticals', 1);
INSERT INTO skills (name, common) VALUES ('Physical init', 1);
INSERT INTO skills (name, common) VALUES ('Piercing', 1);
INSERT INTO skills (name, common) VALUES ('Pistol', 1);
INSERT INTO skills (name, common) VALUES ('Playfield proxy', 0);
INSERT INTO skills (name, common) VALUES ('Playfield type', 0);
INSERT INTO skills (name, common) VALUES ('Poison AC', 0);
INSERT INTO skills (name, common) VALUES ('Poison damage modifier', 1);
INSERT INTO skills (name, common) VALUES ('Proc chance 1', 0);
INSERT INTO skills (name, common) VALUES ('Proc chance 2', 0);
INSERT INTO skills (name, common) VALUES ('Proc initiative 1', 0);
INSERT INTO skills (name, common) VALUES ('Proc initiative 2', 0);
INSERT INTO skills (name, common) VALUES ('Proc nano 1', 0);
INSERT INTO skills (name, common) VALUES ('Proc nano 2', 0);
INSERT INTO skills (name, common) VALUES ('Profession', 0);
INSERT INTO skills (name, common) VALUES ('Profession level', 0);
INSERT INTO skills (name, common) VALUES ('Projectile AC', 0);
INSERT INTO skills (name, common) VALUES ('Projectile damage modifier', 1);
INSERT INTO skills (name, common) VALUES ('Psychic', 1);
INSERT INTO skills (name, common) VALUES ('Psychological modifications', 1);
INSERT INTO skills (name, common) VALUES ('Psychology', 1);
INSERT INTO skills (name, common) VALUES ('Quantum physics', 1);
INSERT INTO skills (name, common) VALUES ('Radiation AC', 0);
INSERT INTO skills (name, common) VALUES ('Radiation damage modifier', 1);
INSERT INTO skills (name, common) VALUES ('Random roll', 0);
INSERT INTO skills (name, common) VALUES ('Ranged energy', 1);
INSERT INTO skills (name, common) VALUES ('Ranged init', 1);
INSERT INTO skills (name, common) VALUES ('Recharge time cap', 0);
INSERT INTO skills (name, common) VALUES ('Reflect chemical damage', 0);
INSERT INTO skills (name, common) VALUES ('Reflect cold damage', 0);
INSERT INTO skills (name, common) VALUES ('Reflect energy damage', 0);
INSERT INTO skills (name, common) VALUES ('Reflect fire damage', 0);
INSERT INTO skills (name, common) VALUES ('Reflect melee damage', 0);
INSERT INTO skills (name, common) VALUES ('Reflect nano damage', 0);
INSERT INTO skills (name, common) VALUES ('Reflect poison damage', 0);
INSERT INTO skills (name, common) VALUES ('Reflect projectile damage', 0);
INSERT INTO skills (name, common) VALUES ('Reflect radiation damage', 0);
INSERT INTO skills (name, common) VALUES ('Reset points', 0);
INSERT INTO skills (name, common) VALUES ('Rifle', 1);
INSERT INTO skills (name, common) VALUES ('Riposte', 1);
INSERT INTO skills (name, common) VALUES ('Run speed', 1);
INSERT INTO skills (name, common) VALUES ('SL zone protection', 0);
INSERT INTO skills (name, common) VALUES ('Scale', 0);
INSERT INTO skills (name, common) VALUES ('Secondary item', 0);
INSERT INTO skills (name, common) VALUES ('Selected item template', 0);
INSERT INTO skills (name, common) VALUES ('Sense', 1);
INSERT INTO skills (name, common) VALUES ('Sensory improvement', 1);
INSERT INTO skills (name, common) VALUES ('Shadow breed', 0);
INSERT INTO skills (name, common) VALUES ('Shadow breed template', 0);
INSERT INTO skills (name, common) VALUES ('Sharp objects', 1);
INSERT INTO skills (name, common) VALUES ('Shield chemical damage', 0);
INSERT INTO skills (name, common) VALUES ('Shield cold damage', 0);
INSERT INTO skills (name, common) VALUES ('Shield energy damage', 0);
INSERT INTO skills (name, common) VALUES ('Shield fire damage', 0);
INSERT INTO skills (name, common) VALUES ('Shield melee damage', 0);
INSERT INTO skills (name, common) VALUES ('Shield nano damage', 0);
INSERT INTO skills (name, common) VALUES ('Shield poison damage', 0);
INSERT INTO skills (name, common) VALUES ('Shield projectile damage', 0);
INSERT INTO skills (name, common) VALUES ('Shield radiation damage', 0);
INSERT INTO skills (name, common) VALUES ('Shotgun', 1);
INSERT INTO skills (name, common) VALUES ('Sitting', 0);
INSERT INTO skills (name, common) VALUES ('Skill lock modifier', 1);
INSERT INTO skills (name, common) VALUES ('Smg', 1);
INSERT INTO skills (name, common) VALUES ('Sneak attack', 1);
INSERT INTO skills (name, common) VALUES ('Social status', 0);
INSERT INTO skills (name, common) VALUES ('Specialization', 0);
INSERT INTO skills (name, common) VALUES ('Speed', 0);
INSERT INTO skills (name, common) VALUES ('Stacking order', 0);
INSERT INTO skills (name, common) VALUES ('Stamina', 1);
INSERT INTO skills (name, common) VALUES ('Strength', 1);
INSERT INTO skills (name, common) VALUES ('Swimming', 1);
INSERT INTO skills (name, common) VALUES ('Target', 0);
INSERT INTO skills (name, common) VALUES ('Target type', 0);
INSERT INTO skills (name, common) VALUES ('Taunt', 0);
INSERT INTO skills (name, common) VALUES ('Team', 0);
INSERT INTO skills (name, common) VALUES ('Team side', 0);
INSERT INTO skills (name, common) VALUES ('Time and space', 1);
INSERT INTO skills (name, common) VALUES ('Title level', 0);
INSERT INTO skills (name, common) VALUES ('Trap disarming', 1);
INSERT INTO skills (name, common) VALUES ('Treatment', 1);
INSERT INTO skills (name, common) VALUES ('Tutoring', 1);
INSERT INTO skills (name, common) VALUES ('Vehicle air', 1);
INSERT INTO skills (name, common) VALUES ('Vehicle ground', 1);
INSERT INTO skills (name, common) VALUES ('Vehicle water', 1);
INSERT INTO skills (name, common) VALUES ('Visual breed', 0);
INSERT INTO skills (name, common) VALUES ('Visual profession', 0);
INSERT INTO skills (name, common) VALUES ('Weapon range', 1);
INSERT INTO skills (name, common) VALUES ('Weapon smithing', 1);
INSERT INTO skills (name, common) VALUES ('Wielded weapons', 0);