DROP TABLE IF EXISTS skills;
CREATE TABLE skills (id INT NOT NULL PRIMARY KEY, name VARCHAR(50) NOT NULL, common INT NOT NULL);
INSERT INTO skills (id, name, common) VALUES (0, '1h Blunt', 1);
INSERT INTO skills (id, name, common) VALUES (1, '1h Edged', 1);
INSERT INTO skills (id, name, common) VALUES (2, '2h Blunt', 1);
INSERT INTO skills (id, name, common) VALUES (3, '2h Edged', 1);
INSERT INTO skills (id, name, common) VALUES (4, 'Absorb chemical damage', 0);
INSERT INTO skills (id, name, common) VALUES (5, 'Absorb cold damage', 0);
INSERT INTO skills (id, name, common) VALUES (6, 'Absorb energy damage', 0);
INSERT INTO skills (id, name, common) VALUES (7, 'Absorb fire damage', 0);
INSERT INTO skills (id, name, common) VALUES (8, 'Absorb hits', 0);
INSERT INTO skills (id, name, common) VALUES (9, 'Absorb melee damage', 0);
INSERT INTO skills (id, name, common) VALUES (10, 'Absorb poison damage', 0);
INSERT INTO skills (id, name, common) VALUES (11, 'Absorb projectile damage', 0);
INSERT INTO skills (id, name, common) VALUES (12, 'Absorb radiation damage', 0);
INSERT INTO skills (id, name, common) VALUES (13, 'Absorb special attacks', 0);
INSERT INTO skills (id, name, common) VALUES (14, 'Adventuring', 1);
INSERT INTO skills (id, name, common) VALUES (15, 'Agg/Def', 1);
INSERT INTO skills (id, name, common) VALUES (16, 'Aggressiveness', 0);
INSERT INTO skills (id, name, common) VALUES (17, 'Agility', 1);
INSERT INTO skills (id, name, common) VALUES (18, 'Aimed shot', 1);
INSERT INTO skills (id, name, common) VALUES (19, 'Alien level', 0);
INSERT INTO skills (id, name, common) VALUES (20, 'Assault rifle', 1);
INSERT INTO skills (id, name, common) VALUES (21, 'Attack modifier', 1);
INSERT INTO skills (id, name, common) VALUES (22, 'Attack rating cap', 0);
INSERT INTO skills (id, name, common) VALUES (23, 'Attack time cap', 0);
INSERT INTO skills (id, name, common) VALUES (24, 'Attribute 0xad', 0);
INSERT INTO skills (id, name, common) VALUES (25, 'Behind target', 0);
INSERT INTO skills (id, name, common) VALUES (26, 'Belt decks', 1);
INSERT INTO skills (id, name, common) VALUES (27, 'Biological metamorphosis', 1);
INSERT INTO skills (id, name, common) VALUES (28, 'Body development', 1);
INSERT INTO skills (id, name, common) VALUES (29, 'Bow', 1);
INSERT INTO skills (id, name, common) VALUES (30, 'Bow special attack', 1);
INSERT INTO skills (id, name, common) VALUES (31, 'Brawl', 1);
INSERT INTO skills (id, name, common) VALUES (32, 'Breaking and entry', 1);
INSERT INTO skills (id, name, common) VALUES (33, 'Breed', 1);
INSERT INTO skills (id, name, common) VALUES (34, 'Burst', 1);
INSERT INTO skills (id, name, common) VALUES (35, 'Burst cycle', 0);
INSERT INTO skills (id, name, common) VALUES (36, 'Chance of break on attack', 0);
INSERT INTO skills (id, name, common) VALUES (37, 'Chance of break on debuff', 0);
INSERT INTO skills (id, name, common) VALUES (38, 'Chance of break on nano', 0);
INSERT INTO skills (id, name, common) VALUES (39, 'Character state', 0);
INSERT INTO skills (id, name, common) VALUES (40, 'Chemical AC', 0);
INSERT INTO skills (id, name, common) VALUES (41, 'Chemical damage modifier', 1);
INSERT INTO skills (id, name, common) VALUES (42, 'Chemistry', 1);
INSERT INTO skills (id, name, common) VALUES (43, 'Clan tokens', 0);
INSERT INTO skills (id, name, common) VALUES (44, 'Cold AC', 0);
INSERT INTO skills (id, name, common) VALUES (45, 'Cold damage modifier', 1);
INSERT INTO skills (id, name, common) VALUES (46, 'Computer literacy', 1);
INSERT INTO skills (id, name, common) VALUES (47, 'Concealment', 1);
INSERT INTO skills (id, name, common) VALUES (48, 'Credits', 0);
INSERT INTO skills (id, name, common) VALUES (49, 'Critical chance', 1);
INSERT INTO skills (id, name, common) VALUES (50, 'Critical decrease', 1);
INSERT INTO skills (id, name, common) VALUES (51, 'Current nano', 0);
INSERT INTO skills (id, name, common) VALUES (52, 'Cyberdeck', 1);
INSERT INTO skills (id, name, common) VALUES (53, 'Damage type', 1);
INSERT INTO skills (id, name, common) VALUES (54, 'Defense modifier', 1);
INSERT INTO skills (id, name, common) VALUES (55, 'Dimach', 1);
INSERT INTO skills (id, name, common) VALUES (56, 'Distinance to target delta', 0);
INSERT INTO skills (id, name, common) VALUES (57, 'Dodge ranged', 1);
INSERT INTO skills (id, name, common) VALUES (58, 'Duck explosives', 1);
INSERT INTO skills (id, name, common) VALUES (59, 'Effect icon', 0);
INSERT INTO skills (id, name, common) VALUES (60, 'Electrical engineering', 1);
INSERT INTO skills (id, name, common) VALUES (61, 'Energy', 1);
INSERT INTO skills (id, name, common) VALUES (62, 'Energy AC', 0);
INSERT INTO skills (id, name, common) VALUES (63, 'Energy damage modifier', 1);
INSERT INTO skills (id, name, common) VALUES (64, 'Evade close', 1);
INSERT INTO skills (id, name, common) VALUES (65, 'Expansion sets', 1);
INSERT INTO skills (id, name, common) VALUES (66, 'Experience', 0);
INSERT INTO skills (id, name, common) VALUES (67, 'Experience modifier', 1);
INSERT INTO skills (id, name, common) VALUES (68, 'Experience recovery', 0);
INSERT INTO skills (id, name, common) VALUES (69, 'Experience regain percentage', 0);
INSERT INTO skills (id, name, common) VALUES (70, 'Faction', 0);
INSERT INTO skills (id, name, common) VALUES (71, 'Faction Conserver', 0);
INSERT INTO skills (id, name, common) VALUES (72, 'Faction Devoted', 0);
INSERT INTO skills (id, name, common) VALUES (73, 'Faction Followers', 0);
INSERT INTO skills (id, name, common) VALUES (74, 'Faction Operators', 0);
INSERT INTO skills (id, name, common) VALUES (75, 'Faction Redeemed', 0);
INSERT INTO skills (id, name, common) VALUES (76, 'Faction Unredeemed', 0);
INSERT INTO skills (id, name, common) VALUES (77, 'Fast attack', 1);
INSERT INTO skills (id, name, common) VALUES (78, 'Fatness', 0);
INSERT INTO skills (id, name, common) VALUES (79, 'Features', 0);
INSERT INTO skills (id, name, common) VALUES (80, 'Fire AC', 0);
INSERT INTO skills (id, name, common) VALUES (81, 'Fire damage modifier', 1);
INSERT INTO skills (id, name, common) VALUES (82, 'First aid', 1);
INSERT INTO skills (id, name, common) VALUES (83, 'Fling shot', 1);
INSERT INTO skills (id, name, common) VALUES (84, 'Form', 0);
INSERT INTO skills (id, name, common) VALUES (85, 'Full auto', 1);
INSERT INTO skills (id, name, common) VALUES (86, 'Fullauto cycle', 0);
INSERT INTO skills (id, name, common) VALUES (87, 'GM level', 0);
INSERT INTO skills (id, name, common) VALUES (88, 'GOS', 0);
INSERT INTO skills (id, name, common) VALUES (89, 'Gender', 0);
INSERT INTO skills (id, name, common) VALUES (90, 'Grenade', 1);
INSERT INTO skills (id, name, common) VALUES (91, 'Have apartment', 0);
INSERT INTO skills (id, name, common) VALUES (92, 'Heal delta', 1);
INSERT INTO skills (id, name, common) VALUES (93, 'Heal interval', 0);
INSERT INTO skills (id, name, common) VALUES (94, 'Heal modifier', 1);
INSERT INTO skills (id, name, common) VALUES (95, 'Health', 0);
INSERT INTO skills (id, name, common) VALUES (96, 'Heavy weapons', 1);
INSERT INTO skills (id, name, common) VALUES (97, 'IP', 0);
INSERT INTO skills (id, name, common) VALUES (98, 'In battle', 0);
INSERT INTO skills (id, name, common) VALUES (99, 'Initiative skill', 0);
INSERT INTO skills (id, name, common) VALUES (100, 'Inside Shadowlands', 0);
INSERT INTO skills (id, name, common) VALUES (101, 'Intelligence', 1);
INSERT INTO skills (id, name, common) VALUES (102, 'Last random roll', 0);
INSERT INTO skills (id, name, common) VALUES (103, 'Level', 0);
INSERT INTO skills (id, name, common) VALUES (104, 'Lock difficulty', 0);
INSERT INTO skills (id, name, common) VALUES (105, 'Map navigation', 1);
INSERT INTO skills (id, name, common) VALUES (106, 'Map upgrades', 0);
INSERT INTO skills (id, name, common) VALUES (107, 'Maps A', 0);
INSERT INTO skills (id, name, common) VALUES (108, 'Maps B', 0);
INSERT INTO skills (id, name, common) VALUES (109, 'Maps C', 0);
INSERT INTO skills (id, name, common) VALUES (110, 'Maps D', 0);
INSERT INTO skills (id, name, common) VALUES (111, 'Martial arts', 1);
INSERT INTO skills (id, name, common) VALUES (112, 'Mass', 0);
INSERT INTO skills (id, name, common) VALUES (113, 'Matter creation', 1);
INSERT INTO skills (id, name, common) VALUES (114, 'Matter metamorphosis', 1);
INSERT INTO skills (id, name, common) VALUES (115, 'Max health', 1);
INSERT INTO skills (id, name, common) VALUES (116, 'Max nano', 1);
INSERT INTO skills (id, name, common) VALUES (117, 'Maximum chemical reflect', 0);
INSERT INTO skills (id, name, common) VALUES (118, 'Maximum cold reflect', 0);
INSERT INTO skills (id, name, common) VALUES (119, 'Maximum damage', 0);
INSERT INTO skills (id, name, common) VALUES (120, 'Maximum energy reflect', 0);
INSERT INTO skills (id, name, common) VALUES (121, 'Maximum fire reflect', 0);
INSERT INTO skills (id, name, common) VALUES (122, 'Maximum melee reflect', 0);
INSERT INTO skills (id, name, common) VALUES (123, 'Maximum nano reflect', 0);
INSERT INTO skills (id, name, common) VALUES (124, 'Maximum poison reflect', 0);
INSERT INTO skills (id, name, common) VALUES (125, 'Maximum projectile reflect', 0);
INSERT INTO skills (id, name, common) VALUES (126, 'Maximum radiation reflect', 0);
INSERT INTO skills (id, name, common) VALUES (127, 'Mechanical engineering', 1);
INSERT INTO skills (id, name, common) VALUES (128, 'Melee AC', 0);
INSERT INTO skills (id, name, common) VALUES (129, 'Melee damage modifier', 1);
INSERT INTO skills (id, name, common) VALUES (130, 'Melee energy', 1);
INSERT INTO skills (id, name, common) VALUES (131, 'Melee init', 1);
INSERT INTO skills (id, name, common) VALUES (132, 'Minimum damage', 0);
INSERT INTO skills (id, name, common) VALUES (133, 'Multi melee', 1);
INSERT INTO skills (id, name, common) VALUES (134, 'Multi ranged', 1);
INSERT INTO skills (id, name, common) VALUES (135, 'NCU memory', 1);
INSERT INTO skills (id, name, common) VALUES (136, 'NPC hatelist size', 0);
INSERT INTO skills (id, name, common) VALUES (137, 'NPC type', 0);
INSERT INTO skills (id, name, common) VALUES (138, 'Nano attack damage modifier', 1);
INSERT INTO skills (id, name, common) VALUES (139, 'Nano cost modifier', 1);
INSERT INTO skills (id, name, common) VALUES (140, 'Nano damage modifier', 1);
INSERT INTO skills (id, name, common) VALUES (141, 'Nano delta', 1);
INSERT INTO skills (id, name, common) VALUES (142, 'Nano init', 1);
INSERT INTO skills (id, name, common) VALUES (143, 'Nano interrupt chance', 1);
INSERT INTO skills (id, name, common) VALUES (144, 'Nano pool', 1);
INSERT INTO skills (id, name, common) VALUES (145, 'Nano programming', 1);
INSERT INTO skills (id, name, common) VALUES (146, 'Nano range', 1);
INSERT INTO skills (id, name, common) VALUES (147, 'Nano resist', 1);
INSERT INTO skills (id, name, common) VALUES (148, 'Nano vulnerability', 0);
INSERT INTO skills (id, name, common) VALUES (149, 'Number of team members', 0);
INSERT INTO skills (id, name, common) VALUES (150, 'Object', 0);
INSERT INTO skills (id, name, common) VALUES (151, 'Offense modifier', 1);
INSERT INTO skills (id, name, common) VALUES (152, 'Omni tokens', 0);
INSERT INTO skills (id, name, common) VALUES (153, 'Organization', 0);
INSERT INTO skills (id, name, common) VALUES (154, 'Organization rank', 0);
INSERT INTO skills (id, name, common) VALUES (155, 'Organization upkeep', 0);
INSERT INTO skills (id, name, common) VALUES (156, 'Parry', 1);
INSERT INTO skills (id, name, common) VALUES (157, 'Percentage of health', 0);
INSERT INTO skills (id, name, common) VALUES (158, 'Perception', 1);
INSERT INTO skills (id, name, common) VALUES (159, 'Pets', 0);
INSERT INTO skills (id, name, common) VALUES (160, 'Pharmaceuticals', 1);
INSERT INTO skills (id, name, common) VALUES (161, 'Physical init', 1);
INSERT INTO skills (id, name, common) VALUES (162, 'Piercing', 1);
INSERT INTO skills (id, name, common) VALUES (163, 'Pistol', 1);
INSERT INTO skills (id, name, common) VALUES (164, 'Playfield proxy', 0);
INSERT INTO skills (id, name, common) VALUES (165, 'Playfield type', 0);
INSERT INTO skills (id, name, common) VALUES (166, 'Poison AC', 0);
INSERT INTO skills (id, name, common) VALUES (167, 'Poison damage modifier', 1);
INSERT INTO skills (id, name, common) VALUES (168, 'Proc chance 1', 0);
INSERT INTO skills (id, name, common) VALUES (169, 'Proc chance 2', 0);
INSERT INTO skills (id, name, common) VALUES (170, 'Proc initiative 1', 0);
INSERT INTO skills (id, name, common) VALUES (171, 'Proc initiative 2', 0);
INSERT INTO skills (id, name, common) VALUES (172, 'Proc nano 1', 0);
INSERT INTO skills (id, name, common) VALUES (173, 'Proc nano 2', 0);
INSERT INTO skills (id, name, common) VALUES (174, 'Profession', 0);
INSERT INTO skills (id, name, common) VALUES (175, 'Profession level', 0);
INSERT INTO skills (id, name, common) VALUES (176, 'Projectile AC', 0);
INSERT INTO skills (id, name, common) VALUES (177, 'Projectile damage modifier', 1);
INSERT INTO skills (id, name, common) VALUES (178, 'Psychic', 1);
INSERT INTO skills (id, name, common) VALUES (179, 'Psychological modifications', 1);
INSERT INTO skills (id, name, common) VALUES (180, 'Psychology', 1);
INSERT INTO skills (id, name, common) VALUES (181, 'Quantum physics', 1);
INSERT INTO skills (id, name, common) VALUES (182, 'Radiation AC', 0);
INSERT INTO skills (id, name, common) VALUES (183, 'Radiation damage modifier', 1);
INSERT INTO skills (id, name, common) VALUES (184, 'Random roll', 0);
INSERT INTO skills (id, name, common) VALUES (185, 'Ranged energy', 1);
INSERT INTO skills (id, name, common) VALUES (186, 'Ranged init', 1);
INSERT INTO skills (id, name, common) VALUES (187, 'Recharge time cap', 0);
INSERT INTO skills (id, name, common) VALUES (188, 'Reflect chemical damage', 0);
INSERT INTO skills (id, name, common) VALUES (189, 'Reflect cold damage', 0);
INSERT INTO skills (id, name, common) VALUES (190, 'Reflect energy damage', 0);
INSERT INTO skills (id, name, common) VALUES (191, 'Reflect fire damage', 0);
INSERT INTO skills (id, name, common) VALUES (192, 'Reflect melee damage', 0);
INSERT INTO skills (id, name, common) VALUES (193, 'Reflect nano damage', 0);
INSERT INTO skills (id, name, common) VALUES (194, 'Reflect poison damage', 0);
INSERT INTO skills (id, name, common) VALUES (195, 'Reflect projectile damage', 0);
INSERT INTO skills (id, name, common) VALUES (196, 'Reflect radiation damage', 0);
INSERT INTO skills (id, name, common) VALUES (197, 'Reset points', 0);
INSERT INTO skills (id, name, common) VALUES (198, 'Rifle', 1);
INSERT INTO skills (id, name, common) VALUES (199, 'Riposte', 1);
INSERT INTO skills (id, name, common) VALUES (200, 'Run speed', 1);
INSERT INTO skills (id, name, common) VALUES (201, 'SL zone protection', 0);
INSERT INTO skills (id, name, common) VALUES (202, 'Scale', 0);
INSERT INTO skills (id, name, common) VALUES (203, 'Secondary item', 0);
INSERT INTO skills (id, name, common) VALUES (204, 'Selected item template', 0);
INSERT INTO skills (id, name, common) VALUES (205, 'Sense', 1);
INSERT INTO skills (id, name, common) VALUES (206, 'Sensory improvement', 1);
INSERT INTO skills (id, name, common) VALUES (207, 'Shadow breed', 0);
INSERT INTO skills (id, name, common) VALUES (208, 'Shadow breed template', 0);
INSERT INTO skills (id, name, common) VALUES (209, 'Sharp objects', 1);
INSERT INTO skills (id, name, common) VALUES (210, 'Shield chemical damage', 0);
INSERT INTO skills (id, name, common) VALUES (211, 'Shield cold damage', 0);
INSERT INTO skills (id, name, common) VALUES (212, 'Shield energy damage', 0);
INSERT INTO skills (id, name, common) VALUES (213, 'Shield fire damage', 0);
INSERT INTO skills (id, name, common) VALUES (214, 'Shield melee damage', 0);
INSERT INTO skills (id, name, common) VALUES (215, 'Shield nano damage', 0);
INSERT INTO skills (id, name, common) VALUES (216, 'Shield poison damage', 0);
INSERT INTO skills (id, name, common) VALUES (217, 'Shield projectile damage', 0);
INSERT INTO skills (id, name, common) VALUES (218, 'Shield radiation damage', 0);
INSERT INTO skills (id, name, common) VALUES (219, 'Shotgun', 1);
INSERT INTO skills (id, name, common) VALUES (220, 'Sitting', 0);
INSERT INTO skills (id, name, common) VALUES (221, 'Skill lock modifier', 1);
INSERT INTO skills (id, name, common) VALUES (222, 'Smg', 1);
INSERT INTO skills (id, name, common) VALUES (223, 'Sneak attack', 1);
INSERT INTO skills (id, name, common) VALUES (224, 'Social status', 0);
INSERT INTO skills (id, name, common) VALUES (225, 'Specialization', 0);
INSERT INTO skills (id, name, common) VALUES (226, 'Speed', 0);
INSERT INTO skills (id, name, common) VALUES (227, 'Stacking order', 0);
INSERT INTO skills (id, name, common) VALUES (228, 'Stamina', 1);
INSERT INTO skills (id, name, common) VALUES (229, 'Strength', 1);
INSERT INTO skills (id, name, common) VALUES (230, 'Swimming', 1);
INSERT INTO skills (id, name, common) VALUES (231, 'Target', 0);
INSERT INTO skills (id, name, common) VALUES (232, 'Target type', 0);
INSERT INTO skills (id, name, common) VALUES (233, 'Taunt', 0);
INSERT INTO skills (id, name, common) VALUES (234, 'Team', 0);
INSERT INTO skills (id, name, common) VALUES (235, 'Team side', 0);
INSERT INTO skills (id, name, common) VALUES (236, 'Time and space', 1);
INSERT INTO skills (id, name, common) VALUES (237, 'Title level', 0);
INSERT INTO skills (id, name, common) VALUES (238, 'Trap disarming', 1);
INSERT INTO skills (id, name, common) VALUES (239, 'Treatment', 1);
INSERT INTO skills (id, name, common) VALUES (240, 'Tutoring', 1);
INSERT INTO skills (id, name, common) VALUES (241, 'Vehicle air', 1);
INSERT INTO skills (id, name, common) VALUES (242, 'Vehicle ground', 1);
INSERT INTO skills (id, name, common) VALUES (243, 'Vehicle water', 1);
INSERT INTO skills (id, name, common) VALUES (244, 'Visual breed', 0);
INSERT INTO skills (id, name, common) VALUES (245, 'Visual profession', 0);
INSERT INTO skills (id, name, common) VALUES (246, 'Weapon range', 1);
INSERT INTO skills (id, name, common) VALUES (247, 'Weapon smithing', 1);
INSERT INTO skills (id, name, common) VALUES (248, 'Wielded weapons', 0);