DROP TABLE IF EXISTS `whompa_cities`;
CREATE TABLE IF NOT EXISTS `whompa_cities` ( `id` INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT, `city_name` varchar(50) NOT NULL, `zone` varchar(50) NOT NULL, `faction` varchar(10) NOT NULL, `short_name` varchar(255) DEFAULT NULL);
INSERT INTO `whompa_cities` (`id`, `city_name`, `zone`, `faction`, `short_name`) VALUES(1, 'ICC', 'Andromeda', 'Neutral', 'icc');
INSERT INTO `whompa_cities` (`id`, `city_name`, `zone`, `faction`, `short_name`) VALUES(2, 'Camelot', 'Avalon', 'Clan', 'camelot');
INSERT INTO `whompa_cities` (`id`, `city_name`, `zone`, `faction`, `short_name`) VALUES(3, 'Bliss', 'The Longest Road', 'Clan', 'bliss');
INSERT INTO `whompa_cities` (`id`, `city_name`, `zone`, `faction`, `short_name`) VALUES(4, 'Broken Shores - North', 'Broken Shores', 'Clan', 'bsn');
INSERT INTO `whompa_cities` (`id`, `city_name`, `zone`, `faction`, `short_name`) VALUES(5, 'Old Athen', 'Athen', 'Clan', 'oa');
INSERT INTO `whompa_cities` (`id`, `city_name`, `zone`, `faction`, `short_name`) VALUES(6, 'Tir', 'Tir County', 'Clan', 'tir');
INSERT INTO `whompa_cities` (`id`, `city_name`, `zone`, `faction`, `short_name`) VALUES(7, 'Varmint Woods', 'Varmint Woods', 'Clan', 'vw');
INSERT INTO `whompa_cities` (`id`, `city_name`, `zone`, `faction`, `short_name`) VALUES(8, 'Wailing Wastes', 'Wailing Wastes', 'Clan', 'ww');
INSERT INTO `whompa_cities` (`id`, `city_name`, `zone`, `faction`, `short_name`) VALUES(9, 'Wine', 'Belial Forest', 'Clan', 'wine');
INSERT INTO `whompa_cities` (`id`, `city_name`, `zone`, `faction`, `short_name`) VALUES(10, 'Newland City', 'Newland', 'Neutral', 'nlc');
INSERT INTO `whompa_cities` (`id`, `city_name`, `zone`, `faction`, `short_name`) VALUES(11, 'Newland Desert', 'Newland Desert', 'Neutral', 'nld');
INSERT INTO `whompa_cities` (`id`, `city_name`, `zone`, `faction`, `short_name`) VALUES(12, 'Borealis', 'Borealis', 'Neutral', 'bor');
INSERT INTO `whompa_cities` (`id`, `city_name`, `zone`, `faction`, `short_name`) VALUES(13, 'Hope', 'Mort', 'Neutral', 'hope');
INSERT INTO `whompa_cities` (`id`, `city_name`, `zone`, `faction`, `short_name`) VALUES(14, 'Stret West Bank', 'Stret West Bank', 'Neutral', 'swb');
INSERT INTO `whompa_cities` (`id`, `city_name`, `zone`, `faction`, `short_name`) VALUES(15, 'Omni Trade', 'Omni Trade', 'Omni', 'trade');
INSERT INTO `whompa_cities` (`id`, `city_name`, `zone`, `faction`, `short_name`) VALUES(16, 'Omni Entertainment', 'Omni Entertainment', 'Omni', 'ent');
INSERT INTO `whompa_cities` (`id`, `city_name`, `zone`, `faction`, `short_name`) VALUES(17, 'Galway Castle', 'Galway County', 'Omni', 'gc');
INSERT INTO `whompa_cities` (`id`, `city_name`, `zone`, `faction`, `short_name`) VALUES(18, '20K', 'Pleasant Meadows', 'Omni', '20k');
INSERT INTO `whompa_cities` (`id`, `city_name`, `zone`, `faction`, `short_name`) VALUES(19, '4 Holes', '4 Holes', 'Omni', '4ho');
INSERT INTO `whompa_cities` (`id`, `city_name`, `zone`, `faction`, `short_name`) VALUES(20, 'Broken Shores - South', 'Broken Shores', 'Omni', 'bss');
INSERT INTO `whompa_cities` (`id`, `city_name`, `zone`, `faction`, `short_name`) VALUES(21, 'Outpost 10-3', 'SouthernArteryValley', 'Omni', '10-3');
INSERT INTO `whompa_cities` (`id`, `city_name`, `zone`, `faction`, `short_name`) VALUES(22, '2HO', 'Stret East Bank', 'Omni', '2ho');
INSERT INTO `whompa_cities` (`id`, `city_name`, `zone`, `faction`, `short_name`) VALUES(23, 'Rome', 'Rome Red', 'Omni', 'rr');
INSERT INTO `whompa_cities` (`id`, `city_name`, `zone`, `faction`, `short_name`) VALUES(24, 'The Longest Road', 'The Longest Road', 'Omni', 'tlr');

DROP TABLE IF EXISTS `whompa_cities_rel`;
CREATE TABLE `whompa_cities_rel` ( `city1_id` int(11) NOT NULL, `city2_id` int(11) NOT NULL);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(1, 10);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(1, 15);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(1, 6);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(2, 3);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(2, 8);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(3, 2);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(3, 4);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(3, 5);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(4, 3);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(4, 9);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(5, 3);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(5, 6);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(5, 8);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(6, 1);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(6, 5);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(6, 7);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(7, 6);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(7, 8);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(7, 9);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(8, 2);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(8, 5);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(8, 7);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(9, 4);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(9, 7);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(10, 1);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(10, 11);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(10, 12);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(11, 10);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(11, 13);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(12, 10);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(12, 14);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(13, 11);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(13, 14);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(14, 12);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(14, 13);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(15, 1);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(15, 16);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(15, 17);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(16, 15);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(16, 18);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(16, 23);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(17, 15);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(17, 21);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(17, 23);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(18, 16);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(18, 19);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(18, 21);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(19, 18);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(19, 20);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(19, 22);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(20, 19);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(20, 23);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(21, 17);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(21, 18);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(21, 22);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(22, 19);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(22, 21);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(22, 24);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(23, 16);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(23, 17);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(23, 20);
INSERT INTO `whompa_cities_rel` (`city1_id`, `city2_id`) VALUES(24, 22);

-- test congruency
-- SELECT * FROM (SELECT city1_id, count(*) AS cnt FROM whompa_cities_rel GROUP BY city1_id ) t1 JOIN (SELECT city2_id, count(*) AS cnt FROM whompa_cities_rel GROUP BY city2_id) t2 ON t1.city1_id = t2.city2_id WHERE t1.cnt <> t2.cnt
