DROP TABLE IF EXISTS boss_namedb;
CREATE TABLE boss_namedb (`bossid` int(10) PRIMARY KEY,`bossname` varchar(50),`location` varchar(75), `keyname` varchar(200));
INSERT INTO `boss_namedb` VALUES (1,'Afreet Ellis','NE of Frontier Garden','Afreet, Ellis');
INSERT INTO `boss_namedb` VALUES (2,'Akshki','South of Frontier','Ashki'); 
INSERT INTO `boss_namedb` VALUES (3,'Alpha Skincrawler','Crypt of Home, Broken Shores','Skincrawler Coh Crypt Of Home');
INSERT INTO `boss_namedb` VALUES (4,'Anansis Left Hand','Inferno, East of Sorrow','Anasis L Hand Anasis Lhand');
INSERT INTO `boss_namedb` VALUES (5,'Anansis Right Hand','Inferno, East of Sorrow','Anasis R Hand Anasis Rhand');
INSERT INTO `boss_namedb` VALUES (6,'Anasis Abettor','Inferno, Far SW of Sorrow','Anasis Abetor Anasis Abetter');
INSERT INTO `boss_namedb` VALUES (7,'Anansis Favorite','Inferno, just NE of Frontier','Anasis Favorit Anansis Favorite');
INSERT INTO `boss_namedb` VALUES (8,'Aniitaps Shadow','Inferno, North of Frontier','Anitaps Shadow');
INSERT INTO `boss_namedb` VALUES (9,'Apprentice Beasthandler','Inferno, 255 Incarnator','Beasthandler');
INSERT INTO `boss_namedb` VALUES (10,'Aquarius','Pandemonium, East Node','Zods Zodiac Zodiacs Akwerius');
INSERT INTO `boss_namedb` VALUES (11,'Aries','Pandemonium, West Node','Arees Zods Zodiac Zodiacs,');
INSERT INTO `boss_namedb` VALUES (12,'Asperous Imp','Elysium, Near Ergo','Asperus Imp');
INSERT INTO `boss_namedb` VALUES (13,'Astypalia','Inferno, West of Razors Lair','Asteepalia');
INSERT INTO `boss_namedb` VALUES (14,'Atakirh','Inferno, South of Frontier','Atakir');
INSERT INTO `boss_namedb` VALUES (15,'Athlar','Elysium, inside mountains SW and NW','Athler');
INSERT INTO `boss_namedb` VALUES (16,'Bane','Crypt of Home, Broken Shores','Bane Coh Crypt Of Home');
INSERT INTO `boss_namedb` VALUES (17,'Bending Eremite','Elysium, Sand dunes near Cold Rock','Bending Eremite');
INSERT INTO `boss_namedb` VALUES (18,'Bigot','Inferno, SW of Sorrow, N of Sorrow, 255 Inc','Bigot');
INSERT INTO `boss_namedb` VALUES (19,'Black','Adonis, Abyss NW','Black');
INSERT INTO `boss_namedb` VALUES (20,'Brutish Dryad','Elysium, Utopolis and South Elysium','Brutish Dryad');
INSERT INTO `boss_namedb` VALUES (21,'Cacophonous Imp','Elysium, Near Ergo','Cacaphonus Imp');
INSERT INTO `boss_namedb` VALUES (22,'Cancer','Pandemonium, East Node','Cancer Zods Zodiac Zodiacs');
INSERT INTO `boss_namedb` VALUES (23,'Cantankerous Golem','Adonis, SE Whirling Rocks, SW Golems','Cantakerus Golem');
INSERT INTO `boss_namedb` VALUES (24,'Capricorn','Pandemonium, North Node','Capricorn Zods Zodiac Zodiacs');
INSERT INTO `boss_namedb` VALUES (25,'Catervauling Minx','Elysium, Near Ergo & Fallen Forest','Cantervauling Mix Cantervaling Minx');
INSERT INTO `boss_namedb` VALUES (26,'Cenobite Shadow','Crypt of Home, Broken Shores','Cenabite Shadow Cenobyte Cenobite Crypt Of Home Coh');
INSERT INTO `boss_namedb` VALUES (27,'Cerubin The Rejected','Crypt of Home, Broken Shores','Cerubin Crypt Of Home Coh');
INSERT INTO `boss_namedb` VALUES (28,'Chimera Monitor','Inferno, West of Dark Marshes Unred Temple','Chimera Monitor ');
INSERT INTO `boss_namedb` VALUES (29,'Chimera Trainer','Inferno, West of Dark Marshes Unred Temple','Chimera Trainer ');
INSERT INTO `boss_namedb` VALUES (30,'Clan Modified A-4000','1105x2520, Avalon.','A-4000 a4000');
INSERT INTO `boss_namedb` VALUES (31,'Clan Modified A-4001','Wailing Wastes','A4001 A-4001');
INSERT INTO `boss_namedb` VALUES (32,'Chimera Trainer','Elysium, Sand dunes near Cold Rock','Chimera Trainer ');
INSERT INTO `boss_namedb` VALUES (33,'Colonel Frank Kaehler','700x2000, Omni-Forest','Colonel Kaehler');
INSERT INTO `boss_namedb` VALUES (34,'Comatosed Soul','Elysium, E Whispervale and 115 Inc','Comatosed Soul ');
INSERT INTO `boss_namedb` VALUES (35,'Commander Kelly Frederickson','1750x1100, Tir County','Commander Fredrickson Fredrickson');
INSERT INTO `boss_namedb` VALUES (36,'Conflagrant Spirit','Inferno, NW of Yuttos','Confligrant Spirit');
INSERT INTO `boss_namedb` VALUES (37,'Corrupt Spirit','Adonis, Island bridge center of Adonis','Corrupt Spirit ');
INSERT INTO `boss_namedb` VALUES (38,'Crabby Golem','Adonis, SE Whirling Rocks, SW Golems','Crabby Golem ');
INSERT INTO `boss_namedb` VALUES (39,'Cranky Golem','Adonis, SE Whirling Rocks, SW Golems','Cranky Golem ');
INSERT INTO `boss_namedb` VALUES (40,'Creepy Spider','Inferno, N of 255 Incarnator','Creepy Spider ');
INSERT INTO `boss_namedb` VALUES (41,'Crete','Inferno, 255 Incarnator','Crete ');
INSERT INTO `boss_namedb` VALUES (42,'Cuty','1500x600, Crater Farm Region, Tir County','Cuty ');
INSERT INTO `boss_namedb` VALUES (43,'Daria Marie Walzer','1782x2062, Lush Fields','Daria Daria Marie Daria Walzer');
INSERT INTO `boss_namedb` VALUES (44,'Daring Dryad','Penumbra, South of W Pipe Entrance',' Daring Dryad');
INSERT INTO `boss_namedb` VALUES (45,'Dauntless Dryad','Penumbra, South of W Pipe Entrance','Dauntless Dryad ');
INSERT INTO `boss_namedb` VALUES (46,'Delinquent Spirit','Adonis City SW','Delinquent Spirit ');
INSERT INTO `boss_namedb` VALUES (47,'Devoted Spirit Hunter','Inferno, West of Sorrow','Devoted Spirit Hunter ');
INSERT INTO `boss_namedb` VALUES (48,'Diamondine Soldier','1925x1450, Eastern Fouls Plains.','Diamondine Soldier ');
INSERT INTO `boss_namedb` VALUES (49,'Diamondine Trainee','1925x1450, Eastern Fouls Plains','Diamondine Trainee ');
INSERT INTO `boss_namedb` VALUES (50,'Ding','3300x600, Inquisitive Wasp, Tir County','Ding ');
INSERT INTO `boss_namedb` VALUES (51,'Disturbing Imp','Elysium, Near Ergo',' Disturbing Imp');
INSERT INTO `boss_namedb` VALUES (52,'Elian Zuwadza','450x1300, Galway','Elian');
INSERT INTO `boss_namedb` VALUES (53,'Enkindled Spirit','Inferno, NW of Yuttos','Enkindled Spirit ');
INSERT INTO `boss_namedb` VALUES (54,'Escaped Gargantula','2160x1150, Galway','Escaped Gargantula ');
INSERT INTO `boss_namedb` VALUES (55,'Fanatic Spirit Hunter','Inferno, North of Sorrow','Fanatic Spirit Hunter ');
INSERT INTO `boss_namedb` VALUES (56,'Fearless Dryad','Penumbra, South of W Pipe Entrance','Fearless Dryad ');
INSERT INTO `boss_namedb` VALUES (57,'Fiery Soldier','365x2060, Eastern Fouls Plains','Fiery Soldier ');
INSERT INTO `boss_namedb` VALUES (58,'Forefather','Smugglers Den, 1755x872, SFH.','Clawfinger Forefather Smugglers');
INSERT INTO `boss_namedb` VALUES (59,'Gemini','Pandemonium, East Node','Gemini Zods Zodiac Zodiacs');
INSERT INTO `boss_namedb` VALUES (60,'General Kaehler Jr','Avalon, Secondary Base','General Kaehler Kaehler Jr');
INSERT INTO `boss_namedb` VALUES (61,'General Kronilis','2000x2500, Perpetual Wastelands','Kronilis');
INSERT INTO `boss_namedb` VALUES (62,'General Nirtox','Perpetual Wastelands','Nirtrox');
INSERT INTO `boss_namedb` VALUES (63,'General Vivyan','2120x1760, Perpetual Wastelands','Vivyan General Vivian');
INSERT INTO `boss_namedb` VALUES (64,'George','3200x2300, Greater Tir County','George ');
INSERT INTO `boss_namedb` VALUES (65,'Hawqana','Inferno, 225 Incarnator','Hawquana');
INSERT INTO `boss_namedb` VALUES (66,'High Commander Frederickson','Wailing Wastes','High Commander Frederickson ');
INSERT INTO `boss_namedb` VALUES (67,'Howling Minx','Elysium, Near Ergo & Fallen Forest','Howling Minx ');
INSERT INTO `boss_namedb` VALUES (68,'Howling Predator','Elysium, South of Remnans','Howling Predator ');
INSERT INTO `boss_namedb` VALUES (69,'Ian Warr','Primus Camp, EFP','Ian Warr Primus Camp Merc Mercs Ace Camp Ace');
INSERT INTO `boss_namedb` VALUES (70,'Incandescent Spirit','Inferno, NW of Yuttos','Incandescent Spirit ');
INSERT INTO `boss_namedb` VALUES (71,'Irascible Golem','Adonis, SE Whirling Rocks, SW Golems','Irascible Golem ');
INSERT INTO `boss_namedb` VALUES (72,'Iron Reet','857x986, Mutant Domain','Iron Reet ');
INSERT INTO `boss_namedb` VALUES (73,'Isham','Inferno, South of Frontier','Isham ');
INSERT INTO `boss_namedb` VALUES (74,'Ishimkimk','Inferno, 225 Incarnator','Ishimkimk ');
INSERT INTO `boss_namedb` VALUES (75,'Ithaki','Inferno, 255 Incarnator','Ithaki ');
INSERT INTO `boss_namedb` VALUES (76,'Joo','Sunken Swamps, Omni-Forest','Joo ');
INSERT INTO `boss_namedb` VALUES (77,'Jukes','Adonis, Abyss NW','Jukes ');
INSERT INTO `boss_namedb` VALUES (78,'Lab Director','Foremans, 2000x800, TLR','Lab Director Foremans Biomare ');
INSERT INTO `boss_namedb` VALUES (79,'Leo','Pandemonium, West Node','Leo Zods Zodiac Zodiacs ');
INSERT INTO `boss_namedb` VALUES (80,'Libra','Pandemonium, Middle Node','Libra Zods Zodiac Zodiacs');
INSERT INTO `boss_namedb` VALUES (81,'Limber Dryad','Elysium, Utopolis and South Elysium','Limber Dryad ');
INSERT INTO `boss_namedb` VALUES (82,'Limnos','Inferno, 255 Incarnator','Limnos ');
INSERT INTO `boss_namedb` VALUES (83,'Limping Predator','Elysium, South of Remnans','Limping Predator ');
INSERT INTO `boss_namedb` VALUES (84,'Ljotur The Lunatic','1103x722, Drill Island, DAV','Ljotur Dav');
INSERT INTO `boss_namedb` VALUES (85,'Lord Of The Void','Inferno, E of Frontier, W of Frontier. Nasc Wilds','Lord Of The Void ');
INSERT INTO `boss_namedb` VALUES (86,'Lost Soul','Elysium, E Whispervale and 115 Inc','Lost Soul ');
INSERT INTO `boss_namedb` VALUES (87,'Lurking Dryad','Adonis, West and NW Island','Lurking Dryad ');
INSERT INTO `boss_namedb` VALUES (88,'Mantis Queen','Smugglers Den, 1755x872, SFH','Mantis Queen Smugglers ');
INSERT INTO `boss_namedb` VALUES (89,'Marcus Robicheaux','1500x2900, Broken Shores','Marcus');
INSERT INTO `boss_namedb` VALUES (90,'Maychwaham','Inferno, South of Frontier','Maychwam');
INSERT INTO `boss_namedb` VALUES (91,'Mick Nugget Mcmullet','1100x3700, Clondyke','Mick Mick Nugget');
INSERT INTO `boss_namedb` VALUES (92,'Mooching Dryad','Adonis, West and NW Island','Mooching Dryad ');
INSERT INTO `boss_namedb` VALUES (93,'Morgan Le Faye','2092x3822, Camelot, Avalon','Morgan La Faye Morgan Lefaye Morgan Lafaye Morgan La Fey Morgan Le Fay, Camelot');
INSERT INTO `boss_namedb` VALUES (94,'Morty','300x1200, Kuroshio Forest, Tir County','Morty ');
INSERT INTO `boss_namedb` VALUES (95,'Mull','Adonis, Abyss NW','Mull ');
INSERT INTO `boss_namedb` VALUES (96,'Neleb The Deranged','800x2800, Steps of Madness, Omni-Forest','Neleb, Steps Of Madness, Som');
INSERT INTO `boss_namedb` VALUES (97,'Nelly Johnson','720x1380, Primus Camp, Eastern Fouls Plains','Nelly Primus Camp Primus Merc Mercs Ace Camp Ace');
INSERT INTO `boss_namedb` VALUES (98,'Notum Soldier','2000x2400, Eastern Fouls Plains',' Notum Soldier');
INSERT INTO `boss_namedb` VALUES (99,'Notum Trainee','2000x2400, Eastern Fouls Plains','Notum Trainee ');
INSERT INTO `boss_namedb` VALUES (100,'Obediency Inspector','2000x2400, Eastern Fouls Plains','Obediency Inspector ');
INSERT INTO `boss_namedb` VALUES (101,'Omni-Pol Command Juggernaut','Primary Base, Avalon. E-W Road Mutant Domain','Command Juggernaut');
INSERT INTO `boss_namedb` VALUES (102,'Oscar','Greater Omni-Forest','Oscar ');
INSERT INTO `boss_namedb` VALUES (103,'Ossuz','Elysium, inside mountains SW and NW','Ossuz ');
INSERT INTO `boss_namedb` VALUES (104,'Ownz','2200x700, Crownhead Forest, Tir County','Ownz ');
INSERT INTO `boss_namedb` VALUES (105,'Pained Predator','Elysium, South of Remnans','Pained Predator ');
INSERT INTO `boss_namedb` VALUES (106,'Patricia Johnson','720x1380, Ace Camp, Eastern Fouls Plains','Patricia Johnson Ace Camp Ace Primus Camp Primus Merc Mercs ');
INSERT INTO `boss_namedb` VALUES (107,'Peristaltic Abomination','Adonis Abyss East & West','Peristaltic Abomination ');
INSERT INTO `boss_namedb` VALUES (108,'Peristaltic Aversion','Adonis Abyss East & West','Peristaltic Aversion ');
INSERT INTO `boss_namedb` VALUES (109,'Peter Lee','720x1380, Ace Camp, Eastern Fouls Plains','Peter Lee Ace Camp Ace Primus Camp Merc Mercs Notum Tank');
INSERT INTO `boss_namedb` VALUES (110,'Phatmos','Inferno, West of Razors Lair','Phatmos ');
INSERT INTO `boss_namedb` VALUES (111,'Pisces','Pandemonium, Middle Node','Pisces ');
INSERT INTO `boss_namedb` VALUES (112,'Pit Demon','Crypt of Home, Broken Shores','Pit Demon Coh Crypt Of Home ');
INSERT INTO `boss_namedb` VALUES (113,'Polly','Swamp River Delta, Omni-Forest',' Polly');
INSERT INTO `boss_namedb` VALUES (114,'Polymorphed Lunatic','1103x722, Drill Island, DAV','Polymorphed Lunatic Drill Island ');
INSERT INTO `boss_namedb` VALUES (115,'Powa','800x2400, Greater Tir County','Powa ');
INSERT INTO `boss_namedb` VALUES (116,'Professor Van Horn','2900x1600, Newland Desert','Van Horn');
INSERT INTO `boss_namedb` VALUES (117,'Punctilious Hiathlin','Inferno, 255 Incarnator','Punctilious Hiathlin ');
INSERT INTO `boss_namedb` VALUES (118,'Putrid Eremite','Inferno, 225 Incarnator','Putrid Eremite ');
INSERT INTO `boss_namedb` VALUES (119,'R-2000 Vermin Disposal Unit','800x1800, Greater Tir County','R-2000 R2000');
INSERT INTO `boss_namedb` VALUES (120,'Ris Lee','720x1380, Ace Camp, Eastern Fouls Plains','Ris Lee Ace Camp Ace Mercs Merc Primus Camp');
INSERT INTO `boss_namedb` VALUES (121,'Rotting Eremite','Inferno, 225 Incarnator','Rotting Eremite ');
INSERT INTO `boss_namedb` VALUES (122,'Sadistic Soul Dredge','Elysium, E Whispervale and 115 Inc','Sadistic Soul Dredge ');
INSERT INTO `boss_namedb` VALUES (123,'Sagittarius','Pandemonium, North Node','Sagittarius Zods Zodiac Zodiacs');
INSERT INTO `boss_namedb` VALUES (124,'Salahpt','Inferno, South of Frontier','Salahpt ');
INSERT INTO `boss_namedb` VALUES (125,'Scary Spider','Inferno, SE of 255 Incarnator','Scary Spider ');
INSERT INTO `boss_namedb` VALUES (126,'Scorpio','Pandemonium, North Node','Scorpio Zods Zodiac Zodiacs');
INSERT INTO `boss_namedb` VALUES (127,'Scratching Soul Dredge','Adonis, Dead Ends Ark','Scratching Soul Dredge ');
INSERT INTO `boss_namedb` VALUES (128,'Screeching Imp','Elysium, Near Ergo','Screeching Imp ');
INSERT INTO `boss_namedb` VALUES (129,'Scrupulous Hiathlin','Inferno, 255 Incarnator','Scrupulous Hiathlin ');
INSERT INTO `boss_namedb` VALUES (130,'Sinful Soul Dredge','Adonis, Island bridge center of Adonis','Sinful Soul Dredge ');
INSERT INTO `boss_namedb` VALUES (131,'Skulking Dryad','Adonis, West and NW Island','Skulking Dryad ');
INSERT INTO `boss_namedb` VALUES (132,'Skylight','Adonis, Abyss NW','Skylight ');
INSERT INTO `boss_namedb` VALUES (133,'Slinking Dryad','Adonis, West and NW Island','Slinking Dryad ');
INSERT INTO `boss_namedb` VALUES (134,'Snatching Soul Dredge','Adonis, Dead Ends Ark','Snatching Soul Dredge ');
INSERT INTO `boss_namedb` VALUES (135,'Special Agent Lamb','DAV','Lamb Dav');
INSERT INTO `boss_namedb` VALUES (136,'Spetses','Inferno, 255 Incarnator','Spetses ');
INSERT INTO `boss_namedb` VALUES (137,'Splintered Girder','Elysium, West wall of Central Ely','Splintered Girder ');
INSERT INTO `boss_namedb` VALUES (138,'Stark','Adonis, Abyss NW','Stark ');
INSERT INTO `boss_namedb` VALUES (139,'Steele Filar','Inferno, NE of Frontier','Steel Filar Steel Filler Steele Filler');
INSERT INTO `boss_namedb` VALUES (140,'Stumpy','2200x1300, Greater Omni-Forest','Stumpy ');
INSERT INTO `boss_namedb` VALUES (141,'Supply Master Eel','Secondary Base, Avalon','Supplymaster Eel Eel');
INSERT INTO `boss_namedb` VALUES (142,'Supply Master Smug','NE Wailing Wastes','Supplymaster Smaug Smaug');
INSERT INTO `boss_namedb` VALUES (143,'Swirling Eremite','Elysium, Sand dunes near Cold Rock','Swirling Eremite ');
INSERT INTO `boss_namedb` VALUES (144,'T.I.M.','Foremans, 2000x800, TLR','TIM Biomare Foremans');
INSERT INTO `boss_namedb` VALUES (145,'Tarasque','2092x3822, Camelot, Avalon','Tara Camelot');
INSERT INTO `boss_namedb` VALUES (146,'Taurus','Pandemonium, Middle Node','Taurus Zods Zodiac Zodiacs ');
INSERT INTO `boss_namedb` VALUES (147,'Tdecin','Elysium, inside mountains SW and NW','Tdecin ');
INSERT INTO `boss_namedb` VALUES (148,'The Beast','Pandemonium','Beast');
INSERT INTO `boss_namedb` VALUES (149,'The Nightheart','Pandemonium','Nightheart');
INSERT INTO `boss_namedb` VALUES (150,'The Obediency Enforcer','2000x2400, Eastern Fouls Plains','Obediency Enforcer');
INSERT INTO `boss_namedb` VALUES (151,'The One','2250x1810, Southern Fouls Hills','The One ');
INSERT INTO `boss_namedb` VALUES (152,'The Pest','1360x2300, DAV','The Pest Dav ');
INSERT INTO `boss_namedb` VALUES (153,'Tinos','Inferno, West of Razors Lair','Tinos ');
INSERT INTO `boss_namedb` VALUES (154,'Tiunissik','Inferno, North of Sorrow','Tiunissik ');
INSERT INTO `boss_namedb` VALUES (155,'Torrid Spirit','Inferno, North of Sorrow',' Torrid Spirit');
INSERT INTO `boss_namedb` VALUES (156,'Torrith The Ancient','Greater Tir County Coords: 400x2200','Torrith');
INSERT INTO `boss_namedb` VALUES (157,'Tri-Plumbo','Foremans, 2000x800, TLR','Tri Plumbo Foremans Biomare');
INSERT INTO `boss_namedb` VALUES (158,'Tuqusk','Inferno, South of Frontier','Tuqusk ');
INSERT INTO `boss_namedb` VALUES (159,'Turk','Adonis, Abyss NW','Turk ');
INSERT INTO `boss_namedb` VALUES (160,'Tyro Beasthandler','Inferno, 255 Incarnator','Tyro Beasthandler');
INSERT INTO `boss_namedb` VALUES (161,'Ushamaham','Inferno, South of Frontier','Ushamaham ');
INSERT INTO `boss_namedb` VALUES (162,'Virgo','Pandemonium, West Node','Virgo Zods Zodiac Zodiacs');
INSERT INTO `boss_namedb` VALUES (163,'Waning Soul','Elysium, E Whispervale and 115 Inc','Waning Soul ');
INSERT INTO `boss_namedb` VALUES (164,'Wounded Predator','Elysium, South of Remnans','Wounded Predator ');
INSERT INTO `boss_namedb` VALUES (165,'Zias','Elysium, inside mountains SW and NW','Zias ');
INSERT INTO `boss_namedb` VALUES (166,'Xark The Battletoad','Inferno, Xarks Lair, NE of Yuttos','Xark');
INSERT INTO `boss_namedb` VALUES (167,'Inobak The Gelid','Inner Sanctum, 3rd Floor','Inobak Inner Sanctum');
INSERT INTO `boss_namedb` VALUES (168,'Hezak The Immortal','Inner Sanctum, 3rd Floor','Hezak Inner Sanctum');
INSERT INTO `boss_namedb` VALUES (169,'Dominus Facut The Bloodless','Inner Sanctum, 3rd Floor','Dominus Facut The Bloodless Inner Sanctum');
INSERT INTO `boss_namedb` VALUES (170,'Dominus Ummoh The Pedagogue','Inner Sanctum, 3rd Floor','Dominus Ummoh The Pedagogue Inner Sanctum');
INSERT INTO `boss_namedb` VALUES (171,'Dominus Jiannu','Inner Sanctum, 3rd Floor','Dominus Jiannu Inner Sanctum');
INSERT INTO `boss_namedb` VALUES (172,'Iskop The Idolator','Inner Sanctum, 3rd Floor','Iskop The Idolator Inner Sanctum');
INSERT INTO `boss_namedb` VALUES (173,'Jeuru The Defiler','Inner Sanctum, 3rd Floor','Jeuru The Defiler Inner Sanctum');
INSERT INTO `boss_namedb` VALUES (174,'Wicked Soul Dredge','Adonis, Dead Ends Ark',' ');
INSERT INTO `boss_namedb` VALUES (175,'Numiel','Inferno, Fronter','Numiel ');
INSERT INTO `boss_namedb` VALUES (176,'Asanon','Inferno, Fronter','Asanon ');
INSERT INTO `boss_namedb` VALUES (177,'Ahomac','Inferno, Fronter','Ahomac ');
INSERT INTO `boss_namedb` VALUES (178,'Hebial','Inferno, Fronter',' Hebial');
INSERT INTO `boss_namedb` VALUES (179,'Primus Scrap Pillager','Primus Camp (EFP)','Scrap Pillager Primus Camp Primus');
INSERT INTO `boss_namedb` VALUES (180,'Primus Outlaw','Primus Camp(EFP)','Primus Outlaw Primus Camp Primus ');
INSERT INTO `boss_namedb` VALUES (181,'Distracted Snake Tamer','Inferno, 225 Incarnator','Snake Tamer');
INSERT INTO `boss_namedb` VALUES (182,'First Brood Champion','Hollow Island','First Brood Champion Hollow Island ');
INSERT INTO `boss_namedb` VALUES (183,'Second Brood Champion','Hollow Island','Second Brood Champion Hollow Island ');
INSERT INTO `boss_namedb` VALUES (184,'Third Brood Champion','Hollow Island','Third Brood Champion Hollow Island ');
INSERT INTO `boss_namedb` VALUES (185,'Fourth Brood Champion','Hollow Island',' Fourth Brood Champion Hollow Island');
INSERT INTO `boss_namedb` VALUES (186,'Fifth Brood Champion','Hollow Island','Fifth Brood Champion Hollow Island ');
INSERT INTO `boss_namedb` VALUES (187,'Sixth Brood Champion','Hollow Island','Sixth Brood Champion Hollow Island ');
INSERT INTO `boss_namedb` VALUES (188,'Seventh Brood Champion','Hollow Island','Seventh Brood Champion Hollow Island ');
INSERT INTO `boss_namedb` VALUES (189,'Eighth Brood Champion','Hollow Island','Eighth Brood Champion Hollow Island ');
INSERT INTO `boss_namedb` VALUES (190,'Ninth Brood Champion','Hollow Island','Ninth Brood Champion Hollow Island ');
INSERT INTO `boss_namedb` VALUES (191,'Tenth Brood Champion','Hollow Island','Tenth Brood Champion Hollow Island ');
INSERT INTO `boss_namedb` VALUES (192,'The Hollow Island Suzerain','Hollow Island','The Hollow Island Suzerain Hollow Island');
INSERT INTO `boss_namedb` VALUES (193,'The Brood Mother','Hollow Island','The Brood Mother Hollow Island');
INSERT INTO `boss_namedb` VALUES (194,'Hollow Island Weed','Hollow Island','Hollow Island Weed Hollow Island ');
INSERT INTO `boss_namedb` VALUES (195,'Algid Slither','Adonis, NW Cave underwater','Algid Slither ');
INSERT INTO `boss_namedb` VALUES (196,'Brumal Slither','Adonis, NW Cave underwater','Brumal Slither ');
INSERT INTO `boss_namedb` VALUES (197,'Chilly Slither','Adonis, NW Cave underwater','Chilly Slither ');
INSERT INTO `boss_namedb` VALUES (198,'Cold Slither','Adonis, NW Cave underwater','Cold Slither ');
INSERT INTO `boss_namedb` VALUES (199,'Nippy Slither','Adonis, NW Cave underwater','Nippy Slither ');
INSERT INTO `boss_namedb` VALUES (200,'Gashing Soul Dredge','?','Gashing Soul Dredge ');
INSERT INTO `boss_namedb` VALUES (201,'Iced Slither','Adonis, NW Cave underwater','Iced Slither ');
INSERT INTO `boss_namedb` VALUES (202,'Iniquitous Spirit','?','Iniquitous Spirit ');
INSERT INTO `boss_namedb` VALUES (203,'Tiny','?','Tiny ');
INSERT INTO `boss_namedb` VALUES (204,'Trup','?','Trup ');
INSERT INTO `boss_namedb` VALUES (205,'Vile Spirit','?','Vile Spirit ');
INSERT INTO `boss_namedb` VALUES (206,'Jack Legchopper','Varmint Woods','Jack Legchopper ');
INSERT INTO `boss_namedb` VALUES (207,'Trash King','Junkyard outside West Athen, Athen Shire, 1600 x 1000','TK ');
INSERT INTO `boss_namedb` VALUES (208,'Colonel Frank Kaehler','Omni-Forest Coordinates 700 x 2000','Colonel Frank Kaehler ');
INSERT INTO `boss_namedb` VALUES (209,'Lord Ghasap','2092x3822, Camelot, Avalon','Camelot Lord Gasp Lord Ghasp');
INSERT INTO `boss_namedb` VALUES (210,'Eumenides','Condemned Subway','Eumendes Subway');
INSERT INTO `boss_namedb` VALUES (211,'Vergil Aeneid','Condemned Subway','Subway Virgil Aeneid Vergil Aeneid Virgil Aeneid');
INSERT INTO `boss_namedb` VALUES (212,'Abmouth Supremus','Condemned Subway','Subway');
INSERT INTO `boss_namedb` VALUES (213,'General Serverus','Cyborg Barracks Greater Tir County 3232 x 2340','Cyborg Barracks Severous Serverous');
INSERT INTO `boss_namedb` VALUES (214,'Eradicator Deimos','Cyborg Barracks Greater Tir County 3232 x 2340','Cyborg Barracks');
INSERT INTO `boss_namedb` VALUES (215,'Techleader Praetor','Cyborg Barracks Greater Tir County 3232 x 2340','Cyborg Barracks ');
INSERT INTO `boss_namedb` VALUES (216,'Augmented Cyborg Hellfury','Cyborg Barracks Greater Tir County 3232 x 2340','Cyborg Barracks ');
INSERT INTO `boss_namedb` VALUES (217,'Prototype Inferno','Cyborg Barracks Greater Tir County 3232 x 2340','Cyborg Barracks ');
INSERT INTO `boss_namedb` VALUES (218,'Commander Jocasta','Cyborg Barracks Greater Tir County 3232 x 2340','Cyborg Barracks ');
INSERT INTO `boss_namedb` VALUES (219,'Defender Of The Three','Temple Of The Three Winds Greater Tir County','Totw Dot Temple Of The Three Winds');
INSERT INTO `boss_namedb` VALUES (220,'The Curator','Temple Of The Three Winds Greater Tir County','Totw Yoda Temple Of The Three Winds');
INSERT INTO `boss_namedb` VALUES (221,'Nematet The Custodian Of Time','Temple Of The Three Winds Greater Tir County','Totw Temple Of The Three Winds');
INSERT INTO `boss_namedb` VALUES (222,'The Re-animator','Temple Of The Three Winds Greater Tir County','Totw Temple Of The Three Winds Reanimator');
INSERT INTO `boss_namedb` VALUES (223,'Lein The Memorystalker','Temple Of The Three Winds Greater Tir County','Totw Temple Of The Three Winds');
INSERT INTO `boss_namedb` VALUES (224,'Guardian Of Tomorrow','Temple Of The Three Winds Greater Tir County','Totw Got Temple Of The Three Winds');
INSERT INTO `boss_namedb` VALUES (225,'Uklesh The Frozen','Temple Of The Three Winds Greater Tir County','Totw Temple Of The Three Winds');
INSERT INTO `boss_namedb` VALUES (226,'Aztur The Immortal','Temple Of The Three Winds Greater Tir County','Totw Aztur Temple Of The Three Winds');
INSERT INTO `boss_namedb` VALUES (227,'Gartua The Doorkeeper','Temple Of The Three Winds Greater Tir County','Totw Temple Of The Three Winds Keeper');
INSERT INTO `boss_namedb` VALUES (228,'Windcaller Yatilla','Temple Of The Three Winds Greater Tir County','Totw Temple Of The Three Winds');
INSERT INTO `boss_namedb` VALUES (229,'Den Smuggler Pilot','Smugglers Den, 1755x872, SFH.','Smugglers Smugglers Den Pilot');
