<?php

/*
** Author: Honge (RK2)
** Description: Shows a random chuck quote 
** Version: 1.0
**
** Developed for: Budabot(http://sourceforge.net/projects/budabot)
** Additions taken from a module written by Temar for Bebot: http://bebot.shadow-realm.org/0-3-x-customunofficial-modules/chuck-norris/
** Date(created):2.6.08
** Date(last modified): 2.7.08
**
** Licence Infos: 
** This file is part of Budabot.
**
** Budabot is free software; you can redistribute it and/or modify
** it under the terms of the GNU General Public License as published by
** the Free Software Foundation; either version 2 of the License, or
** (at your option) any later version.
**
** Budabot is distributed in the hope that it will be useful,
** but WITHOUT ANY WARRANTY; without even the implied warranty of
** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
** GNU General Public License for more details.
**
** You should have received a copy of the GNU General Public License
** along with Budabot; if not, write to the Free Software
** Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
*/

$chuck = array( 
    "Chuck Norris counted to infinity - twice.", 
    "Some kids piss their name in the snow. Chuck Norris can piss his name into concrete.",
    "Leading hand sanitizers claim they can kill 99.9 percent of germs. Chuck Norris can kill 100 percent of whatever the fuck he wants.",
    "Chuck Norris' calendar goes straight from March 31st to April 2nd; no one fools Chuck Norris.",
    "Chuck Norris' tears cure cancer. Too bad he has never cried.",
    "Chuck Norris does not sleep. He waits.",
    "Once, while having sex in a tractor-trailer, part of Chuck Norris' sperm escaped and got into the engine. We now know this truck as Optimus Prime.",
    "Chuck Norris can speak braille.",
    "Chuck Norris puts the laughter in manslaughter",
    "If you spell Chuck Norris wrong on Google it doesn't say, Did you mean Chuck Norris? It simply replies, Run while you still have the chance.",
    "Chuck Norris owns the greatest Poker Face of all-time. It helped him win the 1983 World Series of Poker despite him holding just a Joker, a Get out of Jail Free Monopoly card, a 2 of clubs, 7 of spades and a green #4 card from the game Uno.",
    "On a high school math test, Chuck Norris put down Violence as every one of the answers. He got an A+ on the test because Chuck Norris solves all his problems with Violence.",
    "Chuck Norris can do a wheelie on a unicycle.",
    "Chuck Norris once won a game of Connect Four in 3 moves.",
    "Chuck Norris can delete the Recycling Bin.",
    "Once a cobra bit Chuck Norris leg. After five days of excruciating pain, the cobra died.",
    "When the Boogeyman goes to sleep every night he checks his closet for Chuck Norris.",
    "Chuck Norris was originally cast as the main character in 24, but was replaced by the producers when he managed to kill every terrorist and save the day in 12 minutes and 37 seconds.",
    "Chuck Norris died ten years ago, but the Grim Reaper can't get up the courage to tell him.",
    "Chuck Norris does not hunt because the word hunting implies the possibility of failure. Chuck Norris goes killing.",
    "Chuck Norris can slam revolving doors.",
    "If it looks like chicken, tastes like chicken, and feels like chicken but Chuck Norris says its beef, then it's fucking beef.",
    "Superman owns a pair of Chuck Norris pajamas.",
    "Giraffes were created when Chuck Norris uppercutted a horse.",
    "Chuck Norris can have both feet on the ground and kick ass at the same time.",
    "Chuck Norris' house does not have security guards. Rather, he employs a single man in uniform to lead burglars to his bedroom, where they are never heard from again.",
    "Chuck Norris doesn't read books. He stares them down until he gets the information he wants.",
    "Chuck Norris sleeps with a night light. Not because Chuck Norris is afraid of the dark, but the dark is afraid of Chuck Norris",
    "Chuck Norris secretly sleeps with every woman in the world once a month. They bleed for a week as a result.",
    "When Chuck Norris gives you the finger, he's telling you how many seconds you have left to live.",
    "Chuck Norris sold his soul to the devil for his rugged good looks and unparalleled martial arts ability. Shortly after the transaction was finalized, Chuck roundhouse kicked the devil in the face and took his soul back. The devil, who appreciates irony, couldn't stay mad and admitted he should have seen it coming. They now play poker every second Wednesday of the month.",
    "If you play Led Zeppelin's Stairway to Heaven backwards, you will hear Chuck Norris banging your sister.",
    "Chuck Norris' dog is trained to pick up his own poop because Chuck Norris will not take shit from anyone.",
    "Chuck Norris can kill two stones with one bird.",
    "Chuck Norris was once on Celebrity Wheel of Fortune and was the first to spin. The next 29 minutes of the show consisted of everyone standing around awkwardly, waiting for the wheel to stop.",
    "Chuck Norris is always on top during sex because Chuck Norris never fucks up.",
    "Chuck Norris can play the violin with a piano",
    "Chuck Norris is the only person on the planet that can kick you in the back of the face.",
    "Chuck Norris doesn't have hair on his testicles, because hair does not grow on steel.",
    "Chuck Norris eats the core of an apple first.",
    "Ghosts are actually caused by Chuck Norris killing people faster than Death can process them.",
    "Bill Gates lives in constant fear that Chuck Norris' PC will crash.",
    "Chuck Norris doesn't pop his collar, his shirts just get erections when they touch his body.",
    "The best part of waking up is not Folgers in your cup, but knowing that Chuck Norris didn't kill you in your sleep.",
    "Death once had a near-Chuck-Norris experience.",
    "Chuck Norris never retreats, he just attacks in the opposite direction.",
    "Chuck Norris was once charged with three attempted murdered in Boulder County, but the Judge quickly dropped the charges because Chuck Norris does not attempt murder.",
    "Chuck Norris can strangle you with a cordless phone.",
    "The reason newborn babies cry is because they know they have just entered a world with Chuck Norris.",
    "Chuck Norris has to maintain a concealed weapon license in all 50 states in order to legally wear pants.",
    "Chuck Norris can build a snowman out of rain.",
    "Chuck Norris plays russian roulette with a fully loded revolver... and wins.",
    "M.C. Hammer learned the hard way that Chuck Norris can touch this.",
    "Chuck Norris is not hung like a horse... horses are hung like Chuck Norris",
    "Chuck Norris once punched a man in the soul.",
    "Mr. T once defeated Chuck Norris in a game of Tic-Tac-Toe. In retaliation, Chuck Norris invented racism.",
    "Chuck Norris likes to knit sweaters in his free time. And by knit, I mean kick, and by sweaters, I mean babies",
    "Chuck Norris is 1/8th Cherokee. This has nothing to do with ancestry, the man ate a fucking Jeep.",
    "Chuck Norris once had a heart attack; his heart lost.",
    "It is considered a great accomplishment to go down Niagara Falls in a wooden barrel. Chuck Norris can go up Niagara Falls in a cardboard box.",
    "When Chuck Norris looks in a mirror the mirror shatters, because not even glass is stupid enough to get in between Chuck Norris and Chuck Norris.",
    "When Chuck Norris enters a room, he doesn't turn the lights on, he turns the dark off.",
    "Chuck Norris can drown a fish.",
    "Jack was nimble, Jack was quick, but Jack still couldn't dodge Chuck Norris' roundhouse kick.",
    "The only time Chuck Norris was wrong was when he thought he had made a mistake.",
    "Chuck Norris doesn't need a miracle in order to split the ocean. He just walks in and the water gets the fuck out of the way.",
    "A Handicap parking sign does not signify that this spot is for handicapped people. It is actually in fact a warning, that the spot belongs to Chuck Norris and that you will be handicapped if you park there.",
    "Rosa Parks refused to get out of her seat because she was saving it for Chuck Norris.",
    "A rogue squirrel once challenged Chuck Norris to a nut hunt around the park. Before beginning, Chuck simply dropped his pants, instantly killing the squirrel and 3 small children. Chuck knows you can't find bigger, better nuts than that.",
    "Chuck Norris can make a paraplegic run for his life.",
    "Chuck Norris doesn't use pickup lines, he simply says, Now.",
    "Brett Favre can throw a football over 50 yards. Chuck Norris can throw Brett Favre even further.",
    "The chief export of Chuck Norris is pain.",
    "When God said, Let there be light, Chuck Norris said, say please.",
    "The last digit of pi is Chuck Norris. He is the end of all things.",
    "Chuck Norris can create a rock so heavy that even he can't lift it. And then he lifts it anyways, just to show you who the fuck Chuck Norris is.",
    "Chuck Norris is the only person that can punch a cyclops between the eye.",
    "Chuck Norris once bowled a 300. Without a ball. He wasn't even in a bowling alley.",
    "Chuck Norris can tie his shoes with his feet.",
    "The quickest way to a man's heart is with Chuck Norris's fist.",
    "Chuck Norris doesn't play hide-and-seek. He plays hide-and-pray-I-don't-find-you.",
    "If you can see Chuck Norris, he can see you. If you can't see Chuck Norris you may be only seconds away from death.",
    "Chuck Norris is currently suing NBC, claiming Law and Order are trademarked names for his left and right legs.",
    "The phrase, You are what you eat cannot be true based on the amount of pussy Chuck Norris eats.",
    "Chuck Norris once had an erection while lying face down and struck oil.",
    "Chuck Norris was originally offered the role as Frodo in Lord of the Rings. He declined because, Only a pussy would need three movies to destroy a piece of jewelery.",
    "Chuck Norris does not know where you live, but he knows where you will die.",
    "Chuck Norris is currently in a legal battle with the makers of Bubble Tape. Norris claims 6 Feet of Fun is actually the trademark for his penis.",
    "Bullets dodge Chuck Norris.",
    "When Chuck Norris goes cow-tipping, he lifts a cow up and drop kicks it into the neighboring farm. All the other cows simply tip themselves over to keep from having to walk back in the dark.",
    "Chuck Norris used to beat the shit out of his shadow because it was following to close. It now stands a safe 30 feet behind him.",
    "The saddest moment for a child is not when he learns Santa Claus isn't real, it's when he learns Chuck Norris is.",
    "Someone once tried to tell Chuck Norris that roundhouse kicks aren't the best way to kick someone. This has been recorded by historians as the worst mistake anyone has ever made.",
    "Before Chuck Norris was born, the martial arts weapons with two pieces of wood connected by a chain were called NunBarrys. No one ever did find out what happened to Barry.",
    "Pinatas were made in an attempt to get Chuck Norris to stop kicking the people of Mexico. Sadly this backfired, as all it has resulted in is Chuck Norris now looking for candy after he kicks his victims.",
    "Chuck Norris cannot predict the future; the future just better fucking do what Chuck Norris says.",
    "Most men are okay with their wives fantasizing about Chuck Norris during sex, because they are doing the same thing.",
    "Upon hearing that his good friend, Lance Armstrong, lost his testicles to cancer, Chuck Norris donated one of his to Lance. With just one of Chuck's nuts, Lance was able to win the Tour De France seven times. By the way, Chuck still has two testicles; either he was able to produce a new one simply by flexing, or he had three to begin with. No one knows for sure.",
    "We all know the magic word is please. As in the sentence, Please don't kill me. Too bad Chuck Norris doesn't believe in magic.",
    "Chuck Norris built a time machine and went back in time to stop the JFK assassination. As Oswald shot, Chuck Norris met all three bullets with his beard, deflecting them. JFK's head exploded out of sheer amazement.",
    "Chuck Norris has already been to Mars; that's why there are no signs of life there.",
    "They once made a Chuck Norris toilet paper, but it wouldn't take shit from anybody.",
    "A blind man once stepped on Chuck Norris' shoe. Chuck replied, Don't you know who I am? I'm Chuck Norris! The mere mention of his name cured this man blindness. Sadly the first, last, and only thing this man ever saw, was a fatal roundhouse delivered by Chuck Norris.",
    "There is no chin behind Chuck Norris' beard. There is only another fist.",
    "In fine print on the last page of the Guinness Book of World Records it notes that all world records are held by Chuck Norris, and those listed in the book are simply the closest anyone else has ever gotten.", 
    "The Great Wall of China was originally created to keep Chuck Norris out. It failed misserably.",
    "Crop circles are Chuck Norris' way of telling the world that sometimes corn needs to lie the fuck down.",
    "Chuck Norris once ate an entire ream of rice paper and shat out origami swans and Mister Miyagi from Karate Kid.",
    "Chuck Norris is ten feet tall, weighs two-tons, breathes fire, and could eat a hammer and take a shotgun blast standing. ",
    "The Four Horsemen of the Apocalypse actually live in Chuck Norris's nutsack.",
    "Chuck Norris put humpty dumpty back together again, only to roundhouse kick him in the face. Later Chuck dined on scrambled eggs with all the king's horses and all the king's men. The king himself could not attend for unspecified reasons. Coincidentally, the autopsoy revealed the cause of death to be a roundhouse kick to the face. There is only one King.",
    "When Chuck Norris played golf for money, chuck marked down a hole in 0 every time, a pro at the golf club, said to Chuck: excuse me sir, but you cant score zero on a hole. Chuck Norris turned towards the man and said, im Chuck Norris, the man then proceeded to pour gas over his body and set himself on fire because that would be less painful than getting roundhouse kicked by Chuck Norris, Chuck Norris roundhouse kicked him in the face anyways.",
    "Chuck Norris made Ellen Degeneres straight.",
    "Chuck Norris kicked Neo out of Zion , now Neo is The Two",
    "Chuck Norris' iPod came with a real charger instead of just a USB cord",
    "Chuck Norris knows where Carmen Sandiego is.",
    "Rudolph has a red nose because he got lippy and Chuck Norris roundhouse kicked him across the face several times",
    "China was once bordering the United States, until Chuck Norris roundhouse kicked it all the way through the Earth.",
    "Chuck Norris is what Willis was talking about",
    "If you have five dollars and Chuck Norris has five dollars, Chuck Norris has more money than you.",
    "When Chuck Norris had surgery, the anesthesia was applied to the doctors.",
    "Chuck Norris once broke the land speed record on a bicycle that was missing its chain and the back tire.",
    "Chuck Norris once kicked a baby elephant into puberty",
    "Multiple people have died from Chuck Norris giving them the finger.",
    "Chuck Norris once tried to wear glasses. The result was him seeing around the world to the point where he was looking at the back of his own head.",
    "Pee Wee Herman got arrested for masturbating in public. The same day, Chuck Norris got an award for masturbating in public.",
    "Once a grizzly bear threatened to eat Chuck Norris. Chuck showed the bear his fist and the bear proceeded to eat himself, because it would be the less painful way to die.",
    "If Chuck Norris is late, time better slow the fuck down",
    "Chuck Norris ordered a Big Mac at Burger King, and got one.",
    "Chuck Norris frequently donates blood to the Red Cross. Just never his own.",
    "There is no such thing as tornados. Chuck Norris just hates trailer parks",
    "Chuck Norris doesn't worry about changing his clock twice a year for daylight savings time. The sun rises and sets when Chuck tells it to.",
    "Chuck Norris was the fourth Wiseman. He brought baby Jesus the gift of \"beard\". Jesus wore it proudly to his dying day. The other Wisemen, jealous of Jesus' obvious gift favoritism, used their combined influence to have Chuck omitted from the Bible. Shortly after all three died of roundhouse kick related deaths. ",
    "If paper beats rock, rock beats scissors, and scissors beats paper, what beats all 3 at the same time? Answer: Chuck Norris. ",
    "Although it is not common knowledge, there are actually three sides to the Force: the light side, the dark side, and Chuck Norris.",
    "Scientists used to believe that diamond was the world's hardest substance. But then they met Chuck Norris, who gave them a roundhouse kick to the face so hard, and with so much heat and pressure, that the scientists turned into artificial Chuck Norris. ",
    "When Chuck Norris was denied a Bacon McMuffin at McDonalds because it was 10:35, he roundhouse kicked the store so hard it became a KFC.",
    "Chuck Norris drinks napalm to quell his heartburn.",
    "A duck's quack does not echo. Chuck Norris is solely responsible for this phenomenon. When asked why he will simply stare at you, grimly.",
    "Chuck Norris' roundhouse kick is so powerful, it can be seen from outer space by the naked eye. ",
    "Chuck Norris doesn't believe in Germany. ",
    "If you want a list of Chuck Norris' enemies, just check the extinct species list. ",
    "Chuck Norris has never blinked in his entire life. Never. ",
    "Chuck Norris eats transformer toys in vehicle mode and poos them out transformed into a robot. ",
    "Ironically, Chuck Norris' hidden talent is invisibility. ",
    "Chuck Norris invented water.",
    "Chuck Norris went looking for a bar but couldn't find one. He walked to a vacant lot and sat there. Sure enough within an hour and a half someone constructed a bar around him. He then ordered a shot, drank it, and then burned the place to the ground. Chuck Norris yelled over the roar of the flames, always leave things the way you found em.",
    "One time while sparring with Wolverine, Chuck Norris accidentally lost his left testicle. You might be familiar with it to this very day by its technical term: Jupiter. ",
    "Chuck Norris is Luke Skywalker's real father.",
    "Chuck Norris once visited the Virgin Islands. They are now The Islands.",
	"Chuck Norris once roundhouse kicked someone so hard that his foot broke the speed of light, went back in time, and killed Amelia Earhart while she was flying over the Pacific Ocean. ",
	"Crop circles are Chuck Norris' way of telling the world that sometimes corn needs to lie down. ",
	"Chuck Norris is ten feet tall, weighs two-tons, breathes fire, and could eat a hammer and take a shotgun blast standing.",
	"The Great Wall of China was originally created to keep Chuck Norris out. It failed miserably.",
	"Contrary to popular belief, Chuck Norris, not the box jellyfish of northern Australia, is the most venomous creature on earth. Within 3 minutes of being bitten, a human being experiences the following symptoms: fever, blurred vision, beard rash, tightness of the jeans, and the feeling of being repeatedly kicked through a car windshield.",
	"Most people have 23 pairs of chromosomes. Chuck Norris has 72... and they're all poisonous.",
	"If you ask Chuck Norris what time it is, he always says, &quot;Two seconds 'til.&quot; After you ask, &quot;Two seconds 'til what?&quot; he roundhouse kicks you in the face.",
	"Chuck Norris drives an ice cream truck covered in human skulls.",
	"When Chuck Norris sends in his taxes, he sends blank forms and includes only a picture of himself, crouched and ready to attack. Chuck Norris has not had to pay taxes, ever.",
	"The quickest way to a man's heart is with Chuck Norris' fist.",
	"Chuck Norris invented Kentucky Fried Chicken's famous secret recipe, with eleven herbs and spices. But nobody ever mentions the twelfth ingredient: Fear.",
	"CNN was originally created as the &quot;Chuck Norris Network&quot; to update Americans with on-the-spot ass kicking in real-time.",
	"Chuck Norris can win a game of Connect Four in only three moves.",
	"There is no theory of evolution, just a list of creatures Chuck Norris allows to live.",
	"Chuck Norris once ate three 72 oz. steaks in one hour. He spent the first 45 minutes having sex with his waitress.",
	"What was going through the minds of all of Chuck Norris' victims before they died? His shoe.",
	"Chuck Norris is the only man to ever defeat a brick wall in a game of tennis.",
	"Police label anyone attacking Chuck Norris as a Code 45-11.... a suicide.",
	"Chuck Norris doesn't churn butter. He roundhouse kicks the cows and the butter comes straight out.",
	"Chuck Norris doesn’t wash his clothes, he disembowels them.",
	"A Handicapped parking sign does not signify that this spot is for handicapped people. It is actually in fact a warning, that the spot belongs to Chuck Norris and that you will be handicapped if you park there.",
	"Chuck Norris will attain statehood in 2009. His state flower will be the Magnolia.",
	"Someone once videotaped Chuck Norris getting pissed off. It was called Walker: Texas Chain Saw Masacre.",
	"If you spell Chuck Norris in Scrabble, you win. Forever.",
	"Chuck Norris originally appeared in the &quot;Street Fighter II&quot; video game, but was removed by Beta Testers because every button caused him to do a roundhouse kick. When asked bout this &quot;glitch,&quot; Norris replied, &quot;That's no glitch.&quot;",
	"Fool me once, shame on you. Fool Chuck Norris once and he will roundhouse you in the face. ",
	"The opening scene of the movie &quot;Saving Private Ryan&quot; is loosely based on games of dodgeball Chuck Norris played in second grade.",
	"Chuck Norris once shot down a German fighter plane with his finger, by yelling, &quot;Bang!&quot;",
	"Chuck Norris once bet NASA he could survive re-entry without a spacesuit. On July 19th, 1999, a naked Chuck Norris re-entered the earth's atmosphere, streaking over 14 states and reaching a temperature of 3000 degrees. An embarrassed NASA publically claimed it was a meteor, and still owes him a beer.",
	"Chuck Norris has two speeds: Walk and Kill.",
	"Someone once tried to tell Chuck Norris that roundhouse kicks aren't the best way to kick someone. This has been recorded by historians as the worst mistake anyone has ever made.",
	"Contrary to popular belief, America is not a democracy, it is a Chucktatorship.",
	"Teenage Mutant Ninja Turtles is based on a true story: Chuck Norris once swallowed a turtle whole, and when he crapped it out, the turtle was six feet tall and had learned karate.",
	"Chuck Norris is not hung like a horse... horses are hung like Chuck Norris.",
	"Faster than a speeding bullet ... more powerful than a locomotive ... able to leap tall buildings in a single bound... yes, these are some of Chuck Norris's warm-up exercises.",
	"Chuck Norris is the only human being to display the Heisenberg uncertainty principle -- you can never know both exactly where and how quickly he will roundhouse-kick you in the face.",
	"In the Bible, Jesus turned water into wine. But then Chuck Norris turned that wine into beer.",
	"Chuck Norris can hit you so hard that he can actually alter your DNA. Decades from now your descendants will occasionally clutch their heads and yell &quot;What The Hell was That?&quot; ",
	"Time waits for no man. Unless that man is Chuck Norris.",
	"Chuck Norris discovered a new theory of relativity involving multiple universes in which Chuck Norris is even more badass than in this one. When it was discovered by Albert Einstein and made public, Chuck Norris roundhouse-kicked him in the face. We know Albert Einstein today as Stephen Hawking.",
	"Chuck Norris doesn't shower, he only takes blood baths.",
	"The Chuck Norris military unit was not used in the game Civilization 4, because a single Chuck Norris could defeat the entire combined nations of the world in one turn.",
	"In an average living room there are 1,242 objects Chuck Norris could use to kill you, including the room itself.",
	"According to the Encyclopedia Brittanica, the Native American &quot;Trail of Tears&quot; has been redefined as anywhere that Chuck Norris walks.",
	"Chuck Norris does not teabag the ladies. He potato-sacks them.",
	"Pluto is actually an orbiting group of British soldiers from the American Revolution who entered space after the Chuck gave them a roundhouse kick to the face.",
	"When Chuck Norris goes to donate blood, he declines the syringe, and instead requests a hand gun and a bucket.",
	"There are no steroids in baseball. Just players Chuck Norris has breathed on.",
	"Chuck Norris once challenged Lance Armstrong in a &quot;Who has more testicles?&quot; contest. Chuck Norris won by 5.",
	"Chuck Norris was the fourth wise man, who gave baby Jesus the gift of beard, which he carried with him until he died. The other three wise men were enraged by the preference that Jesus showed to Chuck's gift, and arranged to have him written out of the bible. All three died soon after of mysterious roundhouse-kick related injuries.",
	"Chuck Norris sheds his skin twice a year.",
	"When Chuck Norris calls 1-900 numbers, he doesnt get charged. He holds up the phone and money falls out.",
	"Chuck Norris once ate a whole cake before his friends could tell him there was a stripper in it.",
	"Some people like to eat frogs' legs. Chuck Norris likes to eat lizard legs. Hence, snakes.",
	"There are no races, only countries of people Chuck Norris has beaten to different shades of black and blue.",
	"When Chuck Norris was denied an Egg McMuffin at McDonald's because it was 10:35, he roundhouse kicked the store so hard it became a Wendy's.",
	"Chuck Norris can't finish a &quot;color by numbers&quot; because his markers are filled with the blood of his victims. Unfortunately, all blood is dark red.",
	"A Chuck Norris-delivered Roundhouse Kick is the preferred method of execution in 16 states.",
	"When Chuck Norris falls in water, Chuck Norris doesn't get wet. Water gets Chuck Norris.",
	"Scientists have estimated that the energy given off during the Big Bang is roughly equal to 1CNRhK (Chuck Norris Roundhouse Kick)",
	"Chuck Norris’ house has no doors, only walls that he walks through.",
	"When Chuck Norris has sex with a man, it won't be because he is gay. It will be because he has run out of women.",
	"How much wood would a woodchuck chuck if a woodchuck could Chuck Norris? ...All of it.",
	"Chuck Norris doesn't actually write books, the words assemble themselves out of fear.",
	"In honor of Chuck Norris, all McDonald's in Texas have an even larger size than the super-size. When ordering, just ask to be Chucksized. ",
	"Chuck Norris CAN believe it's not butter.",
	"If tapped, a Chuck Norris roundhouse kick could power the country of Australia for 44 minutes.",
	"Chuck Norris can divide by zero.",
	"The grass is always greener on the other side, unless Chuck Norris has been there. In that case the grass is most likely soaked in blood and tears.",
	"A picture is worth a thousand words. A Chuck Norris is worth 1 billion words.",
	"Newton's Third Law is wrong: Although it states that for each action, there is an equal and opposite reaction, there is no force equal in reaction to a Chuck Norris roundhouse kick.",
	"Chuck Norris invented his own type of karate. It's called Chuck-Will-Kill.",
	"When an episode of Walker Texas Ranger was aired in France, the French surrendered to Chuck Norris just to be on the safe side.",
	"While urinating, Chuck Norris is easily capable of welding titanium.",
	"Chuck Norris once sued the Houghton-Mifflin textbook company when it became apparent that their account of the war of 1812 was plagiarized from his autobiography.",
	"When Chuck Norris talks, everybody listens. And dies.",
	"When Steven Seagal kills a ninja, he only takes its hide. When Chuck Norris kills a ninja, he uses every part.",
	"Wilt Chamberlain claims to have slept with more than 20,000 women in his lifetime. Chuck Norris calls this &quot;a slow Tuesday.&quot;",
	"Contrary to popular belief, there is indeed enough Chuck Norris to go around.",
	"Chuck Norris doesnt shave; he kicks himself in the face. The only thing that can cut Chuck Norris is Chuck Norris.",
	"For some, the left testicle is larger than the right one. For Chuck Norris, each testicle is larger than the other one.",
	"Chuck Norris always knows the EXACT location of Carmen SanDiego.",
	"When taking the SAT, write &quot;Chuck Norris&quot; for every answer. You will score over 8000.",
	"Chuck Norris invented black. In fact, he invented the entire spectrum of visible light. Except pink. Tom Cruise invented pink.",
	"When you're Chuck Norris, anything + anything is equal to 1. One roundhouse kick to the face.",
	"Chuck Norris has the greatest Poker-Face of all time. He won the 1983 World Series of Poker, despite holding only a Joker, a Get out of Jail Free Monopoloy card, a 2 of clubs, 7 of spades and a green #4 card from the game UNO.",
	"On his birthday, Chuck Norris randomly selects one lucky child to be thrown into the sun.",
	"Nobody doesn't like Sara Lee. Except Chuck Norris.",
	"Chuck Norris doesn't throw up if he drinks too much. Chuck Norris throws down!",
	"In the beginning there was nothing...then Chuck Norris Roundhouse kicked that nothing in the face and said &quot;Get a job&quot;. That is the story of the universe.",
	"Chuck Norris has 12 moons. One of those moons is the Earth.",
	"Chuck Norris grinds his coffee with his teeth and boils the water with his own rage.",
	"Archeologists unearthed an old english dictionary dating back to the year 1236. It defined &quot;victim&quot; as &quot;one who has encountered Chuck Norris&quot;",
	"Chuck Norris ordered a Big Mac at Burger King, and got one.",
	"Chuck Norris and Mr. T walked into a bar. The bar was instantly destroyed, as that level of awesome cannot be contained in one building.",
	"If you Google search &quot;Chuck Norris getting his ass kicked&quot; you will generate zero results. It just doesn't happen.",
	"Chuck Norris can drink an entire gallon of milk in thirty-seven seconds.",
	"Little known medical fact: Chuck Norris invented the Caesarean section when he roundhouse-kicked his way out of his monther's womb.",
	"Chuck Norris doesn't bowl strikes, he just knocks down one pin and the other nine faint.",
	"The show Survivor had the original premise of putting people on an island with Chuck Norris. There were no survivors, and nobody is brave enough to go to the island to retrieve the footage.",
	"It takes Chuck Norris 20 minutes to watch 60 Minutes.",
	"You know how they say if you die in your dream then you will die in real life? In actuality, if you dream of death then Chuck Norris will find you and kill you.",
	"Chuck Norris has a deep and abiding respect for human life... unless it gets in his way.",
	"The Bermuda Triangle used to be the Bermuda Square, until Chuck Norris Roundhouse kicked one of the corners off.",
	"There are no weapons of mass destruction in Iraq, Chuck Norris lives in Oklahoma.",
	"Chuck Norris doesn't believe in Germany.",
	"When Chuck Norris is in a crowded area, he doesn't walk around people. He walks through them.",
	"Chuck Norris once ate an entire bottle of sleeping pills. They made him blink.",
	"James Cameron wanted Chuck Norris to play the Terminator. However, upon reflection, he realized that would have turned his movie into a documentary, so he went with Arnold Schwarzenegger.",
	"Chuck Norris can touch MC Hammer.",
	"Thousands of years ago Chuck Norris came across a bear. It was so terrified that it fled north into the arctic. It was also so terrified that all of its decendents now have white hair.",
	"Chuck Norris played Russian Roulette with a fully loaded gun and won.",
	"It takes 14 puppeteers to make Chuck Norris smile, but only 2 to make him destroy an orphanage.",
	"Chuck Norris is responsible for China's over-population. He hosted a Karate tournament in Beijing and all women within 1,000 miles became 	pregnant instantly.",
	"Some people wear Superman pajamas. Superman wears Chuck Norris pajamas.",
	"Chuck Norris once worked as a weatherman for the San Diego evening news. Every night he would make the same forecast: Partly cloudy with a 75% chance of Pain.",
	"Simply by pulling on both ends, Chuck Norris can stretch diamonds back into coal.",
	"When Chuck Norris does a pushup, he isn't lifting himself up, he's pushing the Earth down.",
	"Chuck Norris invented the bolt-action rifle, liquor, sexual intercourse, and football-- in that order.",
	"A high tide means Chuck Norris is flying over your coast. The tide is caused by God pissing his pants. ",
	"Chuck Norris keeps his friends close and his enemies closer. Close enough to drop them with one round house kick to the face. ",
	"There is in fact an “I” in Norris, but there is no “team”… not even close. ",
	"Scotty in Star Trek often says “Ye cannae change the laws of physics.” This is untrue. Chuck Norris can change the laws of physics. With his fists.",
	"An anagram for Walker Texas Ranger is KARATE WRANGLER SEX. I don't know what that is, but it sounds AWESOME.",
	"Chuck Norris doesn't stub his toes. He accidentally destroys chairs, bedframes, and sidewalks.",
	"Using his trademark roundhouse kick, Chuck Norris once made a fieldgoal in RJ Stadium in Tampa Bay from the 50 yard line of Qualcomm stadium in San Diego.",
	"Chuck Norris roundhouse kicks don't really kill people. They wipe out their entire existence from the space-time continuum.",
	"Chuck Norris does not own a stove, oven, or microwave , because revenge is a dish best served cold.",
	"Tom Clancy has to pay royalties to Chuck Norris because &quot;The Sum of All Fears&quot; is the name of Chuck Norris' autobiography.",
	"Chuck Norris can slam a revolving door.",
	"Chuck Norris is expected to win gold in every swimming competition at the 2008 Beijing Olympics, even though Chuck Norris does not swim. This is because when Chuck Norris enters the water, the water gets out of his way and Chuck Norris simply walks across the pool floor.",
	"Chuck Norris built a better mousetrap, but the world was too frightened to beat a path to his door.",
	"The original draft of The Lord of the Rings featured Chuck Norris instead of Frodo Baggins. It was only 5 pages long, as Chuck roundhouse-kicked Sauron’s ass halfway through the first chapter.",
	"Hellen Keller's favorite color is Chuck Norris.",
	"Chuck Norris eats beef jerky and craps gunpowder. Then, he uses that gunpowder to make a bullet, which he uses to kill a cow and make more beef jerky. Some people refer to this as the &quot;Circle of Life.&quot;",
	"If, by some incredible space-time paradox, Chuck Norris would ever fight himself, he'd win. Period.",
	"Chuck Norris is currently suing myspace for taking the name of what he calls everything around you.",
	"The crossing lights in Chuck Norris's home town say &quot;Die slowly&quot; and &quot;die quickly&quot;. They each have a picture of Chuck Norris punching or kicking a pedestrian.",
	"Science Fact: Roundhouse kicks are comprised primarily of an element called Chucktanium.",
	"The Sherman tank was originaly called the Norris tank until Chuck Norris decided it wasn't tough enough to be associated with him. The Army, for fear of Chuck Norris, renamed the tank and promised to develop a weapon more fitting of his name. To date, no weapon created has been badass enough to be named after Chuck Norris.",
	"Chuck Norris proved that we are alone in the universe. We weren't before his first space expedition.",
	"Superman once watched an episode of Walker, Texas Ranger. He then cried himself to sleep.",
	"Chuck Norris doesn't step on toes. Chuck Norris steps on necks.",
	"The movie &quot;Delta Force&quot; was extremely hard to make because Chuck had to downplay his abilities. The first few cuts were completely unbelievable.",
	"Movie trivia: The movie &quot;Invasion U.S.A.&quot; is, in fact, a documentary.",
	"Chuck Norris does not &quot;style&quot; his hair. It lays perfectly in place out of sheer terror.",
	"There is no such thing as global warming. Chuck Norris was cold, so he turned the sun up.",
	"A study showed the leading causes of death in the United States are: 1.Heart disease, 2. Chuck Norris, 3. Cancer",
	"It's widely believed that Jesus was Chuck Norris' stunt double for crucifixion due to the fact that it is impossible for nails to pierce Chuck Norris' skin.",
	"Chuck Norris did in fact, build Rome in a day.",
	"Along with his black belt, Chuck Norris often chooses to wear brown shoes. No one has DARED call him on it. Ever.",
	"Anytime someone is elected president in the United States, they must ask permission from Chuck Norris to live in the White House. The reason for this is because Chuck Norris had won every Federal, State, and Local election since 1777. He just allows others to run the country in his place.",
	"Once you go Norris, you are physically unable to go back.",
	"Ninjas want to grow up to be just like Chuck Norris. But usually they grow up just to be killed by Chuck Norris.",
	"Chuck Norris once sued Burger King after they refused to put razor wire in his Whopper Jr, insisting that that actually is &quot;his&quot; way.",
	"The last thing you hear before Chuck Norris gives you a roundhouse kick? No one knows because dead men tell no tales.",
	"Chuck Norris doesn't play god. Playing is for children.",
	"As a teen, Chuck Norris had sex with every nun in a convent tucked away in the hills of Tuscany. Nine months later the nuns gave birth to the 1972 Miami Dolphins, the only undefeated and untied team in professional football history.",
	"Chuck Norris is the only person in the world that can actually email a roundhouse kick.",
	"Chuck Norris won super bowls VII and VIII singlehandedly before unexpectedly retiring to pursue a career in ass-kicking.",
	"Wo hu cang long. The translation from Mandarin Chinese reads: &quot;Crouching Chuck, Hidden Norris&quot;",
	"Chuck Norris can set ants on fire with a magnifying glass. At night.",
	"Some kids play Kick the can. Chuck Norris played Kick the keg.",
	"'Icy-Hot' is too weak for Chuck Norris. After a workout, Chuck Norris rubs his muscles down with liquid-hot MAGMA.",
	"Chuck Norris cannot love, he can only not kill.",
	"When Chuck Norris was a baby, he didn't suck his mother's breast. His mother served him whiskey, straight out of the bottle.",
	"According to Einstein's theory of relativity, Chuck Norris can actually roundhouse kick you yesterday.",
	"Chuck Norris once pulled out a single hair from his beard and skewered three men through the heart with it.",
	"In an act of great philanthropy, Chuck made a generous donation to the American Cancer Society. He donated 6,000 dead bodies for scientific research.",
	"Chuck Norris’ favourite cut of meat is the roundhouse.",
	"WhWhen J. Robert Oppenheimer said &quot;I am become death, the destroyer Of worlds&quot;, He was not referring to the atomic bomb. He was referring to the Chuck Norris halloween costume he was wearing.",
	"Chuck Norris recently had the idea to sell his urine as a canned beverage. We know this beverage as Red Bull.",
	"In a recent survey it was discovered the 94% of American women lost their virginity to Chuck Norris. The other 6% were incredibly fat or ugly.",
	"Chuck Norris invented a language that incorporates karate and roundhouse kicks. So next time Chuck Norris is kicking your ass, don’t be offended or hurt, he may be just trying to tell you he likes your hat.",
	"If at first you don't succeed, you're not Chuck Norris.",
	"If Chuck Norris were a calendar, every month would be named Chucktober, and every day he'd kick your ass.",
	"Fear is not the only emotion Chuck Norris can smell. He can also detect hope, as in &quot;I hope I don't get a roundhouse kick from Chuck Norris.&quot;",
	"Chuck Norris's show is called Walker: Texas Ranger, because Chuck Norris doesn't run.",
	"MacGyver can build an airplane out of gum and paper clips, but Chuck Norris can roundhouse-kick his head through a wall and take it.",
	"Behind every successful man, there is a woman. Behind every dead man, there is Chuck Norris.",
	"What’s known as the UFC, or Ultimate Fighting Championship, doesn’t use its full name, which happens to be “Ultimate Fighting Championship, Non-Chuck-Norris-Division”.",
	"Chuck Norris brushes his teeth with a mixture of iron shavings, industrial paint remover, and wood-grain alcohol.",
	"The easiest way to determine Chuck Norris' age is to cut him in half and count the rings.",
	"There is endless debate about the existence of the human soul. Well it does exist, and Chuck Norris finds it delicious.",
	"Most boots are made for walkin'. Chuck Norris' boots ain't that merciful.",
	"The US did not boycott the 1980 Summer Olympics in Moscow due to political reasons: Chuck Norris killed the entire US team with a single round-house kick during TaeKwonDo practice.",
	"Chuck Norris wears a live rattlesnake as a condom.",
	"The Bible was originally titled &quot;Chuck Norris and Friends&quot;",
	"Chuck Norris began selling the Total Gym as an ill-fated attempt to make his day-to-day opponents less laughably pathetic.",
	"Do you know why Baskin Robbins only has 31 flavors? Because Chuck Norris doesn't like Fudge Ripple.",
	"When Chuck Norris says &quot;More cowbell&quot;, he MEANS it. ",
	"On the set of Walker Texas Ranger Chuck Norris brought a dying lamb back to life by nuzzling it with his beard. As the onlookers gathered, the lamb sprang to life. Chuck Norris then roundhouse kicked it, killing it instantly. This was just to prove that the good Chuck giveth, and the good Chuck, he taketh away.",
	"Chuck Norris was what Willis was talkin' about.",
	"Google won't search for Chuck Norris because it knows you don't find Chuck Norris, he finds you.",
	"Chuck Norris can lead a horse to water AND make it drink.",
	"Nagasaki never had a bomb dropped on it. Chuck Norris jumped out of a plane and punched the ground.",
	"It is scientifically impossible for Chuck Norris to have had a mortal father. The most popular theory is that he went back in time and fathered himself.",
	"Chuck Norris destroyed the periodic table, because Chuck Norris only recognizes the element of surprise.",
	"It is believed dinosaurs are extinct due to a giant meteor. That's true if you want to call Chuck Norris a giant meteor.",
	"Chuck Norris shot the sheriff, but he round house kicked the deputy.",
	"That's not Chuck Norris doing push-ups -- that's Chuck Norris moving the Earth away from the path of a deadly asteroid.",
	"Chuck Norris can judge a book by its cover.",
	"Nothing can escape the gravity of a black hole, except for Chuck Norris. Chuck Norris eats black holes. They taste like chicken.",
	"Chuck Norris does not play the lottery. It doesn't have nearly enough balls.",
	"Q: How many Chuck Norris' does it take to change a light bulb? A: None, Chuck Norris prefers to kill in the dark.",
	"As President Roosevelt said: &quot;We have nothing to fear but fear itself. And Chuck Norris.&quot;",
	"Chuck Norris just says &quot;no&quot; to drugs. If he said &quot;yes&quot;, it would collapse Colombia's infrastructure.",
	"Since 1940, the year Chuck Norris was born, roundhouse-kick related deaths have increased 13,000 percent.",
	"Crime does not pay - unless you are an undertaker following Walker, Texas Ranger, on a routine patrol.",
	"Chuck Norris invented the internet… just so he had a place to store his porn.",
	"Chuck Norris does not own a house. He walks into random houses and people move.",
	"It is better to give than to receive. This is especially true of a Chuck Norris roundhouse kick.",
	"Chuck Norris is the only person to ever win a staring contest against Ray Charles and Stevie Wonder at the same time.",
	"Industrial logging isn't the cause of deforestation. Chuck Norris needs toothpicks.",
	"Chuck Norris smells what the Rock is cooking... because the Rock is Chuck Norris' personal chef.",
	"When Chuck Norris plays Oregon Trail, his family does not die from cholera or dysentery, but rather, roundhouse kicks to the face. He also requires no wagon, since he carries the oxen, axels, and buffalo meat on his back. He always makes it to Oregon before you.",
	"Chuck Norris is the reason why Waldo is hiding.",
	"&quot;Brokeback Mountain&quot; is not just a movie. It's also what Chuck Norris calls the pile of dead ninjas in his front yard.",
	"When God said, &quot;let there be light&quot;, Chuck Norris said, &quot;say 'please'.&quot;",
	"Chuck Norris does not eat. Food understands that the only safe haven from Chuck Norris' fists is inside his own body.",
	"One day Chuck Norris walked down the street with a massive erection. There were no survivors.",
	"Chuck Norris built a time machine and went back in time to stop the JFK assassination. As Oswald shot, Chuck met all three bullets with his beard, deflecting them. JFK's head exploded out of sheer amazement.",
	"Chuck Norris doesn't read books. He stares them down until he gets the information he wants.",
	"Chuck Norris uses a night light. Not because Chuck Norris is afraid of the dark, but the dark is afraid of Chuck Norris.",
	"Chuck Norris is not capable of hitting a target on the broad side of a barn. Every time he tries, the whole damn barn falls down.",
	"Before each filming of Walker: Texas Ranger, Chuck Norris is injected with fourteen times the lethal dose of elephant tranquilzer. This is, of course, to limit his strength and mobility, in an attempt to lower the fatality rate of the actors he fights.",
	"When Bruce Banner gets mad, he turns into the Hulk. When the Hulk gets mad, he turns into Chuck Norris.",
	"Chuck Norris kills anyone that asks, &quot;You want fries with that&quot; because by now everyone should know that Chuck doesn't ever want fries with anything. Ever.",
	"Chuck Norris once kicked a horse in the chin. Its decendants are known today as Giraffes.",
	"Sticks and stones may break your bones, but a Chuck Norris glare will liquefy your kidneys.",
	"Human cloning is outlawed because if Chuck Norris were cloned, then it would be possible for a Chuck Norris roundhouse kick to meet another chuck Norris roundhouse kick. Physicists theorize that this contact would end the universe.",
	"Chuck Norris once went skydiving, but promised never to do it again. One Grand Canyon is enough.",
	"Chuck Norris's version of a &quot;chocolate milkshake&quot; is a raw porterhouse 	wrapped around ten Hershey bars, and doused in diesel fuel.",
	"If Chuck Norris round-house kicks you, you will die. If Chuck Norris' 	misses you with the round-house kick, the wind behind the kick will tear out 	your pancreas.",
	"In a fight between Batman and Darth Vader, the winner would be Chuck 	Norris.",
	"Chuck Norris puts his pants on one leg at a time, just like the rest of us. The only difference is, then he kills people. ",
	"Everybody loves Raymond. Except Chuck Norris.",
	"Contrary to popular belief, the Titanic didn't hit an iceberg. The ship was off course and accidentally ran into Chuck Norris while he was doing the backstroke across the Atlantic.",
	"Chuck Norris got his drivers license at the age of 16. Seconds.",
	"The original title for Alien vs. Predator was Alien and Predator vs Chuck Norris. The film was cancelled shortly after going into preproduction. No one would pay nine dollars to see a movie fourteen seconds long.",
	"Chuck Norris’ sperm is so badass, he had sex with Nicole Kidman, and 7 months later she prematurely gave birth to a Ford Excursion.",
	"Chuck Norris can win at solitaire with only 18 cards.",
	"Chuck Norris once shat blood - the blood of 11,940 natives he had killed and eaten.",
	"Maslow's theory of higher needs does not apply to Chuck Norris. He only has two needs: killing people and finding people to kill.",
	"The truth will set you free. Unless Chuck Norris has you, in which case, forget it buddy!",
	"For most people, home is where the heart is. For Chuck Norris, home is where he stores his collection of human skulls.",
	"Kryptonite has been found to contain trace elements of Chuck Norris roundhouse kicks to the face. This is why it is so deadly to Superman.",
	"Saddam Hussein was not found hiding in a &quot;hole.&quot; Saddam was roundhouse-kicked in the head by Chuck Norris in Kansas, which sent him through the earth, stopping just short of the surface of Iraq.",
	"Coroners refer to dead people as &quot;ABC's&quot;. Already Been Chucked.",
	"Chuck Norris doesn't look both ways before he crosses the street... he just roundhouses any cars that get too close.",
	"Chuck Norris does not have to answer the phone. His beard picks up the incoming electrical impulses and translates them into audible sound.",
	"How many roundhouse kicks does it take to get to the center of a tootsie pop? Just one. From Chuck Norris.",
	"Chuck Norris doesnt wear a watch, HE decides what time it is.",
	"The phrase 'break a leg' was originally coined by Chuck Norris's co-stars in Walker, Texas Ranger as a good luck charm, indicating that a broken leg might be the worst extent of their injuries. This never proved to be the case.",
	"When chuck Norris does division, there are no remainders.",
	"If you rearrange the letters in &quot;Chuck Norris&quot;, they also spell &quot;Crush Rock In&quot;. The words &quot;with his fists&quot; are understood.",
	"Never look a gift Chuck Norris in the mouth, because he will bite your damn eyes off.",
	"Give a man a fish, and you will feed him for a day. Give a man anything that is better than a fish, and Chuck Norris will beat his ass and take it.",
	"Chuck Norris used to play baseball. When Babe Ruth was hailed as the better player, Chuck Norris killed him with a baseball bat to the throat. Lou Gehrig got off easy.",
	"The original title for Star Wars was &quot;Skywalker: Texas Ranger&quot;. Starring Chuck Norris.",
	"Guantuanamo Bay, Cuba, is the military code-word for &quot;Chuck Norris' basement&quot;.",
	"The phrase 'balls to the wall' was originally conceived to describe Chuck Norris entering any building smaller than an aircraft hangar.",
	"Chuck Norris’ roundhouse kick is so powerful, it can be seen from outer space by the naked eye.",
	"Ozzy Osbourne bites the heads off of bats. Chuck Norris bites the heads off of Siberian Tigers.",
	"He who lives by the sword, dies by the sword. He who lives by Chuck Norris, dies by the roundhouse kick.",
	"The best-laid plans of mice and men often go awry. Even the worst-laid plans of Chuck Norris come off without a hitch.",
	"The phrase 'dead ringer' refers to someone who sits behind Chuck Norris in a movie theater and forgets to turn their cell phone off.",
	"Chuck Norris' Roundhouse kick is so powerful, that on the set of Sidekicks he single-footedly destroyed Jonathan Brandis' Career.",
	"Staring at Chuck Norris for extended periods of time without proper eye protection will cause blindess, and possibly foot sized brusies on the face.",
	"Chuck Norris can taste lies.",
	"Chuck Norris does not kick ass and take names. In fact, Chuck Norris kicks ass and assigns the corpse a number. It is currently recorded to be in the billions.",
	"One time, Chuck Norris accidentally stubbed his toe. It destroyed the entire state of Ohio.",
	"Little Miss Muffet sat on her tuffet, until Chuck Norris roundhouse kicked her into a glacier.",
	"In 1990, Chuck Norris founded the non-profit organization &quot;Kick Drugs Out of America&quot;. If the organization's name were &quot;Roundhouse Kick Drugs out of America&quot;, there wouldn't be any drugs in the Western Hemisphere. Anywhere.",
	"Chuck Norris can blow bubbles with beef jerky.",
	"They had to edit the first ending of 'Lone Wolf McQuade' after Chuck Norris kicked David Carradine's ass, then proceeded to barbecue and eat him.",
	"Chuck Norris does, in fact, live in a round house.",
	"Chuck Norris was once on Jeopardy. This show is notable in that it was the first occasion in Jeopardy history that Alex Trebek had appeared without a mustache. And a head.",
	"When Chuck Norris works out on the Total Gym, the Total Gym feels like it's been raped.",
	"4 out of 5 doctors fail to recommend Chuck Norris as a solution to most problems. Also, 80% of doctors die unexplained, needlessly brutal deaths.",
	"Chuck Norris can skeletize a cow in two minutes.",
	"The only sure things are Death and Taxes…and when Chuck Norris goes to work for the IRS, they'll be the same thing.",
	"Chuck Norris' first job was as a paperboy. There were no survivors.",
	"With the rising cost of gasoline, Chuck Norris is beginning to worry about his drinking habit.",
	"The square root of Chuck Norris is pain. Do not try to square Chuck Norris, the result is death.",
	"chuck Norris' testicles do not produce sperm. They produce tiny white ninjas that recognize only one mission: seek and destroy.",
	"To be or not to be? That is the question. The answer? Chuck Norris.",
	"Chuck Norris has never been in a fight, ever. Do you call one roundhouse kick to the face a fight?",
	"There are two types of people in the world... people that suck, and Chuck Norris.",
	"Chuck Norris never wet his bed as a child. The bed wet itself out of fear.",
	"If you were somehow able to land a punch on Chuck Norris your entire arm would shatter upon impact. This is only in theory, since, come on, who in their right mind would try this?",
	"70% of a human's weight is water. 70% of Chuck Norris' weight is his dick.",
	"Jean-Claude Van Damme once kicked Chuck Norris' ass. He was then awakened from his dream by a roundhouse kick to the face.",
	"The pie scene in &quot;American Pie&quot; is based on a dare Chuck Norris took when he was younger. However, in Chuck Norris' case, the &quot;pie&quot; was the molten crater of an active volcano.",
	"Chuck Norris uses 8'x10' sheets of plywood as toilet paper.",
	"Noah was the only man notified before Chuck Norris relieved himself in the Atlantic Ocean.",
	"Chuck Norris once invited all of the other badasses from TV to duke it out in order to see who was the supreme badass. Only two showed up-- Jack Bauer and MacGyver.",
	"MacGyver immediately tried to make a bomb out of some Q-Tips and Gatorade, but Chuck Norris roundhouse-kicked him in the solar plexus. MacGyver promptly threw up his own heart.",
	"Jack Bauer tried to use his detailed knowledge of torture techniques, but to no avail: Chuck Norris thrives on pain. Chuck Norris then ripped off Jack Bauer's arm and beat him to death with it. Game, set, match.",
	"Chuck Norris eats steak for every single meal. Most times he forgets to kill the cow.",
	"The First Law of Thermodynamics states that energy can neither be created nor destroyed... unless it meets Chuck Norris.",
	"Chuck Norris doesn't go on the internet, he has every internet site stored in his memory. He refreshes webpages by blinking.",
	"Fact: Chuck Norris doesn't consider it sex if the woman survives.",
	"It is said that looking into Chuck Norris' eyes will reveal your future. Unfortunately, everybody's future is always the same: death by a roundhouse-kick to the face.",
	"Chuck Norris knows everything there is to know - Except for the definition of mercy.",
	"Scientifically speaking, it is impossible to charge Chuck Norris with &quot;obstruction of justice.&quot; This is because even Chuck Norris cannot be in two places at the same time.",
	"Chuck Norris never has to wax his skis because they're always slick with blood.",
	"When you say &quot;no one's perfect&quot;, Chuck Norris takes this as a personal insult.",
	"Chuck Norris can win a game of Trivial Pursuit with one roll of the dice, and without answering a single question... just a nod of the head, and a stroke of the beard.",
	"182,000 Americans die from Chuck Norris-related accidents every year.",
	"Paper beats rock, rock beats scissors, and scissors beats paper, but Chuck Norris beats all 3 at the same time.",
	"Jesus can walk on water, but Chuck Norris can walk on Jesus.",
	"All roads lead to Chuck Norris. And by the transitive property, a roundhouse kick to the face.",
	"If you're driving down the road and you think Chuck Norris just cut you off, you better thank your lucky stars it wasn't the other way around.",
	"July 4th is Independence day. And the day Chuck Norris was born. Coincidence? I think not.",
	"Chuck Norris never goes to the dentist because his teeth are unbreakable. His enemies never go to the dentist because they have no teeth.",
	"In the medical community, death is referred to as &quot;Chuck Norris Disease&quot;",
	"Chuck Norris was once in a knife fight, and the knife lost.",
	"If you work in an office with Chuck Norris, don't ask him for his three-hole-punch.",
	"In the Words of Julius Caesar, &quot;Veni, Vidi, Vici, Chuck Norris&quot;. Translation: I came, I saw, and I was roundhouse-kicked inthe face by Chuck Norris.",
	"The First rule of Chuck Norris is: you do not talk about Chuck Norris.",
	"Chuck Norris is widely predicted to be first black president. If you're thinking to yourself, &quot;But Chuck Norris isn't black&quot;, then you are dead wrong. And stop being a racist.",
	"When Chuck Norris plays Monopoly, it affects the actual world economy.",
	"Chuck Norris can be unlocked on the hardest level of Tekken. But only Chuck Norris is skilled enough to unlock himself. Then he roundhouse kicks the Playstation back to Japan.",
	"Chuck Norris drinks napalm to quell his heartburn.",
	"Every time someone uses the word &quot;intense&quot;, Chuck Norris always replies &quot;you know what else is intense?&quot; followed by a roundhouse kick to the face.",
	"As an infant, Chuck Norris' parents gave him a toy hammer. He gave the world Stonehenge.",
	"Chuck Norris once ordered a steak in a restaurant. The steak did what it was told.",
	"Most people fear the Reaper. Chuck Norris considers him &quot;a promising Rookie&quot;.",
	"There are only two things that can cut diamonds: other diamonds, and Chuck Norris.",
	"President Roosevelt once rode his horse 100 miles. Chuck Norris carried his the same distance in half the time.",
	"Chuck Norris once ate four 30lb bowling balls without chewing.",
	"What many people dont know is chuck norris is the founder of planned parenthood. Not even unborn children can escape his wrath.",
	"Chuck Norris was banned from competitive bullriding after a 1992 exhibition in San Antonio, when he rode the bull 1,346 miles from Texas to Milwaukee Wisconsin to pick up his dry cleaning.",
	"Chuck Norris qualified with a top speed of 324 mph at the Daytona 500, without a car.",
	"Chuck Norris likes his coffee half and half: half coffee grounds, half wood-grain alcohol.",
	"Chuck Norris uses tabasco sauce instead of visine.",
	"The chemical formula for the highly toxic cyanide ion is CN-. These are also Chuck Norris' initials. This is not a coincidence.",
	"Chuck Norris' credit cards have no limit. Last weekend, he maxed them out.",
	"Think of a hot woman. Chuck Norris did her.",
	"A man once claimed Chuck Norris kicked his ass twice, but it was promptly dismissed as false - no one could survive it the first time.",
	"Chuck Norris sleeps with a pillow under his gun.",
	"Chuck Norris owns a chain of fast-food restaurants throughout the southwest. They serve nothing but barbecue-flavored ice cream and Hot Pockets.",
	"Chuck Norris doesn't chew gum. Chuck Norris chews tin foil.",
	"Aliens DO indeed exist. They just know better than to visit a planet that Chuck Norris is on.",
	"When in a bar, you can order a drink called a &quot;Chuck Norris&quot;. It is also known as a &quot;Bloody Mary&quot;, if your name happens to be Mary.",
	"Every time Chuck Norris smiles, someone dies. Unless he smiles while he’s roundhouse kicking someone in the face. Then two people die.",
	"Some people ask for a Kleenex when they sneeze, Chuck Norris asks for a body bag.",
	"There’s an order to the universe: space, time, Chuck Norris.... Just kidding, Chuck Norris is first.",
	"A man once asked Chuck Norris if his real name is &quot;Charles&quot;. Chuck Norris did not respond, he simply stared at him until he exploded.",
	"Chuck Norris starts everyday with a protein shake made from Carnation Instant Breakfast, one dozen eggs, pure Colombian cocaine, and rattlesnake venom. He injects it directly into his neck with a syringe.",
	"In a tagteam match, Chuck Norris was teamed with Hulk Hogan against King Kong Bundy and Andre The Giant. He pinned all 3 at the same time.",
	"Chuck Norris doesn't see dead people. He makes people dead.",
	"Chuck Norris is the only person who can simultaneously hold and fire FIVE Uzis: One in each hand, one in each foot -- and the 5th one he roundhouse-kicks into the air, so that it sprays bullets.",
	"For undercover police work, Chuck Norris pins his badge underneath his shirt, directly into his chest.",
	"In the X-Men movies, none of the X-Men super-powers are done with special effects. Chuck Norris is the stuntman for every character.",
	"We live in an expanding universe. All of it is trying to get away from Chuck Norris.",   "It is said that every time you masturbate, God kills a kitten. Every time God masturbates, Chuck Norris kills a lion.",
	"The word 'Kill' was invented by Chuck Norris. Other words were 'Die', 'Beer', and 'What'.",
	"Chuck Norris is a vegetarian. Meaning, he does not eat animals until first he puts them into vegetative state with his fists.",
	"The 11th commandment is “Thou shalt not piss off Chuck Norris” This commandment is rarely enforced, as it is impossible to accomplish.",
	"Chuck Norris is his own line at the DMV.",
	"Two wrongs don't make a right. Unless you're Chuck Norris. Then two wrongs make a roundhouse kick to the face.",
	"Who let the dogs out? Chuck Norris let the dogs out... and then roundhouse kicked them through an Oldsmobile.",
	"Chuck Norris can do a roundhouse kick faster than the speed of light. This means that if you turn on a light switch, you will be dead before the lightbulb turns on.",
	"When Chuck Norris goes to out to eat, he orders a whole chicken, but he only eats its soul.",
	"Chuck Norris sold his soul to the devil for his rugged good looks and unparalleled martial arts ability. Shortly after the transaction was finalized, Chuck roundhouse-kicked the devil in the face and took his soul back. The devil, who appreciates irony, couldn't stay mad and admitted he should have seen it coming. They now play poker every second Wednesday of the month.",
	"Chuck Norris has never won an Academy Award for acting... because he's not acting.",
	"If Chuck Norris wants your opinion, he'll beat it into you.",
	"Not everyone that Chuck Norris is mad at gets killed. Some get away. They are called astronauts.",
	"Chuck Norris has to register every part of his body as a separate lethal weapon. His spleen is considered a concealed weapon in over 50 states.",
	"A movie scene depicting Chuck Norris losing a fight with Bruce Lee was the product of history's most expensive visual effect. When adjusted for inflation, the effect cost more than the Gross National Product of Paraguay.",
	"Godzilla is a Japanese rendition of Chuck Norris' first visit to Tokyo.",
	"They once made a Chuck Norris toilet paper, but there was a problem-- It wouldn't take shit from anybody.",
	"Chuck Norris once rode a nine foot grizzly bear through an automatic car wash, instead of taking a shower.",
	"&quot;Sweating bullets&quot; is literally what happens when Chuck Norris gets too hot.",
	"Chuck Norris' sperm can be seen with the naked eye. Each one is the size of a quarter.",
	"After taking a steroids test doctors informed Chuck Norris that he had tested positive. He laughed upon receiving this information, and said &quot;of course my urine tested positive, what do you think they make steroids from?&quot;",
	"Chuck Norris doesn't daydream. He's too busy giving other people nightmares.",
	"When Arnold says the line &quot;I'll be back&quot; in the first Terminator movie it is implied that is he going to ask Chuck Norris for help.",
	"There are no such things as tornados. Chuck Norris just hates trailer parks.",
	"Chuck Norris' Penis is a third degree blackbelt, and an honorable 32nd-degree mason.",
	"Chuck Norris does not follow fashion trends, they follow him. But then he turns around and kicks their ass. Nobody follows Chuck Norris.",
	"The phrase 'break a leg' was originally coined by Chuck Norris's co-stars in Walker, Texas Ranger as a good luck charm indicating that a broken leg might be the worst extent of their injuries. This never proved to be the case.",
	"Chuck Norris’ roundhouse kick is so powerful, it can be seen from outer space by the naked eye.",
	"Diamonds are not, despite popular belief, carbon. They are, in fact, Chuck Norris fecal matter. This was proven a recently, when scientific analysis revealed what appeared to be Jean-Claude Van Damme bone fragments inside the Hope Diamond.",
	"Chuck Norris once participated in the running of the bulls. He walked.",
	"The Drummer for Def Leppard's only got one arm. Chuck Norris needed a back scratcher.",
	"Chuck Norris was the orginal sculptor of Mount Rushmore. He completed the entire project using only a bottle opener and a drywall trowel.",
	"Chuck Norris once rode a bull, and nine months later it had a calf.",
	"Chuck Norris once lost the remote, but maintained control of the TV by yelling at it in between bites of his &quot;Filet of Child&quot; sandwich.",
	"For Spring Break '05, Chuck Norris drove to Madagascar, riding a chariot pulled by two electric eels.",
	"The Manhattan Project was not intended to create nuclear weapons, it was meant to recreate the destructive power in a Chuck Norris Roundhouse Kick. They didn't even come close.",
	"Chuck Norris has banned rainbows from the state of North Dakota.",
	"Divide Chuck Norris by zero and you will in fact get one........one bad-ass that is. ",
	"TNT was originally developed by Chuck Norris to cure indigestion.",
	"After returning from World War 2 unscathed, Bob Dole was congratulated by Chuck Norris with a handshake. The rest is history.",
	"Chuck Norris runs on batteries. Specifically, Die Hards.",
	"&quot;Let the Bodies Hit the Floor&quot; was originally written as Chuck Norris' theme song.",
	"Chuck Norris will never have a heart attack. His heart isn't nearly foolish enough to attack him.",
	"Only Chuck Norris can prevent forest fires.",
	"When Chuck Norris makes a burrito, its main ingredient is real toes.",
	"Chuck Norris is not Irish. His hair is soaked in the blood of his victims.",
	"In the movie &quot;The Matrix&quot;, Chuck Norris is the Matrix. If you pay close attention in the green &quot;falling code&quot; scenes, you can make out the faint texture of his beard.",
	"Chuck Norris' dick is so big, it has it's own dick, and that dick is still bigger than yours.",
	"They say curiosity killed the cat. This is false. Chuck Norris killed the cat. Every single one of them.",
	"There is no such thing as a lesbian, just a woman who has never met Chuck Norris.",
	"Chuck Norris crossed the road. No one has ever dared question his motives.",
	"When Chuck Norris was born, he immediately had sex with the first nurse he saw. He was her first. She was his third. That afternoon.",
	"One time, at band camp, Chuck Norris ate a percussionist.",
	"Chuck Norris doesn't say &quot;who's your daddy&quot;, because he knows the answer.",
	"Chuck Norris originally wrote the first dictionary. The definition for each word is as follows - A swift roundhouse kick to the face.",
	"Love does not hurt. Chuck Norris does.",
	"The term &quot;Cleveland Steamer&quot; got its name from Chuck Norris, when he took a dump while visiting the Rock and Roll Hall of fame and buried northern Ohio under a glacier of fecal matter.",
	"Chuck Norris once round-house kicked a salesman. Over the phone.",
	"The pen is mighter than the sword, but only if the pen is held by Chuck Norris.",
	"Chuck Norris doesn't kill two birds with one stone. Chuck Norris kills all birds, with two stones. The ones in his pants.",
	"Chuck Norris knows the last digit of pi.",
	"Those aren't credits that roll after Walker Texas Ranger. It is actually a list of fatalities that occurred during the making of the episode.",
	"The air around Chuck Norris is always a balmy 78 degrees.",
	"When Chuck Norris wants an egg, he cracks open a chicken.",
	"Chuck Norris plays racquetball with a waffle iron and a bowling ball.",
	"According to the Bible, God created the universe in six days. Before that, Chuck Norris created God by snapping his fingers.",
	"Chuck Norris doesn't believe in ravioli. He stuffs a live turtle with beef and smothers it in pig's blood.",
	"Count from one to ten. That's how long it would take Chuck Norris to kill you...Fourty seven times.",
	"The 1972 Miami Dolphins lost one game, it was an exhibition game vs. Chuck Norris and three seven year old girls. Chuck Norris won with a roundhouse-kick to the face in overtime.",
	"Chuck Norris is not Politically Correct. He is just Correct. Always.",
	"Mr. T pities the fool. Chuck Norris rips the fool's head off. ",
	"Chuck Norris had to stop washing his clothes in the ocean. The tsunamis were killing people.",
	"Chuck Norris has volunteered to remain on earth after the Rapture; he will spend his time fighting the Anti-Christ.",
	"They were going to release a Chuck Norris edition of Clue, but the answer always turns out to be &quot;Chuck Norris. In The Library. With a Roundhouse Kick.&quot;",
	"Chuck Norris is the only known mammal in history to have an opposable thumb. On his penis.",
	"A man once taunted Chuck Norris with a bag of Lay's potato chips, saying &quot;Betcha can't eat just one!&quot; Chuck Norris proceeded to eat the chips, the bag, and the man in one deft move.",
	"Chuck Norris' favorite cereal is Kellogg's Nails 'N' Gravel.",
	"In the first Jurassic Park movie, the Tyrannosaurus Rex wasn't chasing the jeep. Chuck Norris was chasing the Tyrannosaurus AND the jeep.",
	"Chuck Norris has never been accused of murder for the simple fact that his roundhouse kicks are recognized world-wide as &quot;acts of God.&quot;",
	"&quot;Brokeback Mountain&quot; is not just a movie. It's also what Chuck Norris calls the pile of dead ninjas in his front yard.",
	"Chuck Norris does not wear a condom. Because there is no such thing as protection from Chuck Norris.",
	"Chuck Norris once had sex with a cigarette machine in the Osaka airport.",
	"Rules of fighting: 1) Don't bring a knife to a gun fight. 2) Don't bring a gun to a Chuck Norris fight.",
	"Chuck Norris is the only man who has, literally, beaten the odds. With his fists.",
	"In ancient China there is a legend that one day a child will be born from a dragon, grow to be a man, and vanquish evil from the land. That man is not Chuck Norris, because Chuck Norris killed that man.",
	"Chuck Norris wipes his ass with chain mail and sandpaper.",
	"When you play Monopoly with Chuck Norris, you do not pass go, and you do not collect two hundred dollars. You will be lucky if you make it out alive.",
	"Chuck Norris describes human beings as &quot;a sociable holder for blood and guts&quot;.",
	"Chuck Norris once got into a fight with a one-armed Ninja. Seeing that he had an unfair advantage, Chuck Norris ripped both of his arms off and one of his legs. He then roundhouse-kicked the ninja in the head, killing him instantly, and proceeded to sow his limbs back on using only a rusty tent spike and bailing wire.",
	"Chuck Norris likes his ice like he likes his skulls: crushed.",
	"Chuck Norris can kick through all 6 degrees of separation, hitting anyone, anywhere, in the face, at any time.",
	"Most tough men eat nails for breakfast. chuck Norris does all of his grocery shopping at Home Depot.",
	"Chuck Norris did not &quot;lose&quot; his virginity, he stalked it and then destroyed it with extreme prejudice.",
	"Everything King Midas touches turnes to gold. Everything Chuck Norris touches turns up dead.",
	"Chuck Norris' pulse is measured on the richter scale.",
	"Most people know that Descarte said, &quot;I think, therefore I am.&quot; What most people don't know is that that quote continues, &quot;...afraid of Chuck Norris.&quot;",
	"Chuck Norris once roundhouse-kicked a ten dollar bill into 200 nickels.",
	"For every movie about Vietnam starring Chuck Norris, the historical duration of the war decreases. Just 3 more &quot;Missing in Action&quot; sequels, and that war will have never actually existed.",
	"Chuck Norris' penis has a Hemi.",
	"Chuck Norris enjoys a good practical joke. His favorite is where he removes your lower intestine and pretends to make a balloon animal out of it. Then he cracks your skull open with a Volvo for not complimenting him on his balloon animal.",
	"Chuck Norris CAN in fact 'raise the roof'. And he can do it with one hand.",
	"Kenny G is allowed to live because Chuck Norris doesn't kill women.",
	"Life is not, in fact, like a box of chocolates. It is more like a box of Chuck Norris, roundhouse kicking you in the face. And if you receive a box of Chuck Norris, you ALWAYS know what you are going to get.",
	"For Chuck Norris, every street is &quot;one way&quot;. HIS WAY.",
	"There are now five cup sizes at Starbucks: Short, Tall, Grande, Venti, and Chuck Norris.",
	"During the Vietnam War, Chuck Norris allowed himself to be captured. For torture, they made him eat his own entrails. He asked for seconds.",
	"Chuck Norris once created a flamethrower by urinating into a lighter.",
	"Instead of having a cigarette after sex, Chuck Norris heads outside and brands his cattle.",
	"Chuck Norris actually built the stairway to heaven.",
	"Whoever said &quot;only the good die young&quot; was probably in Chuck Norris's kindergarten class.",
	"Chuck Norris once skewered a man with the Eiffel tower.",
	"The best part of waking up, is not Folgers in your cup, but knowing that Chuck Norris didn't kill you in your sleep.",
	"Chuck Norris doesn't own a can opener, he just chews through the can.",
	"Occam's Razor says that the simplest answer tends to be the correct one. Norris' Razor involves a flick of the wrist and a Columbian Necktie.",
	"Chuck Norris needs a monkeywrench and a blowtorch to masturbate.",
	"Proponents of higher-order theories of consciousness argue that consciousness is explained by the relation between two levels of mental states in which a higher-order mental state takes another mental state. If you mention this to Chuck Norris, expect an explosive roundhouse kick to the face for spouting too much fancy-talk.",
	"Chuck Norris invented all 32 letters of the alphabet.",
	"Remember The Ultimate Warrior? He quit wrestling because Chuck Norris wanted his nickname back.",
	"If a tree falls in the forest, does anybody hear? Yes. Chuck Norris hears it. Chuck Norris can hear everything. Chuck Norris can hear the shrieking terror in your soul.",
	"Chuck Norris actually owns IBM. It was an extremely hostile takeover.",
	"He, who laughs last, laughs best. He who laughs at Chuck Norris … dies.",
	"Chuck Norris is like a dog, not only because he can smell fear, but because he can piss on whatever he wants. ",
	"Chuck Norris can jump-start a car using jumper cables attached to his nipples.",
	"Chuck Norris neither melts in your mouth nor in your hand. He shreds your trachea before ravaging your soul with a combination of chocolate, whickey, roundhouse kicks and death. Oh, and pain. Lots of pain.",
	"Chuck Norris doesn't have blood. He is filled with magma.",
	"Chuck Norris uses Tabasco Sauce for eye drops.",
	"Chuck Norris can get Blackjack with just one card.",
	"&quot;One time I was with Norris in the back of a pickup truck, along with a live deer. Norris goes up to the deer and says, 'I'm Chuck Norris! SAY IT!' Then he manipulates the deer's lips in such a way as to make it say, 'ChuckNorris' ... It wasn't exactly like it, but it was pretty good for a deer!'&quot;",
	"People created the automobile to escape from Chuck Norris...Not to be outdone, Chuck Norris created the automobile accident.",
	"Chuck Norris roundhouse kicks people in the face first and asks questions later.",
	"When Chuck Norris was born, the only person who cried was the doctor. Never slap Chuck Norris.",
	"Chuck Norris can sneeze with his&nbsp;eyes open.",
	"Archeologists in India recently uncovered a new dinosaur. It’s actually many dinosaurs but one is in the middle of all the others. The one in the middle is believed to have killed the others with a single roundhouse kick to the face. The archeologists wanted to call it ChuckNorrisaurs but the Indian government changed the name to Himotosaurous because it’s simply not possible for Mr. Norris to be killed.",
	"Chuck Norris got a perfect score on his SAT's, simply by writing Chuck Norris for every answer.",
	"Chuck Norris has to use a stunt double when he does crying scenes.",
	"Chuck Norris successfully seperated twins conjoined at the head by roundkicking them in the face.",
	"Dinosaurs went extinct because of the Chuck Norrisaurus.",
	"People have often asked the United States, What is your secret weapon against terrorists? We simply reply...Chuck Norris",
	"Chuck Norris wears Orion's Belt around his pinky toe and he eats with the Big Dipper. ",
	"Chuck Norris eats lightning and farts thunder.",
	"Lightning never strikes twice in one place because Chuck Norris is looking for it.&nbsp;",
	"Chuck Norris was once a knight in King Arthur's court.&nbsp; He was known as Sir Beatdown.",
	"Chuck Norris once played rugby by himself.&nbsp; He went undefeated.",
	"In Desert Storm the reason why the Iraqi army surrendered so quickly because they knew Chuck Norris was coming.&nbsp;",
	"Chuck Norris has never looked a baby in the eyes cause it might him cry but if he does it also makes him want to punch a baby.",
	"Chuck norris doesnt go at the speed of light, he goes at the speed of Norris",
	"Chuck Norris does not know about this website. If he did he would have just deleted the internet.",
	"Before sliced bread, people used to say &quot;Thats the greatest thing since Chuck Norris&quot;. But Chuck Norris was displeased by this. So he roundhouse kicked a loaf of bread into slices.",
	"Chuck Norris's sweat has burned holes in concrete.",
	"The wind of Chuck Norris’s round house kick can be felt from 1600 million miles away",
	"Chuck Norris has held the World Championship in every weight class at the same time.",
	"There is no Control button on Chuck Norris' computer. Chuck Norris is always in control.",
	"Chuck Norris is so bad he makes viruses sick. As such, Chuck Norris is also responsible for the eradication of smallpox.",
	"There are four legal methods of execution in the United States: lethal injection, gas chamber, electric chair and Chuck Norris.",
	"Earth's emergency defence plan in case of alien invasion is Chuck Norris.",
	"Chuck Norris stared evil in the face, and it backed down",
	"Chuck Norris can split the atom. With his bare hands.",
	"On the SAT if you put Chuck Norris for every answer you will score over 8000",
	"The United States could save billions in defense funding if they trade the Military for Chuck Norris",
	"When Chuck Norris spits out watermelon seeds, he puts a machine gun to shame",
	"Chuck Norris doesnt use after shave, he uses liquid hot magma.",
	"When Chuck norris found this web-site while surfing the internt, he round house kicked his computer...10 new facts were added instantly...including this one",
	"You can lead a horse to water but cannot make him drink, unless you’re Chuck Norris",
	"No matter what your mother always said, Chuck Norris can tune a fish.",
	"Chuck&nbsp;Norris is&nbsp;'' The best a man can get ''",
	"On Valentine's Day, Chuck Norris gives his wife the still beating heart of one of his enemies. Being very romantic, Chuck Norris believes every day should be Valentine's Day.",
	"Scientists believe the world began with the &quot;Big Bang&quot;. Chuck Norris shrugs it off as a &quot;bad case of gas&quot;.",
	"Chuck Norris let the dogs out.",
	"Chuck Norris visits an active volcano every morning to get some of &quot;the best damn espresso on Earth&quot;.",
	"Chuck Norris eats eight meals a day. Seven are steak, and the last is the rest of the cow.",
	"Chuck Norris does know what&nbsp;Willis is talking about!",
	"Chuck Norris don't open no can of whoopass. He makes his own.",
	"Chuck Norris could shoot someone and still have time to roundhouse kick him in the face before the bullet hit.",
	"Chuck Norris's body temperature is 98.6 degrees... Celsius.",
	"The world's fastest car has 7 gears.&nbsp; 5, 6, and Chuck Norris.",
	"The active ingredient in Red Bull is Chuck Norris's sweat.",
	"The Seven Wonders of the ancient world were: Chuck Norris' left and right hands, his left and right feet, his belly button, his liver, and his beard.",
	"When Chuck Norris goes to Vegas, he doesn't have to gamble. The casinos just give him stacks of money.",
	"In an emergency, Chuck Norris can be used as a floatation device.",
	"When Chuck Norris is ready to wake up, he tells the sun to get above the horizon.",
	"The speed of light was instituted because Chuck Norris didn't want get winded outrunning it. Chuck Norris hates to sweat.",
	"Chuck Norris once bench-pressed the entire state of Ohio, and all of its residents.",
	"Chuck Norris can hold his breathe for nine years.",
	"When somebody yells &quot;Last one in is a rotten egg,&quot; Chuck Norris is never the rotten egg.",
	"Chuck Norris invented the question mark.",
	"Chuck Norris trick-or-treated as himself as a child.",
	"Chuck Norris has 3 knees on each leg.",
	"Chuck Norris likes long walks on the beach, Barry White music, Harlequin romance novels, songbirds, rainbows, and quiet time with his lady…just before he roundhouse kicks her in the face.",
	"Chuck Norris can cook minute rice in 30 seconds.",
	"If you gave Chuck Norris a typewriter and 0.000000000000000000001th of a second he can write the Complete Works of Shakespeare",
	"Chuck Norris puts the laughter in manslaughter.",
	"Chuck Norris' beard hair is believed to be an aphrodisiac in China.",
	"The helicopter was invented after Chuck Norris was observed doing 8 roundhouse kicks a second.",
	"Cars were invented to have a faster way of fleeing from Chuck Norris. Not to be outdone, Chuck Norris invented the car accident.",
	"Chuck Norris brushes his teeth with barbed wire.",
	"Chuck Norris can watch an episode of 60 minutes in 22 seconds.",
	"Chuck Norris make onions CRY!!!",
	"Some people say that Chuck Norris is a myth. Those &quot;some people&quot; are now dead.",
	"When Chuck Norris sneezes, he doesn't say &quot;Atchoo&quot; he says &quot;DIE EVERYONE!!!&quot;. That's what happens next.",
	"Chuck Norris eats a bowl of diamonds every morning.",
	"Chuck Norris is not only a noun, but a verb."); 

if (preg_match("/^chuck/i", $message)) {
	$sendto->reply(Util::rand_array_value($chuck));
} else {
	$syntax_error = true;
}

?>