CREATE TABLE IF NOT EXISTS tower_attack_<myname> (`time` int, `att_guild` VARCHAR(50), `att_side` VARCHAR(10), `att_player` VARCHAR(20), `att_level` int, `att_profession` VARCHAR(15), `def_guild` VARCHAR(50), `def_side` VARCHAR(10), `zone` VARCHAR(50), `x` INT, `y` INT);
CREATE TABLE IF NOT EXISTS tower_result_<myname> (`time` int, `win_guild` VARCHAR(50), `win_side` VARCHAR(10), `lose_guild` VARCHAR(50), `lose_side` VARCHAR(10));
DROP TABLE towerranges;
CREATE TABLE towerranges (`id` int(11), `low_level` int(10) default NULL, `high_level` int(10) default NULL, `playfield` varchar(250) default NULL, `hugemaploc` varchar(10) default NULL, `coordx` varchar(10) 	default NULL, `coordy` varchar(10) default NULL, `location` varchar(250) default NULL);
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (1, '10', '15', 'Clondyke', '7', '2500', '1220', 'Micron Slopes Notum Mine');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (2, '10', '15', 'Greater Omni Forest', '5', '1500', '1300', 'Greater Omni Forest South');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (3, '10', '15', 'Galway Shire', '1', '500', '1900', 'Blossom Valley');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (4, '10', '15', 'Galway Shire', '2', '380', '1300', 'Konty Passage Plains');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (5, '10', '15', 'Galway Shire', '5', '380', '580', 'Kontys Sixth Passage - West');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (6, '10', '15', 'Galway Shire', '6', '620', '540', 'Kontys Sixth Passage - East');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (7, '10', '15', 'Holes in the Wall', '4', '740', '820', 'Snake Mountain');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (8, '10', '15', 'Lush Fields', '7', '2860', '420', 'South East Lush Fields');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (9, '10', '15', 'Omni Forest', '4', '700', '2180', 'Rocky Upsurge');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (10, '10', '15', 'Tir County', '1', '460', '1300', 'Great W. Forest Vein');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (11, '10', '15', 'Tir County', '2', '2940', '980', 'The Hidden Notum Canal');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (12, '10', '15', 'Tir County', '4', '580', '580', 'Great W. Forest Dorsal');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (13, '10', '15', 'Tir County', '5', '1500', '460', 'Western Mountain Areas');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (14, '11', '16', 'Aegean', '2', '2180', '2580', 'West Wastelands');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (15, '11', '16', 'Aegean', '5', '1180', '1340', 'West of the Dead Forest');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (16, '10', '20', 'Athen Shire', '1', '2660', '2020', 'Sifter Beach');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (17, '10', '20', 'Athen Shire', '4', '2660', '820', 'Grindmoore');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (18, '10', '20', 'Holes in the Wall', '6', '380', '340', 'Transit Valley Ore');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (19, '10', '20', 'Omni Forest', '3', '460', '2180', 'Dungeon Hilltop');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (20, '12', '20', 'Holes in the Wall', '3', '220', '1060', 'Stret West Notum Ore');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (21, '12', '20', 'Newland', '1', '1220', '1060', 'In the Newland Desert');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (22, '12', '22', 'Holes in the Wall', '2', '660', '1500', 'Hound Land Mining');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (23, '15', '22', 'Aegean', '7', '1420', '1020', 'Canyon East');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (24, '15', '23', 'Athen Shire', '5', '1380', '380', 'Gladius Grove');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (25, '10', '25', 'Greater Omni Forest', '7', '1940', '900', 'Ring Mountain Range');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (26, '14', '25', 'Greater Omni Forest', '8', '940', '460', 'Southern Isle');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (27, '15', '25', 'Athen Shire', '3', '1980', '1340', 'Athen Fault');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (28, '15', '25', 'Galway County', '5', '1140', '1100', 'V-Hill');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (29, '15', '25', 'Greater Omni Forest', '2', '1180', '2460', 'Dragonback Ridge');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (30, '15', '25', 'Galway Shire', '4', '780', '900', "Arthur\'s Pass");
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (31, '15', '25', 'Mutant Domain', '1', '780', '1420', 'Mutant Domain North');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (32, '15', '25', 'Newland', '2', '540', '460', 'West of Newland Lake');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (33, '15', '25', 'Omni Forest', '5', '340', '1420', 'Northern Easy Swamps Notum Fields');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (34, '15', '25', 'Stret West Bank', '2', '2300', '2860', 'Pondus Beach');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (35, '15', '26', 'Holes in the Wall', '1', '420', '2020', 'Populous Mountain');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (36, '15', '26', 'Omni Forest', '6', '460', '820', 'Ocean Inlet');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (37, '17', '28', 'Galway Shire', '3', '900', '1220', "Vas\' Pass");
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (38, '12', '30', 'Stret West Bank', '6', '1340', '1220', 'Omni Outpost');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (39, '15', '30', 'Omni Forest', '2', '980', '3020', 'Moderate Grassland');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (40, '15', '30', 'Stret West Bank', '3', '1700', '2780', 'Hound Land');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (41, '15', '30', 'Wailing Wastes', '8', '660', '900', 'North of Yuttos');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (42, '20', '30', 'Athen Shire', '2', '1780', '1780', 'Academy Ore');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (43, '20', '30', 'Galway County', '6', '1580', '700', 'Lunder Hills - North');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (44, '20', '30', 'Galway County', '8', '1220', '380', 'Lunder Hills');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (45, '20', '30', 'Greater Tir County', '2', '2900', '2940', 'NE Desert Aperient');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (46, '20', '30', 'Lush Fields', '2', '2420', '3180', 'North East Lush Fields');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (47, '20', '30', 'Lush Fields', '6', '1780', '1820', 'Central Lush Fields');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (48, '20', '30', 'Mutant Domain', '2', '500', '860', 'Mutant Domain Central');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (49, '20', '30', 'Stret West Bank', '1', '1700', '3100', 'Hells Courtyard');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (50, '20', '30', 'Stret West Bank', '5', '1700', '1940', 'East Mutie');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (51, '20', '30', 'Stret West Bank', '7', '660', '1180', 'South Mutie');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (52, '20', '30', 'Tir County', '3', '3220', '620', 'Mountain Areas');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (53, '20', '30', 'Wailing Wastes', '6', '580', '1740', 'Charred Groove');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (54, '20', '35', 'Greater Omni Forest', '4', '1860', '1340', 'Waterfall Swamp');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (55, '20', '35', 'Omni Forest', '1', '500', '3220', 'Northern Grassland');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (56, '25', '35', 'Aegean', '8', '820', '780', 'Canyon South');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (57, '25', '35', 'Wailing Wastes', '4', '340', '2420', 'Powdered Dunes');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (58, '10', '40', 'Lush Fields', '3', '3460', '2940', 'Stret River Island');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (59, '20', '40', 'Holes in the Wall', '5', '780', '460', 'Southern Empty Wastes and Roads');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (60, '20', '40', 'Stret West Bank', '4', '1980', '2780', 'Hound Notum Field');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (61, '25', '40', 'Galway County', '7', '2740', '460', 'Galway Hills');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (62, '25', '40', 'Galway County', '9', '2260', '380', 'South-east Woods');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (63, '25', '40', 'Greater Omni Forest', '6', '900', '1220', 'Northern Semi-Barren Area');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (64, '25', '40', 'Greater Tir County', '4', '2220', '1900', 'Piercing Thundertube');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (65, '25', '40', 'Greater Tir County', '6', '620', '1660', 'Tir Prarie');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (66, '25', '40', 'Greater Tir County', '7', '1180', '1700', 'Crater Swamp');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (67, '25', '40', 'Mutant Domain', '3', '780', '460', 'Mutant Domain South');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (68, '25', '40', 'Newland Desert', '1', '2940', '2900', 'Rich Desert Ridge');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (69, '12', '45', 'Wailing Wastes', '7', '940', '1540', 'West of Perdition');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (70, '30', '45', 'Aegean', '4', '2140', '1660', 'Giant Green River Bank North');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (71, '30', '45', 'Aegean', '6', '2100', '1340', 'Giant Green River Bank South');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (72, '30', '45', 'Andromeda', '1', '420', '2700', 'Skop Notum Mine');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (73, '30', '45', 'Clondyke', '1', '1100', '4340', 'Yukon Source');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (74, '30', '45', 'Clondyke', '3', '2140', '2420', 'Round Hills');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (75, '30', '45', 'Greater Omni Forest', '1', '1620', '2660', 'Greater Omni Forest Swamps');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (76, '30', '45', 'Greater Omni Forest', '3', '1900', '1820', 'Mountainous Regions');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (77, '30', '45', 'Greater Tir County', '5', '2820', '1940', 'Central Striking Ant');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (78, '30', '45', 'Lush Fields', '1', '940', '3260', 'North West Lush Fields');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (79, '30', '45', 'Lush Fields', '8', '980', '380', 'South West Lush Fields');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (80, '30', '45', 'Newland Desert', '2', '1980', '2580', 'East of Meetmedere');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (81, '30', '45', 'Pleasant Meadows', '9', '740', '460', 'West of Versailles Tower');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (82, '30', '45', 'Varmint Woods', '1', '2420', '2980', 'By the Rivers Edge');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (83, '30', '45', 'Varmint Woods', '4', '3740', '2500', 'East Forest');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (84, '32', '45', 'Wailing Wastes', '5', '2540', '2060', 'Dust Bank');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (85, '25', '50', 'The Longest Road', '3', '3420', '1540', 'Fate Notum Field');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (86, '25', '50', 'Varmint Woods', '3', '1300', '2660', 'Along the Rivers Edge');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (87, '25', '50', 'Varmint Woods', '5', '3140', '2020', 'Rhino Hills');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (88, '26', '50', 'Wailing Wastes', '3', '980', '3140', 'Between the Craters');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (89, '35', '50', '4 Holes', '2', '940', '2020', 'Mountain of Fourtyone');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (90, '35', '50', '4 Holes', '3', '1300', '1980', 'Mountain in 4Holes');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (91, '35', '50', '4 Holes', '6', '1460', '1260', 'Mountain of Fortytwo');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (92, '35', '50', 'Aegean', '9', '900', '460', 'By the River');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (93, '35', '50', 'Clondyke', '2', '1460', '2540', 'Frisko');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (94, '35', '50', 'Clondyke', '5', '1260', '1820', 'Borrowed Hill');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (95, '35', '50', 'Clondyke', '6', '1340', '1340', 'Narrow Lune');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (96, '35', '50', 'Galway County', '1', '2140', '2620', 'Nature Reserve - East');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (97, '35', '50', 'Galway County', '2', '1900', '2580', 'Nature Reserve - West');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (98, '35', '50', 'Wailing Wastes', '2', '2220', '3340', 'Carbon Grove');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (99, '40', '55', 'Aegean', '3', '1020', '2460', 'Mid Wastelands');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (100, '30', '60', 'Andromeda', '7', '820', '340', 'Mocnuf Notum Mine');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (101, '30', '60', 'Stret West Bank', '8', '2260', '1140', 'The Beach');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (102, '35', '60', 'Lush Fields', '5', '1740', '2460', 'East of Outpost');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (103, '40', '60', 'Aegean', '1', '1220', '2740', 'Northern Wastelands');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (104, '40', '60', 'Andromeda', '5', '1420', '1580', 'Flubu Notum Mine');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (105, '40', '60', 'Lush Fields', '4', '1260', '2460', 'West of Outpost');	
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (106, '40', '60', 'Newland Desert', '4', '2580', '1940', 'North of Rhino Village');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (107, '40', '60', 'Newland Desert', '5', '2700', '1260', 'South of Rhino Village');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (108, '40', '60', 'Pleasant Meadows', '1', '1540', '2660', 'Pleasant Range Offense Hill');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (109, '40', '60', 'Pleasant Meadows', '7', '2260', '1140', 'Central Pleasant Plains');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (110, '40', '60', 'The Longest Road', '1', '4220', '1580', 'Illuminati');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (111, '40', '60', 'Wailing Wastes', '1', '1700', '3700', 'Styx Magma');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (112, '45', '60', '4 Holes', '4', '1660', '1740', 'South of Ahenus');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (113, '45', '60', 'Broken Shores', '7', '1260', '2140', 'Notum Mountain');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (114, '37', '64', 'Greater Tir County', '3', '1900', '2700', 'Surrounding Temple of Three Winds');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (115, '30', '70', 'Pleasant Meadows', '4', '3220', '2220', 'Pleasant Range Defense');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (116, '30', '70', 'Pleasant Meadows', '8', '3020', '1020', 'East Pleasant Plains');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (117, '40', '70', 'Andromeda', '6', '4340', '900', 'Plago');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (118, '45', '70', '4 Holes', '8', '1180', '500', 'Ibreri');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (119, '45', '70', '4 Holes', '9', '460', '420', 'Jall Mountain');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (120, '55', '70', 'Stret East Bank', '1', '700', '2420', 'Northern River Bank');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (121, '55', '70', 'Stret East Bank', '4', '2020', '1740', 'Klompfot Defense');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (122, '55', '70', 'Stret East Bank', '7', '1780', '700', 'Aprils Rock Offense');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (123, '45', '75', 'Broken Shores', '2', '1260', '3860', 'Notum Disruption Mountain');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (124, '50', '75', 'Avalon', '6', '2420', '1900', 'Waylander Mines');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (125, '50', '75', 'Clondyke', '4', '2140', '1900', 'Dense Drewen');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (126, '50', '75', 'Clondyke', '8', '2100', '540', 'High Juniper');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (127, '50', '75', 'Clondyke', '9', '2300', '460', 'High Juniper Notum Vein');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (128, '50', '75', 'Galway County', '3', '1300', '1900', 'Poole - West');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (129, '50', '75', 'Galway County', '4', '1580', '1820', 'Poole - East');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (130, '50', '75', 'Milky Way', '8', '2460', '540', 'The Silent Woods - East');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (131, '50', '75', 'Newland Desert', '3', '540', '2020', 'Middle of Western Desert');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (132, '50', '75', 'Pleasant Meadows', '3', '580', '2420', 'West of 20K');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (133, '50', '75', 'The Longest Road', '6', '4020', '620', 'Winterbottom');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (134, '50', '75', 'Upper Stret East Bank', '1', '540', '2820', 'West Pass');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (135, '50', '75', 'Varmint Woods', '2', '620', '2900', 'North Forest Road');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (136, '50', '75', 'Varmint Woods', '9', '3220', '1140', 'East of Crater');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (137, '65', '75', 'Upper Stret East Bank', '2', '900', '2300', 'Crowning Shallows');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (138, '50', '76', 'Varmint Woods', '6', '580', '1700', 'West Forest');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (139, '45', '80', 'Broken Shores', '5', '1300', '3060', 'Central Mountains');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (140, '30', '80', 'Andromeda', '2', '2820', '2340', 'Klor');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (141, '60', '80', 'Andromeda', '3', '2820', '1660', 'Harstad');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (142, '60', '80', 'Andromeda', '8', '2260', '380', 'Jucha');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (143, '61', '82', 'Avalon', '8', '460', '1380', 'Dome Ore');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (144, '40', '90', 'Andromeda', '4', '540', '1580', 'Ubleo');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (145, '60', '90', '4 Holes', '1', '1580', '2380', 'Notum Ore in Buttu');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (146, '60', '90', 'Avalon', '5', '580', '3140', 'Western Desert');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (147, '60', '90', 'Pleasant Meadows', '2', '2380', '2500', 'Central Pleasant Range');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (148, '60', '90', 'Pleasant Meadows', '5', '3220', '1980', 'Pleasant River Defense');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (149, '60', '90', 'Pleasant Meadows', '6', '3260', '1500', 'Pleasant River Offense');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (150, '60', '90', 'Southern Artery Valley', '1', '1380', '2780', 'Tetlies Land control area');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (151, '60', '90', 'Southern Artery Valley', '3', '660', '2460', 'West of outpost 10-3');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (152, '60', '90', 'Stret East Bank', '2', '1780', '2460', 'Hawker Trench');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (153, '60', '90', 'The Longest Road', '8', '2900', '500', 'Summer');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (154, '60', '90', 'Upper Stret East Bank', '7', '940', '420', 'Greenslopes');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (155, '60', '90', 'Varmint Woods', '7', '1940', '1620', 'Crossroads');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (156, '60', '90', 'Varmint Woods', '8', '1140', '1500', 'Forestdawn');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (157, '75', '90', 'Upper Stret East Bank', '6', '1820', '740', 'Stret Woods');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (158, '70', '95', 'Avalon', '3', '1740', '3460', 'Dreadfire Volcano');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (159, '1', '100', 'Mort', '5', '900', '1460', 'Green Crater');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (160, '55', '100', 'Broken Shores', '8', '2020', '1980', 'Near Omni-Tek Outpost');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (161, '60', '100', 'Southern Fouls Hills', '1', '1900', '3020', 'North of Lenne');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (162, '60', '100', 'Southern Fouls Hills', '4', '900', '2100', 'By the Ocean');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (163, '61', '100', 'Southern Fouls Hills', '5', '2300', '1180', 'Birm');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (164, '70', '100', '4 Holes', '5', '1820', '1340', 'Ibreri Woods North');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (165, '70', '100', 'Avalon', '7', '1860', '1700', 'North of Main Omni Base');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (166, '75', '100', 'Broken Shores', '3', '1940', '3860', 'The Notum Plains');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (167, '70', '105', 'Andromeda', '9', '4380', '380', 'Mune');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (168, '70', '105', 'Stret East Bank', '3', '1460', '1740', 'Klapam Forest Defense');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (169, '70', '105', 'Stret East Bank', '5', '1900', '1220', 'South of Trench');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (170, '80', '110', 'Avalon', '2', '540', '4180', 'Draught');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (171, '71', '120', 'The Longest Road', '4', '580', '820', 'Pegrama');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (172, '80', '120', 'Avalon', '4', '2780', '3420', 'Northeast Barren Lands');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (173, '80', '120', 'Southern Artery Valley', '2', '2900', '2660', 'East of the Great Marsh');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (174, '80', '120', 'Stret East Bank', '6', '1140', '940', 'Nile Hills');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (175, '84', '120', 'The Longest Road', '5', '1220', '700', 'Grazeland Notum Field');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (176, '90', '120', 'Milky Way', '2', '1900', '1540', 'The Resilient Forest - East');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (177, '90', '120', 'Southern Fouls Hills', '3', '2620', '2660', 'Defense of Zoto');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (178, '90', '120', 'The Longest Road', '7', '540', '500', 'Southern Forest of Illuminations');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (179, '110', '120', 'Belial Forest', '2', '1100', '2620', 'Muddy Pools');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (180, '100', '125', 'Milky Way', '4', '1380', '1180', 'Central Resilient Forest');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (181, '100', '125', 'Milky Way', '7', '1740', '860', 'The Resilient Forest - South');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (182, '90', '130', 'Central Artery Valley', '4', '3340', '2700', 'North-East Forest');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (183, '90', '130', 'Milky Way', '1', '1460', '1940', 'The Resilient Forest - North');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (184, '90', '135', 'Greater Tir County', '1', '1100', '3100', 'The Mineral Mine');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (185, '70', '140', 'Upper Stret East Bank', '4', '2020', '1740', 'Stret Vale Deux Drilling Field');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (186, '106', '143', 'Southern Artery Valley', '5', '2740', '1180', 'South of Forest of Geholva');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (187, '55', '15', 'Broken Shores', '6', '380', '2300', 'Surrounding Evil');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (188, '80', '150', 'Broken Shores', '1', '940', '4820', 'Central Desert North');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (189, '80', '150', 'Stret East Bank', '8', '820', '420', 'Southern Lower River Bank');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (190, '80', '150', 'Stret East Bank', '9', '1700', '340', 'Aprils Rock Defense');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (191, '100', '150', '4 Holes', '7', '1740', '1060', 'Ibreri Woods');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (192, '100', '150', 'Avalon', '1', '2740', '4260', 'Griffon Frontier');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (193, '100', '150', 'Avalon', '9', '2700', '620', 'Crystal Forge Volcano');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (194, '100', '150', 'Avalon', '10', '660', '460', 'SW Low Plateau');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (195, '100', '150', 'Belial Forest', '3', '1700', '2300', 'West of Wine');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (196, '100', '150', 'Broken Shores', '4', '940', '3380', 'Near Clan Outpost');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (197, '100', '150', 'Broken Shores', '9', '420', '820', 'Shores Notum Vein');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (198, '100', '150', 'Central Artery Valley', '6', '3100', '980', 'Mid Clutching Forest');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (199, '100', '150', 'Central Artery Valley', '8', '3180', '620', 'South Clutching Forest');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (200, '100', '150', 'Deep Artery Valley', '1', '1140', '3380', 'Old Ruins');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (201, '100', '150', 'Deep Artery Valley', '2', '3180', '2900', 'Plains of Defense');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (202, '100', '150', 'Eastern Fouls Plain', '7', '2020', '860', 'Central Sharewood');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (203, '100', '150', 'Mort', '8', '540', '540', 'South West Craterwall');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (204, '100', '150', 'Milky Way', '6', '4020', '980', 'The Barren Hills');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (205, '100', '150', 'Perpetual Wastelands', '7', '1500', '1340', 'Lower Plateu Zone');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (206, '100', '150', 'Perpetual Wastelands', '8', '2100', '1380', 'The Mid Canyon Crossing');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (207, '100', '150', 'Perpetual Wastelands', '10', '900', '1060', 'West of Canyon');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (208, '100', '150', 'Perpetual Wastelands', '11', '3180', '940', 'The Canyon Mines');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (209, '100', '150', 'Southern Artery Valley', '4', '2300', '2020', 'Defense of Geholva');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (210, '100', '150', 'Southern Artery Valley', '8', '2460', '540', 'Bendelham forest Defense');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (211, '100', '150', 'Southern Fouls Hills', '2', '860', '2820', 'Little Hawaii Defense');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (212, '100', '150', 'The Longest Road', '2', '500', '1540', 'Northern Forest of Illuminations');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (213, '100', '150', 'Upper Stret East Bank', '3', '1660', '2180', 'Haven Notum Crematorium');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (214, '100', '150', 'Southern Fouls Hills', '7', '1860', '500', 'South in Nightplain');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (215, '120', '150', 'Belial Forest', '8', '2340', '860', 'Borderline');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (216, '110', '160', 'Mort', '6', '3100', '1460', 'Oasis Ore');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (217, '100', '170', 'Central Artery Valley', '3', '2900', '2820', 'North Forest');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (218, '100', '170', 'Mort', '1', '1500', '3420', 'Terraform Edge');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (219, '125', '170', 'Milky Way', '3', '2780', '1380', 'Central Prowler Waste');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (220, '125', '170', 'Milky Way', '5', '2860', '1020', 'Southern Prowler Waste');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (221, '130', '170', 'Central Artery Valley', '5', '860', '1220', 'North-West of Lava Ditches');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (222, '130', '170', 'Central Artery Valley', '7', '860', '780', 'South-West of Lava Ditches');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (223, '130', '170', 'Mort', '4', '1220', '2220', 'Middle Mort Desert');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (224, '120', '180', 'Belial Forest', '4', '2940', '2260', 'East of Wine');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (225, '120', '180', 'Belial Forest', '9', '2020', '420', 'Southern Belial Mine');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (226, '120', '180', 'Eastern Fouls Plain', '3', '620', '2980', 'Plains of Jarga Defense');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (227, '120', '180', 'Perpetual Wastelands', '3', '980', '2060', 'South of Sabulum');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (228, '120', '180', 'Perpetual Wastelands', '9', '3020', '1220', 'Plains of dust');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (229, '120', '180', 'Southern Artery Valley', '6', '860', '900', 'Avid Crater');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (230, '120', '180', 'Southern Artery Valley', '7', '1540', '900', 'East of Avid Crater');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (231, '120', '180', 'Southern Fouls Hills', '6', '2700', '660', 'SFH Defense');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (232, '120', '180', 'Upper Stret East Bank', '5', '1340', '1620', 'The Flooded Bottomland');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (233, '130', '180', 'Deep Artery Valley', '3', '1740', '2300', 'The Haunted Forest Outskirt');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (234, '130', '180', 'Deep Artery Valley', '4', '900', '2200', 'Forest of Xzawkaz');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (235, '130', '180', 'Deep Artery Valley', '6', '1420', '1500', 'Island of Control');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (236, '130', '180', 'Deep Artery Valley', '7', '1340', '1140', 'The Swamp of Hope');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (237, '130', '190', 'Belial Forest', '6', '2500', '1660', 'River Delta');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (238, '130', '195', 'Belial Forest', '5', '1900', '1740', 'Central Belial Forest');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (239, '130', '200', 'Eastern Fouls Plain', '6', '1540', '1140', 'Clefre Defense');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (240, '140', '200', 'Belial Forest', '10', '620', '380', 'Southwest Belial Mining District');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (241, '140', '200', 'Central Artery Valley', '1', '1740', '3100', 'By the Fisher Village');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (242, '140', '200', 'Central Artery Valley', '2', '2100', '3060', 'Fisher Village Approach');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (243, '150', '200', 'Eastern Fouls Plain', '1', '2700', '3860', 'Krud the Lost Valley Defense');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (244, '150', '200', 'Mort', '7', '2740', '700', 'South East Craterwall');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (245, '160', '200', 'Belial Forest', '1', '2940', '2820', 'Forest Waters');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (246, '160', '200', 'Belial Forest', '7', '2540', '1220', 'Junction Forest');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (247, '140', '210', 'Deep Artery Valley', '9', '2140', '780', 'Middle of the Foul Forest');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (248, '160', '210', 'Mort', '9', '2780', '540', 'Stormshelter');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (249, '150', '225', 'Eastern Fouls Plain', '2', '1900', '3180', 'Pranade');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (250, '190', '230', 'Perpetual Wastelands', '4', '3940', '2060', 'Cyborg Border');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (251, '190', '230', 'Perpetual Wastelands', '12', '2300', '780', 'South of Canyon');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (252, '170', '250', 'Mort', '2', '3060', '3020', 'West Spirals');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (253, '170', '250', 'Mort', '3', '3500', '2980', 'East Sprials');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (254, '191', '250', 'Perpetual Wastelands', '2', '3780', '2540', 'Middle of Liberty');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (255, '200', '300', 'Deep Artery Valley', '5', '2260', '1860', 'In the Swamp of Horrors');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (256, '200', '300', 'Deep Artery Valley', '8', '2900', '1100', 'South of the Medusa');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (257, '200', '300', 'Deep Artery Valley', '10', '540', '540', 'Southern Forest of Xzawkaz');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (258, '200', '300', 'Eastern Fouls Plain', '4', '2460', '2260', 'Old Plains');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (259, '200', '300', 'Eastern Fouls Plain', '5', '1540', '1780', 'Middle of Easter Fouls Plains');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (260, '200', '300', 'Eastern Fouls Plain', '8', '820', '540', 'Pegradul');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (261, '200', '300', 'Perpetual Wastelands', '1', '3220', '3020', 'North of Cyborg Hideout');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (262, '200', '300', 'Perpetual Wastelands', '5', '2820', '1820', 'Middle of Perpetual Wastelands');
INSERT INTO towerranges (id, low_level, high_level, playfield, hugemaploc, coordx, coordy, location) VALUES (263, '200', '300', 'Perpetual Wastelands', '6', '3740', '1700', 'South of Cyborg Hideout');