DROP TABLE IF EXISTS whereis;
CREATE TABLE whereis (`whereisid` int(10),`name` varchar(255),`answer` text,`keywords` text);
INSERT INTO `whereis` VALUES (1,'A Spoiled Brat','in a park in Omni-Ent, at 946 x 350.',NULL);
INSERT INTO `whereis` VALUES (2,'Ellsolan','behind you, trying to kill you',NULL);
INSERT INTO `whereis` VALUES (3,'Glarawyn','lost. Where are you?',NULL);
INSERT INTO `whereis` VALUES (4,'Supply Master Eel','at the Secondary Base in Avalon near 900 x 1600.','Supplymaster Eel');
INSERT INTO `whereis` VALUES (5,'The Essence Of Primal Understanding','in the Burning Marshes area of Inferno at 1975 x 1115.',NULL);
INSERT INTO `whereis` VALUES (6,'Sentinel Commander Higgins','in Tir City 500 x 500',NULL);
INSERT INTO `whereis` VALUES (7,'Lilredhot','at reclaim.',NULL);
INSERT INTO `whereis` VALUES (8,'Kimarzt','eating pie and cake',NULL);
INSERT INTO `whereis` VALUES (9,'4 Holes (aka 4HO)','in the west central part of the world. It has a grid access point at 893x1754, whompas at 1200 x 1225 to 2ho, 20k, and Broken Shores. North of 4holes is Stret West Bank, south is Andromeda, east Stret East Bank, no zone avail to the west.','Four Holes Fourholes');
INSERT INTO `whereis` VALUES (10,'A Dancing Fool','in Baboons (located in Omni Entertainment at 766 x 766)',NULL);
INSERT INTO `whereis` VALUES (11,'Abmouth Supremus','in the lower levels of the Subway Dungeon at the very end. He spawns two infectors when attacked.',NULL);
INSERT INTO `whereis` VALUES (14,'One Whose Words Happen To Rhyme','just north of the portal to Penumbra in Infero at 905 x 180.',NULL);
INSERT INTO `whereis` VALUES (13,'A Fire Flea','in Inferno.  It''s the first creature you will encounter. When killed, a Firey Imp will appear.',NULL);
INSERT INTO `whereis` VALUES (15,'One Who Learns The Past','just north of the portal to Penumbra in Infero at 905 x 180.',NULL);
INSERT INTO `whereis` VALUES (16,'Anansi Devotee','East of Sorrow In Inferno, 1650 x 1400',NULL);
INSERT INTO `whereis` VALUES (17,'Anansi Protector','East of Sorrow In Inferno, 1650 x 1400',NULL);
INSERT INTO `whereis` VALUES (18,'Anansi Scribe','East of Sorrow In Inferno, 1650 x 1400',NULL);
INSERT INTO `whereis` VALUES (19,'Spirit Of Disruption','among the ruins just north of the portal to Penumbra in Inferno at 1015 x 205.',NULL);
INSERT INTO `whereis` VALUES (20,'Contemplating Spirits And Unrepentant Spirits','among the runes just north of the portal to Penumbra in Inferno surrounding the Spirit Of Disruption.',NULL);
INSERT INTO `whereis` VALUES (23,'Chimera Aberrant','around the +10 ring dungeon just inside Inf',NULL);
INSERT INTO `whereis` VALUES (24,'City Administrator Rex Chapman','at Pos: 905 x 522, Area: Omni-1 Entertainment. Near the billboards next to the Whompa to Rome.',NULL);
INSERT INTO `whereis` VALUES (25,'Unicorn Landing Beacon','at Pos: 3440 x 1308, Area: Nepal in Andromoda. North of ICC HQ.',NULL);
INSERT INTO `whereis` VALUES (26,'The Outzone (AKA APF)','is a raid zone for L180+ characters. To enter the Outzone, board the Unicorn Transport Shuttle found in Andromeda outside the ICC. 3440 x 1300. Or use a <a href=''itemref://260424/260424/1''>Decrypted Kyr''Ozch Data Core</a> when you''re near the ICC or Unicorn Shuttle Boarding Zone.','Apf Icc');
INSERT INTO `whereis` VALUES (27,'Ace Camp','in Eastern Fouls Plains somewhere.','Primus');
INSERT INTO `whereis` VALUES (28,'Aegean','in the northeast part of the world. No grid access point and no whompa. East of Aegean is Varmint Woods, to the west is Athen Shire, southeast is Upper Stret East Bank, southwest Wartorn Valley and Stret West Bank, no zone available to the north.','Aegean Aegan Aegean Aegeon Aegon Agean Ageon');
INSERT INTO `whereis` VALUES (29,'Alvin Odeleder','in the Lush Fields Outpost at 1538 x2500 ','Alvinodeleder');
INSERT INTO `whereis` VALUES (30,'Andromeda','in the southwest part of the world. Whompas to Tir, Newland, and Omni Trade at 3250 x 900. To the north (east) of Andromeda is 4 Holes, to the north (west) is Stret East Bank. To the east is Milky Way, south (east) is Lush Fields, south Clondyke. No zone avail to the west.','655 Andromada Andromedia Andromida Icc');
INSERT INTO `whereis` VALUES (31,'Shy Eremite','in Inferno South-East of Sorrow (straight south of Anansi Devotee''s) around 1650 x 1150',NULL);
INSERT INTO `whereis` VALUES (32,'Bold Eremite','in Inferno South-East of Sorrow (straight south of Anansi Devotee''s) around 1650 x 1150',NULL);
INSERT INTO `whereis` VALUES (33,'Another Face In The Sand','at 1300 x 2650 in Mort.',NULL);
INSERT INTO `whereis` VALUES (34,'Architect Striker','in the Subway Dungeon, usually on the bridge.',NULL);
INSERT INTO `whereis` VALUES (35,'Area Y','beyond Galway View next to Arthers Pass',NULL);
INSERT INTO `whereis` VALUES (36,'Athen Old','in the northwest part of the world. Grid access at 512 x 573. It has a whompa to Tir, Wailing Wastes and Bliss at 445 x 318. Out the east gate is Wartorn Valley and out west gate is West Athen.',NULL);
INSERT INTO `whereis` VALUES (37,'Athen Shire','in the northwest part of the world. It has no grid access or whompa. To the north is Wailing Wastes, to the east is Wartorn Valley and Aegean, to the west is The Longest Road, to the south is Holes in the Wall. The War Academy at 1740 x 1970.','Athen Shir Shire Shite Shrine Sire Athens Athenshire');
INSERT INTO `whereis` VALUES (38,'Athen West','in the northwest part of the world. It has a grid access point at 472 x 410 and no whompa. To the north, south and west is Athen Shire, to the east Athen Old.','Athen West Athens Athenwest Old Weat Grid');
INSERT INTO `whereis` VALUES (39,'Avalon','in the north west part of the world. It has a grid entry at 2070 x 3760 and a whompa to Athens and Wailing Wastes at 2175x3815. There is no zone available to the north, east and west. Southeast is Wailing Wastes. camelot castle (dungeon) at 2090 x 3820. clan op with scanner at 1540 x 3730 and 2140 x 3110. Omni outposts with scanner at 800 x 1630 and at 1870 x 1230.','Avalon Avolon Omni Outpost');
INSERT INTO `whereis` VALUES (40,'Calamity Eremite','in Inferno SouthEast of Sorrow (South of Anansi Devotees) 1685 x 1164, Area: Burning Marshes (south of the rock)',NULL);
INSERT INTO `whereis` VALUES (41,'Aztur','in the Temple of the Three Winds,  The Dungeon Boss, he drops the red sword called Sygian Desolator. You need to kill Uklesh the Frozen and Khalum before he spawns.',NULL);
INSERT INTO `whereis` VALUES (42,'Baboons','in Omni Entertainment at 766 x 766.',NULL);
INSERT INTO `whereis` VALUES (43,'Beer And Booze Bar','in Mort at 2840 x 1920, in the city called Hope. The bar has a 5% supression gas.','Beer &amp; Booze And Bar N');
INSERT INTO `whereis` VALUES (44,'Best In Brass','in Galway Shire, Rome Stretch 400 x750','Bestinbrass Brast');
INSERT INTO `whereis` VALUES (45,'Biomare (Biological Materials Research) (aka Omni-Med Bio Facility) (aka Foremans Office)','in The Longest Road at 1930 x 775. Recommended for teams of lvl 40-70. Look for a door that says Foreman above the doorway.',NULL);
INSERT INTO `whereis` VALUES (46,'Bliss','in The Longest Road at 3700 x 1615. Bliss has shops, clan insure terms, banks and mission terms. Bliss has whompas to Athen Old, Avalon, and Broken Shores','Bilss Blis Bliss Worms');
INSERT INTO `whereis` VALUES (47,'Bonzo','at the Beer and Booze Bar, Mort at 2835 x 1930',NULL);
INSERT INTO `whereis` VALUES (48,'Borealis','in the central-west part of the world. Grid access at 635 x 727. Whompa to Stret West Bank at 682 x 531. Whompa to Newland right next to that. East of Borealis is Holes in the Wall. No zones currently available to the north, south, and west.','Bor Borealis Approach City Grid');
INSERT INTO `whereis` VALUES (49,'Brainy Ant Woods','in Greater Tir County near 1300 x 1500,','Ants Biniary');
INSERT INTO `whereis` VALUES (50,'Brenda Diamond','at the ruins near Home in Broken Shores at 430 x 2200',NULL);
INSERT INTO `whereis` VALUES (51,'Broken Shores','in the southwest corner of the world. It has a grid access point in City of Home at 644 x 1313. In the north is a Whompah at 1000 x 3760 to Bliss and to Wine. There is a Whompah to Rome Red and 4 Holes Trade at 2340 x 2250','Broken Shord Shore Shores Brokenshores Bs Grid');
INSERT INTO `whereis` VALUES (52,'Brutus Leonidis','at 1550 x 300 in Athen Shire',NULL);
INSERT INTO `whereis` VALUES (53,'Captain Lewison','at Reet retreat, Stret West Bank',NULL);
INSERT INTO `whereis` VALUES (54,'City Of Home','in the Broken Shores zone, at 735 x 1459. It has shops, clan/neut insure terms, banks.','Cityofhome');
INSERT INTO `whereis` VALUES (55,'Clan Modified A-4000','at Avalon at 1105 x 2520','Clan Modified A 4000 a-4000 A4000');
INSERT INTO `whereis` VALUES (56,'Clawfinger Forefather','at Smuggler''s Den, Southern Fouls Hills at 1749 x 869','Claw Finger Forefather Clawfinger Fore Father');
INSERT INTO `whereis` VALUES (57,'Coco','next to the bar in ''The Cup'', in West Athen',NULL);
INSERT INTO `whereis` VALUES (58,'Colonel Frank Kaehler','at Omni-Forest at 700 x 2000','Colonel Frank Kaehler Keahler Kehler');
INSERT INTO `whereis` VALUES (59,'Commander Jocasta','at Cyborg Barracks in GTC at 3232 x 2340',NULL);
INSERT INTO `whereis` VALUES (60,'Commander Kelly Frederickson','at Tir County at 1750 x 1100','Commander Kelly Frederickson Fredrickson');
INSERT INTO `whereis` VALUES (61,'Condemned Subway','in several cities.  A dungeon for L 1-24 players. There are 3 Subway dungeons. In Borealis at 637 x 463 (south part of city). In Galyway Shire at 168 x 874, just outside the east gates of Rome Blue. And in Old Athen at 487 x 439, just NE of town center.','Add Abandoned Subway Athen Athens Borealis Dungeon Clan Codemned Comdemned Condemned Condemnedsubway Old Rome Blue In Tir Athenes Station');
INSERT INTO `whereis` VALUES (62,'Cuty','at Tir County Area, Crater Farm Region at 1500 x 600',NULL);
INSERT INTO `whereis` VALUES (63,'Cyborg Barracks','in the northeast part of the world, in Greater Tir County at 3230 x 2340. Recommended for teams of lvl 70-90.','Borg Baracks Barrack Barrackes Barracks Barracksccccc Barracs Barraks Camp Campp Camps Domain Dungeon Borgbarracks Borgs Cyborg Cyborgbarracks');
INSERT INTO `whereis` VALUES (64,'Daedra Iberra','at Pleasent Meadows at 1510 x 720',NULL);
INSERT INTO `whereis` VALUES (65,'Dancing Atrox Bar','at 300 x 1850, Omni-1 Screening Area (Omni Forest). You may know this place as called Relax Bar.','Club Bar');
INSERT INTO `whereis` VALUES (262,'Chimera Crusher','at 1090 x 400, East of the Portal to Pen, around the +10 ring dungeon just inside Inf',NULL);
INSERT INTO `whereis` VALUES (69,'Ding','at Greater Tir County',NULL);
INSERT INTO `whereis` VALUES (70,'Dodga Demercel','in Rising Sun, in Aegean.',NULL);
INSERT INTO `whereis` VALUES (71,'Eddie','in Stret West Bank (outside Reets Retreat) at 1212 x 2828.','Eddy');
INSERT INTO `whereis` VALUES (72,'Eden Cafe','in Omni Entertainment,South 744 x 417',NULL);
INSERT INTO `whereis` VALUES (73,'Electro Unique','in Wailing Wastes, north of Athens Shire 650 x1950','Electro Umique Uneak Unique Uniqui Electrounique');
INSERT INTO `whereis` VALUES (74,'Elian Zuwadza','at Galway at 450 x 1300',NULL);
INSERT INTO `whereis` VALUES (75,'Elmer Ragg','at Mort at 1731 x 942',NULL);
INSERT INTO `whereis` VALUES (76,'Enjoy It While It Lasts','at 650 x 400, Tir City','bar club');
INSERT INTO `whereis` VALUES (77,'Eradicator Deimos','at Cyborg Barracks in GTC at 3232 x 2340','deimos demos eradicater eradicator');
INSERT INTO `whereis` VALUES (78,'Eric Mendelson Outpost','in Varmint Woods at 2450 x 2100. There are mission terms, insure term and shopping terms.','Erik Ericmendelsonoutpost');
INSERT INTO `whereis` VALUES (80,'Escaped Gargantula','at Galway, Central Galway County at 2160 x 1150',NULL);
INSERT INTO `whereis` VALUES (81,'Eumenides','in the Subway Dungeon, at the end of the one rail way hall, past the slum runners but before the infectors.',NULL);
INSERT INTO `whereis` VALUES (82,'Fiery Trainee','at Eastern Fouls Plains at 365 x 2060',NULL);
INSERT INTO `whereis` VALUES (83,'Freedom Outpost','in Athen Shire at 1553 x 370. Insure terms, shops and mission terms and banks are available here. Directly beside the outpost is the zone to Wailing Wastes.','Freedomoutpost');
INSERT INTO `whereis` VALUES (84,'Galvano','in Greater Omni-Forest, Grassland 2020 x 2190','Galivino Galvano Galven Galvino');
INSERT INTO `whereis` VALUES (85,'Galway Castle Model','at 1110 x 1000 in Galway County',NULL);
INSERT INTO `whereis` VALUES (86,'General Freewheeler','at the Main OT Base in Avalon near 1800 x 1200',NULL);
INSERT INTO `whereis` VALUES (87,'General Hardcastle','at the Main OT Base in Avalon near 1800 x 1200',NULL);
INSERT INTO `whereis` VALUES (88,'General Serverus','at Cyborg Barracks in GTC at 3232 x 2340',NULL);
INSERT INTO `whereis` VALUES (89,'Genghis Pan','at Mongol Meat, Tir',NULL);
INSERT INTO `whereis` VALUES (90,'George','at Greater Tir County at 3200 x 2300',NULL);
INSERT INTO `whereis` VALUES (91,'Gnuff','in the Will to Fight dungeon, in the center at 1111 x 833. He drops a Crystal of Rift Power, which will give you a random buff, like when you open a shrine.',NULL);
INSERT INTO `whereis` VALUES (92,'Good Time Party Mixer','at Newland City at 463 x 339. And one for Clans is located at Reets Retreat',NULL);
INSERT INTO `whereis` VALUES (93,'Greasy Joints','in Newland Desert 890 x 950','Greasy Gears Jints Joings Joint Joints Now Jones Greasyjoints Greazy Greazyjoints');
INSERT INTO `whereis` VALUES (94,'Greater Omni Forest','in the southeast part of the world. No grid or whompa.','Greater Omni Foreset Forest Forrest Greateromniforest');
INSERT INTO `whereis` VALUES (96,'Greater Tir County Hotsprings','at 2850 x 1650 in Greater Tir County','Hot spring Springs Hotsprings');
INSERT INTO `whereis` VALUES (97,'Gridman','at Fixer Grid, at the top','Grid Man Gridman');
INSERT INTO `whereis` VALUES (98,'Harry''s Outpost','in Lush Feilds. You can grid to Harry''s or take the west exit from Omni-Trade. Or take the teleportal from the west side of Pleasent Meadows.','Harries Harry''s Harry;s Harrys Grid Outpost');
INSERT INTO `whereis` VALUES (99,'Harry, Himself','at Harry''s Outpost in Lush Fields',NULL);
INSERT INTO `whereis` VALUES (100,'High Commander Brock','at SE OP of Tir, 2861 x 738',NULL);
INSERT INTO `whereis` VALUES (101,'High Commander Fielding','at the northeast corner of Wailing Wastes at 2700 x 3500',NULL);
INSERT INTO `whereis` VALUES (102,'High Commander Hoover','at the northeast corner of Wailing Wastes at 2700 x 3500',NULL);
INSERT INTO `whereis` VALUES (103,'Holes In The Wall','in the west central part of the world. No grid access and no whompa. North of Holes in the Wall is Athen Shire, south and east is Stret West bank, Borealis to the west.',NULL);
INSERT INTO `whereis` VALUES (104,'Hope','a neutral city in Mort. It has whompas to Stret West Bank and Newland Desert at 2888 x 1909',NULL);
INSERT INTO `whereis` VALUES (105,'Horatio Campbell','at 300 x 200 in Omni Trade',NULL);
INSERT INTO `whereis` VALUES (106,'Ian Warr','at Eastern Fouls Plains at 720 x 1380',NULL);
INSERT INTO `whereis` VALUES (107,'ICC','located in Andromeda at 3250 x 900. Whompas to ICC come from Newland, Omni Trade and Tir.',NULL);
INSERT INTO `whereis` VALUES (108,'Ida Schuller','in Omni-Trade',NULL);
INSERT INTO `whereis` VALUES (109,'Information Officer Stiller','in Avalon at the main OTAF base, at 1800 x 1288',NULL);
INSERT INTO `whereis` VALUES (110,'Inventor Bobic','at Tir Country at 1910 x 1398',NULL);
INSERT INTO `whereis` VALUES (111,'Iziris Agathon','in Northeastern Omni-Trade',NULL);
INSERT INTO `whereis` VALUES (112,'Janella Gheron','at Cyborg Barracks, GTC at 3200 x 2300',NULL);
INSERT INTO `whereis` VALUES (113,'Joo','at Omni Forest Area, Sunken Swamps at 500 x 2700',NULL);
INSERT INTO `whereis` VALUES (114,'Kendric Kuzio','at Deep Artery Valley at 1532 x 999',NULL);
INSERT INTO `whereis` VALUES (115,'Klapam Forest','in Stret East Bank',NULL);
INSERT INTO `whereis` VALUES (116,'Lab Director','at Longest Road, The Foremans Office at 1940 x 775',NULL);
INSERT INTO `whereis` VALUES (117,'Leet Crater','just south east of Omni-Pol Barracks region in Omni Forrest, which is just south outside Omni Entertainment''s City Gates.',NULL);
INSERT INTO `whereis` VALUES (118,'Live Metal','in Greater Tir County, Rocky Outcrops 1520 x 2210','Livemetal');
INSERT INTO `whereis` VALUES (120,'Lord Ghasap','at Avalon Dungeon, Avalon at 2092 x 3822',NULL);
INSERT INTO `whereis` VALUES (121,'Lush Fields','located in the south central part of the world. Lush Fields has grid access at 1443 x 667 (Lush Hills Resort)and at Harry''s at 3115 x 3183. Ferrys to Harry''s at 3563 x 916, ferrys to PM OT outpost at 3391 x 797 and 3195 x 3178 and ferry to Omni Trade at 3295 x 2917. No whompa. NW is Andromeda, northeast is Milky Way, west is Clondyke, east is Pleasant Meadows. MutantDomain is located centrally on eastern border.','Lush Feilds Fhields Field Fields Outpost Resort Forest Hill Hills Meadows Op Woods Lushfields North West Mines Nw Omni Mine Prime');
INSERT INTO `whereis` VALUES (122,'Majestik Woods','at 400 x 2520 northeast of Rome Blue',NULL);
INSERT INTO `whereis` VALUES (123,'Mantis Queen','at Smuggler''s Den, Southern Fouls Hills at 1749 x 869',NULL);
INSERT INTO `whereis` VALUES (124,'Marcus Poet Laureate','at Broken Shores at 1500 x 2900',NULL);
INSERT INTO `whereis` VALUES (125,'Marvin','at 1250 x 2350 in Southern Artery Valley',NULL);
INSERT INTO `whereis` VALUES (126,'Metalomania','in Lush Fields, Harry''s Outpost 2980 x 3125',NULL);
INSERT INTO `whereis` VALUES (127,'Mick Nugget McMullet','at Clondyke at 1100 x 3700','Mc Nugget Mcnugget Mick Mcmullet Nuggets');
INSERT INTO `whereis` VALUES (128,'Milky Way','located in the southeast part of the world. No grid access or whompa. North of Milky Way is S.Artery Valley, nw is Stret East Bank, west is Andromeda, sw is Lush Fields, south is Pleasant Meadows, SE is Eastern Foul Plains, NE is Belial Forest.',NULL);
INSERT INTO `whereis` VALUES (129,'Milky Way Spaceship Crash Site','at 3300 x 700 in Milky Way',NULL);
INSERT INTO `whereis` VALUES (130,'Miner Beetles','at 1100 x 2300 in Pleasant Meadows',NULL);
INSERT INTO `whereis` VALUES (131,'Molested Molecules','at Subway Dungeon',NULL);
INSERT INTO `whereis` VALUES (132,'Monday Kline','at Stret E at 1300 x 890 at TRA only',NULL);
INSERT INTO `whereis` VALUES (133,'Moog','at 1850 x 2550 in Southern Artery Valley',NULL);
INSERT INTO `whereis` VALUES (134,'Morgan LaFaye','at Avalon Dungeon, Avalon at 2092 x 3822, down the stairs where the PvP zone starts, and to the right.',NULL);
INSERT INTO `whereis` VALUES (135,'Mort','located in the northeast part of the world. It has whompas to Stret West Bank and Newland Desert at 2888 x 1909. Grid access is at 1928 x 1255 (Sentinels). There is no zones available to the north or west of Mort, to the south is Newland, to the east is Perpetual Wastelands.','Mort Crater Dungeon Sentinel Base Outpost Sentinels');
INSERT INTO `whereis` VALUES (136,'Morty','at Tir County Area, Kuroshio Forest at 300 x 1200',NULL);
INSERT INTO `whereis` VALUES (137,'Mutant Domain','located in the west central part of the world. No grid access or whompa. To the north, south and west of Mutant Domain is Lush Fields, east is Pleasant Meadows. This zone lies centrally on the eastern border of Lush Fields.','Mutant Domain Swamp Village Mutantdomain');
INSERT INTO `whereis` VALUES (139,'Neleb The Deranged','at Omni Forest, at the very end of the Steps of Madness dungeon at 800 x 2844',NULL);
INSERT INTO `whereis` VALUES (140,'Nelly Johnson','at Eastern Fouls Plains, 720 x 1380',NULL);
INSERT INTO `whereis` VALUES (141,'Netrom','in Southern Artery Valley at coords 1988 x 606.  A small outpost type ruins. ',NULL);
INSERT INTO `whereis` VALUES (142,'Neuts R Us','in Newland City at 447 x 340.  A club.  most Player Cities have a Whampa to here.','Neuters R Us Neutsrus');
INSERT INTO `whereis` VALUES (143,'Newland City','in the north east part of the world. It has a grid access point outside city west gate at 1172 x 482 and whompas to the ICC, Tir, and Borealis at 390 x 300. To the north, east, south and west of Newland City is Newland.',NULL);
INSERT INTO `whereis` VALUES (144,'Newland Desert','in the northeast part of the world. It has a grid access point at 1172 x 482 and whompas to Newland City and Hope at 2200 x 1575. To the north is Newland, to the south is Varmint Woods. There are currently no zones available to the east or west.','Meetmedeer Meetmeder Meetmedere Metmedere Newland Dessert Newlanddesert');
INSERT INTO `whereis` VALUES (145,'Newland','in the northeast part of the world. Grid access at 1527 x 2767 (Meetmedere), whompas inside Newland City to ICC, Newland Desert, and Borealis at 390 x 300. To the north of Newland is Mort, to the south is Newland Desert. Currently no zones available to the east or west.',NULL);
INSERT INTO `whereis` VALUES (146,'Nodda Gregg','at Tir Country/OP at 1933 x 1494',NULL);
INSERT INTO `whereis` VALUES (147,'Nolan Deslandes','in Neuters R Us, Newland City',NULL);
INSERT INTO `whereis` VALUES (148,'Notum Cannons','at 1200 x 3400 in Clondyke',NULL);
INSERT INTO `whereis` VALUES (149,'Notum Profundis','at Eastern Fouls Plains at 773 x 1430',NULL);
INSERT INTO `whereis` VALUES (150,'Notum Soldier','at Eastern Fouls Plains at 2000 x 2400',NULL);
INSERT INTO `whereis` VALUES (151,'Notum Trainee','at Eastern Fouls Plains at 2000 x 2400',NULL);
INSERT INTO `whereis` VALUES (152,'Notum Tree','at 2450 x 1300 in Avalon',NULL);
INSERT INTO `whereis` VALUES (153,'Nuts & Bolts','in Aegan, Wartorn Valley 790 x 680',NULL);
INSERT INTO `whereis` VALUES (154,'Obediency Inspector','at Eastern Fouls Plains, at the lake, near 1225 x 2800',NULL);
INSERT INTO `whereis` VALUES (155,'Ofoz','in Newland city to avoid the attention of the Unicorn forces. You can find him near the north city gate by the mission terminals.',NULL);
INSERT INTO `whereis` VALUES (156,'Omni Forest','in the southeast part of the world. No grid access or whompa. North of Omni Forest is Pleasant Meadows, northeast is Eastern Foul Plains, east us Southern Foul Plains. To the west is Omni Entertainment.','Omni Forrest ');
INSERT INTO `whereis` VALUES (157,'Omni-1 Entertainment','in the southeast part of the world. It has a grid access point at 879 x 579 and 582x337. Whompa in the north east of town at 890 x 671 lead to 20K. Whompas in south east at 900 x 470 lead to Omni-1 Trade and Rome Red.','Omni Entertainment, Omni Ent');
INSERT INTO `whereis` VALUES (158,'Omni-1 HQ','in the southeast part of the world. It has a grid access point at 602 x 468.','Hq Omni Hq');
INSERT INTO `whereis` VALUES (159,'Omni-1 Trade','in the southeast part of the world. It has a grid access point at 407 x 575. Whompas to ICC, Omni Entertainment, and Galway Castle at 370x380. Out the east gate is Omni1 HQ. Out the west gate is Lush Fields.','Omni Trade');
INSERT INTO `whereis` VALUES (160,'Oscar','at Greater Omni Forest',NULL);
INSERT INTO `whereis` VALUES (161,'Outpost 10-3','in Southern Artery Valley with whompas to Galway Castle, 2HO, and 20K at 1150 x  2340.','Outpost 10 3 Outpost 103');
INSERT INTO `whereis` VALUES (162,'Ownz','at Tir County Area, Crownhead Forrest at 2200 x 700',NULL);
INSERT INTO `whereis` VALUES (164,'Perpetual Wastelands','in the northeast part of the world. It has no grid access point and no whompa. To the west is Mort and there are currently no zones available to the east, north or south.','Perpetual Wasetlands Perpetual Waste Lands');
INSERT INTO `whereis` VALUES (165,'Pleasant Meadows (aka 20K)','in the southeast part of the world. It has a ferry grid to Harry''s at 360x1568, grid ferry to Omni Outpost in Lush Fields at 360 x 1565. Whompas at 1261 x 2300 to Outpost 10-3, OmniEntertainment, and 4HOles . North is Milky Way, south is Omni Forest, east is Eastern Foul Plains, west is Lush Fields.','20k Pleasant Fields Pleasent Meadows Pleasant Meadow Pleasent Meadow');
INSERT INTO `whereis` VALUES (166,'Polly','at Omni Forest Area, Swamp River Delta and Northern Drylands at 450 x 1280',NULL);
INSERT INTO `whereis` VALUES (167,'Powa','at Greater Tir County at 800 x 2400',NULL);
INSERT INTO `whereis` VALUES (168,'Professor Van Horn','at Newland Desert at 2900 x 1600',NULL);
INSERT INTO `whereis` VALUES (169,'Quintus Romulus','at Foremans Office',NULL);
INSERT INTO `whereis` VALUES (170,'R-2000 Vermin Disposal Unit','at Greater Tir County, Brainy Ant Woods at 800 x 1800','R 2000 Vermin Disposal Unit R2000 Vermin Disposal Unit');
INSERT INTO `whereis` VALUES (171,'Red','at 650 x 1450 in Aegean',NULL);
INSERT INTO `whereis` VALUES (172,'Reet Retreat','in Last Ditch in Stret West Bank at 1206 x 2807.  A club.','Leet Retreat Reet Retrat');
INSERT INTO `whereis` VALUES (173,'Rhino Cockpit','at 3140 x 1920 in Newland Desert. You can get there by going NE from Newland City, zone and continue NE once in Newland Desert. Rhino Cockpit has become a pretty popular site for L 25-35 groups','Rhino Pit');
INSERT INTO `whereis` VALUES (174,'Rhompa Bar','in Omni Entertainment at 714 x 698.','Rhompa Club');
INSERT INTO `whereis` VALUES (175,'Richelieu','at 1850 x 2550 in Southern Artery Valley',NULL);
INSERT INTO `whereis` VALUES (176,'Rising Sun','south of Wartorn Valley. It is a neighborhood in the south part of the Aegean zone.','Risingsun');
INSERT INTO `whereis` VALUES (177,'Robin Raag','at Smuggler''s Den, behind Ash at 21 x 217',NULL);
INSERT INTO `whereis` VALUES (178,'Rome Blue','lin the southwest part of the world. Out the west gates is Rome Red where the whompas are. Out the east gate is Galway Shire.','Omni Blue');
INSERT INTO `whereis` VALUES (179,'Rome Green','in the southwest part of the world. Out the east gate is Rome Red where the whompas are.  From SL there is a portal that is located very near some shops.','Romegreen');
INSERT INTO `whereis` VALUES (180,'Rome Red','in the southwest part of the world. It has a grid access point at 251 x 318. Whompas at 350x315 to Omni Entertainment, Galway Castle, and Broken Shores. Rome Blue is to the east and Rome Green is to the west.','Rome Red');
INSERT INTO `whereis` VALUES (181,'Ron McBain','at 750 x 1700 in Stret East Bank, at the 2HO Outpost',NULL);
INSERT INTO `whereis` VALUES (182,'Southern Artery Valley','in the mideastern part of the world. No grid access. Whompas to Galway Castle, 2HO, and 20K at 1150 x 2340. North of S.Artery Valley is Central Artery Valley, south is Milky Way (but a force field will not allow you to zone south), west is Stret East Bank and east is (ne) Deep Artery Valley (se) Belial Forest.',NULL);
INSERT INTO `whereis` VALUES (183,'South Fouls Hills','in the southeast corner of the world. No grid and no whompa.North of S.Fouls Hills is Eastern Foul Plains, west is Omni Forest, northwest is Pleasant Meadows. No zones avail to south or east.',NULL);
INSERT INTO `whereis` VALUES (184,'Sabulum','near 1050 x 2400 in Perpetual Wastelands.  It is a neutral town.',NULL);
INSERT INTO `whereis` VALUES (185,'Sally Tall','in a small pocket of 75% gas in Meetmedere at 1480 x 2760',NULL);
INSERT INTO `whereis` VALUES (186,'Sam Chin','located in Inquisitive Wasp, southeast of Tir City, at 2725 x 620. Deliver the supply crate from Genghis Pan in Tir.',NULL);
INSERT INTO `whereis` VALUES (297,'Sirocco','at 210 x 215 in Old Athen West.',NULL);
INSERT INTO `whereis` VALUES (188,'Smokey Willy','in the north western corner of Omni-Ent sewers, at 472 x 1043',NULL);
INSERT INTO `whereis` VALUES (189,'Smuggler''s Den','in the southeast corner of the world, in Southern Foul Hills at 1755 x 872.','Smuggler Den');
INSERT INTO `whereis` VALUES (190,'Qi Qiao Jie','in Borealis at 720 x 675. He sells valentines items.',NULL);
INSERT INTO `whereis` VALUES (191,'Stanley Adams','at 3850 x 1900 in Varmint Woods',NULL);
INSERT INTO `whereis` VALUES (192,'Steps Of Madness','in the southeast part of the world, in Omni Forest at 800 x 2800. Leave Omni Ent by the east gate to reach the dungeon. Recommended for teams of lvl 35-45.','Step Of Madness Madness Dungeon');
INSERT INTO `whereis` VALUES (193,'Stoltz Outpost','just across the Newland Desert zone line in Newland at 2172 x 1543. It has food machines only.',NULL);
INSERT INTO `whereis` VALUES (194,'Stret East Bank','in the mid-west part of the world. Grid access in 2HO at 667 x 1638, whompas at 783 x 1599 to Outpost 10-3 and 4 Holes. Ferry to 4 HOles at 820 x 1977. To the north of Stret East Bank is Upper Stret East Bank, to the northwest is Stret West Bank, to the northeast is Central Artery Valley, to the southwest is Andromeda, to the southeast is Milky Way, to the east is Southern Artery Valley and to the west is 4 Holes.','Stret Eastbank');
INSERT INTO `whereis` VALUES (195,'Stret West Bank','in the west central part of the world. It has a ferry to Stret East Bank at 1141 x 529 and whompa at 1279 x 2894 (in Last Ditch) to Borealis and to Hope. North is Aegean(ne) and Athen Shire(nw), south is 4HOles, east is Upper Stret East Bank, west is Borealis.','Stret Westbank');
INSERT INTO `whereis` VALUES (196,'Strike Foreman','at Subway Dungeon, usually on the bridge.',NULL);
INSERT INTO `whereis` VALUES (197,'Striking Ant Tir Outpost','northwest of Tir at 1915 x 1492. The outpost has mission terms, shops, banks and insure terms.',NULL);
INSERT INTO `whereis` VALUES (198,'Stumpy','at Greater Omni Forest at 2000 x 1300',NULL);
INSERT INTO `whereis` VALUES (199,'Supply Master Smug','at the northeast corner of Wailing Wastes at 2700 x 3500','Supplymaster Smug');
INSERT INTO `whereis` VALUES (200,'Susan Furor','at Poole/Galway County at 1219 x 1940 at AGT only',NULL);
INSERT INTO `whereis` VALUES (201,'Tarasque','at Avalon Dungeon, Avalon at 2092 x 3822',NULL);
INSERT INTO `whereis` VALUES (202,'Temple Of The Three Winds','out the Tir west gate and go north . There is a shortcut teleportal in the SE part of Rome Green near 420 x 240 (behind some red boxes). You must be L 60 or below to enter.','Totw');
INSERT INTO `whereis` VALUES (203,'The Broken Falls','at 1450 x 3100 in Broken Shores',NULL);
INSERT INTO `whereis` VALUES (204,'The Carbon Crystal','at 2600 x 2900 in Southern Artery Valley',NULL);
INSERT INTO `whereis` VALUES (205,'The Cup','in West Athen directly beside the grid access at 452 x 415.  A quiet little club, the Red Tigers hold their weekly meeting there every Sunday at 20:00 GMT.','thecup');
INSERT INTO `whereis` VALUES (206,'The Enigma House','at 1900 x 1400 in Central Artery Valley',NULL);
INSERT INTO `whereis` VALUES (207,'The Eremite Statue','at 1300 x 2300 in Deep Artery Valley',NULL);
INSERT INTO `whereis` VALUES (208,'The Fixer Grid','accessable from any grid post. You must first complete the Fixer quest, or get a L100+ fixer to help you get inside.',NULL);
INSERT INTO `whereis` VALUES (209,'The Fixer Shop','at 440 400 in Borealis zone. It looks like a pile of junk and you need 180 B&E to use it as well as being a fixer :)','Fixershop');
INSERT INTO `whereis` VALUES (210,'The Forestwatch Trees','at 1650 x 1650 in Southern Fouls Hills',NULL);
INSERT INTO `whereis` VALUES (211,'The Happy Rebel','at 550 x 550 in Tir City',NULL);
INSERT INTO `whereis` VALUES (212,'The Iron Reet','at Lush Hill Mutant Domain at 857 x 986',NULL);
INSERT INTO `whereis` VALUES (213,'The Longest Road','in the northwest part of the world. No grid access, has woompa access to Avalon, Athen Old, and Broken Shores at 3700 x 1615 in the town of Bliss. Athen Shire is to the east. No zones to the north, south, or west. There is a neutral outpost at 3650 x 560 with an ICC scanner and more. Biomare (dungeon) is located at 1930 x 775','Logest Road lLngest Raod');
INSERT INTO `whereis` VALUES (214,'The Obediency Enforcer','at Eastern Fouls Plains, at the lake, near 1225 x 2800','Obediency Inspector OE');
INSERT INTO `whereis` VALUES (215,'The One (Babyface)','at Southern Fouls Hills at 2250 x 1810',NULL);
INSERT INTO `whereis` VALUES (216,'The Pest','at Deep Artery Valley at 1360 x 2300',NULL);
INSERT INTO `whereis` VALUES (217,'The Satellite Dish','at 350 x 350 in Borealis',NULL);
INSERT INTO `whereis` VALUES (218,'The Trash King','in Athens Shire, west of Athens 1600 x 940','Trash King TK');
INSERT INTO `whereis` VALUES (260,'Weakened Chimera','at 1090 x 400, East of the Portal to Pen, around the +10 ring dungeon just inside Inf',NULL);
INSERT INTO `whereis` VALUES (220,'Tir County','in the northeast part of the world. Grid access and whompa in Tir City. To the north is Greater Tir County, south is Deep Artery Valley (but a force field blocks you from zoning south), west is Varmint Woods, southeast is Central Artery Valley, no zones avail to east.',NULL);
INSERT INTO `whereis` VALUES (221,'Tir','located in the north east part of the world. It has a grid access point at 555 x 527 and a whompas at 475 x 466 to Varmint Woods, ICC, and Athen. To the north, south, east and west of Tir is Tir County.',NULL);
INSERT INTO `whereis` VALUES (222,'Torrith The Ancient','at Greater Tir County at 400 x 2200',NULL);
INSERT INTO `whereis` VALUES (223,'Trash King Lackey','in Athens Shire, west of Athens 1600 x 940','Trashkinglackey');
INSERT INTO `whereis` VALUES (224,'Tri Plumbo','at Longest Road, The Foremans Office at 1940 x 775','Triplumbo');
INSERT INTO `whereis` VALUES (225,'Tribo Ratcatcher','at West Athen at 325 x 362 at (low lvl quest)','catcher rat ratcatcher tribo');
INSERT INTO `whereis` VALUES (226,'Tsunayoshi Smith','at 2600 x 2900 in Southern Artery Valley near the Largest Soul Fragment.','Melee Shop');
INSERT INTO `whereis` VALUES (227,'Twin Altars','at 400 x 2250 in Broken Shores',NULL);
INSERT INTO `whereis` VALUES (228,'Upper Stret East Bank','in the central part of the world. No grid access or whompa. To the north (w) of Upper Stret East Bank is Aegean and north (e) Varmint Woods, to the east is Central Artery Valley, to the west is Stret West Bank, southeast is 4Holes, south is Stret East Bank, se is S.Artery Valley.','Upper East Stret Bank Upperstreteastbank Upper Stret Eastbank');
INSERT INTO `whereis` VALUES (229,'Varmint Woods','in the southeast part of the world. No grid but there are woompa''s to Tir, Wine, and Wailing Wastes at 2484 x 2106. To the north of Varmnit Woods is Newland Desert, to the south is Central Artery Valley and Stret East bank, east is Greater Tir County, west is Aegean','Vermint Woods Varmint Wood Varmintwoods');
INSERT INTO `whereis` VALUES (230,'Vergil Aeneid','at Subway Dungeon',NULL);
INSERT INTO `whereis` VALUES (231,'Wailing Wastes','in the northwest part of the world. No grid access, but has whompas at 1370 x 1735 to Athens, Avalon, and Varmit Woods. To the north is Avalon, to the south is Athen Shire, no zones to east and west. Clan OP with scanner at 2430 x 3380','WW Waleing Wastes Waling Waste Wailingwastes');
INSERT INTO `whereis` VALUES (232,'Wartorn Valley','in the northeast part of the world. No grid or whompa. To the north, east and west of Wartorn Valley is Aegean, to the south is gate to Athen Old.','Warton Valley Wartornvalley');
INSERT INTO `whereis` VALUES (233,'Will To Fight','in Stret West Bank, east of Reet Retreet, at 2245 x 3124. You must be L75 or above to enter.','Pvp Dungeon');
INSERT INTO `whereis` VALUES (234,'Wine','in Belial Forest (east side of the world) with whompas to Broken Shores and Varmint Woods at 2150 x 2319.  A clan town.',NULL);
INSERT INTO `whereis` VALUES (236,'Zibell The Wanderer','in the Area: The great bulk, in Central Artery Valley near 3432 x 2649',NULL);
INSERT INTO `whereis` VALUES (237,'Zoftig Blimp','in the City of Hope in Mort.',NULL);
INSERT INTO `whereis` VALUES (238,'A Face In The Sand','at 1400 x 2750 in Aegean',NULL);
INSERT INTO `whereis` VALUES (240,'Belial Forest','in the southeast part of the world. No grid access. Whompas in Wine lead to Broken Shores and Varmint Woods at 2150 x 2319. To the north of Belial Forest is Deep Artery Valley, south is Eastern Foul Plains, west is S.Artery Valley and Milky Way is south and southwest. No zone to east.','Belial Forrest Belialforest');
INSERT INTO `whereis` VALUES (241,'Camelot','in the northwest part of the world, in the center of the city of Avalon and can be reached by whompa from Old Athens or Wailing Wastes.',NULL);
INSERT INTO `whereis` VALUES (242,'Central Artery Valley','in the mideastern part of the world. No grid or whompa. North of Central Artery Valley is Varmint Woods, south is Southern Artery Valley, east is Deep Artery Valley, west is Upper Stret East Bank. NE corner is Greater Tir Cnty and SW corner is Stret East Bank.','Cav Base Central Art Valley Centralarteryvalley');
INSERT INTO `whereis` VALUES (243,'Clondyke','in the southwest part of the world. It has a grid access point at 1054 x 4023, no whompa. North of Clondyke is Andromeda, west is Galway County, east is Lush Fields. No zone avail to the south.','Clondike Coldyke Condyke Klondyke');
INSERT INTO `whereis` VALUES (244,'Daria','at Lush Fields at 1782 x 2062',NULL);
INSERT INTO `whereis` VALUES (245,'Deep Artery Valley','in the mideastern part of the world. No grid and no whompa. To the north of Deep Artery Valley is Greater Tir County (but a force field blocks you from zoning north), south is Belial Forest, west is Central Artery Valley and Southern Artery Valley, no zone to east.','Deeparteryvalley');
INSERT INTO `whereis` VALUES (246,'Eastern Fouls Plain','in the southeast part of the world. No grid or whompa. North of E.Fouls Plain is Belial Forest (but a force field keeps you from zoning north), south is Southern Fouls Hills, north west is Milky Way, southwest is Pleasant Meadow. No zone avail to the east.','East Foul Plains Easternfoulsplain Efp');
INSERT INTO `whereis` VALUES (247,'Fiery Soldier','at Eastern Fouls Plains at 365 x 2060',NULL);
INSERT INTO `whereis` VALUES (248,'Galway County','in the southwest part of the world. It has a grid access point at 1416 x 1091 and whompas at 2530 x 1175 to Outpost 10-3, Omni-1 Trade, and Rome . West is Galway Shire, east is Clondyke, no zones avail to north and south.','Galaway County Galway Country Galwaycounty');
INSERT INTO `whereis` VALUES (250,'Galway Shire','in the southwest part of the world. No grid access or whompa. East is Galway County, west is Broken Shores, no zones avail to north and south. Rome is located midway in Galway Shire on far west side.','Galaway Shire Galwayshire');
INSERT INTO `whereis` VALUES (251,'Greater Tir County','in the northeast part of the world. Grid access in Tir City at 555 x 527 and a whompa in Tir City at 475 x 466 to Newland City. To the south of Greater Tir County is Tir County, west is Varmint Woods, no zones avail to north or east.','Greatertircounty');
INSERT INTO `whereis` VALUES (261,'Feral Vortexoid Striker','at 615 x 765 in Burning Marshes SW of Sorrow',NULL);
INSERT INTO `whereis` VALUES (252,'One Who Asks The Unasked','in the Valley of the Dead area of Inferno under a tent. 1195 x 755.',NULL);
INSERT INTO `whereis` VALUES (253,'One Who Talks With The Past','in the Valley of the Dead area of Inferno under a tent. 1195 x 755.',NULL);
INSERT INTO `whereis` VALUES (254,'Guardian Of Dissent','North East of Dark Marshes around 2065 x 890, has low spawn rate and drop rate, and spawns in multiple locations.',NULL);
INSERT INTO `whereis` VALUES (255,'Somphos Argef','North West of Dark Marshes and spawns around a large rock at 1770 x 900',NULL);
INSERT INTO `whereis` VALUES (256,'Somphos Argeele','North West of Dark Marshes and spawns around a large rock at 1770 x 900',NULL);
INSERT INTO `whereis` VALUES (257,'Somphos Sorlivet','North West of Dark Marshes and spawns around a large rock at 1770 x 900 (Spawns on the East Side of the rock)',NULL);
INSERT INTO `whereis` VALUES (258,'Brimstone Demon','East-North-East of Sorrow and spawns around 1650 x 1625 among the other demons.  Sometimes it''s bugged and spawns inside the nearby mountain, petition to get them killed/moved out.',NULL);
INSERT INTO `whereis` VALUES (259,'Scalding Weaver','in Sorrow Pass (the chasm near sorrow) and spawns around 1450 x 1425, this has a very large spawn area so look all around for them as well including outside the pass',NULL);
INSERT INTO `whereis` VALUES (263,'Ember Chimera','at 757 x 870 burning marshes SW of Sorrow',NULL);
INSERT INTO `whereis` VALUES (264,'Coal Lizard','at 1635 x 1110 Misty Marshes NW from Dark Marshes',NULL);
INSERT INTO `whereis` VALUES (265,'Anansi Speaker','at 890 x 1350, North West from the Petrified Hecklers',NULL);
INSERT INTO `whereis` VALUES (266,'Anansi Storyteller','at 890 x 1350, North West from the Petrified Hecklers',NULL);
INSERT INTO `whereis` VALUES (267,'Anansi Orator','at 890 x 1350, North West from the Petrified Hecklers',NULL);
INSERT INTO `whereis` VALUES (268,'Smoldering Shadow','near the petrified hecklers near Sorrow, around 1081.5, 1160.6 and can also be find north of there around 759.9 x 1436.8',NULL);
INSERT INTO `whereis` VALUES (269,'Feral Vortexoid Soother','at 615 x 765 in Burning Marshes SW of Sorrow',NULL);
INSERT INTO `whereis` VALUES (270,'Feral Vortexoid Mindbreaker','at 615 x 765 in Burning Marshes SW of Sorrow',NULL);
INSERT INTO `whereis` VALUES (271,'Smoky Salamander Is One Of Many Spots In Burning Marshes','at 1650 x 1260',NULL);
INSERT INTO `whereis` VALUES (272,'Circle G City Controller','at 2212 x 2290 in the Boondock area of Stret West Bank. City 3A on CSP Map. Points of ref : South-East of Stret West Bank Whompa exit South-East of Fixer Grid exit 3-R  South-East of Reets Retreat (in Stret West Bank)',NULL);
INSERT INTO `whereis` VALUES (273,'Crashbot','crashed. Duh.',NULL);
INSERT INTO `whereis` VALUES (274,'Stretchicus2','in reclaim',NULL);
INSERT INTO `whereis` VALUES (275,'Krichale','in reclaim',NULL);
INSERT INTO `whereis` VALUES (276,'Geosurvey','stuck in the ICC Shuttleport.',NULL);
INSERT INTO `whereis` VALUES (278,'Stringtheory','at the claw camp kiting.','NT');
INSERT INTO `whereis` VALUES (280,'Herbalist Geralt','in the Rhinoman Villige in Newland Desert. 2815 x 1680','AI Quest Social Clothing');
INSERT INTO `whereis` VALUES (282,'Mary-Ann','at 1144 x 388 in Newland','AI Quest Social Clothing Thermo Vest combined armor');
INSERT INTO `whereis` VALUES (283,'Simon Stark','at 1155 x 1747 in Newland Desert.','AI Quest Social Clothing Antiseptic Protector Combined Armor');
INSERT INTO `whereis` VALUES (284,'Gilbert Glove','at 3110 x 550 in Newland Desert.','AI Quest Social Clothing Cybernetic Fingertips Combined Armor');
INSERT INTO `whereis` VALUES (285,'Scientist Maud Stevens','at 360 x 405 In Borealis (up by the Radar Dish).','AI Quest Social Clothing combined armor');
INSERT INTO `whereis` VALUES (286,'Misa Ramirez','in the Neuts r'' us club in Newland City.','AI Quest Social Clothing Combined Armor');
INSERT INTO `whereis` VALUES (287,'Fritz','in the Neuts r'' us club in Newland City.','AI Quest Social Clothing Hair Care Contraption Combined Armor');
INSERT INTO `whereis` VALUES (288,'Imelda Dane','in the Neuts r'' us club in Newland City.','AI Quest Social Clothing Combined Armor');
INSERT INTO `whereis` VALUES (289,'Ethel Anthony','near the Newland Desert Whompah.','AI Quest Social Clothing Combined Armor');
INSERT INTO `whereis` VALUES (290,'Uncle Bazzit','in his workshop at Meetmedere. 1545 x 2725 in Newland Desert (Meetmedere grid exit).','AI Quest Social Clothing');
INSERT INTO `whereis` VALUES (291,'Deidre Lux','at 1260 x 2845 in the East Last Ditch area of Stret West Bank.','Bazzit''s Alien Library Hacker Tool Vanguard Node Access Card');
INSERT INTO `whereis` VALUES (292,'Ramon Bauer','at 500 x 565 in Old Athen.','Bazzit''s Alien Library Linked Hacker Tool Vanguard Node Access Card Kyr''Ozch Structural Analyzer');
INSERT INTO `whereis` VALUES (293,'Commander Kend Ash','at 415 x 405 in Omni-1 Trade.','Bazzit''s Alien Library Linked Hacker Tool Vanguard Node Access Card Kyr''Ozch Structural Analyzer');
INSERT INTO `whereis` VALUES (294,'Cyborg Lieutenant Colonel','around 1400 x 530 in Mort. (Can be found wandering at the Ruins on Mort Crater, use the Sentinals grid exit).',NULL);
INSERT INTO `whereis` VALUES (295,'Cyborg Brigadier General','around 1400 x 530 in Mort. (Can be found wandering at the Ruins on Mort Crater, use the Sentinals grid exit).',NULL);
INSERT INTO `whereis` VALUES (296,'Prototype Inferno','inside the Cyborg Barracks in Greater Tir County.',NULL);
INSERT INTO `whereis` VALUES (299,'Investigator Marciello','at 1590 x 2820 in Newland Desert, near the Meetmedere grid.','AI Quest Social Clothing Combined Armor Body Heat Pattern Analyzer.');
INSERT INTO `whereis` VALUES (300,'Pietro Molla','at 535 x 345 in Aegan.','Quest Wedding Ring Omni-Tek Trash Can');
INSERT INTO `whereis` VALUES (301,'Gianna Molla/Perugino','at 1285 x 2980 in East Last Ditch area of Stret WEst Bank.','Quest Wedding Ring Omni-Tek Trash Can ');
INSERT INTO `whereis` VALUES (302,'Penelopez Magistrale','at 790 x 2310 in Newland Desert. Multi-grip Soles AI Quest Social Clothing','AI Quest Social Clothing Combined Armor Multi-grip Soles');
INSERT INTO `whereis` VALUES (303,'Doctor Krank','at 2965 x 1315 in Centeral Artery Valley','Dr Krank Dr Crank Drcrank');
INSERT INTO `whereis` VALUES (304,'Master Divenchy','located in Newland at 900 x 860, near the crash site north of the lake.','AI Quest Social Clothing Combined Armor');
INSERT INTO `whereis` VALUES (305,'Leona','at the Bronto Burger in Newland.','Doll Rotten Peter Bacchante''s Fancy Yellow Hanging Lanterns Yellow Lanterns');
INSERT INTO `whereis` VALUES (306,'Donna Red','at 985 x 1760 in Nascense.','Quest Clan Garden Key Alban Redeemed');
INSERT INTO `whereis` VALUES (307,'Ecclesiast Abal Fal','at 1890 x 690 in Nascense.','Quest Clan Garden Key Alban Redeemed');
INSERT INTO `whereis` VALUES (308,'Sipius Aban Lux-Wel','at 465 x 495 in the Garden of Alban in Nascense.','Quest Clan Garden Key Alban Redeemed');
INSERT INTO `whereis` VALUES (309,'FunCom','in Oslo, Norway.',NULL);
INSERT INTO `whereis` VALUES (310,'Click','at http://home.no.net/octos/click.htm','50000 ammo Octo OMG! IT''S TEH CLICK!');
INSERT INTO `whereis` VALUES (313,'Sentinels City','at 540 x 1175 in Stret East Bank. Grid to 2ho and fly south to the island city. (City Site 6 on CSP Map)',NULL);
INSERT INTO `whereis` VALUES (312,'CSPmap','at http://creativestudent.com/ao/','csp map creative studen productions');
INSERT INTO `whereis` VALUES (316,'Anansi''s Left Hand','South West of Oasis, East of Sorrow in Inferno at 1915 x 1745. Calmer reccomended.',NULL);
INSERT INTO `whereis` VALUES (317,'The City For Defenders Of Sol =DoS=','at 650 x 1120 in Galway Shire. (1c on CSP Map) NE of the Junk Yard.',NULL);
INSERT INTO `whereis` VALUES (321,'Inferno Unredeemed Garden Access: Inferno Barracks Lord Mordeth Statue','at 3021 x 975 in Inferno.','Lord Mordeth Statue Garden of Unredeemed Inferno Access Barracks');
INSERT INTO `whereis` VALUES (322,'Inferno Unredeemed Garden Access: Unredeemed Yutto Marshes Lord Mordeth Statue','at 2555 x 1165 in Inferno.','Lord Mordeth Statue Garden of Unredeemed Inferno Access Barracks');
INSERT INTO `whereis` VALUES (323,'Inferno Redeemed Garden Access: Yutto Marshes Lord Galahad Statue','at 2625 x 1190 in Inferno.','Redeemed Lord Galahad Statue Garden of');
INSERT INTO `whereis` VALUES (324,'Inferno Unredeemed Garden Access: Dark Marshes Lord Mordeth Statue','at 2050 x 715 in Inferno.','Lord Mordeth Statue Garden of Unredeemed Inferno Access');
INSERT INTO `whereis` VALUES (325,'Inferno Unredeemed Sanctuary Access: Xark''s Lair','at 3135 x 1895 in Inferno.','Lord Mordeth''s Sanctuary Statue Unredeemed Inferno');
INSERT INTO `whereis` VALUES (326,'Inferno Unredeemed Sanctuary Access: Sorrow Outlook','at 1385 x 1525 in Inferno.','Lord Mordeth''s Sanctuary Statue Unredeemed Inferno');
INSERT INTO `whereis` VALUES (327,'Inferno Unredeemed Sanctuary Access: Oasis','at 2120 x 1990 in Inferno.','Lord Mordeth''s Sanctuary Statue Unredeemed Inferno');
INSERT INTO `whereis` VALUES (328,'Black','in Adonis, Abyss 1644 x 2237 N',NULL);
INSERT INTO `whereis` VALUES (329,'Cantankerous Golem','in Adonis, 2401 x 712 SE and 784 x 892 SW',NULL);
INSERT INTO `whereis` VALUES (330,'Corrupt Spirit','in Adonis, 1524 x 464 S and 1941 x 2241 N',NULL);
INSERT INTO `whereis` VALUES (331,'Crabby Golem','in Adonis, 2334 x 559 SE and 783 x 1012 SW',NULL);
INSERT INTO `whereis` VALUES (332,'Cranky Golem','in Adonis, 2402 x 638 SE and 849 x 1177 SW',NULL);
INSERT INTO `whereis` VALUES (333,'Delinquent Spirit','in Adonis, 1579 x 433 S',NULL);
INSERT INTO `whereis` VALUES (334,'Irascible Golem','in Adonis, 2315 x 665 SE and 865 x 1310 SW',NULL);
INSERT INTO `whereis` VALUES (335,'Jukes','in Adonis, Abyss walking around near other Dryads',NULL);
INSERT INTO `whereis` VALUES (336,'Lurking Dryad','in Adonis, 1232 x 2798 NW',NULL);
INSERT INTO `whereis` VALUES (337,'Mooching Dryad','in Adonis, 986 x 2573 NW',NULL);
INSERT INTO `whereis` VALUES (338,'Mull','in Adonis, Abyss walking around near other Dryads',NULL);
INSERT INTO `whereis` VALUES (339,'Peristaltic Abomination','in Adonis Abyss East & West',NULL);
INSERT INTO `whereis` VALUES (340,'Peristaltic Aversion','in Adonis Abyss East & West',NULL);
INSERT INTO `whereis` VALUES (341,'Scratching Soul Dredge','in Adonis, 2666 x 2562 NE',NULL);
INSERT INTO `whereis` VALUES (342,'Sinful Soul Dredge','in Adonis, 1581 x 595 S and 1741 x 2198 N',NULL);
INSERT INTO `whereis` VALUES (343,'Skulking Dryad','in Adonis, 1113 x 2639 NW',NULL);
INSERT INTO `whereis` VALUES (344,'Skylight','in Adonis, Abyss 1600 x 2075 N',NULL);
INSERT INTO `whereis` VALUES (345,'Slinking Dryad','in Adonis, West and NW Island',NULL);
INSERT INTO `whereis` VALUES (346,'Snatching Soul Dredge','in Adonis, Dead Ends Ark',NULL);
INSERT INTO `whereis` VALUES (347,'Stark','in Adonis, Abyss 1701 x 2321 N',NULL);
INSERT INTO `whereis` VALUES (348,'Turk','in Adonis, Abyss 1755 x 2184 N',NULL);
INSERT INTO `whereis` VALUES (349,'Cold Slither','in Adonis, Abyss 1560 x 3375 N',NULL);
INSERT INTO `whereis` VALUES (350,'Algid Slither','in Adonis, Abyss 1510 x 3320 N',NULL);
INSERT INTO `whereis` VALUES (351,'Nippy Slither','in Adonis, Abyss 1375 x 3472 N',NULL);
INSERT INTO `whereis` VALUES (352,'Brumal Slither','in Adonis, Abyss 1440 x 3414 N',NULL);
INSERT INTO `whereis` VALUES (353,'Stealing Dryad','in Adonis, 920 x 2437 NW',NULL);
INSERT INTO `whereis` VALUES (354,'Iniquitous Spirit','in Adonis, 1624 x 499 S',NULL);
INSERT INTO `whereis` VALUES (355,'Iced Slither','in Adonis, Abyss 1398 x 3470 N',NULL);
INSERT INTO `whereis` VALUES (356,'Chilly Slither','in Adonis, Abyss 1465 x 3373 N',NULL);
INSERT INTO `whereis` VALUES (357,'Snaking Dryad','in Adonis, 868 x 2503  NW',NULL);
INSERT INTO `whereis` VALUES (358,'Vile Spirit','in Adonis, 1541 x 500 S and 1751 x 2244 N',NULL);
INSERT INTO `whereis` VALUES (359,'Gashing Soul Dredge','in Adonis, 2899 x 2580 NE',NULL);
INSERT INTO `whereis` VALUES (360,'Tearing Soul Dredge','in Adonis, 2763 x 2638 NE',NULL);
INSERT INTO `whereis` VALUES (361,'Wicked Soul Dredge','in Adonis, 1530 x 547 NE',NULL);
INSERT INTO `whereis` VALUES (362,'Tiny','in Adonis, Abyss 1691 x 1504',NULL);
INSERT INTO `whereis` VALUES (363,'Trup','in Adonis, Abyss 1729 x 1535',NULL);
INSERT INTO `whereis` VALUES (364,'Trap','in Adonis, Abyss 1718 x 1460',NULL);
INSERT INTO `whereis` VALUES (365,'Trip','in Adonis, Abyss 1766 x 1489',NULL);
INSERT INTO `whereis` VALUES (366,'Afreet Ellis','in Inferno, NE of Frontier Garden',NULL);
INSERT INTO `whereis` VALUES (367,'Akshki','in Inferno, South of Frontier',NULL);
INSERT INTO `whereis` VALUES (368,'Alpha Skincrawler','in Crypt of Home, Broken Shores',NULL);
INSERT INTO `whereis` VALUES (370,'Anansis Right Hand','in Inferno, East of Sorrow',NULL);
INSERT INTO `whereis` VALUES (371,'Anasis Abettor','in Inferno, Far SW of Sorrow',NULL);
INSERT INTO `whereis` VALUES (372,'Anansis Favorite','in Inferno, just NE of Frontier',NULL);
INSERT INTO `whereis` VALUES (373,'Aniitaps Shadow','in Inferno, North of Frontier',NULL);
INSERT INTO `whereis` VALUES (374,'Apprentice Beasthandler','in Inferno, 255 Incarnator',NULL);
INSERT INTO `whereis` VALUES (375,'Aquarius','in Pandemonium, East Node',NULL);
INSERT INTO `whereis` VALUES (376,'Aries','in Pandemonium, West Node',NULL);
INSERT INTO `whereis` VALUES (377,'Asperous Imp','in Elysium, Near Ergo',NULL);
INSERT INTO `whereis` VALUES (378,'Astypalia','in Inferno, West of Razors Lair',NULL);
INSERT INTO `whereis` VALUES (379,'Atakirh','in Inferno, South of Frontier',NULL);
INSERT INTO `whereis` VALUES (380,'Athlar','in Elysium, inside mountains SW and NW',NULL);
INSERT INTO `whereis` VALUES (381,'Bane','in Crypt of Home, Broken Shores',NULL);
INSERT INTO `whereis` VALUES (382,'Bending Eremite','in Elysium, Sand dunes near Cold Rock',NULL);
INSERT INTO `whereis` VALUES (383,'Bigot','in Inferno, SW of Sorrow, N of Sorrow, 255 Inc',NULL);
INSERT INTO `whereis` VALUES (384,'Brutish Dryad','in Elysium by Omni Shunpike exit 699 x 914 and 735 x 956, Utopolis and South Elysium',NULL);
INSERT INTO `whereis` VALUES (385,'Cacophonous Imp','in Elysium, Near Ergo',NULL);
INSERT INTO `whereis` VALUES (386,'Cancer','in Pandemonium, East Node',NULL);
INSERT INTO `whereis` VALUES (387,'Capricorn','in Pandemonium, North Node',NULL);
INSERT INTO `whereis` VALUES (388,'Catervauling Minx','in Elysium, Near Ergo & Fallen Forest',NULL);
INSERT INTO `whereis` VALUES (389,'Cenobite Shadow','in Crypt of Home, Broken Shores',NULL);
INSERT INTO `whereis` VALUES (390,'Cerubin The Rejected','in Crypt of Home, Broken Shores',NULL);
INSERT INTO `whereis` VALUES (391,'Chimera Monitor','in Inferno, West of Dark Marshes Unred Temple',NULL);
INSERT INTO `whereis` VALUES (392,'Chimera Trainer','in Inferno, West of Dark Marshes Unred Temple',NULL);
INSERT INTO `whereis` VALUES (393,'Clan Modified A-4001','in Wailing Wastes',NULL);
INSERT INTO `whereis` VALUES (394,'Coiling Eremite','in Elysium, Sand dunes near Cold Rock',NULL);
INSERT INTO `whereis` VALUES (395,'Comatosed Soul','in Elysium, E Whispervale and 115 Inc',NULL);
INSERT INTO `whereis` VALUES (396,'Conflagrant Spirit','in Inferno, NW of Yuttos',NULL);
INSERT INTO `whereis` VALUES (397,'Creepy Spider','in Inferno, N of 255 Incarnator',NULL);
INSERT INTO `whereis` VALUES (398,'Crete','in Inferno, 255 Incarnator',NULL);
INSERT INTO `whereis` VALUES (399,'Daria Marie Walzer','at 1782 x 2062, Lush Fields',NULL);
INSERT INTO `whereis` VALUES (400,'Daring Dryad','in Penumbra, South of W Pipe Entrance',NULL);
INSERT INTO `whereis` VALUES (401,'Dauntless Dryad','in Penumbra, South of W Pipe Entrance',NULL);
INSERT INTO `whereis` VALUES (402,'Devoted Spirit Hunter','in Inferno, West of Sorrow',NULL);
INSERT INTO `whereis` VALUES (403,'Diamondine Soldier','at 1925 x 1450, Eastern Fouls Plains.',NULL);
INSERT INTO `whereis` VALUES (404,'Diamondine Trainee','at 1925 x 1450, Eastern Fouls Plains',NULL);
INSERT INTO `whereis` VALUES (405,'Disturbing Imp','in Elysium, Near Ergo',NULL);
INSERT INTO `whereis` VALUES (406,'Enkindled Spirit','in Inferno, NW of Yuttos',NULL);
INSERT INTO `whereis` VALUES (407,'Fanatic Spirit Hunter','in Inferno, North of Sorrow',NULL);
INSERT INTO `whereis` VALUES (408,'Fearless Dryad','in Penumbra, South of W Pipe Entrance',NULL);
INSERT INTO `whereis` VALUES (409,'Forefather','in Smuggler''s Den, 1755 x 872, SFH.',NULL);
INSERT INTO `whereis` VALUES (410,'Gemini','in Pandemonium, East Node',NULL);
INSERT INTO `whereis` VALUES (411,'General Kaehler Jr','in Avalon, Secondary Base',NULL);
INSERT INTO `whereis` VALUES (412,'General Kronilis','in 2000 x 2500, Perpetual Wastelands',NULL);
INSERT INTO `whereis` VALUES (413,'General Nirtox','in Perpetual Wastelands',NULL);
INSERT INTO `whereis` VALUES (414,'General Vivyan','at 2120 x 1760, Perpetual Wastelands',NULL);
INSERT INTO `whereis` VALUES (415,'Hawqana','in Inferno, 225 Incarnator',NULL);
INSERT INTO `whereis` VALUES (416,'High Commander Frederickson','in Wailing Wastes',NULL);
INSERT INTO `whereis` VALUES (417,'Howling Minx','in Elysium, Near Ergo & Fallen Forest',NULL);
INSERT INTO `whereis` VALUES (418,'Howling Predator','in Elysium, South of Remnans',NULL);
INSERT INTO `whereis` VALUES (419,'Incandescent Spirit','in Inferno, NW of Yuttos',NULL);
INSERT INTO `whereis` VALUES (420,'Iron Reet','at 857 x 986, Mutant Domain',NULL);
INSERT INTO `whereis` VALUES (421,'Isham','in Inferno, South of Frontier',NULL);
INSERT INTO `whereis` VALUES (422,'Ishimkimk','in Inferno, 225 Incarnator',NULL);
INSERT INTO `whereis` VALUES (423,'Ithaki','in Inferno, 255 Incarnator',NULL);
INSERT INTO `whereis` VALUES (424,'Leo','in Pandemonium, West Node',NULL);
INSERT INTO `whereis` VALUES (425,'Libra','in Pandemonium, Middle Node',NULL);
INSERT INTO `whereis` VALUES (426,'Limber Dryad','in Elysium, Utopolis and South Elysium',NULL);
INSERT INTO `whereis` VALUES (427,'Limnos','in Inferno, 255 Incarnator',NULL);
INSERT INTO `whereis` VALUES (428,'Limping Predator','in Elysium, South of Remnans',NULL);
INSERT INTO `whereis` VALUES (429,'Ljotur The Lunatic','in 1103 x 722, Drill Island, DAV',NULL);
INSERT INTO `whereis` VALUES (430,'Lord Of The Void','in Inferno, E of Frontier, W of Frontier. Nasc Wilds',NULL);
INSERT INTO `whereis` VALUES (431,'Lost Soul','in Elysium, E Whispervale and 115 Inc',NULL);
INSERT INTO `whereis` VALUES (432,'Marcus Robicheaux','in 1500 x 2900, Broken Shores',NULL);
INSERT INTO `whereis` VALUES (433,'Maychwaham','in Inferno, South of Frontier',NULL);
INSERT INTO `whereis` VALUES (435,'Omni-Pol Command Juggernaut','at Primary Base, Avalon. E-W Road Mutant Domain',NULL);
INSERT INTO `whereis` VALUES (436,'Ossuz','in Elysium, inside mountains SW and NW',NULL);
INSERT INTO `whereis` VALUES (437,'Pained Predator','in Elysium, South of Remnans',NULL);
INSERT INTO `whereis` VALUES (438,'Patricia Johnson','at 720 x 1380, Ace Camp, Eastern Fouls Plains',NULL);
INSERT INTO `whereis` VALUES (439,'Peter Lee','at 720 x 1380, Ace Camp, Eastern Fouls Plains',NULL);
INSERT INTO `whereis` VALUES (440,'Phatmos','in Inferno, West of Razors Lair',NULL);
INSERT INTO `whereis` VALUES (441,'Pisces','in Pandemonium, Middle Node',NULL);
INSERT INTO `whereis` VALUES (442,'Pit Demon','in Crypt of Home, Broken Shores',NULL);
INSERT INTO `whereis` VALUES (443,'Polymorphed Lunatic','at 1103 x 722, Drill Island, DAV',NULL);
INSERT INTO `whereis` VALUES (444,'Punctilious Hiathlin','in Inferno, 255 Incarnator',NULL);
INSERT INTO `whereis` VALUES (445,'Putrid Eremite','in Inferno, 225 Incarnator',NULL);
INSERT INTO `whereis` VALUES (446,'Ris Lee','at 720 x 1380, Ace Camp, Eastern Fouls Plains',NULL);
INSERT INTO `whereis` VALUES (447,'Rotting Eremite','in Inferno, 225 Incarnator',NULL);
INSERT INTO `whereis` VALUES (448,'Sadistic Soul Dredge','in Elysium, E Whispervale and 115 Inc',NULL);
INSERT INTO `whereis` VALUES (449,'Sagittarius','in Pandemonium, North Node',NULL);
INSERT INTO `whereis` VALUES (450,'Salahpt','in Inferno, South of Frontier',NULL);
INSERT INTO `whereis` VALUES (451,'Scary Spider','in Inferno, SE of 255 Incarnator',NULL);
INSERT INTO `whereis` VALUES (452,'Scorpio','in Pandemonium, North Node',NULL);
INSERT INTO `whereis` VALUES (453,'Screeching Imp','in Elysium, Near Ergo',NULL);
INSERT INTO `whereis` VALUES (454,'Scrupulous Hiathlin','in Inferno, 255 Incarnator',NULL);
INSERT INTO `whereis` VALUES (455,'Special Agent Lamb','at DAV',NULL);
INSERT INTO `whereis` VALUES (456,'Spetses','in Inferno, 255 Incarnator',NULL);
INSERT INTO `whereis` VALUES (457,'Splintered Girder','in Elysium, West wall of Central Ely',NULL);
INSERT INTO `whereis` VALUES (458,'Steele Filar','in Inferno, NE of Frontier',NULL);
INSERT INTO `whereis` VALUES (459,'Swirling Eremite','in Elysium, Sand dunes near Cold Rock',NULL);
INSERT INTO `whereis` VALUES (460,'T.I.M.','in Foremans, 2000 x 800, TLR',NULL);
INSERT INTO `whereis` VALUES (461,'Taurus','in Pandemonium, Middle Node',NULL);
INSERT INTO `whereis` VALUES (462,'Tdecin','in Elysium, inside mountains SW and NW',NULL);
INSERT INTO `whereis` VALUES (463,'The Beast','in Pandemonium',NULL);
INSERT INTO `whereis` VALUES (464,'The Nightheart','in Pandemonium',NULL);
INSERT INTO `whereis` VALUES (465,'Tinos','in Inferno, West of Razors Lair',NULL);
INSERT INTO `whereis` VALUES (466,'Tiunissik','in Inferno, North of Sorrow',NULL);
INSERT INTO `whereis` VALUES (467,'Torrid Spirit','in Inferno, North of Sorrow',NULL);
INSERT INTO `whereis` VALUES (469,'Tuqusk','in Inferno, South of Frontier',NULL);
INSERT INTO `whereis` VALUES (470,'Tyro Beasthandler','in Inferno, 255 Incarnator',NULL);
INSERT INTO `whereis` VALUES (471,'Ushamaham','in Inferno, South of Frontier',NULL);
INSERT INTO `whereis` VALUES (472,'Virgo','in Pandemonium, West Node',NULL);
INSERT INTO `whereis` VALUES (473,'Waning Soul','in Elysium, E Whispervale and 115 Inc',NULL);
INSERT INTO `whereis` VALUES (474,'Wounded Predator','in Elysium, South of Remnans',NULL);
INSERT INTO `whereis` VALUES (475,'Zias','in Elysium, inside mountains SW and NW',NULL);
INSERT INTO `whereis` VALUES (476,'Xark the Battletoad','in Inferno, Xarks Lair, NE of Yuttos',NULL);
INSERT INTO `whereis` VALUES (477,'Inobak the Gelid','in Inner Sanctum, 3rd Floor',NULL);
INSERT INTO `whereis` VALUES (478,'Hezak The Immortal','in Inner Sanctum, 3rd Floor',NULL);
INSERT INTO `whereis` VALUES (479,'Dominus Facut the Bloodless','in Inner Sanctum, 3rd Floor',NULL);
INSERT INTO `whereis` VALUES (480,'Dominus Ummoh the Pedagogue','in Inner Sanctum, 3rd Floor',NULL);
INSERT INTO `whereis` VALUES (481,'Dominus Jiannu','in Inner Sanctum, 3rd Floor',NULL);
INSERT INTO `whereis` VALUES (482,'Iskop the Idolator','in Inner Sanctum, 3rd Floor',NULL);
INSERT INTO `whereis` VALUES (483,'Jeuru the Defiler','in Inner Sanctum, 3rd Floor',NULL);
INSERT INTO `whereis` VALUES (484,'Numiel','in Inferno, Fronter',NULL);
INSERT INTO `whereis` VALUES (485,'Asanon','in Inferno, Fronter',NULL);
INSERT INTO `whereis` VALUES (486,'Ahomac','in Inferno, Fronter',NULL);
INSERT INTO `whereis` VALUES (487,'Hebial','in Inferno, Fronter',NULL);
INSERT INTO `whereis` VALUES (488,'Primus Scrap Pillager','at Primus Camp (EFP)',NULL);
INSERT INTO `whereis` VALUES (489,'Primus Outlaw','at Primus Camp(EFP)',NULL);
INSERT INTO `whereis` VALUES (490,'Distracted Snake Tamer','in Inferno, 225 Incarnator',NULL);
INSERT INTO `whereis` VALUES (491,'First Brood Champion','at Hollow Island',NULL);
INSERT INTO `whereis` VALUES (492,'Second Brood Champion','at Hollow Island',NULL);
INSERT INTO `whereis` VALUES (493,'Third Brood Champion','at Hollow Island',NULL);
INSERT INTO `whereis` VALUES (494,'Fourth Brood Champion','at Hollow Island',NULL);
INSERT INTO `whereis` VALUES (495,'Fifth Brood Champion','at Hollow Island',NULL);
INSERT INTO `whereis` VALUES (496,'Sixth Brood Champion','at Hollow Island',NULL);
INSERT INTO `whereis` VALUES (497,'Seventh Brood Champion','at Hollow Island',NULL);
INSERT INTO `whereis` VALUES (498,'Eighth Brood Champion','at Hollow Island',NULL);
INSERT INTO `whereis` VALUES (499,'Ninth Brood Champion','at Hollow Island',NULL);
INSERT INTO `whereis` VALUES (500,'Tenth Brood Champion','at Hollow Island',NULL);
INSERT INTO `whereis` VALUES (501,'The Hollow Island Suzerain','at Hollow Island',NULL);
INSERT INTO `whereis` VALUES (502,'The Brood Mother','at Hollow Island',NULL);
INSERT INTO `whereis` VALUES (503,'Hollow Island Weed','at Hollow Island',NULL);
INSERT INTO `whereis` VALUES (505,'Jack Legchopper','Creeping about Varmint Woods',NULL);
INSERT INTO `whereis` VALUES (506,'Trash King','Junkyard outside West Athen, Athen Shire, 1600 x 1000',NULL);
INSERT INTO `whereis` VALUES (507,'Techleader Praetor','Cyborg Barracks Greater Tir County 3232 x 2340',NULL);
INSERT INTO `whereis` VALUES (508,'Augmented Cyborg Hellfury','Cyborg Barracks Greater Tir County 3232 x 2340',NULL);
INSERT INTO `whereis` VALUES (509,'Defender Of The Three','Temple Of The Three Winds Greater Tir County',NULL);
INSERT INTO `whereis` VALUES (510,'The Curator','Temple Of The Three Winds Greater Tir County',NULL);
INSERT INTO `whereis` VALUES (511,'Nematet The Custodian Of Time','Temple Of The Three Winds Greater Tir County',NULL);
INSERT INTO `whereis` VALUES (512,'The Re-animator','Temple Of The Three Winds Greater Tir County',NULL);
INSERT INTO `whereis` VALUES (513,'Lien The Memorystalker','Temple Of The Three Winds Greater Tir County',NULL);
INSERT INTO `whereis` VALUES (514,'Guardian Of Tomorrow','Temple Of The Three Winds Greater Tir County',NULL);
INSERT INTO `whereis` VALUES (515,'Uklesh The Frozen','Temple Of The Three Winds Greater Tir County',NULL);
INSERT INTO `whereis` VALUES (516,'Aztur The Immortal','Temple Of The Three Winds Greater Tir County',NULL);
INSERT INTO `whereis` VALUES (517,'Gartua The Doorkeeper','Temple Of The Three Winds Greater Tir County',NULL);
INSERT INTO `whereis` VALUES (518,'Windcaller Yatilla','Temple Of The Three Winds Greater Tir County',NULL);
INSERT INTO `whereis` VALUES (519,'Den Smuggler Pilot','Smugglers Den, 1755 x 872, SFH.',NULL);
INSERT INTO `whereis` VALUES (520,'Lacerator Gunbeetle','Pleasant Meadows, 2405 x 633 (within a fairly large area of)', 'Bronto');
INSERT INTO `whereis` VALUES (521,'Pendpod Trapper','Pleasant Meadows, 890 x 1689 (within a fairly large area of)', 'Bronto');
INSERT INTO `whereis` VALUES (522,'Gouger Scorpiod','Pleasant Meadows, 2188 x 1938 (within a fairly large area of)', 'Bronto');
INSERT INTO `whereis` VALUES (523,'Fly Agaric','Clondyke, 588 x 3441', 'Bronto Amanita Muscaria');
INSERT INTO `whereis` VALUES (524,'Angel''s Trumpet','Clondyke, 2359 x 3656 (seems to be in multiple locations nearby)', 'Bronto Datura Inoxia');
INSERT INTO `whereis` VALUES (524,'Cardboard Palm','Clondyke, 1684 x 1516', 'Bronto Zamia Furfuracea');
INSERT INTO `whereis` VALUES (525,'Bahirae Serugiusu','Omni Trade, 411 x 394.', 'Token');
INSERT INTO `whereis` VALUES (526,'Technologist Frank Jobin','Lower Scheol, 1066 x 1813', NULL);