DROP TABLE IF EXISTS `buffitems`;
CREATE TABLE `buffitems` (`skill` VARCHAR(50) NOT NULL, `name` VARCHAR(150) NOT NULL, `lowid` int(11) NOT NULL, `highid` int(11) NOT NULL, `minql` int(11) NOT NULL, `buffed` int(11) NOT NULL, `type` VARCHAR(10) NOT NULL, `info` VARCHAR(255) NOT NULL);
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Master G-Staff', 130050, 130050, 200, 60, 'weap', 'Rollable');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Bloodlust', 238981, 238981, 300, 50, 'weap', 'Shade only');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'MTI VP300 Red s. Caseless', 123805, 123806, 180, 30, 'weap', 'Lowest QL');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Premium Dual Razor Disaffiliation Sniper', 249852, 249852, 200, 30, 'weap', 'Requires AI');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Tsakachumi PTO-HV6 Counter-Sniper Rifle', 124346, 124346, 175, 30, 'weap', 'Rollable');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'O.E.T. Co. Urban Sniper Kaiser', 124312, 124312, 192, 30, 'weap', 'QL 300');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'OT PF57 Flechette System', 123990, 123990, 160, 25, 'weap', 'No info');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'OT Backup Pundit', 123901, 123901, 180, 24, 'weap', 'No info');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'G.C. AKMR 1K20 Prospero', 124483, 124483, 200, 20, 'weap', 'No info');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'OT-WC RM73 Junior Big Sister', 124214, 124214, 190, 20, 'weap', 'No info');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Gripo-Com AKR 1K21', 123977, 123977, 50, 15, 'weap', 'QL 50 only');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Sleek Shank of Maze', 238962, 238962, 300, 15, 'weap', 'Dual Wieldable');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'OT M500 SWAT Monster', 124355, 124355, 180, 12, 'weap', 'No info');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Custom KIWD 37 Hunter Crossbow', 160171, 160171, 200, 10, 'weap', 'No info');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Explosif''s Polychromatic Pillows', 258343, 258343, 300, 10, 'weap', 'QL 300');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Intelligent Mole Stinger', 163285, 163285, 200, 10, 'weap', 'No info');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'OT-Windchaser M06 Hematite', 124148, 124148, 26, 8, 'weap', 'No info');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Sleek Black Staff of the Lithe Dancer', 164103, 164103, 200, 8, 'weap', 'Enfo only');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Loose Incan Blood Tainter', 206084, 206084, 100, 7, 'weap', 'Advy only');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Kiddy', 160449, 160449, 200, 5, 'weap', 'No info');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Notum-Infused Chimera Rifle', 227108, 227108, 15, 5, 'weap', 'Requires SL');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Schiacciamento Vento', 164057, 164057, 200, 5, 'weap', 'No info');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Illicit Laser Backup', 233794, 233794, 21, 2, 'weap', 'No info');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Notum-Infused Silvertail Dagger', 227096, 227096, 15, 2, 'weap', 'No info');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Notum-Infused Spider Shank Machete', 227091, 227091, 15, 2, 'weap', 'No info');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Carpenter - Sugarfree Rum', 159076, 159076, 4, 1, 'weap', 'Buyable from Tradershop');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Improvised Woodwolf Beer', 157972, 157972, 3, 1, 'weap', 'No info');

INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Penultimate Ofab Shade Pants', 264566, 264566, 300, 35, 'armor', 'Shade only, Upgraded Ofab');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Faithful Shade Leg Covers', 216690, 216690, 300, 30, 'armor', 'Shade + Clan only');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Burden of Competence', 244718, 244718, 300, 30, 'armor', 'Lvl req 215+');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Eye of the Evening Star', 238912, 238913, 295, 30, 'armor', 'QL 295-300, Can wear two');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Very Very Very Hot Pants', 152543, 152543, 150, 27, 'armor', 'MA only');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Perfected Infused Dust Brigade Bracer', 274551, 274551, 250, 25, 'armor', 'Tradeskilled');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Special Edition Ofab Shade Headgear', 267378, 267378, 300, 25, 'armor', 'Shade only');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Penultimate Ofab Agent Pants', 264314, 264314, 300, 24, 'armor', 'Agent only, Upgraded Ofab');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Enhanced Dustbrigade Covering', 269997, 269997, 200, 22, 'armor', 'Lvl 216+ req');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Miy''s Melee Armor Legs', 268856, 268857, 300, 22, 'armor', 'Melee/Nano/Ranged/Scary/Tank included');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Penultimate Ofab Enforcer Pants', 264216, 264216, 300, 22, 'armor', 'Enfo only, Upgraded Ofab');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Penultimate Ofab Fixer Pants', 264494, 264494, 300, 21, 'armor', 'Fixer only, Upgraded Ofab');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Faithful Fixer Pants', 218275, 218275, 300, 20, 'armor', 'Chosen armor is omni variant');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Faithful Agent Pants', 218490, 218490, 300, 20, 'armor', 'Chosen armor is omni variant');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Enhanced Dustbrigade Sleeves', 269996, 269996, 200, 20, 'armor', 'Can wear two');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Gemini''s Double Band of Linked Information', 244572, 244572, 250, 20, 'armor', 'Drops off Gemini');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Improved Ofab Adventurer Pants', 264187, 264187, 300, 20, 'armor', 'Advy only, Upgraded Ofab');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Lya''s Sangi Patch', 269194, 269195, 300, 20, 'armor', 'Can wear two');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Desert Nomad Shoulder Pad', 290224, 290225, 300, 20, 'armor', 'Can wear two');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Masterpiece Ancient Bracer', 267780, 267780, 250, 20, 'armor', 'Tradeskilled');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Penultimate Ofab Engineer Pants', 264605, 264605, 300, 20, 'armor', 'Engi only, Upgraded ofab');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Penultimate Ofab Keeper Pants', 264641, 264641, 300, 20, 'armor', 'Keeper only, Upgraded ofab');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Penultimate Ofab Soldier Pants', 264458, 264458, 300, 20, 'armor', 'Soldier only, Upgraded ofab');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Ring of Divine Teardrops', 238915, 238915, 300, 20, 'armor', 'Can wear two');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Ring of Plausibility', 260693, 260693, 250, 20, 'armor', 'Quest reward');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Penultimate Ofab Martial Artist Pants', 264350, 264350, 300, 19, 'armor', 'MA only, Upgraded Ofab');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Miy''s Melee Armor Gloves', 268852, 268853, 300, 17, 'armor', 'No info');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Miy''s Ranged Armor Gloves', 268865, 268865, 300, 17, 'armor', 'No info');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Faithful Enforcer Pants', 220238, 220238, 300, 16, 'armor', 'Chosen armor is omni variant');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Faithful Soldier Pants', 214825, 214825, 300, 16, 'armor', 'Chosen armor is omni variant');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Faithful Keeper Greaves', 216674, 216674, 300, 16, 'armor', 'Chosen armor is omni variant');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Faithful Adventurer Pants', 218636, 218636, 300, 16, 'armor', 'Chosen armor is omni variant');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Penultimate Ofab Bureaucrat Pants', 264530, 264530, 300, 16, 'armor', 'Crat only, Upgraded Ofab');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Penultimate Ofab Doctor Pants', 264677, 264677, 300, 16, 'armor', 'Doc only, Upgraded Ofab');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Penultimate Ofab Metaphysicist Pants', 264386, 264386, 300, 16, 'armor', 'MP only, Upgraded Ofab');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Penultimate Ofab Nano Technician Pants', 264422, 264422, 300, 15, 'armor', 'NT only, Upgraded Ofab');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Armplates of Meteorite Assembly', 245855, 245855, 250, 15, 'armor', 'Engi/Trad/Crat/Doc/Nt/Mp only');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Penultimate Ofab Trader Pants', 264272, 264272, 300, 15, 'armor', 'Trader only, Upgraded Ofab');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Pilgrim Protector Armor Pants', 201203, 201203, 300, 15, 'armor', 'Sold/Enfo + Clan only');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'The sacrificed wedding ring of Lady Ettard', 245905, 245905, 250, 15, 'armor', 'No info');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Talented Cloak', 152702, 152702, 145, 14, 'armor', 'Might not be in-game No info');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Faithful Bureaucrat Pants', 218946, 218946, 300, 12, 'armor', 'Chosen armor is omni variant');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Faithful Doctor Pants', 217725, 217725, 300, 12, 'armor', 'Chosen armor is omni variant');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Faithful Engineer Pants', 218207, 218207, 300, 12, 'armor', 'Chosen armor is omni variant')
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Faithful Metaphysicist Pants', 221453, 221453, 300, 12, 'armor', 'Chosen armor is omni variant');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Faithful Nano Technician Pants', 222771, 222771, 300, 10, 'armor', 'Chosen armor is omni variant');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Faithful Trader Pants', 218821, 218821, 300, 10, 'armor', 'Chosen armor is omni variant');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Legs of the Servants of Eight', 160436, 160436, 200, 10, 'armor', 'Dyna Loot');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Pilgrim Protector Armor Pants', 201202, 201202, 200, 10, 'armor', 'Sold/Enfo + Clan only');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Omni-Armed Forces Boots', 203446, 203446, 200, 9, 'armor', 'Omni only');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Omni-Med Battle Boots', 206971, 206971, 200, 9, 'armor', 'Doc + Omni only');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Superior Sentinel Armor Boots', 203452, 203452, 200, 9, 'armor', 'Clan only');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Boots of Azure Reveries', 165305, 165305, 200, 8, 'armor', 'Level 175+ req');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'I am the Eel', 163633, 163633, 200, 8, 'armor', 'Opifex only');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Flaxen Notum Pants', 165206, 165206, 200, 8, 'armor', 'Opifex only');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Luxurious Rubber Pants', 168670, 168670, 200, 8, 'armor', 'MP only');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Pure Novictum Ring for the Artillery Unit', 226308, 226308, 1, 8, 'armor', 'Sold/Agent/Fix only');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Pure Novictum Ring for the Infantry Unit', 226307, 226307, 1, 8, 'armor', 'Enfo/MA/Keeper/Shade only');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Pure Novictum Ring for the Support Unit', 226288, 226288, 1, 8, 'armor', 'MP/Advy/Doc only');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Titan Viper Tattoo', 165202, 165202, 200, 8, 'armor', 'MA only');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Bag of Exchange', 206725, 206725, 100, 7, 'armor', 'Trader only, TL4 lock');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Lamnidae Gloves', 252991, 252991, 300, 6, 'armor', 'Requires AI');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Neutral Ring of Survival', 163639, 163639, 200, 6, 'armor', 'Neutral only');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Subspace Storage Device', 245823, 245823, 250, 6, 'armor', 'Requires SL');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Enhanced Jathos'' Molybdenum Plate Vest', 272444, 272444 , 250, 5, 'armor', 'Helm/Legs/Chest each give +5');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Gold Monkey Helmet of Extreme Merriment', 163719, 163719, 200, 5, 'armor', 'Might not be in-game, No info');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Platinum Filigree Ring set with a Perfectly Cut Almandine', 244477, 244483, 234, 5, 'armor', 'Froob wearable, Can wear two');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Headband of Haste', 245677, 245677, 150, 5, 'armor', 'No info');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Sekutek Chilled Plasteel Body Armor', 160392, 160392, 200, 5, 'armor', 'Each piece gives +5');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Kirch Kevlar Armor Body', 160337, 160337, 200, 5, 'armor', 'Each piece gives +5');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Nar Shere''s Temperamental Spirit Tattoo', 223725, 223725, 50, 5, 'armor', 'Advy/Enfo/Shade only');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Veil of the Revoked', 247081, 247081, 100, 5, 'armor', 'Trader/Enfo only');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Aban Fala''s Bracer of Dexterity', 223679, 223679, 40, 4, 'armor', 'Might not be in-game, Omni only');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Eva Pourais'' Snakeskin Patch', 224093, 224093, 150, 4, 'armor', 'MA/Fix/Agent/Shade, Omni variant: Joshua Khan''s Catskin Patch)');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Nova Dillon Body Armor', 163946, 163946, 200, 4, 'armor', 'Each piece gives +4');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Sergeant of Tir Ring', 168415, 168415, 30, 4, 'armor', 'Clan only, TL2 lock');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Enhanced Jathos'' Molybdenum Plate Gloves', 272447, 272447, 250, 3, 'armor', 'Gloves/boots/sleeves give +3, Omni Variant: Kegern''s');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Custom-Made Adventurer Ring of Versatility', 163687, 163687, 200, 3, 'armor', 'Advy only');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Tech Pants of the Rose', 168950, 168950, 200, 3, 'armor', 'TL 6 lock');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Anything', 165215, 165215, 200, 2, 'armor', 'Goes just about anywhere');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Custom-Made Trader Ring of Production', 163647, 163647, 200, 2, 'armor', 'Trader only');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Grand Armband of Agility', 223693, 223693, 40, 2, 'armor', 'Might not drop anymore, Clan only');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Reactive Helmet', 251999, 251999, 200, 2, 'armor', 'Omni variant: Proactive');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Silly Ring', 163645, 163645, 200, 2, 'armor', 'Drops from HI');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Sleeves of Gashing', 245433, 245433, 150, 2, 'armor', 'Advy only, Requires SL');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Marius'' Black and White Disco Shoes', 249707, 249707, 1, 1, 'armor', 'No info');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Reactive Gloves', 251998, 251998, 200, 1, 'armor', 'Omni Varient: Proactive');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'Spirit Tech Circlet of Cerubin', 245139, 245139, 100, 1, 'armor', 'Drops in CoH');
INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Agility', 'The Pioneer Backpack', 152039, 152039, 1, 1, 'armor', 'Rare item only buyable from players');

INSERT INTO buffitems (skill, name, lowid, highid, minql, buffed, type, info) VALUES ('Sense', 'Explosif''s Polychromatic Pillows', 258343, 258343, 300, 10, 'weap', 'QL 300');