DROP TABLE IF EXISTS raidloot;
CREATE TABLE IF NOT EXISTS raidloot (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, raid VARCHAR(255), area VARCHAR(255), boss VARCHAR(255), name VARCHAR(255), img INT, ref INT);
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('Pande', 'BeastArmor', 'The Beast', 'Sigil of Bahomet', '131259', '244750');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'BeastArmor', 'The Beast', 'Helmet of Hypocrisy', '245034', '244716');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'BeastArmor', 'The Beast', 'Burden of Competence', '245030', '244718');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'BeastArmor', 'The Beast', 'Shoulderplates of Sabotage', '245036', '244713');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'BeastArmor', 'The Beast', 'Cuirass of Obstinacy', '245031', '244717');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'BeastArmor', 'The Beast', 'Sleeves of Senseless Violence', '245029', '244705');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'BeastArmor', 'The Beast', 'Gauntlets of Deformation', '245033', '244704');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'BeastArmor', 'The Beast', 'Armplates of Elimination', '245029', '244712');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'BeastArmor', 'The Beast', 'Greaves of Malfeasance', '245035', '244715');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'BeastArmor', 'The Beast', 'Boots of Concourse', '245032', '244714');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'Shadowbreeds', 'The Beast', 'The Dark Side (Omni)', '136597', '215444');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'Shadowbreeds', 'The Beast', 'The Lighter Side (Clan)', '136594', '215442');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'Shadowbreeds', 'The Beast', 'The Unknown Path (Neutral)', '136596', '215443');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'Stars', 'The Beast', 'Star of Ardency (NT)', '131260', '244700');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'Stars', 'The Beast', 'Star of Enterprice (Fixer)', '131260', '244693');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'Stars', 'The Beast', 'Star of Enticement (Shade)', '131260', '244703');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'Stars', 'The Beast', 'Star of Equanimity (MA)', '131260', '244691');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'Stars', 'The Beast', 'Star of Faith (Keeper)', '131260', '244702');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'Stars', 'The Beast', 'Star of Fidelity (Soldier)', '131260', '244690');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'Stars', 'The Beast', 'Star of Fortitude (Enf)', '131260', '244698');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'Stars', 'The Beast', 'Star of Freedom (Adv)', '131260', '244695');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'Stars', 'The Beast', 'Star of Ingenuity (Engi)', '131260', '244692');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'Stars', 'The Beast', 'Star of Interchange (Trader)', '131260', '244696');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'Stars', 'The Beast', 'Star of Management (Crat)', '131260', '244697');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'Stars', 'The Beast', 'Star of Moral (MP)', '131260', '244701');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'Stars', 'The Beast', 'Star of Recovery (Doc)', '131260', '244699');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'Stars', 'The Beast', 'Star of Stealth (Agent)', '131260', '244694');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'BeastWeapons', 'The Beast', 'Sunrise Hilt (Clan)', '235342', '246813');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'BeastWeapons', 'The Beast', 'Sunset Hilt (Omni)', '235341', '246814');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'BeastWeapons', 'The Beast', 'Lord of Abandonment', '245083', '244742');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'BeastWeapons', 'The Beast', 'Lord of Anger', '210184', '244802');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'BeastWeapons', 'The Beast', 'Lord of Angst', '245082', '244821');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'BeastWeapons', 'The Beast', 'Lord of Chaos', '245089', '244910');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'BeastWeapons', 'The Beast', 'Lord of Deceit', '213075', '244779');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'BeastWeapons', 'The Beast', 'Lord of Envy', '244836', '244843');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'BeastWeapons', 'The Beast', 'Lord of Gluttony', '218714', '244785');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'BeastWeapons', 'The Beast', 'Lord of Greed', '244931', '244862');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'BeastWeapons', 'The Beast', 'Lord of Hatred', '158269', '244762');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'BeastWeapons', 'The Beast', 'Lord of Lust', '244837', '244914');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'BeastWeapons', 'The Beast', 'Lord of Pride', '233217', '244783');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'BeastWeapons', 'The Beast', 'Lord of Sloth', '233214', '244912');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'BeastWeapons', 'The Beast', 'Lady of Abandonment', '245083', '244743');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'BeastWeapons', 'The Beast', 'Lady of Anger', '210184', '244801');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'BeastWeapons', 'The Beast', 'Lady of Angst', '245082', '244820');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'BeastWeapons', 'The Beast', 'Lady of Chaos', '245089', '244909');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'BeastWeapons', 'The Beast', 'Lady of Deceit', '213075', '244778');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'BeastWeapons', 'The Beast', 'Lady of Envy', '244836', '244842');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'BeastWeapons', 'The Beast', 'Lady of Gluttony', '218714', '244784');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'BeastWeapons', 'The Beast', 'Lady of Greed', '244931', '244859');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'BeastWeapons', 'The Beast', 'Lady of Hatred', '158269', '244761');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'BeastWeapons', 'The Beast', 'Lady of Lust', '244837', '244913');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'BeastWeapons', 'The Beast', 'Lady of Pride', '233217', '244782');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'BeastWeapons', 'The Beast', 'Lady of Sloth', '233214', '244911');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'TNH', 'The Night Heart', 'Maar''s Blue Belt of Double Prudence (Int/Psy)', '244991', '244989');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'TNH', 'The Night Heart', 'Maar''s Red Belt of Double Power (Str/Sta)', '244991', '244988');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'TNH', 'The Night Heart', 'Maar''s Yellow Belt of Double Speed (Agi/Sen)', '244991', '244990');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'TNH', 'The Night Heart', 'Notum Seed (Clan)', '246815', '246818');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'TNH', 'The Night Heart', 'Novictum Seed (Omni)', '246816', '246817');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'NorthZods', 'Capricorn', 'Capricorn Bracer of Toxication', '205519', '244564');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'NorthZods', 'Capricorn', 'Capricorn''s Guide to Alchemy', '136332', '244563');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'NorthZods', 'Capricorn', 'Capricorn''s Reliable Memory', '205523', '244561');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'NorthZods', 'Capricorn', 'Gloves of the Caring Capricorn', '21871', '244562');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'NorthZods', 'Sagittarius', 'Comfort of the Sagittarius', '37969', '244645');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'NorthZods', 'Sagittarius', 'First Creation of the Sagittarius', '226595', '244644');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'NorthZods', 'Sagittarius', 'Sagittarius'' Hearty Spirit Helper', '12701', '244643');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'NorthZods', 'Sagittarius', 'Strong Mittens of the Sagittarius', '22939', '244647');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'NorthZods', 'Scorpio', 'Punters of the Scorpio', '213546', '244650');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'NorthZods', 'Scorpio', 'Sash of Scorpio Strength', '161070', '244648');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'NorthZods', 'Scorpio', 'Scorpio''s Aim of Anger', '245000', '244655');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'NorthZods', 'Scorpio', 'Scorpio''s Shell of Change', '22401', '244654');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'MiddleZods', 'Libra', 'Aim of Libra', '130840', '244637');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'MiddleZods', 'Libra', 'Libra''s Charming Assistant', '213659', '244635');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'MiddleZods', 'Libra', 'Urbane Pants of Libra', '22914', '244581');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'MiddleZods', 'Libra', 'Well Balanced Spirit Helper of Libra', '119141', '244579');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'MiddleZods', 'Pisces', 'Cosmic Guide of the Pisces', '151918', '244641');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'MiddleZods', 'Pisces', 'Mystery of Pisces', '161079', '244640');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'MiddleZods', 'Pisces', 'Octopus Contraption of the Pisces', '203513', '244639');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'MiddleZods', 'Pisces', 'Soul Mark of Pisces', '226602', '244638');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'MiddleZods', 'Taurus', 'Taurus'' Ring of the Heart', '84067', '244661');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'MiddleZods', 'Taurus', 'Taurus'' Spirit of Patience', '130792', '244659');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'MiddleZods', 'Taurus', 'Taurus'' Spirit of Reflection', '149940', '244658');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'MiddleZods', 'Taurus', 'Taurus'' Swordmaster Spirit', '130788', '244660');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'EastZods', 'Aquarius', 'Aquarius'' Boots of Small Steps', '37596', '244357');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'EastZods', 'Aquarius', 'Aquarius'' Multitask Calculator', '205528', '244376');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'EastZods', 'Aquarius', 'Intuitive Memory of the Aquarius', '244359', '244358');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'EastZods', 'Aquarius', 'Mediative Gloves of the Aquarius', '99790', '244223');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'EastZods', 'Cancer', 'Cancer''s Gloves of Automatic Knowledge', '37106', '244559');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'EastZods', 'Cancer', 'Cancer''s Ring of Circumspection', '84063', '244560');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'EastZods', 'Cancer', 'Cancer''s Silver Boots of the Autodidact', '37127', '244543');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'EastZods', 'Cancer', 'Cancer''s Time-Saving Memory', '205514', '244558');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'EastZods', 'Gemini', 'Collector Pants of Gemini', '30938', '244566');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'EastZods', 'Gemini', 'Cross Dimensional Gyro of Gemini', '149938', '244567');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'EastZods', 'Gemini', 'Gemini''s Double Band of Linked Information', '151932', '244572');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'EastZods', 'Gemini', 'Gemini''s Green Scope of Variety', '130891', '244565');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'WestZods', 'Aries', 'Aries'' Tiara of the Quick Witted', '84061', '244540');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'WestZods', 'Aries', 'Boon of Aries', '205497', '244405');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'WestZods', 'Aries', 'Dynamic Sleeve of Aries (Multi Melee - Right Arm)', '22953', '244542');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'WestZods', 'Aries', 'Dynamic Sleeve of Aries (Multi Ranged - Left Arm)', '22953', '244541');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'WestZods', 'Aries', 'Quick-Draw Holster of Aries', '205533', '244469');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'WestZods', 'Leo', 'Enthusiastic Spirit Helper of the Leo', '119139', '244575');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'WestZods', 'Leo', 'Leo''s Faithful Boots of Ancient Gold', '22883', '244574');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'WestZods', 'Leo', 'Leo''s Grandiose Gold Armband of Plenty', '151931', '244573');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'WestZods', 'Leo', 'Leo''s Mellow Gold Pad of Auto-Support', '213665', '244578');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'WestZods', 'Virgo', 'Virgo''s Analytical Spirit Helper', '11652', '244665');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'WestZods', 'Virgo', 'Virgo''s Arrow Guide', '13280', '244662');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'WestZods', 'Virgo', 'Virgo''s Modest Spirit of Faith', '20411', '244664');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('pande', 'WestZods', 'Virgo', 'Virgo''s Practical Spirit Helper', '11646', '244663');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '10', 'Boss Loot', 'Inactive Alien Tank Armor', '22401', '268507');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '10', 'Boss Loot', 'Inactive Alien Battery', '220416', '268496');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '10', 'Boss Loot', 'Inactive Alien Beacon', '220416', '268494');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '10', 'Boss Loot', 'Inactive Alien Material Conversion Kit', '99658', '268510');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '10', 'Boss Loot', 'Inactive Alien Reflex Modifier', '220416', '268499');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '10', 'Boss Loot', 'Inactive Alien Translation Device', '12692', '268477');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '10', 'Boss Loot', 'Inactive Empty Alien Augmentation Device', '218751', '268493');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '10', 'Common Loot', 'Alien Activation Crystal', '12252', '268478');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '10', 'Common Loot', 'Alien Data Storage Crystal - Combat', '83069', '268479');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '10', 'Common Loot', 'Alien Data Storage Crystal - Defense', '83069', '268481');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '10', 'Common Loot', 'Alien Data Storage Crystal - Insight', '83069', '268484');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '10', 'Common Loot', 'Alien Data Storage Crystal - Medical', '83069', '268483');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '10', 'Common Loot', 'Alien Data Storage Crystal - Nano Technology', '83069', '268480');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '10', 'Common Loot', 'Alien Data Storage Crystal - Protection', '83069', '268485');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '10', 'Common Loot', 'Alien Data Storage Crystal - Technical', '83069', '268482');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '10', 'Common Loot', 'Alien Armor Materials', '144715', '268508');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '13', 'Master Genesplicer Cha''Khaz', 'Action Probability Estimator', '203502', '257960');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '13', 'Master Genesplicer Cha''Khaz', 'Dynamic Gas Redistribution Valves', '205508', '257962');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '13', 'Master Genesplicer Cha''Khaz', 'Kyr''Ozch Helmet', '230855', '257706');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '13', 'Master Genesplicer Cha''Khaz', 'Hacker Ice-Breaker Source', '257196', '257968');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '13', 'Master Genesplicer Cha''Khaz', 'Kyr''Ozch Battlesuit Audio Processor', '218775', '257529');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '13', 'Master Genesplicer Cha''Khaz', 'Kyr''Ozch Rank Identification', '218768', '257531');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '13', 'Master Genesplicer Cha''Khaz', 'Kyr''Ozch Video Processing Unit', '218758', '257533');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '13', 'Master Genesplicer Cha''Khaz', 'Kyr''Ozch Data Core', '25800', '258294');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '13', 'Master Genesplicer Cha''Khaz', 'Biotech Matrix', '275972', '275916');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '13', 'Master Genesplicer Cha''Khaz', 'Gelatinous Lump', '275962', '275909');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '28', 'Embalmer Cha''Khaz', 'Notum Amplification Coil', '257195', '275963');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '28', 'Embalmer Cha''Khaz', 'Inertial Adjustment Processing Unit', '11618', '275959');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '28', 'Embalmer Cha''Khaz', 'Kyr''Ozch Helmet', '230855', '257706');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '28', 'Embalmer Cha''Khaz', 'Hacker Ice-Breaker Source', '257196', '257968');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '28', 'Embalmer Cha''Khaz', 'Kyr''Ozch Battlesuit Audio Processor', '218775', '257529');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '28', 'Embalmer Cha''Khaz', 'Kyr''Ozch Rank Identification', '218768', '257531');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '28', 'Embalmer Cha''Khaz', 'Kyr''Ozch Video Processing Unit', '218758', '257533');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '28', 'Embalmer Cha''Khaz', 'Kyr''Ozch Data Core', '25800', '258293');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '28', 'Embalmer Cha''Khaz', 'Crystalline Matrix', '275964', '275912');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '28', 'Embalmer Cha''Khaz', 'Kyr''Ozch Circuitry', '275965', '275914');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '35', 'Field Marshal and Support Cha''Khaz', 'Visible Light Remodulation Device', '235270', '257964');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '35', 'Field Marshal and Support Cha''Khaz', 'Energy Redistribution Unit', '257197', '257961');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '35', 'Field Marshal and Support Cha''Khaz', 'Kyr''Ozch Helmet', '230855', '257706');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '35', 'Field Marshal and Support Cha''Khaz', 'Hacker Ice-Breaker Source', '257196', '257968');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '35', 'Field Marshal and Support Cha''Khaz', 'Kyr''Ozch Battlesuit Audio Processor', '218775', '257529');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '35', 'Field Marshal and Support Cha''Khaz', 'Kyr''Ozch Rank Identification', '218768', '257531');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '35', 'Field Marshal and Support Cha''Khaz', 'Kyr''Ozch Video Processing Unit', '218758', '257533');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '35', 'Field Marshal and Support Cha''Khaz', 'Kyr''Ozch Data Core', '25800', '258292');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '35', 'Field Marshal and Support Cha''Khaz', 'Alpha Program Chip', '275970', '275918');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '35', 'Field Marshal and Support Cha''Khaz', 'Beta Program Chip', '275969', '275919');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '35', 'Field Marshal and Support Cha''Khaz', 'Kyr''Ozch Processing Unit', '275960', '275907');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '35', 'Field Marshal and Support Cha''Khaz', 'Odd Kyr''Ozch Nanobots', '11750', '275906');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '42', 'East - Field Marshal & Support', 'Visible Light Remodulation Device', '235270', '257964');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '42', 'East - Field Marshal & Support', 'Energy Redistribution Unit', '257197', '257961');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '42', 'East - Field Marshal & Support', 'Hacker Ice-Breaker Source', '257196', '257968');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '42', 'North - Master Genesplicer', 'Action Probability Estimator', '203502', '257960');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '42', 'North - Master Genesplicer', 'Dynamic Gas Redistribution Valves', '205508', '257962');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '42', 'North - Master Genesplicer', 'Hacker Ice-Breaker Source', '257196', '257968');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '42', 'West - Proto-Embalmer', 'Notum Amplification Coil', '257195', '275963');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '42', 'West - Proto-Embalmer', 'Inertial Adjustment Processing Unit', '11618', '275959');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '42', 'West - Proto-Embalmer', 'Hacker Ice-Breaker Source', '257196', '257968');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '42', 'West - Proto-Embalmer', 'Alien Matrix Alpha Box', '275887', '275706');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '42', 'West - Proto-Embalmer', 'Alien Matrix Beta Box', '275889', '275854');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '42', 'Artillery Commander', 'Kyr''Ozch Invasion Plan', '35990', '262656');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('apf', '42', 'Artillery Commander', 'Unlearning Device', '99257', '260422');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('db', 'db2', 'Ground Chief Aune', 'Basic Infused Dust Brigade Bracer', '84062', '274541');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('db', 'db2', 'Ground Chief Aune', 'Dust Brigade Notum Infuser', '218768', '274552');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('db', 'db2', 'Ground Chief Aune', 'Dust Brigade Solar Notum Infuser', '218768', '274558');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('db', 'db2', 'Ground Chief Aune', 'Dust Brigade Engineer Pistol', '264787', '274559');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('db', 'db2', 'Ground Chief Aune', 'Black Molybdenum-Matrix of Xan', '272534', '272458');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('db', 'db2', 'Ground Chief Aune', 'White Molybdenum-Matrix of Xan', '272535', '272459');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('db', 'db2', 'Ground Chief Aune', 'Enhanced Dustbrigade Chemist Gloves', '21871', '270393');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('db', 'db2', 'Ground Chief Aune', 'Enhanced Dustbrigade Covering', '155108', '269997');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('db', 'db2', 'Ground Chief Aune', 'Enhanced Dustbrigade Flexible Boots', '31746', '270392');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('db', 'db2', 'Ground Chief Aune', 'Enhanced Dustbrigade Notum Gloves', '21871', '270394');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('db', 'db2', 'Ground Chief Aune', 'Enhanced Dustbrigade Sleeves', '13233', '269996');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('db', 'db1', 'Ground Chief Mikkelsen', 'Enhanced Dustbrigade Chemist Gloves', '21871', '270393');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('db', 'db1', 'Ground Chief Mikkelsen', 'Enhanced Dustbrigade Combat Chestpiece', '32162', '269993');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('db', 'db1', 'Ground Chief Mikkelsen', 'Enhanced Dustbrigade Covering', '155108', '269997');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('db', 'db1', 'Ground Chief Mikkelsen', 'Enhanced Dustbrigade Fleixble Boots', '31746', '270392');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('db', 'db1', 'Ground Chief Mikkelsen', 'Enhanced Dustbrigade Notum Gloves', '21871', '270394');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('db', 'db1', 'Ground Chief Mikkelsen', 'Enhanced Dustbrigade Sleeves', '13233', '269996');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('db', 'db1', 'Ground Chief Mikkelsen', 'Enhanced Dustbrigade Spirit-tech Chestpiece', '32162', '269994');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('db', 'db1', 'Ground Chief Mikkelsen', 'Enhanced Safeguarded NCU Memory Unit (Int/Psy)', '119134', '269985');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('db', 'db1', 'Ground Chief Mikkelsen', 'Enhanced Safeguarded NCU Memory Unit (Str/Sta)', '119134', '269986');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('db', 'db1', 'Ground Chief Mikkelsen', 'Enhanced Safeguarded NCU Memory Unit (Agi/Sen)', '119134', '269987');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('db', 'db1', 'Ground Chief Mikkelsen', 'Protected Safeguarded NCU Memory Unit (Evades)', '119134', '269990');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('db', 'db1', 'Ground Chief Mikkelsen', 'Master Combat Program', '269949', '269960');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('db', 'db1', 'Ground Chief Mikkelsen', 'Master Melee Program', '269948', '269961');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('db', 'db1', 'Ground Chief Mikkelsen', 'Master Nano Technology Program', '269950', '269959');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('alappaa', 'alappaa', 'Reprogrammed Mezzorash', 'Frozen Shoulderpads', '269968', '269896');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('alappaa', 'alappaa', 'Reprogrammed Mezzorash', 'Combat Program', '269949', '269946');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('alappaa', 'alappaa', 'Reprogrammed Mezzorash', 'Melee Program', '269948', '269947');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('alappaa', 'alappaa', 'Reprogrammed Mezzorash', 'Nano Technology Program', '269950', '269945');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('albtraum', 'albmemories', 'Crystalised Memories', 'Crystalised Memories of a Defender', '72771', '267711');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('albtraum', 'albmemories', 'Crystalised Memories', 'Crystalised Memories of a Doctor', '72771', '267726');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('albtraum', 'albmemories', 'Crystalised Memories', 'Crystalised Memories of a Engineer', '72771', '267714');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('albtraum', 'albmemories', 'Crystalised Memories', 'Crystalised Memories of a Mechanic', '72771', '267701');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('albtraum', 'albmemories', 'Crystalised Memories', 'Crystalised Memories of an Archer', '72771', '267708');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('albtraum', 'albmemories', 'Crystalised Memories', 'Crystalised Memories of an Instructor', '72771', '267710');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('albtraum', 'albmemories', 'Crystalised Memories', 'Crystalised Memories of a Scientist', '72771', '267713');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('albtraum', 'albmemories', 'Crystalised Memories', 'Crystalised Memories of a Sniper', '72771', '267704');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('albtraum', 'albmemories', 'Crystalised Memories', 'Crystalised Memories of a Surgeon', '72771', '267728');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('albtraum', 'albmemories', 'Crystalised Memories', 'Crystalised Memories of a Technician', '72771', '267698');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('albtraum', 'albmemories', 'Crystalised Memories', 'Crystalised Memories of a Warrior', '72771', '267697');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('albtraum', 'albrings', 'Albtraum Rings', 'Ring of Divided Loyalty', '245483', '267905');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('albtraum', 'albrings', 'Albtraum Rings', 'Ring of Gruesome Misery', '84067', '267906');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('albtraum', 'albrings', 'Albtraum Rings', 'Ring of Sister Merciless', '84067', '267907');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('albtraum', 'albrings', 'Albtraum Rings', 'Ring of Sister Pestilence', '84067', '267909');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('albtraum', 'albrings', 'Albtraum Rings', 'Ring of Summoned Terror', '84067', '267911');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('albtraum', 'albmisc', 'Albtraum Misc', 'Ancient Damage Generation Device', '218770', '267725');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('albtraum', 'albmisc', 'Albtraum Misc', 'Ancient Scrap of Spirit Knowledge', '163575', '267681');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('albtraum', 'albmisc', 'Albtraum Misc', 'Ancient Scrap of Saturated Spirit Knowledge', '163575', '267679');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('albtraum', 'albmisc', 'Albtraum Misc', 'Ancient Speed Preservation Unit', '218753', '267625');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('albtraum', 'albmisc', 'Albtraum Misc', 'Ancient Vision Preservation Unit', '218752', '267626');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('albtraum', 'albmisc', 'Albtraum Misc', 'Dormant Ancient Circuit', '158233', '267794');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('albtraum', 'albmisc', 'Albtraum Misc', 'Empty Ancient Device', '218753', '267709');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('albtraum', 'albmisc', 'Albtraum Misc', 'Energy Infused Crystal', '156567', '267749');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('albtraum', 'albmisc', 'Albtraum Misc', 'Inactive Ancient Engineering Device', '156094', '267748');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('albtraum', 'albmisc', 'Albtraum Misc', 'Inactive Ancient Medical Device', '218774', '267735');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('albtraum', 'albmisc', 'Albtraum Misc', 'Inactive Ancient Bracer', '84048', '267746');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('albtraum', 'albmisc', 'Albtraum Misc', 'Inert Knowledge Crystal', '151030', '267737');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('biodome', 'biodome', 'Uqhart the Absorber', 'Pattern of Indomitable Life (MP Rihwen)', '231182', '255549');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('biodome', 'biodome', 'Uqhart the Absorber', 'Pattern of the Occurence of Death (NT Self Illumination)', '231182', '255554');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('biodome', 'biodome', 'Uqhart the Absorber', 'Business Card (Associate) (Crat Carlo)', '258540', '258563');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('biodome', 'biodome', 'Jathos'' Molybdenum Armor (Not Omni)', 'Jathos'' Molybdenum Plate Boots', '252431', '252002');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('biodome', 'biodome', 'Jathos'' Molybdenum Armor (Not Omni)', 'Jathos'' Molybdenum Plate Gloves', '252439', '252004');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('biodome', 'biodome', 'Jathos'' Molybdenum Armor (Not Omni)', 'Jathos'' Molybdenum Plate Helmet', '252430', '252005');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('biodome', 'biodome', 'Jathos'' Molybdenum Armor (Not Omni)', 'Jathos'' Molybdenum Plate Pants', '252437', '252000');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('biodome', 'biodome', 'Jathos'' Molybdenum Armor (Not Omni)', 'Jathos'' Molybdenum Plate Sleeves', '252435', '252003');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('biodome', 'biodome', 'Jathos'' Molybdenum Armor (Not Omni)', 'Jathos'' Molybdenum Plate Vest', '252433', '252001');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('biodome', 'biodome', 'Kegern''s Molybdenum Armor (Not Clan)', 'Kegern''s Molybdenum Plate Boots', '252432', '252020');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('biodome', 'biodome', 'Kegern''s Molybdenum Armor (Not Clan)', 'Kegern''s Molybdenum Plate Gloves', '252440', '252018');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('biodome', 'biodome', 'Kegern''s Molybdenum Armor (Not Clan)', 'Kegern''s Molybdenum Plate Helmet', '252429', '252017');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('biodome', 'biodome', 'Kegern''s Molybdenum Armor (Not Clan)', 'Kegern''s Molybdenum Plate Pants', '252438', '252022');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('biodome', 'biodome', 'Kegern''s Molybdenum Armor (Not Clan)', 'Kegern''s Molybdenum Plate Sleeves', '252436', '252019');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('biodome', 'biodome', 'Kegern''s Molybdenum Armor (Not Clan)', 'Kegern''s Molybdenum Plate Vest', '252434', '252021');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('biodome', 'biodome', 'Proactive Armor (Not Clan)', 'Proactive Boots', '252432', '252013');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('biodome', 'biodome', 'Proactive Armor (Not Clan)', 'Proactive Gloves', '252440', '252015');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('biodome', 'biodome', 'Proactive Armor (Not Clan)', 'Proactive Helmet', '252429', '252016');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('biodome', 'biodome', 'Proactive Armor (Not Clan)', 'Proactive Pants', '252438', '252011');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('biodome', 'biodome', 'Proactive Armor (Not Clan)', 'Proactive Sleeves', '252436', '252014');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('biodome', 'biodome', 'Proactive Armor (Not Clan)', 'Proactive Vest', '252434', '252012');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('biodome', 'biodome', 'Reactive Armor (Not Omni)', 'Reactive Boots', '252431', '251996');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('biodome', 'biodome', 'Reactive Armor (Not Omni)', 'Reactive Gloves', '252439', '251998');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('biodome', 'biodome', 'Reactive Armor (Not Omni)', 'Reactive Helmet', '252430', '251999');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('biodome', 'biodome', 'Reactive Armor (Not Omni)', 'Reactive Pants', '252437', '251995');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('biodome', 'biodome', 'Reactive Armor (Not Omni)', 'Reactive Sleeves', '252435', '251997');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('biodome', 'biodome', 'Reactive Armor (Not Omni)', 'Reactive Vest', '252433', '251994');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('dreadloch', 'dreadweapons', 'Dreadloch Weapons', 'Doctor''s Left Hand of Grace', '264789', '267618');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('dreadloch', 'dreadweapons', 'Dreadloch Weapons', 'Doctor''s Right Hand of Hope', '264786', '267619');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('dreadloch', 'dreadweapons', 'Dreadloch Weapons', 'Dreadloch Balanced Freedom Arms (Crat)', '264788', '267255');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('dreadloch', 'dreadweapons', 'Dreadloch Weapons', 'Dreadloch Combat Remodulator ', '264837', '267261');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('dreadloch', 'dreadweapons', 'Dreadloch Weapons', 'Dreadloch Enhanced Bear', '264827', '267254');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('dreadloch', 'dreadweapons', 'Dreadloch Weapons', 'Dreadloch Enhanced Panther', '264815', '267253');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('dreadloch', 'dreadweapons', 'Dreadloch Weapons', 'Dreadloch Modified Shark', '264839', '267158');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('dreadloch', 'dreadweapons', 'Dreadloch Weapons', 'Dreadloch Obliterator', '19800', '27127');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('dreadloch', 'dreadweapons', 'Dreadloch Weapons', 'Dreadloch Rapier', '31807', '267128');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('dreadloch', 'dreadweapons', 'Dreadloch Weapons', 'Dreadloch Remodulator', '264837', '267256');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('dreadloch', 'dreadweapons', 'Dreadloch Weapons', 'Dreadloch Shen Sticks', '229956', '267258');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('dreadloch', 'dreadweapons', 'Dreadloch Weapons', 'Dreadloch Thrasher', '210185', '267125');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('dreadloch', 'dreadweapons', 'Dreadloch Weapons', 'Dreadloch Tigress (MP)', '264841', '267257');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('dreadloch', 'dreadarmor', 'Dreadloch Armor', 'Hellfyre Magma Suit', '41162', '267317');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('dreadloch', 'dreadarmor', 'Dreadloch Armor', 'Smuggled Combat Merit Board Base', '216287', '267106');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('dreadloch', 'dreadarmor', 'Dreadloch Armor', 'Smuggled Nanite Merit Board Base', '216287', '267108');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('dreadloch', 'dreadutil', 'Dreadloch Utilities', 'Dreadloch Aiming Apparatus', '130840', '267164');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('dreadloch', 'dreadutil', 'Dreadloch Utilities', 'Dreadloch Damage Amplifier (Soldier or MA)', '99264', '267260');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('dreadloch', 'dreadutil', 'Dreadloch Utilities', 'Dreadloch Endurance Booster', '99266', '267166');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('dreadloch', 'dreadutil', 'Dreadloch Utilities', 'Dreadloch Endurance Booster - Enforcer Special', '99266', '267168');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('dreadloch', 'dreadutil', 'Dreadloch Utilities', 'Dreadloch Endurance Booster - Nanomage Edition', '99266', '267167');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('dreadloch', 'dreadutil', 'Dreadloch Utilities', 'Dreadloch Sniper''s Friend', '99265', '267286');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('dreadloch', 'dreadutil', 'Dreadloch Utilities', 'Dreadloch Stab Guidance System', '99265', '267285');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('dreadloch', 'dreadutil', 'Dreadloch Utilities', 'Dreadloch Stabilising Aid', '130840', '267165');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('dreadloch', 'dreadutil', 'Dreadloch Utilities', 'Dreadloch Survival Predictor (Crat or Trader)', '99265', '267259');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('prisoners', 'prisoners', 'Prisoner Items', 'Reflex Pistol (Adv)', '264785', '274977');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('prisoners', 'prisoners', 'Prisoner Items', 'Sturdy Detention Boots', '31746', '274976');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('prisoners', 'prisoners', 'Prisoner Items', 'Hacked Medi-Blade', '264782', '274974');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('prisoners', 'prisoners', 'Prisoner Items', 'Crude Upgrade Kit', '218768', '274975');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hilion', 'Lion''s Leather Armor', 'Lion''s Leather Boots', '13261', '216281');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hilion', 'Lion''s Leather Armor', 'Lion''s Leather Gloves', '21871', '216279');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hilion', 'Lion''s Leather Armor', 'Lion''s Leather Pants', '13304', '216280');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hilion', 'Lion''s Leather Armor', 'Lion''s Leather Sleeves', '21849', '216278');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hilion', 'Lion''s Leather Armor', 'Lion''s Leather Vest', '19812', '216277');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hifirstbrood', 'First Brood Champion', 'Liquid Notum Ring', '151921', '163696');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hifirstbrood', 'First Brood Champion', 'Nelly''s Chip', '43133', '216341');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hisecondbrood', 'Second Brood Champion', 'Remains of AESA 10', '144712', '216272');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hisecondbrood', 'Second Brood Champion', 'Soft Ring with Fluff', '84064', '163712');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hithirdbrood', 'Third Brood Champion', 'Notum Miner''s Hard Hat', '205765', '216276');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hithirdbrood', 'Third Brood Champion', 'Glimmering Magnetic Ring', '84046', '163710');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hifourthbrood', 'Fourth Brood Champion', 'Mutated Eremite Leg', '20411', '216271');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hifourthbrood', 'Fourth Brood Champion', 'Luminous Copper Band', '151930', '163706');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hifourthbrood', 'Fourth Brood Champion', 'Crystalized Medusa Queen Hippocampus', '156559', '164598');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hififthbrood', 'Fifth Brood Champion', 'Ring of the Endless Depths', '151920', '163704');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hififthbrood', 'Fifth Brood Champion', 'Thick Leather Wristbands', '161086', '216283');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hisixthbrood', 'Sixth Brood Champion', 'I am the Eel', '151923', '163633');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hisixthbrood', 'Sixth Brood Champion', 'Suzerain''s Spiritual Chief Headwear (MP)', '205776', '216450');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hiseventhbrood', 'Seventh Brood Champion', 'I am the Bear', '151923', '163637');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hiseventhbrood', 'Seventh Brood Champion', 'Suzerain''s Military Chief Headwear (NT)', '205774', '216449');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hiseventhbrood', 'Seventh Brood Champion', 'Gurgling River Sprite', '20407', '216268');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hiseventhbrood', 'Seventh Brood Champion', 'Expensive Gift from Earth', '205832', '216286');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hieighthbrood', 'Eighth Brood Champion', 'I am the Owl', '151923', '163635');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hieighthbrood', 'Eighth Brood Champion', 'Chip of the Eight', '43118', '216381');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hieighthbrood', 'Eighth Brood Champion', 'Suzerain''s Political Chief Headwear (Crat)', '205775', '216448');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hininthbrood', 'Ninth Brood Champion', 'Smooth Gold Alloy Ring', '151931', '163699');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hininthbrood', 'Ninth Brood Champion', 'Mutated Eremite Foetus', '20411', '216270');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hitenthbrood', 'Tenth Brood Champion', 'Hammered Gold Ring', '151927', '163701');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hisuzerain', 'Hollow Island Suzerain', 'Brood Champion Gauntlets', '21870', '216372');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hisuzerain', 'Hollow Island Suzerain', 'Clan Ring of Salvation', '84067', '163641');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hibroodmother', 'Brood Mother', 'Professional Marksman''s Kit', '130788', '216282');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hiweed', 'Hollow Island Weed', 'The Argument', '21138', '223469');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hiweed', 'Hollow Island Weed', 'Fly Catcher''s Specs', '205757', '216430');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hiweed', 'Hollow Island Weed', 'Profiteer''s Helper', '159123', '223466');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hiweed', 'Hollow Island Weed', 'Silly Ring', '151927', '163645');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hiweed', 'Hollow Island Weed', 'Beefeater''s Merit Board (Clan Enf)', '216287', '216284');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hiweed', 'Hollow Island Weed', 'Captain Lotto''s Merit Board (Omni Enf)', '216287', '216285');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hiweed', 'Hollow Island Weed', 'Front Fighter Merit Board (Clan Agent/Soldier)', '216287', '216366');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hiweed', 'Hollow Island Weed', 'Merit Board of the Angry Men (Clan NT or Doc)', '216287', '216303');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hiweed', 'Hollow Island Weed', 'Merit Board of the Blue Wolf (Clan Engi or Trader)', '216287', '216369');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hiweed', 'Hollow Island Weed', 'Merit Board of the Long Distance Runner (Clan Fixer or Adv)', '216287', '216363');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hiweed', 'Hollow Island Weed', 'Merit Board of the Rainbow Chrysanthemum (Clan MA)', '216287', '216370');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hiweed', 'Hollow Island Weed', 'Messenger Merit Board (Omni Fixer or Adv)', '216287', '216364');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hiweed', 'Hollow Island Weed', 'Metal Fungus Merit Board (Omni MA)', '216287', '216371');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hiweed', 'Hollow Island Weed', 'Omni-Tek Engineer Corps Merit Board (Omni Engi or Trader)', '216287', '216368');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hiweed', 'Hollow Island Weed', 'Omni-Tek Nano Reservoire Merit Board (Omni NT or Doc)', '216287', '216302');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hiweed', 'Hollow Island Weed', 'Omni-Tek Shock Trooper Merit Board (Omni Agent/Soldier)', '216287', '216367');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hiweed', 'Hollow Island Weed', 'Standard Clan Leader Merit Board (Clan Crat or MP)', '216287', '216323');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('hi', 'hiweed', 'Hollow Island Weed', 'Technocrat Merit Board (Omni Crat or MP)', '216287', '216325');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'iskey', 'Jeuru the Defiler', 'Inner Sanctum Knowledge (Top Half of Key)', '154676', '206257');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'iskey', 'Iskop the Idolator', 'Inner Sanctum Knowledge (Bottom Half of Key)', '154676', '206258');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isweapons', 'IS Weapons', 'Abyssal Desecrator', '204827', '206058');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isweapons', 'IS Weapons', 'Frost-bound Reaper', '204741', '206061');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isweapons', 'IS Weapons', 'Frost Shard', '204740', '206055');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isweapons', 'IS Weapons', 'Gelid Blade of Inobak', '204740', '206057');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isweapons', 'IS Weapons', 'Icebound Heart', '204740', '206056');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isweapons', 'IS Weapons', 'Impious Dominator', '13339', '206052');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isweapons', 'IS Weapons', 'Maw of the Abyss', '13340', '206049');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isweapons', 'IS Weapons', 'Parasitic Hecataleech', '38056', '206047');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isweapons', 'IS Weapons', 'Permafrost', '204741', '206062');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isweapons', 'IS Weapons', 'Prelude to Chaos', '113994', '206053');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isweapons', 'IS Weapons', 'Right Hand of Entropy', '113997', '206054');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isweapons', 'IS Weapons', 'Skull of Despair', '204742', '206060');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isweapons', 'IS Weapons', 'Skull of Misery', '204742', '206059');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isrings', 'IS Rings', 'First Circle of the Inner Sanctum (BM/MM)', '84065', '206224');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isrings', 'IS Rings', 'First Circle of the Inner Sanctum (MC/TS)', '84065', '206225');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isrings', 'IS Rings', 'First Circle of the Inner Sanctum (PM/SI)', '84065', '206226');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isrings', 'IS Rings', 'Second Circle of the Inner Sanctum (BM/MM)', '84068', '206235');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isrings', 'IS Rings', 'Second Circle of the Inner Sanctum (MC/TS)', '84068', '206236');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isrings', 'IS Rings', 'Second Circle of the Inner Sanctum (PM/SI)', '84068', '206232');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isrings', 'IS Rings', 'Third Circle of the Inner Sanctum (BM/MM)', '151926', '206238');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isrings', 'IS Rings', 'Third Circle of the Inner Sanctum (MC/TS)', '151926', '206237');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isrings', 'IS Rings', 'Third Circle of the Inner Sanctum (PM/SI)', '151926', '206239');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isrings', 'IS Rings', 'Bloodslave Ring', '84066', '206201');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isrings', 'IS Rings', 'Ring of Putrescent Flesh', '151927', '206202');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isrings', 'IS Rings', 'Ring of Wilting Flame', '84060', '206203');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isrings', 'IS Rings', 'Twilight''s Murder', '151921', '206204');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isabaddon', 'Abaddon', 'Charred Abaddon Chassis', '41163', '206136');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isabaddon', 'Abaddon', 'Abaddon Upgrade: Defense', '43126', '206153');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isabaddon', 'Abaddon', 'Abaddon Upgrade: Essence', '43121', '206156');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isabaddon', 'Abaddon', 'Abaddon Upgrade: Life', '43135', '206151');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isabaddon', 'Abaddon', 'Abaddon Upgrade: Nano', '43126', '206154');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isabaddon', 'Abaddon', 'Abaddon Upgrade: Offense', '43135', '206152');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isabaddon', 'Abaddon', 'Abaddon Upgrade: Skill', '43121', '206155');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'iskarmic', 'Tattered Book: Karmic Fist', 'Tattered book: Karmic Fist (section 1)', '136332', '206180');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'iskarmic', 'Tattered Book: Karmic Fist', 'Tattered book: Karmic Fist (section 2)', '136332', '206181');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'iskarmic', 'Tattered Book: Karmic Fist', 'Tattered book: Karmic Fist (section 3)', '136332', '206182');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'iskarmic', 'Tattered Book: Karmic Fist', 'Tattered book: Karmic Fist (section 4)', '136332', '206183');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'iskarmic', 'Tattered Book: Karmic Fist', 'Tattered book: Karmic Fist (section 5)', '136332', '206184');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'iskarmic', 'Tattered Book: Karmic Fist', 'Tattered book: Karmic Fist (section 6)', '136332', '206185');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isarmor', 'Carapace of the Infernal Tyrant', 'Carapace of the Infernal Tyrant (Body)', '21977', '205957');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isarmor', 'Carapace of the Infernal Tyrant', 'Carapace of the Infernal Tyrant (Boots)', '21978', '205960');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isarmor', 'Carapace of the Infernal Tyrant', 'Carapace of the Infernal Tyrant (Gloves', '21979', '205959');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isarmor', 'Carapace of the Infernal Tyrant', 'Carapace of the Infernal Tyrant (Helmet)', '22270', '205961');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isarmor', 'Carapace of the Infernal Tyrant', 'Carapace of the Infernal Tyrant (Pants)', '21980', '205958');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isarmor', 'Carapace of the Infernal Tyrant', 'Carapace of the Infernal Tyrant (Sleeves)', '21976', '205956');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isarmor', 'Carapace of the Infernal Tyrant', 'Bloodseal of the Infernal Tyrant', '25801', '206196');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isarmor', 'Carapace of the Infernal Tyrant', 'Ichor of the Immortal One', '11753', '206067');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isarmor', 'Gloomfall Armor', 'Gloomfall Armor (Body)', '13249', '205951');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isarmor', 'Gloomfall Armor', 'Gloomfall Armor (Boots)', '13265', '205955');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isarmor', 'Gloomfall Armor', 'Gloomfall Armor (Gloves)', '13279', '205953');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isarmor', 'Gloomfall Armor', 'Gloomfall Armor (Helmet)', '22269', '205950');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isarmor', 'Gloomfall Armor', 'Gloomfall Armor (Pants)', '13294', '205952');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isarmor', 'Gloomfall Armor', 'Gloomfall Armor (Sleeves)', '13227', '205954');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isarmor', 'IS Armor', 'Blighted Soulmark', '25794', '206011');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isarmor', 'IS Armor', 'Bloodmark', '25796', '206006');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isarmor', 'IS Armor', 'Bloodshed Armband', '84050', '206248');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isarmor', 'IS Armor', 'Corrupted Flesh', '144704', '206015');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isarmor', 'IS Armor', 'Defiled Bloodmark', '25796', '206007');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isarmor', 'IS Armor', 'Desecrated Bloodmark', '25796', '206008');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isarmor', 'IS Armor', 'Jeuru''s Oscillating Ligature', '84053', '206064');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isarmor', 'IS Armor', 'Might of the Revenant', '144709', '206013');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isarmor', 'IS Armor', 'Obsidian Jar', '119185', '206457');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isarmor', 'IS Armor', 'Small Obsidian Jar', '119173', '206477');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isarmor', 'IS Armor', 'Soulmark', '25794', '206009');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'isarmor', 'IS Armor', 'Tainted Soulmark', '25794', '206010');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'ismisc', 'IS Miscellaneous', 'Constrained Gridspace Waveform', '25798', '206068');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'ismisc', 'IS Miscellaneous', 'Fist of the Dominator', '12666', '206247');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'ismisc', 'IS Miscellaneous', 'Mnemonic Fragment', '119141', '206018');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'ismisc', 'IS Miscellaneous', 'Nano Crystal (Saemus'' Crystalizer)', '42450', '206753');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'ismisc', 'IS Miscellaneous', 'Rod of Dismissal', '100306', '206017');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'ismisc', 'IS Miscellaneous', 'Teachings of the Immortal One', '136329', '206242');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'ismisc', 'IS Miscellaneous', 'The Primeval Skull', '195259', '206246');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('is', 'ismisc', 'IS Miscellaneous', 'Unhallowed Chalice', '37929', '206016');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('jack', 'legchopper', 'Jack "Leg-chopper" Menendez', 'Ambidextrous Plasteel Gloves', '21979', '151686');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('jack', 'legchopper', 'Jack "Leg-chopper" Menendez', 'Bloodstained Dog-Tag (Soldier)', '149944', '165466');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('jack', 'legchopper', 'Jack "Leg-chopper" Menendez', 'Disposal Unit Electrical Toolset', '12710', '164552');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('jack', 'legchopper', 'Jack "Leg-chopper" Menendez', 'DNA Sample (Doctor)', '11750', '165470');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('jack', 'legchopper', 'Jack "Leg-chopper" Menendez', 'Glowing Amygdaloid Nucleus (MP and NT)', '144711', '165471');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('jack', 'legchopper', 'Jack "Leg-chopper" Menendez', 'Important Looking Briefcase (Crat)', '99668', '165472');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('jack', 'legchopper', 'Jack "Leg-chopper" Menendez', 'Jack''s Head (Adv, Fixer and Trader)', '144703', '165469');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('jack', 'legchopper', 'Jack "Leg-chopper" Menendez', 'Jack''s Reinforced Gloves (Enf)', '21979', '165468');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('jack', 'legchopper', 'Jack "Leg-chopper" Menendez', 'Proof of what happened to Joslyn (Agent)', '144709', '165474');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('jack', 'legchopper', 'Jack "Leg-chopper" Menendez', 'Remains of a long lost pet (Engi)', '144707', '165473');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('jack', 'legchopper', 'Jack "Leg-chopper" Menendez', 'Severed leg of the Grand Master (MA)', '144709', '165467');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('jack', 'legchopper', 'Jack "Leg-chopper" Menendez', 'Silken Legchopper Gloves', '37105', '152544');
INSERT INTO raidloot (raid, area, boss, name, img, ref) VALUES('jack', 'legchopper', 'Jack "Leg-chopper" Menendez', 'Supporting Carbonan Holster', '13227', '151715');
