DROP TABLE IF EXISTS raidloot;
CREATE TABLE IF NOT EXISTS raidloot (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, raid VARCHAR(255), area VARCHAR(255), boss VARCHAR(255), name VARCHAR(255), img INT, ref INT, quantity INT);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '10', 'Boss Loot', 'Inactive Alien Tank Armor', '22401', '268507', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '10', 'Boss Loot', 'Inactive Alien Battery', '220416', '268496', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '10', 'Boss Loot', 'Inactive Alien Beacon', '220416', '268494', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '10', 'Boss Loot', 'Inactive Alien Material Conversion Kit', '99658', '268510', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '10', 'Boss Loot', 'Inactive Alien Reflex Modifier', '220416', '268499', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '10', 'Boss Loot', 'Inactive Alien Translation Device', '12692', '268477', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '10', 'Boss Loot', 'Inactive Empty Alien Augmentation Device', '218751', '268493', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '10', 'Common Loot', 'Alien Activation Crystal', '12252', '268478', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '10', 'Common Loot', 'Alien Data Storage Crystal - Combat', '83069', '268479', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '10', 'Common Loot', 'Alien Data Storage Crystal - Defense', '83069', '268481', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '10', 'Common Loot', 'Alien Data Storage Crystal - Insight', '83069', '268484', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '10', 'Common Loot', 'Alien Data Storage Crystal - Medical', '83069', '268483', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '10', 'Common Loot', 'Alien Data Storage Crystal - Nano Technology', '83069', '268480', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '10', 'Common Loot', 'Alien Data Storage Crystal - Protection', '83069', '268485', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '10', 'Common Loot', 'Alien Data Storage Crystal - Technical', '83069', '268482', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '10', 'Common Loot', 'Alien Armor Materials', '144715', '268508', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '13', 'Master Genesplicer Cha''Khaz', 'Action Probability Estimator', '203502', '257960', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '13', 'Master Genesplicer Cha''Khaz', 'Dynamic Gas Redistribution Valves', '205508', '257962', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '13', 'Master Genesplicer Cha''Khaz', 'Kyr''Ozch Helmet', '230855', '257706', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '13', 'Master Genesplicer Cha''Khaz', 'Hacker Ice-Breaker Source', '257196', '257968', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '13', 'Master Genesplicer Cha''Khaz', 'Kyr''Ozch Battlesuit Audio Processor', '218775', '257529', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '13', 'Master Genesplicer Cha''Khaz', 'Kyr''Ozch Rank Identification', '218768', '257531', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '13', 'Master Genesplicer Cha''Khaz', 'Kyr''Ozch Video Processing Unit', '218758', '257533', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '13', 'Master Genesplicer Cha''Khaz', 'Kyr''Ozch Data Core', '25800', '258294', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '13', 'Master Genesplicer Cha''Khaz', 'Biotech Matrix', '275972', '275916', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '13', 'Master Genesplicer Cha''Khaz', 'Gelatinous Lump', '275962', '275909', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '28', 'Embalmer Cha''Khaz', 'Notum Amplification Coil', '257195', '275963', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '28', 'Embalmer Cha''Khaz', 'Inertial Adjustment Processing Unit', '11618', '275959', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '28', 'Embalmer Cha''Khaz', 'Kyr''Ozch Helmet', '230855', '257706', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '28', 'Embalmer Cha''Khaz', 'Hacker Ice-Breaker Source', '257196', '257968', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '28', 'Embalmer Cha''Khaz', 'Kyr''Ozch Battlesuit Audio Processor', '218775', '257529', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '28', 'Embalmer Cha''Khaz', 'Kyr''Ozch Rank Identification', '218768', '257531', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '28', 'Embalmer Cha''Khaz', 'Kyr''Ozch Video Processing Unit', '218758', '257533', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '28', 'Embalmer Cha''Khaz', 'Kyr''Ozch Data Core', '25800', '258293', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '28', 'Embalmer Cha''Khaz', 'Crystalline Matrix', '275964', '275912', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '28', 'Embalmer Cha''Khaz', 'Kyr''Ozch Circuitry', '275965', '275914', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '35', 'Field Marshal and Support Cha''Khaz', 'Visible Light Remodulation Device', '235270', '257964', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '35', 'Field Marshal and Support Cha''Khaz', 'Energy Redistribution Unit', '257197', '257961', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '35', 'Field Marshal and Support Cha''Khaz', 'Kyr''Ozch Helmet', '230855', '257706', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '35', 'Field Marshal and Support Cha''Khaz', 'Hacker Ice-Breaker Source', '257196', '257968', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '35', 'Field Marshal and Support Cha''Khaz', 'Kyr''Ozch Battlesuit Audio Processor', '218775', '257529', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '35', 'Field Marshal and Support Cha''Khaz', 'Kyr''Ozch Rank Identification', '218768', '257531', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '35', 'Field Marshal and Support Cha''Khaz', 'Kyr''Ozch Video Processing Unit', '218758', '257533', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '35', 'Field Marshal and Support Cha''Khaz', 'Kyr''Ozch Data Core', '25800', '258292', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '35', 'Field Marshal and Support Cha''Khaz', 'Alpha Program Chip', '275970', '275918', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '35', 'Field Marshal and Support Cha''Khaz', 'Beta Program Chip', '275969', '275919', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '35', 'Field Marshal and Support Cha''Khaz', 'Kyr''Ozch Processing Unit', '275960', '275907', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '35', 'Field Marshal and Support Cha''Khaz', 'Odd Kyr''Ozch Nanobots', '11750', '275906', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '42', 'East - Field Marshal & Support', 'Visible Light Remodulation Device', '235270', '257964', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '42', 'East - Field Marshal & Support', 'Energy Redistribution Unit', '257197', '257961', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '42', 'East - Field Marshal & Support', 'Hacker Ice-Breaker Source', '257196', '257968', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '42', 'North - Master Genesplicer', 'Action Probability Estimator', '203502', '257960', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '42', 'North - Master Genesplicer', 'Dynamic Gas Redistribution Valves', '205508', '257962', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '42', 'North - Master Genesplicer', 'Hacker Ice-Breaker Source', '257196', '257968', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '42', 'West - Proto-Embalmer', 'Notum Amplification Coil', '257195', '275963', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '42', 'West - Proto-Embalmer', 'Inertial Adjustment Processing Unit', '11618', '275959', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '42', 'West - Proto-Embalmer', 'Hacker Ice-Breaker Source', '257196', '257968', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '42', 'West - Proto-Embalmer', 'Alien Matrix Alpha Box', '275887', '275706', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '42', 'West - Proto-Embalmer', 'Alien Matrix Beta Box', '275889', '275854', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '42', 'Artillery Commander', 'Kyr''Ozch Invasion Plan', '35990', '262656', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('apf', '42', 'Artillery Commander', 'Unlearning Device', '99257', '260422', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('db', 'db2', 'Ground Chief Aune', 'Basic Infused Dust Brigade Bracer', '84062', '274541', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('db', 'db2', 'Ground Chief Aune', 'Dust Brigade Notum Infuser', '218768', '274552', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('db', 'db2', 'Ground Chief Aune', 'Dust Brigade Solar Notum Infuser', '218768', '274558', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('db', 'db2', 'Ground Chief Aune', 'Dust Brigade Engineer Pistol', '264787', '274559', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('db', 'db2', 'Ground Chief Aune', 'Black Molybdenum-Matrix of Xan', '272534', '272458', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('db', 'db2', 'Ground Chief Aune', 'White Molybdenum-Matrix of Xan', '272535', '272459', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('db', 'db2', 'Ground Chief Aune', 'Enhanced Dustbrigade Chemist Gloves', '21871', '270393', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('db', 'db2', 'Ground Chief Aune', 'Enhanced Dustbrigade Covering', '155108', '269997', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('db', 'db2', 'Ground Chief Aune', 'Enhanced Dustbrigade Flexible Boots', '31746', '270392', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('db', 'db2', 'Ground Chief Aune', 'Enhanced Dustbrigade Notum Gloves', '21871', '270394', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('db', 'db2', 'Ground Chief Aune', 'Enhanced Dustbrigade Sleeves', '13233', '269996', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('db', 'db1', 'Ground Chief Mikkelsen', 'Enhanced Dustbrigade Chemist Gloves', '21871', '270393', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('db', 'db1', 'Ground Chief Mikkelsen', 'Enhanced Dustbrigade Combat Chestpiece', '32162', '269993', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('db', 'db1', 'Ground Chief Mikkelsen', 'Enhanced Dustbrigade Covering', '155108', '269997', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('db', 'db1', 'Ground Chief Mikkelsen', 'Enhanced Dustbrigade Fleixble Boots', '31746', '270392', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('db', 'db1', 'Ground Chief Mikkelsen', 'Enhanced Dustbrigade Notum Gloves', '21871', '270394', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('db', 'db1', 'Ground Chief Mikkelsen', 'Enhanced Dustbrigade Sleeves', '13233', '269996', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('db', 'db1', 'Ground Chief Mikkelsen', 'Enhanced Dustbrigade Spirit-tech Chestpiece', '32162', '269994', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('db', 'db1', 'Ground Chief Mikkelsen', 'Enhanced Safeguarded NCU Memory Unit (Int/Psy)', '119134', '269985', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('db', 'db1', 'Ground Chief Mikkelsen', 'Enhanced Safeguarded NCU Memory Unit (Str/Sta)', '119134', '269986', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('db', 'db1', 'Ground Chief Mikkelsen', 'Enhanced Safeguarded NCU Memory Unit (Agi/Sen)', '119134', '269987', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('db', 'db1', 'Ground Chief Mikkelsen', 'Protected Safeguarded NCU Memory Unit (Evades)', '119134', '269990', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('db', 'db1', 'Ground Chief Mikkelsen', 'Master Combat Program', '269949', '269960', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('db', 'db1', 'Ground Chief Mikkelsen', 'Master Melee Program', '269948', '269961', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('db', 'db1', 'Ground Chief Mikkelsen', 'Master Nano Technology Program', '269950', '269959', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('alappaa', 'alappaa', 'Reprogrammed Mezzorash', 'Frozen Shoulderpads', '269968', '269896', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('alappaa', 'alappaa', 'Reprogrammed Mezzorash', 'Combat Program', '269949', '269946', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('alappaa', 'alappaa', 'Reprogrammed Mezzorash', 'Melee Program', '269948', '269947', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('alappaa', 'alappaa', 'Reprogrammed Mezzorash', 'Nano Technology Program', '269950', '269945', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('biodome', 'biodome', 'Uqhart the Absorber', 'Pattern of Indomitable Life (MP Rihwen)', '231182', '255549', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('biodome', 'biodome', 'Uqhart the Absorber', 'Pattern of the Occurence of Death (NT Self Illumination)', '231182', '255554', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('biodome', 'biodome', 'Uqhart the Absorber', 'Business Card (Associate) (Crat Carlo)', '258540', '258563', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('biodome', 'biodome', 'Jathos'' Molybdenum Armor (Not Omni)', 'Jathos'' Molybdenum Plate Boots', '252431', '252002', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('biodome', 'biodome', 'Jathos'' Molybdenum Armor (Not Omni)', 'Jathos'' Molybdenum Plate Gloves', '252439', '252004', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('biodome', 'biodome', 'Jathos'' Molybdenum Armor (Not Omni)', 'Jathos'' Molybdenum Plate Helmet', '252430', '252005', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('biodome', 'biodome', 'Jathos'' Molybdenum Armor (Not Omni)', 'Jathos'' Molybdenum Plate Pants', '252437', '252000', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('biodome', 'biodome', 'Jathos'' Molybdenum Armor (Not Omni)', 'Jathos'' Molybdenum Plate Sleeves', '252435', '252003', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('biodome', 'biodome', 'Jathos'' Molybdenum Armor (Not Omni)', 'Jathos'' Molybdenum Plate Vest', '252433', '252001', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('biodome', 'biodome', 'Kegern''s Molybdenum Armor (Not Clan)', 'Kegern''s Molybdenum Plate Boots', '252432', '252020', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('biodome', 'biodome', 'Kegern''s Molybdenum Armor (Not Clan)', 'Kegern''s Molybdenum Plate Gloves', '252440', '252018', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('biodome', 'biodome', 'Kegern''s Molybdenum Armor (Not Clan)', 'Kegern''s Molybdenum Plate Helmet', '252429', '252017', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('biodome', 'biodome', 'Kegern''s Molybdenum Armor (Not Clan)', 'Kegern''s Molybdenum Plate Pants', '252438', '252022', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('biodome', 'biodome', 'Kegern''s Molybdenum Armor (Not Clan)', 'Kegern''s Molybdenum Plate Sleeves', '252436', '252019', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('biodome', 'biodome', 'Kegern''s Molybdenum Armor (Not Clan)', 'Kegern''s Molybdenum Plate Vest', '252434', '252021', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('biodome', 'biodome', 'Proactive Armor (Not Clan)', 'Proactive Boots', '252432', '252013', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('biodome', 'biodome', 'Proactive Armor (Not Clan)', 'Proactive Gloves', '252440', '252015', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('biodome', 'biodome', 'Proactive Armor (Not Clan)', 'Proactive Helmet', '252429', '252016', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('biodome', 'biodome', 'Proactive Armor (Not Clan)', 'Proactive Pants', '252438', '252011', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('biodome', 'biodome', 'Proactive Armor (Not Clan)', 'Proactive Sleeves', '252436', '252014', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('biodome', 'biodome', 'Proactive Armor (Not Clan)', 'Proactive Vest', '252434', '252012', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('biodome', 'biodome', 'Reactive Armor (Not Omni)', 'Reactive Boots', '252431', '251996', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('biodome', 'biodome', 'Reactive Armor (Not Omni)', 'Reactive Gloves', '252439', '251998', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('biodome', 'biodome', 'Reactive Armor (Not Omni)', 'Reactive Helmet', '252430', '251999', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('biodome', 'biodome', 'Reactive Armor (Not Omni)', 'Reactive Pants', '252437', '251995', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('biodome', 'biodome', 'Reactive Armor (Not Omni)', 'Reactive Sleeves', '252435', '251997', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('biodome', 'biodome', 'Reactive Armor (Not Omni)', 'Reactive Vest', '252433', '251994', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('dreadloch', 'dreadweapons', 'Dreadloch Weapons', 'Doctor''s Left Hand of Grace', '264789', '267618', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('dreadloch', 'dreadweapons', 'Dreadloch Weapons', 'Doctor''s Right Hand of Hope', '264786', '267619', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('dreadloch', 'dreadweapons', 'Dreadloch Weapons', 'Dreadloch Balanced Freedom Arms (Crat)', '264788', '267255', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('dreadloch', 'dreadweapons', 'Dreadloch Weapons', 'Dreadloch Combat Remodulator ', '264837', '267261', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('dreadloch', 'dreadweapons', 'Dreadloch Weapons', 'Dreadloch Enhanced Bear', '264827', '267254', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('dreadloch', 'dreadweapons', 'Dreadloch Weapons', 'Dreadloch Enhanced Panther', '264815', '267253', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('dreadloch', 'dreadweapons', 'Dreadloch Weapons', 'Dreadloch Modified Shark', '264839', '267158', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('dreadloch', 'dreadweapons', 'Dreadloch Weapons', 'Dreadloch Obliterator', '19800', '27127', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('dreadloch', 'dreadweapons', 'Dreadloch Weapons', 'Dreadloch Rapier', '31807', '267128', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('dreadloch', 'dreadweapons', 'Dreadloch Weapons', 'Dreadloch Remodulator', '264837', '267256', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('dreadloch', 'dreadweapons', 'Dreadloch Weapons', 'Dreadloch Shen Sticks', '229956', '267258', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('dreadloch', 'dreadweapons', 'Dreadloch Weapons', 'Dreadloch Thrasher', '210185', '267125', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('dreadloch', 'dreadweapons', 'Dreadloch Weapons', 'Dreadloch Tigress (MP)', '264841', '267257', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('dreadloch', 'dreadarmor', 'Dreadloch Armor', 'Hellfyre Magma Suit', '41162', '267317', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('dreadloch', 'dreadarmor', 'Dreadloch Armor', 'Smuggled Combat Merit Board Base', '216287', '267106', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('dreadloch', 'dreadarmor', 'Dreadloch Armor', 'Smuggled Nanite Merit Board Base', '216287', '267108', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('dreadloch', 'dreadutil', 'Dreadloch Utilities', 'Dreadloch Aiming Apparatus', '130840', '267164', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('dreadloch', 'dreadutil', 'Dreadloch Utilities', 'Dreadloch Damage Amplifier (Soldier or MA)', '99264', '267260', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('dreadloch', 'dreadutil', 'Dreadloch Utilities', 'Dreadloch Endurance Booster', '99266', '267166', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('dreadloch', 'dreadutil', 'Dreadloch Utilities', 'Dreadloch Endurance Booster - Enforcer Special', '99266', '267168', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('dreadloch', 'dreadutil', 'Dreadloch Utilities', 'Dreadloch Endurance Booster - Nanomage Edition', '99266', '267167', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('dreadloch', 'dreadutil', 'Dreadloch Utilities', 'Dreadloch Sniper''s Friend', '99265', '267286', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('dreadloch', 'dreadutil', 'Dreadloch Utilities', 'Dreadloch Stab Guidance System', '99265', '267285', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('dreadloch', 'dreadutil', 'Dreadloch Utilities', 'Dreadloch Stabilising Aid', '130840', '267165', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('dreadloch', 'dreadutil', 'Dreadloch Utilities', 'Dreadloch Survival Predictor (Crat or Trader)', '99265', '267259', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('prisoners', 'prisoners', 'Prisoner Items', 'Reflex Pistol (Adv)', '264785', '274977', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('prisoners', 'prisoners', 'Prisoner Items', 'Sturdy Detention Boots', '31746', '274976', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('prisoners', 'prisoners', 'Prisoner Items', 'Hacked Medi-Blade', '264782', '274974', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('prisoners', 'prisoners', 'Prisoner Items', 'Crude Upgrade Kit', '218768', '274975', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hilion', 'Lion''s Leather Armor', 'Lion''s Leather Boots', '13261', '216281', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hilion', 'Lion''s Leather Armor', 'Lion''s Leather Gloves', '21871', '216279', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hilion', 'Lion''s Leather Armor', 'Lion''s Leather Pants', '13304', '216280', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hilion', 'Lion''s Leather Armor', 'Lion''s Leather Sleeves', '21849', '216278', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hilion', 'Lion''s Leather Armor', 'Lion''s Leather Vest', '19812', '216277', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hifirstbrood', 'First Brood Champion', 'Liquid Notum Ring', '151921', '163696', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hifirstbrood', 'First Brood Champion', 'Nelly''s Chip', '43133', '216341', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hisecondbrood', 'Second Brood Champion', 'Remains of AESA 10', '144712', '216272', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hisecondbrood', 'Second Brood Champion', 'Soft Ring with Fluff', '84064', '163712', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hithirdbrood', 'Third Brood Champion', 'Notum Miner''s Hard Hat', '205765', '216276', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hithirdbrood', 'Third Brood Champion', 'Glimmering Magnetic Ring', '84046', '163710', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hifourthbrood', 'Fourth Brood Champion', 'Mutated Eremite Leg', '20411', '216271', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hifourthbrood', 'Fourth Brood Champion', 'Luminous Copper Band', '151930', '163706', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hifourthbrood', 'Fourth Brood Champion', 'Crystalized Medusa Queen Hippocampus', '156559', '164598', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hififthbrood', 'Fifth Brood Champion', 'Ring of the Endless Depths', '151920', '163704', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hififthbrood', 'Fifth Brood Champion', 'Thick Leather Wristbands', '161086', '216283', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hisixthbrood', 'Sixth Brood Champion', 'I am the Eel', '151923', '163633', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hisixthbrood', 'Sixth Brood Champion', 'Suzerain''s Spiritual Chief Headwear (MP)', '205776', '216450', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hiseventhbrood', 'Seventh Brood Champion', 'I am the Bear', '151923', '163637', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hiseventhbrood', 'Seventh Brood Champion', 'Suzerain''s Military Chief Headwear (NT)', '205774', '216449', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hiseventhbrood', 'Seventh Brood Champion', 'Gurgling River Sprite', '20407', '216268', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hiseventhbrood', 'Seventh Brood Champion', 'Expensive Gift from Earth', '205832', '216286', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hieighthbrood', 'Eighth Brood Champion', 'I am the Owl', '151923', '163635', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hieighthbrood', 'Eighth Brood Champion', 'Chip of the Eight', '43118', '216381', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hieighthbrood', 'Eighth Brood Champion', 'Suzerain''s Political Chief Headwear (Crat)', '205775', '216448', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hininthbrood', 'Ninth Brood Champion', 'Smooth Gold Alloy Ring', '151931', '163699', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hininthbrood', 'Ninth Brood Champion', 'Mutated Eremite Foetus', '20411', '216270', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hitenthbrood', 'Tenth Brood Champion', 'Hammered Gold Ring', '151927', '163701', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hisuzerain', 'Hollow Island Suzerain', 'Brood Champion Gauntlets', '21870', '216372', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hisuzerain', 'Hollow Island Suzerain', 'Clan Ring of Salvation', '84067', '163641', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hibroodmother', 'Brood Mother', 'Professional Marksman''s Kit', '130788', '216282', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hiweed', 'Hollow Island Weed', 'The Argument', '21138', '223469', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hiweed', 'Hollow Island Weed', 'Fly Catcher''s Specs', '205757', '216430', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hiweed', 'Hollow Island Weed', 'Profiteer''s Helper', '159123', '223466', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hiweed', 'Hollow Island Weed', 'Silly Ring', '151927', '163645', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hiweed', 'Hollow Island Weed', 'Beefeater''s Merit Board (Clan Enf)', '216287', '216284', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hiweed', 'Hollow Island Weed', 'Captain Lotto''s Merit Board (Omni Enf)', '216287', '216285', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hiweed', 'Hollow Island Weed', 'Front Fighter Merit Board (Clan Agent/Soldier)', '216287', '216366', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hiweed', 'Hollow Island Weed', 'Merit Board of the Angry Men (Clan NT or Doc)', '216287', '216303', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hiweed', 'Hollow Island Weed', 'Merit Board of the Blue Wolf (Clan Engi or Trader)', '216287', '216369', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hiweed', 'Hollow Island Weed', 'Merit Board of the Long Distance Runner (Clan Fixer or Adv)', '216287', '216363', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hiweed', 'Hollow Island Weed', 'Merit Board of the Rainbow Chrysanthemum (Clan MA)', '216287', '216370', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hiweed', 'Hollow Island Weed', 'Messenger Merit Board (Omni Fixer or Adv)', '216287', '216364', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hiweed', 'Hollow Island Weed', 'Metal Fungus Merit Board (Omni MA)', '216287', '216371', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hiweed', 'Hollow Island Weed', 'Omni-Tek Engineer Corps Merit Board (Omni Engi or Trader)', '216287', '216368', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hiweed', 'Hollow Island Weed', 'Omni-Tek Nano Reservoire Merit Board (Omni NT or Doc)', '216287', '216302', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hiweed', 'Hollow Island Weed', 'Omni-Tek Shock Trooper Merit Board (Omni Agent/Soldier)', '216287', '216367', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hiweed', 'Hollow Island Weed', 'Standard Clan Leader Merit Board (Clan Crat or MP)', '216287', '216323', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('hi', 'hiweed', 'Hollow Island Weed', 'Technocrat Merit Board (Omni Crat or MP)', '216287', '216325', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'iskey', 'Jeuru the Defiler', 'Inner Sanctum Knowledge (Top Half of Key)', '154676', '206257', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'iskey', 'Iskop the Idolator', 'Inner Sanctum Knowledge (Bottom Half of Key)', '154676', '206258', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isweapons', 'IS Weapons', 'Abyssal Desecrator', '204827', '206058', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isweapons', 'IS Weapons', 'Frost-bound Reaper', '204741', '206061', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isweapons', 'IS Weapons', 'Frost Shard', '204740', '206055', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isweapons', 'IS Weapons', 'Gelid Blade of Inobak', '204740', '206057', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isweapons', 'IS Weapons', 'Icebound Heart', '204740', '206056', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isweapons', 'IS Weapons', 'Impious Dominator', '13339', '206052', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isweapons', 'IS Weapons', 'Maw of the Abyss', '13340', '206049', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isweapons', 'IS Weapons', 'Parasitic Hecataleech', '38056', '206047', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isweapons', 'IS Weapons', 'Permafrost', '204741', '206062', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isweapons', 'IS Weapons', 'Prelude to Chaos', '113994', '206053', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isweapons', 'IS Weapons', 'Right Hand of Entropy', '113997', '206054', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isweapons', 'IS Weapons', 'Skull of Despair', '204742', '206060', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isweapons', 'IS Weapons', 'Skull of Misery', '204742', '206059', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isrings', 'IS Rings', 'First Circle of the Inner Sanctum (BM/MM)', '84065', '206224', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isrings', 'IS Rings', 'First Circle of the Inner Sanctum (MC/TS)', '84065', '206225', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isrings', 'IS Rings', 'First Circle of the Inner Sanctum (PM/SI)', '84065', '206226', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isrings', 'IS Rings', 'Second Circle of the Inner Sanctum (BM/MM)', '84068', '206235', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isrings', 'IS Rings', 'Second Circle of the Inner Sanctum (MC/TS)', '84068', '206236', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isrings', 'IS Rings', 'Second Circle of the Inner Sanctum (PM/SI)', '84068', '206232', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isrings', 'IS Rings', 'Third Circle of the Inner Sanctum (BM/MM)', '151926', '206238', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isrings', 'IS Rings', 'Third Circle of the Inner Sanctum (MC/TS)', '151926', '206237', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isrings', 'IS Rings', 'Third Circle of the Inner Sanctum (PM/SI)', '151926', '206239', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isrings', 'IS Rings', 'Bloodslave Ring', '84066', '206201', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isrings', 'IS Rings', 'Ring of Putrescent Flesh', '151927', '206202', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isrings', 'IS Rings', 'Ring of Wilting Flame', '84060', '206203', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isrings', 'IS Rings', 'Twilight''s Murder', '151921', '206204', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isabaddon', 'Abaddon', 'Charred Abaddon Chassis', '41163', '206136', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isabaddon', 'Abaddon', 'Abaddon Upgrade: Defense', '43126', '206153', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isabaddon', 'Abaddon', 'Abaddon Upgrade: Essence', '43121', '206156', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isabaddon', 'Abaddon', 'Abaddon Upgrade: Life', '43135', '206151', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isabaddon', 'Abaddon', 'Abaddon Upgrade: Nano', '43126', '206154', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isabaddon', 'Abaddon', 'Abaddon Upgrade: Offense', '43135', '206152', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isabaddon', 'Abaddon', 'Abaddon Upgrade: Skill', '43121', '206155', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'iskarmic', 'Tattered Book: Karmic Fist', 'Tattered book: Karmic Fist (section 1)', '136332', '206180', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'iskarmic', 'Tattered Book: Karmic Fist', 'Tattered book: Karmic Fist (section 2)', '136332', '206181', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'iskarmic', 'Tattered Book: Karmic Fist', 'Tattered book: Karmic Fist (section 3)', '136332', '206182', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'iskarmic', 'Tattered Book: Karmic Fist', 'Tattered book: Karmic Fist (section 4)', '136332', '206183', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'iskarmic', 'Tattered Book: Karmic Fist', 'Tattered book: Karmic Fist (section 5)', '136332', '206184', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'iskarmic', 'Tattered Book: Karmic Fist', 'Tattered book: Karmic Fist (section 6)', '136332', '206185', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isarmor', 'Carapace of the Infernal Tyrant', 'Carapace of the Infernal Tyrant (Body)', '21977', '205957', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isarmor', 'Carapace of the Infernal Tyrant', 'Carapace of the Infernal Tyrant (Boots)', '21978', '205960', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isarmor', 'Carapace of the Infernal Tyrant', 'Carapace of the Infernal Tyrant (Gloves', '21979', '205959', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isarmor', 'Carapace of the Infernal Tyrant', 'Carapace of the Infernal Tyrant (Helmet)', '22270', '205961', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isarmor', 'Carapace of the Infernal Tyrant', 'Carapace of the Infernal Tyrant (Pants)', '21980', '205958', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isarmor', 'Carapace of the Infernal Tyrant', 'Carapace of the Infernal Tyrant (Sleeves)', '21976', '205956', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isarmor', 'Carapace of the Infernal Tyrant', 'Bloodseal of the Infernal Tyrant', '25801', '206196', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isarmor', 'Carapace of the Infernal Tyrant', 'Ichor of the Immortal One', '11753', '206067', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isarmor', 'Gloomfall Armor', 'Gloomfall Armor (Body)', '13249', '205951', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isarmor', 'Gloomfall Armor', 'Gloomfall Armor (Boots)', '13265', '205955', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isarmor', 'Gloomfall Armor', 'Gloomfall Armor (Gloves)', '13279', '205953', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isarmor', 'Gloomfall Armor', 'Gloomfall Armor (Helmet)', '22269', '205950', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isarmor', 'Gloomfall Armor', 'Gloomfall Armor (Pants)', '13294', '205952', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isarmor', 'Gloomfall Armor', 'Gloomfall Armor (Sleeves)', '13227', '205954', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isarmor', 'IS Armor', 'Blighted Soulmark', '25794', '206011', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isarmor', 'IS Armor', 'Bloodmark', '25796', '206006', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isarmor', 'IS Armor', 'Bloodshed Armband', '84050', '206248', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isarmor', 'IS Armor', 'Corrupted Flesh', '144704', '206015', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isarmor', 'IS Armor', 'Defiled Bloodmark', '25796', '206007', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isarmor', 'IS Armor', 'Desecrated Bloodmark', '25796', '206008', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isarmor', 'IS Armor', 'Jeuru''s Oscillating Ligature', '84053', '206064', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isarmor', 'IS Armor', 'Might of the Revenant', '144709', '206013', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isarmor', 'IS Armor', 'Obsidian Jar', '119185', '206457', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isarmor', 'IS Armor', 'Small Obsidian Jar', '119173', '206477', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isarmor', 'IS Armor', 'Soulmark', '25794', '206009', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'isarmor', 'IS Armor', 'Tainted Soulmark', '25794', '206010', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'ismisc', 'IS Miscellaneous', 'Constrained Gridspace Waveform', '25798', '206068', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'ismisc', 'IS Miscellaneous', 'Fist of the Dominator', '12666', '206247', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'ismisc', 'IS Miscellaneous', 'Mnemonic Fragment', '119141', '206018', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'ismisc', 'IS Miscellaneous', 'Nano Crystal (Saemus'' Crystalizer)', '42450', '206753', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'ismisc', 'IS Miscellaneous', 'Rod of Dismissal', '100306', '206017', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'ismisc', 'IS Miscellaneous', 'Teachings of the Immortal One', '136329', '206242', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'ismisc', 'IS Miscellaneous', 'The Primeval Skull', '195259', '206246', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('is', 'ismisc', 'IS Miscellaneous', 'Unhallowed Chalice', '37929', '206016', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('jack', 'legchopper', 'Jack "Leg-chopper" Menendez', 'Ambidextrous Plasteel Gloves', '21979', '151686', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('jack', 'legchopper', 'Jack "Leg-chopper" Menendez', 'Bloodstained Dog-Tag (Soldier)', '149944', '165466', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('jack', 'legchopper', 'Jack "Leg-chopper" Menendez', 'Disposal Unit Electrical Toolset', '12710', '164552', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('jack', 'legchopper', 'Jack "Leg-chopper" Menendez', 'DNA Sample (Doctor)', '11750', '165470', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('jack', 'legchopper', 'Jack "Leg-chopper" Menendez', 'Glowing Amygdaloid Nucleus (MP and NT)', '144711', '165471', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('jack', 'legchopper', 'Jack "Leg-chopper" Menendez', 'Important Looking Briefcase (Crat)', '99668', '165472', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('jack', 'legchopper', 'Jack "Leg-chopper" Menendez', 'Jack''s Head (Adv, Fixer and Trader)', '144703', '165469', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('jack', 'legchopper', 'Jack "Leg-chopper" Menendez', 'Jack''s Reinforced Gloves (Enf)', '21979', '165468', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('jack', 'legchopper', 'Jack "Leg-chopper" Menendez', 'Proof of what happened to Joslyn (Agent)', '144709', '165474', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('jack', 'legchopper', 'Jack "Leg-chopper" Menendez', 'Remains of a long lost pet (Engi)', '144707', '165473', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('jack', 'legchopper', 'Jack "Leg-chopper" Menendez', 'Severed leg of the Grand Master (MA)', '144709', '165467', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('jack', 'legchopper', 'Jack "Leg-chopper" Menendez', 'Silken Legchopper Gloves', '37105', '152544', 1);
INSERT INTO raidloot (raid, area, boss, name, img, ref, quantity) VALUES ('jack', 'legchopper', 'Jack "Leg-chopper" Menendez', 'Supporting Carbonan Holster', '13227', '151715', 1);
