DROP TABLE IF EXISTS `ofabweapons`;
CREATE TABLE `ofabweapons` ( `type` int(11) NOT NULL default '0', `name` varchar(255) NOT NULL default '');
INSERT INTO `ofabweapons` (`type`, `name`) VALUES (18, 'Mongoose');
INSERT INTO `ofabweapons` (`type`, `name`) VALUES (18, 'Viper');
INSERT INTO `ofabweapons` (`type`, `name`) VALUES (18, 'Wolf');
INSERT INTO `ofabweapons` (`type`, `name`) VALUES (34, 'Bear');
INSERT INTO `ofabweapons` (`type`, `name`) VALUES (34, 'Panther');
INSERT INTO `ofabweapons` (`type`, `name`) VALUES (687, 'Cobra');
INSERT INTO `ofabweapons` (`type`, `name`) VALUES (687, 'Shark');
INSERT INTO `ofabweapons` (`type`, `name`) VALUES (687, 'Silverback');
INSERT INTO `ofabweapons` (`type`, `name`) VALUES (812, 'Hawk');
INSERT INTO `ofabweapons` (`type`, `name`) VALUES (812, 'Peregrine');
INSERT INTO `ofabweapons` (`type`, `name`) VALUES (812, 'Tiger');

DROP TABLE IF EXISTS `ofabweaponscost`;
CREATE TABLE `ofabweaponscost` (`ql` int(11) NOT NULL, `vp` int(11) NOT NULL);
INSERT INTO `ofabweaponscost` (`ql`, `vp`) VALUES (25, 117);
INSERT INTO `ofabweaponscost` (`ql`, `vp`) VALUES (50, 488);
INSERT INTO `ofabweaponscost` (`ql`, `vp`) VALUES (75, 1110);
INSERT INTO `ofabweaponscost` (`ql`, `vp`) VALUES (100, 1988);
INSERT INTO `ofabweaponscost` (`ql`, `vp`) VALUES (125, 2365);
INSERT INTO `ofabweaponscost` (`ql`, `vp`) VALUES (150, 3497);
INSERT INTO `ofabweaponscost` (`ql`, `vp`) VALUES (175, 5384);
INSERT INTO `ofabweaponscost` (`ql`, `vp`) VALUES (200, 7987);
INSERT INTO `ofabweaponscost` (`ql`, `vp`) VALUES (225, 8617);
INSERT INTO `ofabweaponscost` (`ql`, `vp`) VALUES (250, 10509);
INSERT INTO `ofabweaponscost` (`ql`, `vp`) VALUES (275, 13665);
INSERT INTO `ofabweaponscost` (`ql`, `vp`) VALUES (300, 18000);